### ISSUE TITLE
Epic Mana Potion Bundle returns Lesser Mana Potion Bundle

### ISSUE THREAD

**Issue by JenniLeFur** [Mithion/ArsMagica2#1000]
Upon using the Epic Mana Potion Bundle for the first time, the item disappears and is replaced with a Lesser Mana Potion Bundle with 0 uses. Rather than 0, the uses seem to be infinite.
Each use the bundle will grant the player one empty bottle and one string on use, as well as the mana replenishment and mana regeneration effects.

**Comment by Mithion** [comment]
This has been corrected in 1.4.0.007 (Dev).
