### ISSUE TITLE
Double spell cast

### ISSUE THREAD

**Issue by Gelmo92** [Mithion/ArsMagica2#1001]
Hi, I have a little issue, when I try to cast a spell with projectile inside, it shoots two balls, the first coloured and the second always black and only the second really has effect on the target. 
Can you help me please?

**Comment by TherminatorX** [comment]
We need versions, screenshots, and a pastebin-ed FML log.
Also, telling what you put in your projection spell would be helpful.

**Comment by Gelmo92** [comment]
I tried to make some screenshot but they're useless. Anyway these two are the first and the second projectile which come out in only one mouse click
![2015-01-15_15 47 48](https://cloud.githubusercontent.com/assets/10364476/5759521/c2e81412-9cce-11e4-9af3-193f314bdbb3.png)
![2015-01-15_15 47 48_2](https://cloud.githubusercontent.com/assets/10364476/5759523/c6bf4146-9cce-11e4-9047-317f3227e25a.png)
this is the recipe of the spell:
![2015-01-15_15 34 21](https://cloud.githubusercontent.com/assets/10364476/5759628/59f2c316-9ccf-11e4-9696-edb4dd6bb492.png)
![2015-01-15_15 34 23](https://cloud.githubusercontent.com/assets/10364476/5759632/5d3f16fa-9ccf-11e4-8b0e-3046863859ea.png)
![2015-01-15_15 34 29](https://cloud.githubusercontent.com/assets/10364476/5759634/5ec099f4-9ccf-11e4-9293-04639fb6453c.png)

My version is AM2-1.4.0.006
unfortunately I don't know how to pastebin the FML log sorry

**Comment by TherminatorX** [comment]
Does this happen without the texture pack?

**Comment by Gelmo92** [comment]
yes I tried without any texture pack. Should I try without optifine?

**Comment by Mithion** [comment]
I am going to need the log files to fix this - they're in your instance folder (same directory that includes the "mods" folder), under "logs".

I'll need you to reproduce the issue, then close Minecraft.

Send me the "fml-client-latest.log" file immediately afterward (before starting MC up again)

**Comment by Mithion** [comment]
I got around to looking at this, and figured it out.

You have projectile listed twice in your recipe, once in the shape group, and once in the lower area.  Doing so will cause the spell to do exactly this: fire a projectile, then when it hits, fire another projectile which will do physical and fire damage.

Take out the projectile shape in the lower bar, and your problem is solved.
