### ISSUE TITLE
Instant Client Crash Using Bound Tools to Break Cobweb

### ISSUE THREAD

**Issue by Morpheus1101** [Mithion/ArsMagica2#1003]
AM2 v1.4.0.006

When attempting to use a Bound Axe or Bound Shovel  on a Cobweb the Client immediately Crashes.

Crash Report @ http://www.mediafire.com/view/2w64mp2a1dg9495/AM2.txt

**Comment by Mithion** [comment]
This has been corrected in 1.4.0.007 (dev).
