### ISSUE TITLE
[1.4.0.006] inscription table in multiplayer

### ISSUE THREAD

**Issue by Qendivardo** [Mithion/ArsMagica2#1007]
In the past, we could use the inscription table to write spells cooperatively -- players specializing in different skill trees could input their shapes, components and modifiers to write complex spells. When we tried doing this in the current version, the table's gui didn't show other players' spell parts, only the stuff you put in there yourself. The unfinished spell recipe book doesn't contain a partial recipe either.
Upon finishing the spell recipe book, only the parts added by and visible to the player taking out the book are in it.

**Comment by Mithion** [comment]
This functionality is intentional.
