### ISSUE TITLE
[1.4.0.006] spell issues: drought, daylight, moonrise

### ISSUE THREAD

**Issue by Qendivardo** [Mithion/ArsMagica2#1008]
Contrary to the compendium text, the drought spell does not turn dirt into sand, this only works on grass (and if you're lucky, a dirt block that randomly turned into grass just before the spell hit).

The daylight and moonrise effects reset the world time instead of advancing to the next morning/evening, thereby also resetting the phase of the moon which is relevant for moonstone meteors. Other mods might be disturbed by this sudden travel back in time, too, but I do not know any example.

**Comment by Mithion** [comment]
Daylight and Moonrise now move time forward to the next interval instead of resetting.
The compendium has been corrected.

**Comment by Mithion** [comment]
Correction:  The compendium was correct, drought has been changed to work on:
dirt, grass, mycelium, sandstone (=> sand)
stone (=> cobblestone)
