### ISSUE TITLE
Effect particles not matching spell

### ISSUE THREAD

**Issue by leegee1080** [Mithion/ArsMagica2#1010]
When I cast a spell like slow fall I get the "Spikey" buff. When I cast jump boost I get the "Sticky Items" buff. When I drink a mana potion I get the "Hellfire Aura" buff.

It seems that none of the spells give the correct buff/particles effect.

**Comment by leegee1080** [comment]
I am using 1.4.0.006

**Comment by Mithion** [comment]
You have a potion ID conflict.  Check the configs of your mods for potion IDs and make sure that none of them overlap.

**Comment by leegee1080** [comment]
Cool! Thanks!
