### ISSUE TITLE
Crash with latest version of this mod and latest version of Buildcraft 6.3.2

### ISSUE THREAD

**Issue by crunkazcanbe** [Mithion/ArsMagica2#1012]
Like the title says and here is the crash report http://pastebin.com/mGzT2Qvf

This does not happen with BuildCraft 6.3.1 and earlier versions . BTW I dont know if this is on your end or Buildcraft so I am posting this report on both GitHubs

**Comment by Adaptivity** [comment]
Fixed on BC side

**Comment by Mithion** [comment]
Well that makes it easy.
