### ISSUE TITLE
Ender Affinity - nightvision too powerful (Request)

### ISSUE THREAD

**Issue by Iivaitte** [Mithion/ArsMagica2#1016]
at full ender affinity, the night vision keeps ticking on and off, its really annoying an it lags in some areas. Will you please lower the light level at which night vision activates to that of monster spawn?

AM2 - 1.4.0.006

**Comment by kiomadoushi** [comment]
(or give it a little longer time)

**Comment by Iivaitte** [comment]
nah, I'm sure at what I'm asking

**Comment by Mithion** [comment]
The light level is set for anywhere mobs can spawn, and is intentional. I've increased the duration so it doesn't flicker as much.

**Comment by Iivaitte** [comment]
ty
