### ISSUE TITLE
Unable to disable buff/debuff display

### ISSUE THREAD

**Issue by twothe** [Mithion/ArsMagica2#1017]
If other mods are installed to show buffs/debuffs it would be good to be able to disable the AM2 buff/debuff display, however I can't seem to find a config option for that.

I currently set the X position to 2 as a workaround.

**Comment by Mithion** [comment]
Type /amuicfg in-game and click options. You can drag the ui elements wherever you like and toggle them on/off. You're looking for the "show buffs" option.

**Comment by twothe** [comment]
Call me blind, but I don't see that option:

![amuicfg](https://cloud.githubusercontent.com/assets/1131621/5897690/30098a64-a547-11e4-996b-2c8601ff587e.jpg)

**Comment by Mithion** [comment]
Wow, did I ever word that badly in-game. It's the "durations" button.

**Comment by twothe** [comment]
Yes I agree that "show buffs" would have been a bit more obvious. ;)

**Comment by Mithion** [comment]
I'm going to consider this resolved. I've changed the button text to be more clear too.

**Comment by twothe** [comment]
Thanks!
