### ISSUE TITLE
[1.4.0.006] duplication and item loss when leaving the End

### ISSUE THREAD

**Issue by Qendivardo** [Mithion/ArsMagica2#1018]
When a player leaves the End by the exit portal, soulbound items are restored to the state saved when they were last stored in a death event. This will duplicate them if they were moved to a different slot by now, but also overwrite any item that now occupies the slot a soulbound item was saved with.
This might have been fixed in respone to issue #770 already, but I'm not sure about that.

**Comment by Mithion** [comment]
This is because no death event is thrown by minecraft even though the character dies and is respawned. The coremod fixes this issue in 1.4.0.007.
