### ISSUE TITLE
1.4.0.006 Armor Imbuement 

### ISSUE THREAD

**Issue by Hellhound732** [Mithion/ArsMagica2#1019]
In a multiplayer server I have been playing on for quite some time now I have just created an armor imbuement table and tried to imbue my armor, only to find that it has no experience in it. My player has over 50 levels from killing monsters and if I read correctly in the compendium it said that it gains levels as you do. My armor however, has not gained any xp in any way. I do not know if there is any specific way to give the armor experience, but I would very much like to imbue my armor, especially the armor you get from the bosses that don't have any armor stats.

**Comment by Iivaitte** [comment]
This is a known issue, it was disabled recently.

**Comment by Mithion** [comment]
Known issue fixed in dev
