### ISSUE TITLE
Fly/Leap bug

### ISSUE THREAD

**Issue by mrbeezly** [Mithion/ArsMagica2#1020]
A spell with fly or leap makes a bug that's makin' effects slow, and hunger. I think its something 
about potion.csv. Help?

**Comment by Mithion** [comment]
It's a potion id conflict. You'll have to check configs and make sure none are overlapping. You shouldn't have any potion ids from mods below 32.

**Comment by mrbeezly** [comment]
Hey,
 Thanks for replied! I changed the potion.csv, moved 1-32 to the
end(130-162) and changed 1-32 to null,null,null,null and testing
and still did it, and a did changed a new potion.csv deleted 1-32 and
testing -still- did it. I don't know what configs to check? Any
help you have is appreciated, but you don't have to! Awesome job with the
mod. :)

**Comment by Iivaitte** [comment]
please list some mods you have installed. 
Also list the version of forge, minecraft and ars magica 2 you are using.

**Comment by Gunner76th** [comment]
Correction to livaitte's post, you need to list ALL mods you have installed, not just some. Typically when you submit a bug report you need to submit the following in addition to the narative text describing the bug/crash:

Any log files, preferably posted to http://www.pastebin.com or http://gist.github.com

OS the client is running, OS the server is running (if a server is involved)

Version of Java in use on the client and the server (if a server is involved)

Version of Minecraft in use

Version of forge in use

List of ALL mods in use, preferably posted to either http://www.pastebin.com or http://gist.github.com

By providing all of the above information you can save everyone time as they will not need to play message tag with you asking for different bits of information. It also allows the mod author to get a rather clear and complete picture of the situation, and in most instances, they are able to know within minutes of reading your report what happened.

**Comment by Mithion** [comment]
This is a potion ID conflict.  Potion IDs are configurable in 1.4.0.007 (Dev).  Until then, change the configs for the other mods.
