### ISSUE TITLE
True Sight Does not grant visibility of invisible entities

### ISSUE THREAD

**Issue by Iivaitte** [Mithion/ArsMagica2#1021]
The Title says it all, sorry for reporting so much recently, but the idea of this being the final update has really sunken in. Just reporting what I can if I don't see the issue resolved in an older report.

Note: Illusion blocks work as intended (in regards to True Sight)

1.7.10
Forge 10.13.2.1232
AM 1.4.0.006

**Comment by Mithion** [comment]
This would be nice but would require more asm changes, and as a result will not be added.

**Comment by Iivaitte** [comment]
TY Mithion, if there is a way I could make a plugin for ars magica 2 let me know.

**Comment by Mithion** [comment]
Quite easily, using the api when it comes out. An sample mod and an early version of the api is available at https://github.com/Mithion/APIDemoMod. You'd be interested in the potion helper in the api which will allow you to ask am2 what the id of true sight is. From there you can check isPotionActive and do whatever from there.
