### ISSUE TITLE
Illusion block damages

### ISSUE THREAD

**Issue by Iivaitte** [Mithion/ArsMagica2#1022]
Illusion block damages player, however player can walk through "occasionally"
There are many instances where even with true sight you cannot walk through the block.
The quirk with this is that you can only walk through if you are walking east.

Tested in singleplayer and on server.
Tested in multiple directions in many environment including:
underwater, around sand, stone/cobblestone/brick, and dirt.

Besides being difficult to determine texture usually providing a "missing texture" texture, damaging players and only allowing players to walk through east, functions normally.

AM 1.4.0.006
Forge 10.13.2.1232
Minecraft 1.7.10

**Comment by Mithion** [comment]
Corrected in 1.4.0.007 dev
