### ISSUE TITLE
Unable to add blocks to a dig blacklist

### ISSUE THREAD

**Issue by twothe** [Mithion/ArsMagica2#1024]
The AM2 dig spell is able to dig certain blocks which should not be dig-able, i.E. Thaumcraft nodes, or Environmine gases, however there is no black list for the dig spell, only for appropriation (whatever that is).

**Comment by Iivaitte** [comment]
Thaumcraft nodes are mineable, they turn into essence. Gasses however shouldn't be.
Please list which version of ars magica 2 you are using, as well as minecraft and forge version.
 If you have any modifiers on the spell let me know.

**Comment by Mithion** [comment]
Am2 does have a dig blacklist. it's in the config under dig_blacklist.

**Comment by twothe** [comment]
There is indeed a blacklist... sorry for not seeing that in the first place.
