### ISSUE TITLE
Charming enemies can cause a server crash

### ISSUE THREAD

**Issue by twothe** [Mithion/ArsMagica2#1026]
I did experiment with the charm spell and have a feeling it is not yet fully implemented:
- Enemies which are in pursuit will still attack you if charmed.
- Neutral enemies will not bread if charmed.
- Sometimes charmed creatures just drop dead (seems like when they are out of range).
- When I charmed a Zombie then run away the server crashed with this error: http://pastebin.com/iMAzdMf8

**Comment by Mithion** [comment]
This has already been fixed in 1.4.0.007 (Dev)
