### ISSUE TITLE
Potion ID conflict with Minechem

### ISSUE THREAD

**Issue by plazia** [Mithion/ArsMagica2#1027]
For some reason with AM2 (My favorite mod btw) installed, whenever I quaff a penicillin vial in Minechem I get Strength buff. It's supposed to be like 30 odd seconds of Regen. Someone suggested it could be AM2 causing the issue. Not wanting this to be true I reluctantly removed the mod from my setup and sure enough; drinking penicillin now gives Regen.

I think the code you did to make the potion ID array scanning thing may need a look at.

I thought I could simply go into the Ars magica 2 config file and change potion IDs myself in there but unfortunately I couldn't see anything like that.

Modpack Resonant Rise 3
manually added the AM2
MC 1.7.10

**Comment by Mithion** [comment]
Potion IDs are configurable in 1.4.0.007 (dev).
