### ISSUE TITLE
Magician's Workbench Bucket Duplication

### ISSUE THREAD

**Issue by Paul17041993** [Mithion/ArsMagica2#1029]
Any recipe utilising a bucket of fluid will duplicate the fluid bucket while also still giving back an empty bucket to the player inventory, the fluid bucket remains in the crafting grid, where it should have been destroyed.

Confirmed at least occurs with the TF Enderium recipe.

**Comment by Mithion** [comment]
In testing I couldn't seem to replicate this, but I am also not sure if I am doing it right.  Is this issue persisting in .008?

**Comment by Paul17041993** [comment]
I'll have to get back to you on that, but what have you tested it with and what mod version/s?

**Comment by Mithion** [comment]
I added a dummy recipe that took a water bucket (which would leave the empty bucket afterwards), tried crafting it, and it worked fine.  Just using AM2, no other mods.

**Comment by Paul17041993** [comment]
latest version of AM2 and the bug still exists and confirmed to work with both the standard and upgraded tables, example screenshot where I've done two crafts, one on each table, and ended up with a dupe copy of the ender bucket on each table;
http://i.imgur.com/p2ZEzdD.png

simply put the ender bucket/slot is never deleted/nulled.

**Comment by Paul17041993** [comment]
to add more confirmation; when using a water bucket with an Applied Energistics 2 cable (always crafts the fluix version of the cable in question), the result is identical, the water bucket is duplicated, essentially in this particular recipe means you can get an infinite amount of buckets. Put a stack of cable in with one water bucket and hey presto! 4 stacks of 16 buckets...

**Comment by Mithion** [comment]
Alright, will try again to fix it.

**Comment by jjtParadox** [comment]
This issue has been resolved and should be marked as closed.

**Comment by Mithion** [comment]
Corrected by #1235
