### ISSUE TITLE
Odd issue with light spell

### ISSUE THREAD

**Issue by DLemberg** [Mithion/ArsMagica2#1031]
Not sure if this is working as intended or not.  If I cast a basic touch + light spell in AM2 1.4.006, it creates a glowing sphere as expected.  If I punch the sphere it goes away... visually at least.  But periodically it comes back on its own, and if I place a block where the light was, the light immediately pops back blocking the block placement.  However, using the dig spell works to remove the light totally, allowing you to place blocks again.

**Comment by Hades99** [comment]
that is intended functionality

On Fri, Feb 6, 2015 at 7:39 AM, DLemberg <notifications@github.com> wrote:

> Not sure if this is working as intended or not. If I cast a basic touch +
> light spell in AM2 1.4.006, it creates a glowing sphere as expected. If I
> punch the sphere it goes away... visually at least. But periodically it
> comes back on its own, and if I place a block where the light was, the
> light immediately pops back blocking the block placement. However, using
> the dig spell works to remove the light totally, allowing you to place
> blocks again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mithion/ArsMagica2/issues/1031>.
>



-- 
Eli

**Comment by Mithion** [comment]
This is not intended functionality, but was reported in another issue already.
It has been fixed in 1.4.0.007 (dev).
