### ISSUE TITLE
Summoning Fire Guarding is difficult because the water essence gets destroyed by lava

### ISSUE THREAD

**Issue by twothe** [Mithion/ArsMagica2#1033]
I recently tried to summon the Fire Guardian in the nether. While I was successful eventually, it turned out that unless you throw the required water essence in a high arc, there is a good chance it will get burned in the lava before the game registers it and spawns the Fire Guardian. Effectively you will need to throw several essences until you get lucky.

Note: I am playing on a server, so additional lag might factor in.

**Comment by Mithion** [comment]
Corrected in 1.4.0.009 (dev)
