### ISSUE TITLE
Suffocation 

### ISSUE THREAD

**Issue by Lusaphor** [Mithion/ArsMagica2#1035]
In .007 as with .006 small size morphs, bat, chicken, etc are suffocating in the ceiling if the are near it, ie 1x1 spaces or where Steve's head would be if not in a morph. Disabling shrink in the skill.cfg did not change anything, except making shrink unavailable.  Tested on both Single player and Multiplayer servers. 
http://pastebin.com/BRyhX4bH

**Comment by Mithion** [comment]
Please try this build with Shrink disabled:
https://www.dropbox.com/s/6vihegwd561r2ab/1.7.10_AM2-1.4.0.008.jar?dl=1

Let me know if this resolves the issue.

**Comment by Lusaphor** [comment]
Yes that version, once i change shrink to false in the config, worked and there is  no mismatched character heights or suffocation.
