### ISSUE TITLE
Mage robes un-dyeable 

### ISSUE THREAD

**Issue by Iivaitte** [Mithion/ArsMagica2#1036]
AM2 1.4.007
Forge 10.13.2.1232
Minecraft 1.7.10

Title says it all.
Congrats on the release today though, it was really nice to see everything important working today.

**Comment by Mithion** [comment]
They're not meant to be dyeable...did I mess up on the compendium entry?

**Comment by Iivaitte** [comment]
The compendium doesn't say that so Ill take that at face value.
However I will point out post number #7734 on minecraftforum that you said the intent is for them to be dyeable.

**Comment by Mithion** [comment]
Yup, but I ran out of time...so that was one of the things that got cut.
Sorry for the confusion :(

**Comment by Iivaitte** [comment]
nah, its good, It'll give people an easy project for using the api
