### ISSUE TITLE
Cycle through spells action (hotkeys?) behaving incorrectly.

### ISSUE THREAD

**Issue by Deadgye** [Mithion/ArsMagica2#1041]
Playing on version 1.4.0.008, minecraft version 1.7.10. I made an instance with only Forge and Ars Magica 2 installed and still experienced the problem.

The action to cycle forward through the spell book via hotkeys (key.SpellBookNext) is functioning properly, however trying to cycle backwards through a spell book via hotkeys (key.SpellBookPrev) cycles through forwards as opposed to backwards. Cycling with the mouse wheel behaves appropriately, able to cycle previous and next.

**Comment by Mithion** [comment]
Corrected in 1.4.0.009 (dev)
