### ISSUE TITLE
Keystone Portal doesn't render in SMP

### ISSUE THREAD

**Issue by GrinningMoon** [Mithion/ArsMagica2#1042]
Using build .008 and opening (right-clicking) the portal on a barebones minecraft forge server doesn't render the portal visual. Passing through the portal still triggers the sound and the teleport. 

I've tested it on SP and the portal does render. I've tested it on a server on both a dedicated box and on the same machine that I played single player on. Both do not render the portal.

I've searched this repo, minecraftforum, google, and the AM2 OP and haven't found anything regarding this.

**Comment by Mithion** [comment]
Corrected in 1.4.0.009 (dev)
