### ISSUE TITLE
Mobs spawning in inappropriate Dimensions (and in excessive numbers)

### ISSUE THREAD

**Issue by Durpady** [Mithion/ArsMagica2#1043]
I was testing out AbyssalCraft with AM2 installed, and Dryads and other AM2 mobs (and Witchery Hobgoblins, I need to bug them about this too) were spawning, and they don't despawn.  Ignoring the fact that friendly-looking nature spirits do not belong in a cross between the End and "The Binding of Isaac: Rebirth"'s Dark Room, the fact that they don't despawn means that (especially in Peaceful) there will eventually be so many of them that the game begins choking.  In the picture, only Dryads are shown, but outside of Peaceful other mobs will spawn too.  Now, I've gone into the config and disabled WorldGen for these dimensions, but it (or a new option) should also disable mob spawning.
![2015-02-07_02 24 24](https://cloud.githubusercontent.com/assets/10343498/6094695/d54ac14e-af03-11e4-804a-cb4ba259d095.png)

**Comment by Mithion** [comment]
There already is a dimension blacklist in the config.

**Comment by Mithion** [comment]
Correction:  I added it as an IMC option, not a config option - my mistake.

**Comment by Mithion** [comment]
There is now an option in the config file that can make dryads despawn.
Otherwise, have the other mod author send an IMC to arsmagica2 with the key "dsb" and the data "am2.entities.EntityDryad|<dimenion_id>" (or create a small mod to do this on your own).

**Comment by Durpady** [comment]
Is there an identical IMC for Mana Elementals?  I didn't get them in the screenshot, but they were spawning too.

**Comment by Mithion** [comment]
mana elemental would be am2.entities.EntityManaElemental
