### ISSUE TITLE
Dig spell permanently destroys specific blocks

### ISSUE THREAD

**Issue by Masti6** [Mithion/ArsMagica2#1044]
When using a Dig spell on blocks such as Everstone, the block isn't dropped but still disappears. 
This used to happen with OpenBlocks tanks but it no longer seems to be the case.
Also, when using silk touch dig spell on an Ethereal Illusion Block it becomes a unique (non-stackable) Illusion Block instead.
Version 1.4.0.008.

**Comment by Mithion** [comment]
Corrected in 1.4.0.009 (dev)
