### ISSUE TITLE
Particle Emitter not working as intended

### ISSUE THREAD

**Issue by Masti6** [Mithion/ArsMagica2#1045]
While right-clicking a Particle Emitter with empty hand or with any other item in hand, nothing happens.
While left-clicking (hitting) it, it disappears for a second and then comes back with no particles inside it.
Same while having a Crystal Wrench in hand.
And because attacking it causes it to only temporarily disappear and soon reappear, it is impossible to destroy it.

**Comment by Mithion** [comment]
Fixed in 1.4.0.009 (dev)
