### ISSUE TITLE
Suggestion: give a small damage immunity window after being hit while mana shield is active

### ISSUE THREAD

**Issue by Ipkcle** [Mithion/ArsMagica2#1047]
it might be intentional, but melee mobs will burn though mana shield really quickly due to the fact that there is no delay between their attacks, while ranged mobs do basically nothing in comparison

**Comment by Mithion** [comment]
Mana can be made to regenerate exceptionally fast, and I don't think you should be able to make yourself completely invulnerable using mana shield - it's kind of an equalizer in terms of balance.
