### ISSUE TITLE
Removing other mods that add potion effects causes ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Keyarose** [Mithion/ArsMagica2#1051]
Using AM2 with other mods that add potion effects appears to set the potion effect ids in the AM2 config file.  Then when removing one of the other mods it requires the config to be regenerated or the potion effect ids will be outside the bounds of the array.  This issue was not found when using AM2 1.4.0.006

Current version of AM2 1.4.0.008
Crash report: http://pastebin.com/xdfPf1q2
Mods removed to cause this crash:
-BloodMagic-1.7.10-1.3.0b-3
-Sanguimancy-1.7.10-1.1.8-4

**Comment by Mithion** [comment]
Configure your potion IDs to be something else, or delete the section in config and let it re-generate.
