### ISSUE TITLE
World being taken over by Dryads

### ISSUE THREAD

**Issue by DLemberg** [Mithion/ArsMagica2#1052]
Not sure what is causing this... I'm using Minecraft 1.7.10, Forge 1291, and Ars Magica 2 1.4.008, and dryads are gradually taking over the world.  See below screen shot of me standing in a swarm of them, with about 30 visible.  I believe the issue is that their is no limit on how many spawn, and nothing kills them, so there are just more and more.  But they also seem to spawn a lot more frequently than the AM2 config file would suggest.

![2015-02-08_15 45 51](https://cloud.githubusercontent.com/assets/10882883/6098383/6b36319c-afaa-11e4-8fee-433c95c81e99.png)

**Comment by DLemberg** [comment]
Another example... I'm wondering if this has anything to do with me mostly being in desert.

![2015-02-08_16 46 50](https://cloud.githubusercontent.com/assets/10882883/6099295/891d63f2-afc2-11e4-9d23-6d42527a66a8.png)

**Comment by Mithion** [comment]
I've never seen that many in my test world (and 60% of the exploring was in deserts)...I think a mod may be causing spawning to work differently.

you can also simply turn dryads spawn rate down (or off) in the config.  You'd still need a third party mod to remove the existing ones.

**Comment by Iivaitte** [comment]
or command blocks /kill @e Dryad

**Comment by TherminatorX** [comment]
@livaitte That's a MC1.8 feature, not helpful.

**Comment by Mithion** [comment]
I changed whether or not dryads can despawn to an option in the config - now people can tailor it to their needs.

Between that and a configurable spawn weight, that's all the attention this is getting from me.  If other mods mess with spawn code and the like...not much I can do.

**Comment by DLemberg** [comment]
Thanks Mithion.  I'll drill into it on my side and figure out if I can find
the offending mod.  If I find out which one is doing it, I'll let you know
just as an FYI.

**Comment by mizziness** [comment]
Just to add  my experience, I had over 2000 dryads around my home base - I had to use the cofh command to kill them all because the game became legit unplayable.  -_-
