### ISSUE TITLE
Morph conflict - Player hitbox issue

### ISSUE THREAD

**Issue by rob5251** [Mithion/ArsMagica2#1053]
There seems to be some conflict between AM2 and Morph causing player hitboxes to be incorrect when morphed. Not sure if this has to be fixed on AM2's side or Morph's. I noticed it is reported on their end though.

https://github.com/iChun/Morph/issues/674

When morphed, the player seems to be one block higher than they should be, causing suffocation and incorrect aiming.

**Comment by Mithion** [comment]
Disable shrink in SkillConf.cfg to resolve this issue.

**Comment by rob5251** [comment]
Thanks. :+1:
