### ISSUE TITLE
Dig spell ignores blacklist (or parts of it)

### ISSUE THREAD

**Issue by twothe** [Mithion/ArsMagica2#1054]
With the latest release 8 the dig spell does no longer seem to obey the blacklist.

Current blacklist:
     S:dig_blacklist=Thaumcraft:blockAiry, ExtraUtilities:drum, adventurebackpack:blockBackpack 

The Thaumcraft nodes are ignored (or probably not hit at all), all others are destroyed like the list does not include them at all.

**Comment by Mithion** [comment]
The code has been changed to resolve blocks from the registry by name using:

Block.blockRegistry.getObject(name);

More information is also provided in the logs when either succeeding or failing.

**Comment by twothe** [comment]
Shouldn't that be 
```Java
    GameData.getBlockRegistry().getNameForObject(block)
```
Although that might have been changed in Forge, it's from an older 1.7.10 code.

**Comment by Mithion** [comment]
No, that goes the other way - that is what would give you the block's name to put on the blacklist.
I need to go from a string to a block, not a block to a string.

**Comment by twothe** [comment]
Right... need more coffee. Sorry. ;)
