### ISSUE TITLE
No description in Arcane Compendium on how to do rituals

### ISSUE THREAD

**Issue by twothe** [Mithion/ArsMagica2#1056]
With the (default) incremental compendium there is no description on how to do the rituals to convert your obelisk into a light or dark obelisk, the compendium just mentions at several points that it can be done but not how.

No matter what you create or do the chapter for rituals (if it exists) will never appear in the compendium.

**Comment by Mithion** [comment]
Structures -> Rituals

**Comment by twothe** [comment]
![structures](https://cloud.githubusercontent.com/assets/1131621/6108814/64f6a718-b076-11e4-9b5f-2cb9b2ad8ae1.jpg)

Nope, it's not there.

**Comment by twothe** [comment]
This was done in normal survival in 006, with then an update to 008. Not sure why this was never unlocked, but I think many other survival players will have the same issue.

**Comment by Mithion** [comment]
Quite possibly - it is "linked" to celestial prisms, otherworldly auras, gateways, and obelisks.
Crafting any of these items or using them with right click should unlock the related entries.

If you want to link it to something else, you can simply add it to the "relatedEntries" section in the compendium XML.  For example:

http://pastebin.com/T6EBXCZL

This can be done without re-releasing the mod, as it supports standalone automated compendium updates (if the client allows it in the config, which it is).

**Comment by twothe** [comment]
I actually crafted another Obelisk, placed it, dropped it and picked it up again all in 008 but still the entry was not unlocked.

**Comment by Mithion** [comment]
Did the command work?

**Comment by twothe** [comment]
Yes the command worked.

**Comment by Mithion** [comment]
Okay, this is kind of a stupid question, but when you tried dropping/picking up/etc. you hadn't run the command already right?

**Comment by twothe** [comment]
No, and I double-checked before I run the command that it was a) not in the compendium and b) placing and picking up the Obelisk did not make it appear.

**Comment by Mithion** [comment]
Placing the obelisk wouldn't do it - you would have to actually open the UI (activate the block, basically).

That's a moot point however, since picking it up should have done it.

**Comment by Mithion** [comment]
BTW I appreciate all the testing you're doing - thanks!

**Comment by twothe** [comment]
My pleasure. =)

**Comment by Bahzur** [comment]
Reading this, on another note, i noticed some derpy behaviour with the compendium unlocks (which ultimately made me disable the staged compendium unlocks): Every time i rejoined the server and did something AM related, that appropriate entry "unlocked" again (popping up the toast on the upper right side) and marked it as new in the compendium, which was annoying. And i remember being in a dead end when i wanted to craft a obelisk (maybe that, or something other, i dont remember exactly), which i only was able to see the recipe through crosslinks in the compendium (the "also see this" section on descriptions for other things).
I had to relog twice for the compendium to unlock fully after the configchange, and everything is there (i hope, i cant be sure as im new to AM2 ^^) except the spell shapes, components and modifiers i dont know yet (but they seem to unlock at the right time when i learn them (and the following skills further down the line)). And the additional new entry toasts stopped after that, ofcourse.

**Comment by Mithion** [comment]
Compendium unlocks will be completely re-done as part of the 1.9 upgrade.
I recommend turning off staged compendium until then.
