### ISSUE TITLE
Ars Magica mobs spawn dimension

### ISSUE THREAD

**Issue by CrowAU** [Mithion/ArsMagica2#1059]
I posted this issue on the witchery mod forum post also, but he insisted it's not witchery's fault.

Having Twilight Forest, Ars Magica 2 and Witchery installed causes Ars Magica 2 mobs [Mana elementals, Mana creeps etc...] to spawn in twilight forest only and not in the overworld. this issue however is completely fixed by removing witchery. I'm posting this here on the off chance [or maybe not so off] that it's the mod that the mobs belong to is having a weird interaction with witchery and witchery is working fine. On a side note this same thing happens with gravestone mod forcing the zombie dogs and other mobs from the mod to only spawn in the twilight, but removing witchery fixes this also.

**Comment by CrowAU** [comment]
Uh turns out Ars Magica mobs are actually still spawning in the overworld but they're spawning in the twilight forest with witchery installed, something I don't want to happen.

**Comment by Mithion** [comment]
There is an IMC mod devs can send to AM2 to prevent mobs from spawning in certain dimensions.
The key is "dsb" and the value is "entity_class|dimension_id".

For example:
"am2.entities.EntityManaElemental|7"
