### ISSUE TITLE
Jumping through a gateway with not enough essence is freezing the server.

### ISSUE THREAD

**Issue by ryukra** [Mithion/ArsMagica2#1062]
Forgeversion: 10.13.2.1232
AM2: 1.4.0.008

We reproduced this error alot and this are the fact:
-Jumping with enough etherium is working.
-Jumping without etherium result in freeze after 5 seconds.
-An AM2 User with Magitech Googles can't see saved essence anymore in any devices after the failed jump, even if someone other is jumping through it.
-No logs were made after the freeze.

**Comment by Mithion** [comment]
Log files, please.

**Comment by ryukra** [comment]
I need to say that it occurs in SMP. SP is not tested.

This modpack is hidden.. I dont want someone to get this, but here are the links to it.
http://www.technicpack.net/modpack/ryukraft.510383
www.drakyn.de/ryukraft1.0.1beta.zip

modsfolder as tree:
http://pastebin.com/Yah8H0Nw

fml-server-latest last bit after server loaded up fully:
http://pastebin.com/9WDeQ6TE

**Comment by Bahzur** [comment]
Whelp, that just happened to me too! I have other mods for means of transportations, but AM2 Portals have more style so i put one at our base and one at spawn, hooked a new celestial prism to the one at spawn, then clicked it. I had a moment of doubt if the measly amount of etherium was enough even though the spawn is not far from the base and hoped through, with nothing happening. I immediately remembered that i had seen something on the bugtracker about that, tried to brake a block for at test and landed on the main menu with a lost connection. Even though the serverbrowser saw the server after that, reconnecting didnt do anything and timed out. Then i opened the remoteconsol looking for a crashnotice, but there was nothing, and trying to "/stop" the server or "/say test" also did nothing (completly frozen). Had to kill the javaprocess remotely.

I then looked into the logs, but theres absolutly nothing except the notice that the server was stopped!
Heres the modlist: http://puu.sh/h8Kax/63d2b734ae.png
I can provide you the modpack too if you need to.

**Comment by Mithion** [comment]
This seems to be tied to worldgen, as a gateway with not enough essence will only transport you part of the way there.

I recommend turning off "Hazardous Gateways" in the config to prevent this issue.

The hazardous gateway functionality has been removed in 1.4.0.009 Dev, and instead a gateway with not enough essence will simply send you nowhere at no cost with a chat message indicating insufficient power.

**Comment by ryukra** [comment]
With Hazardous Gateways turned off, the gateway doesn't work anymore, even with enough etherium. At least when I tried the config full of joy. Didn't hold long. :D
