### ISSUE TITLE
Appropriation doesn't work with nether-blocks.

### ISSUE THREAD

**Issue by Deadgye** [Mithion/ArsMagica2#1063]
When trying to use Appropriation in the nether (Only tested with Projectile Apprioriation) I receive this error when trying to release any block: "Something went wrong restoring the block. This spell was likely a spell from an older version. The stored block has been cleared to prevent a crash, and the spell should work moving forward. Sorry!" The spell functions perfectly fine in the overworld.

I made a fresh instance with MultiMC to confirm the above behavior. Minecraft version 1.7.10, Forge version 10.13.2.1307-1.7.10, Ars Magica 2 version 1.4.0.008, AnimationAPI 1.7.10-1.2.4.

**Comment by jawdylawdy** [comment]
Interestingly, the spell actually does work perfectly fine in the nether, it just can't seem to place nether-related blocks (nether quartz ore, netherrack, soul sand, etc.). I carried over a block of grass from the overworld and I was able to move, remove, and repeat as I wished, but as soon as I tried to get a nether block it stopped working.

**Comment by Deadgye** [comment]
Didn't even think to test that. The first block that brought this to my attention was sunstone ore. Tried bringing something nether-blocks to the overworld to see if it still gives the error (it does). Also tried giving myself some nether-blocks with /give and placed them in the overworld. Still got the same error upon trying to place them.

**Comment by Mithion** [comment]
I'll see if I can replicate this.

**Comment by Mithion** [comment]
Corrected in 1.4.0.009 (dev).
