### ISSUE TITLE
8k µs update time for the AM2 Handler

### ISSUE THREAD

**Issue by Neodark7** [Mithion/ArsMagica2#1066]
![am2](https://cloud.githubusercontent.com/assets/7981869/6140971/3ef61ac4-b19f-11e4-9c7c-856c3e1adf3a.PNG)

**Comment by Bahzur** [comment]
Why is that an issue?

**Comment by Neodark7** [comment]
i have nothing related of ars magica in my base so it's probably an issue if i have so many update time...

**Comment by Bahzur** [comment]
I see. But i guess that is still not very much, compared to the other mods.

**Comment by Mithion** [comment]
I wouldn't even consider this an issue...AM2 does stuff in the background even if you aren't actively using it (mobs, worldgen, tick handlers analyzing the world, etc).
