### ISSUE TITLE
Runes float in the air

### ISSUE THREAD

**Issue by Bahzur** [Mithion/ArsMagica2#1067]
Im not entirely sure if thats a bug, but i guess it is:
![2015-02-11_06 18 53](https://cloud.githubusercontent.com/assets/4956200/6142420/87b624e0-b1b6-11e4-99d7-2111f1226bd2.png)
I placed some blocks around the rune to make it more visible, the rune is floating half a block above the block i placed it on.

**Comment by Mithion** [comment]
I can't seem to replicate this issue - I did make some changes to runes in 1.4.0.009 which seem to have solved the issue before I even got to it!

Going to close it as resolved, but as usual if you encounter it again, please post accurate precise steps to reproduce it, and we'll see what can be done.

**Comment by Bahzur** [comment]
How lucky! :D
