### ISSUE TITLE
soulbound items duplicated or lost, loss of other items

### ISSUE THREAD

**Issue by Qendivardo** [Mithion/ArsMagica2#1068]
In 1.4.0.008, when leaving the End, soulbind items stored in the most recent death are still restored, possibly resulting in duplication of the soulbound items and loss of whatever has been moved into the slots since then.
In response to #1018 you mention this being fixed in a coremod. Is this a different file than the 1.7.10_AM2-1.4.0.008.jar that is linked in the original post of the AM2 thread on minecraftforum.net?

Also, if between the events of a player's death and respawn the server is restarted, soulbound items are lost, since the death event handler deletes them from the inventory and soulbound storage is not saved to disk.

**Comment by Mithion** [comment]
Point 1 I can look into, point 2 I won't fix.  It's been like that since I added soulbound.  Not dealing with saving to disk and all that...easier to just say don't ragequit.

**Comment by Mithion** [comment]
Related to #1096, tracking progress there.
