### ISSUE TITLE
Config Request - Toggle Witchwoodforest Biome

### ISSUE THREAD

**Issue by GrinningMoon** [Mithion/ArsMagica2#1070]
Mithion,

I understand that you have a pretty firm stance on not allowing the Witchwoodforest Biome to be disabled via the config. I'd like to ask you to please reconsider this. I know it's part of your mod and I'm not trying to bash your work or the dedication that you put into it but I think it may be fair to allow your players to opt-out of it since you'll most likely be leaving us after .009. 

I have some other reasons as well:
- For those that didn't start their worlds with AM2 (I know, blasphemy!), adding AM2 re-configures the terrain generation and can cause random transition chunks.
- In its current state, and correct me if I'm wrong here, I don't believe the biome does what it was intended to do. The biome is full of vanilla oak trees. There are very few "Witchwood" trees, just those that happened to also generate there. This means that Aums are still very rare, which I think the Witchwoodforest was intended to be a biome were they were plentiful.
- Its not easy to disable the biome otherwise. I've tested multiple ways: setting the biome's ID to 0, turning off AM2 world gen, and trying out various external biome-selector mods. All of these still resulted in the biome generating.
- Going off your near departure from AM2. As far as I've seen, you still haven't chosen a successor right? I would guess that would mean that AM2 .009 will be essentially set in stone until someone else picks up the project. The biome won't be tweaked until then.

All that being said, whether it's a yes or no, thank you for your mod! I feel safe in saying that it has brought the minecraft community a lot of enjoyment!

**Comment by Mithion** [comment]
I'll see what's involved.  If it's simple to do, then OK.  If it's going to take a ton of time, then sorry, it just won't happen.

**Comment by GrinningMoon** [comment]
That's reasonable, considering you're sticking around solely to do some last minute bug fixing. Which that alone is very much appreciated!

**Comment by Mithion** [comment]
Witchwood forests are configurable in 1.4.0.009 (dev).  They can be toggled off entirely, or set to be more rare.
