### ISSUE TITLE
1.7.10_AM2_1.4.0.006 Armor not gaining xp, or infused xp

### ISSUE THREAD

**Issue by noobapalooza** [Mithion/ArsMagica2#1072]
Reading a previous report I have attempted to player kill mobs, with swords, magic, bows, etc.

However, no armor types seem to gain xp.

I have tried looking at previous bug reports but couldn't find any solutions.

Any known patches or command work-around?

Also I am glad you are still at it, I am enjoying your work :)

Also is there any way I can make a small donation for you?

**Comment by Mithion** [comment]
Update the mod to 1.4.0.008, that should fix it. 
I appreciate it, but I'm not accepting donations for mc mods anymore. You could buy a copy of my game when it's done and tell your friends about it if you enjoy it :)
