### ISSUE TITLE
Light Colors Don't Always Apply

### ISSUE THREAD

**Issue by dholmes13** [Mithion/ArsMagica2#1076]
I created a spell like this with version 1.4.0.008:

Shape Group 1: Touch
Shape Group 2: Projectile
Shape Group 3: Projectile, Area of Effect
Combination: Light, Color

When casting with one of the first 2 shape groups, it works as expected and the resulting light is lime green. But, when I cast with the last shape group, the resulting lights are the default blue.

**Comment by Mithion** [comment]
This won't be fixed, it's not a game crashing bug.  Sorry.
