### ISSUE TITLE
Winter's Grasp and Nature Scythe not correctly returning.

### ISSUE THREAD

**Issue by YWZMatt** [Mithion/ArsMagica2#1077]
Both the Winter's Grasp and Nature Scythe are thrown and begin to return very smoothly, but once they reach my player, they comedically spin around above me and refuse to return. Sometimes will flying around and moving at high speeds I manage to make them return, but it is extremely difficult.

**Comment by Hades99** [comment]
are you wearing anything like a ring of magnetism or a coin of fortune or
anything like that?

On Mon, Feb 16, 2015 at 10:41 PM, YWZMatt <notifications@github.com> wrote:

> Both the Winter's Grasp and Nature Scythe are thrown and begin to return
> very smoothly, but once they reach my player, they comedically spin around
> above me and refuse to return. Sometimes will flying around and moving at
> high speeds I manage to make them return, but it is extremely difficult.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mithion/ArsMagica2/issues/1077>.
>



-- 
Eli

**Comment by jawdylawdy** [comment]
Both of those things only apply to item entities, not thrown entities.

**Comment by Hades99** [comment]
are you wearing any sort of armor that blocks projectiles, like the TTKAMI
armor or blood magic armor with whirlwind

On Tue, Feb 17, 2015 at 5:57 PM, jawdylawdy <notifications@github.com>
wrote:

> Both of those things only apply to item entities, not thrown entities.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mithion/ArsMagica2/issues/1077#issuecomment-74782451>.
>



-- 
Eli

**Comment by YWZMatt** [comment]
No, only the fire antennae things and earth armor.

**Comment by Mithion** [comment]
This won't be fixed, it's not a game crashing bug.  Sorry.
