### ISSUE TITLE
Spells can't be cast on blocks with interfaces via spell books

### ISSUE THREAD

**Issue by DLemberg** [Mithion/ArsMagica2#1082]
Using AM2 1.7.10 1.4.0.008, if you have a spell such as touch+dig on your action bar and try to cast it on a block with an interface (such as an enchanting table) by right clicking, Minecraft opens the block interface instead of casting the spell.  You can get around this by shift right clicking, which casts the spell on the block.  However, if you put the spell in a spell book, shift right clicking opens the spell book instead.  This prevents you from being able to cast the spell on the block.  Using a different key combination to open the book would solve this.

**Comment by Mithion** [comment]
That was an intentional decision - it's better to open the block's UI rather than accidentally cast a spell on it when you don't want to.

If you start casting the spell while looking at another block, then aim at the block in question and release RMB, the spell will cast.  So it is still possible.

**Comment by trlababalan** [comment]
Please add that as an in-game tip.

**Comment by DLemberg** [comment]
Thanks Mithion, closing this
