### ISSUE TITLE
Harvest Plants component does not seem to work

### ISSUE THREAD

**Issue by Bahzur** [Mithion/ArsMagica2#1083]
While testing things in my AM2-only environment i came across the Harvest Plants component and i tried to make it work in any way i could think of, but no matter what i did, it did nothing. I also tried the Target Non-solid Blocks modifier, did not work too.
Grow, Plow and Wizards Autumn work, though. 
Version is .008
Edit: the Target Non-solid Block modifier with Harvest Plants, with other things the modifier works.

**Comment by Mithion** [comment]
I've written spells that have worked with harvest plants; let me see if I can come up with a few.  Nothing should have changed, so this is strange.

If I can, I'll post them here as examples, and if it's bugged, I'll fix it.

**Comment by Bahzur** [comment]
I'll retry this right now in my AM2only environment, maybe i derped last time.

**Comment by Bahzur** [comment]
I tried the simplest thing i could do: Projectile + Harvest Plants. Casting that does nothing to plants & grass. :(

**Comment by Mithion** [comment]
With that, the projectile would actually go right through the plants and grass and target the first solid block it hit.
A good rule of thumb for when to use TargetNSB - if you can't collide with it, then neither will a spell.  TargetNSB makes spells collide with things that normally aren't collidable.

That being said...projectile + TargetNSB + Harvest Plants isn't working either -_-.  But that's the way it's supposed to work!

**Comment by Bahzur** [comment]
That was the next thing i tried when it didnt work, already had that idea to include the modifier as i said in the OP, but forgot that when i just tested that again. IMHO that component should have that modifier inbuild like Wizards Autumn has with AoE (not sure though, maybe im missing another thing that could be done without it) But yeah, it does not work.

**Comment by justicesays** [comment]
I made a zone + grow +harvest plants. The grow section worked (but only grows crops + grass), but the harvest plants affected the level *below* where the growth was if I targeted the ground, as you stated. It does work if you target a block one above, such as on an higher block of earth. But it *only* works on flowers, not crops. mushrooms, grass, leaves etc.
So growth doesn't grow flowers, only crops, and harvest doesn't harvest crops, only flowers.
Maybe a consistent definition of "plant" might lead to less confusion...

**Comment by Mithion** [comment]
Heh, consistent definition?  You can dream, I suppose.
I believe there was a split made, something about IPlantable, IGrowable, and BlockCrops...I'll have to look closer and see.

**Comment by Bahzur** [comment]
Any news on this bug here?

**Comment by Mithion** [comment]
Corrected in 1.4.0.009 Dev

**Comment by EoD** [comment]
I think this label should be removed and the milestone added. Looking forward to this fix! :)
