### ISSUE TITLE
Summon spell creation uses neutral essence.

### ISSUE THREAD

**Issue by Deadgye** [Mithion/ArsMagica2#1086]
This is either a mistake in the compendium/spell book or a bug in the spell creation process. The compendium and the spell creation book itself lists the summon spell as using 1500 dark essence. However when making a summon spell (projectile summon, using a dryad phylactery and chicken phylactery, is what I tested with) it uses neutral essence. When I do provide it with dark essence it still works, however it uses 3000 dark essence.

I used the previously made MultiMC instance to confirm the issue. Minecraft version 1.7.10, Forge version 10.13.2.1307-1.7.10, Ars Magica 2 version 1.4.0.008, AnimationAPI 1.7.10-1.2.4.

**Comment by Mithion** [comment]
Darn flexible power system...it's designed to use other power types if valid, but the validity isn't properly set here.  I'll look into it.

**Comment by Mithion** [comment]
Corrected in 1.4.0.009 Dev

**Comment by TheWitcher345** [comment]
Hey uh mithion i have a problem. So it says that I need 500 neutral essence to make a certain spell but I dont know how to collect the essence i made the obelisk and mana battery thing and i even paired it to the crafting altar but nothing worked. Please try to reply in the next few hours. Thanks
