### ISSUE TITLE
Purified and corrupted obelisks disappear when broken

### ISSUE THREAD

**Issue by DLemberg** [Mithion/ArsMagica2#1087]
Although Obelisks can be retrieved with a pickaxe and placed elsewhere, when transformed into a Celestial Prism or Black Aurum trying to do the same causes them to disappear, even with a silk touch enchant.  Is that intentional?  Note: Ars Magica 1.4.0.008, Minecraft 1.7.10

**Comment by Bahzur** [comment]
Noticed that too but forgot to post it here.

**Comment by Mithion** [comment]
This was intentional, but since so many people seem to have a problem with it, I'll make them drop when broken.

**Comment by DLemberg** [comment]
Speaking as a user, that would be great - but if you do want to keep it as is, another option might be to make the glass breaking noise when you break them.  Then it would be clear that it is intentional.

**Comment by Mithion** [comment]
These blocks are droppable in 1.4.0.009 (dev)
