### ISSUE TITLE
Stored workbench recipes not working

### ISSUE THREAD

**Issue by DLemberg** [Mithion/ArsMagica2#1088]
When you craft something on a workbench, the crafted item gets added to a tab below the crafting area.  According to the compendium you should be able to click on the tabs and have the pattern reappear as long as you have the necessary ingredients in the internal storage, but left clicking the tab does nothing.  I am wondering if the left and right clicks are cross linked, as the text on the tab says shift right click to lock and unlock, which works, but shift left click also works.

**Comment by Mithion** [comment]
I need more information than this - could you create a short video of the problem happening, or explain a little more thoroughly (ie exact steps to reproduce, what you crafted, etc.)?

**Comment by DLemberg** [comment]
I've isolated the issue; it is a little different than I thought.  Here is how to reproduce.

Create a new world.  Create a magicians workbench.  Get sticks and iron, put in the workbench.  Create an iron pickaxe - a tab is added below the crafting window with the recipe.  Create an iron axe, that's tab 2.  Create an iron sword, that's tab 3.  Create an iron hoe, that's tab 4.  Click X to clear the crafting window.  Should look like this:

![2015-02-23_21 12 15](https://cloud.githubusercontent.com/assets/10882883/6342113/c8d9603c-bba1-11e4-9ef9-0d7e9deeefd7.png)

Now click any of the tabs below (pickaxe, axe, sword, or hoe).  You will get what's on the first tab, the pickaxe.  Here is me clicking the iron hoe:

![2015-02-23_21 21 36](https://cloud.githubusercontent.com/assets/10882883/6342123/ffb8694a-bba1-11e4-8c8b-9c1b16af49b2.png)

![2015-02-23_21 21 38](https://cloud.githubusercontent.com/assets/10882883/6342127/0c5de224-bba2-11e4-982c-a38d6db57913.png)

In retrospect, the reason I thought it wasn't working at all earlier is my first tab had a recipe that I was lacking ingredients for, so none of the tabs would load recipes.

**Comment by Mithion** [comment]
Corrected in 1.4.0.009 (dev)
