### ISSUE TITLE
Appropriation effect has issues with blocks

### ISSUE THREAD

**Issue by DLemberg** [Mithion/ArsMagica2#1089]
Created a projectile + appropriation spell in Ars Magica 1.4.0.008 in multiplayer.  Zapped a tree block, it disappeared, zapped the floor, and the tree block reappeared.  It worked!  Zapped a villager and replaced him - also worked.  Then I went to a zombie spawner and tried to capture it.  Capturing it worked, but when I tried to respawn it I received an error message stating that the block could not be restored, and that perhaps the spell I was using was created with an earlier version of Ars Magica (it wasn't!).  Afterwards the spell was stuck for a while - every time I tried to recast the spell I got the same error message, even though the error message also states that the block had been cleared.  Restarting the server reset the spell.

**Comment by Mithion** [comment]
I'll see if I can replicate this.

**Comment by Mithion** [comment]
Corrected in 1.4.0.009 (dev)
