### ISSUE TITLE
Arcane Spellbook doesn't show active spell effect on hand

### ISSUE THREAD

**Issue by DLemberg** [Mithion/ArsMagica2#1090]
If you make a spellbook and fill it with spells, and cycle through the spells with x and z, you see the active spell effect on your right hand - fire for a fireball, globe of lightning for a lightning bolt, etc.  If you kill an arcane guardian and get a arcane spellbook, all you see is the spellbook itself as you rotate though spells, which is a shame as the spell effect is a great visual cue.  Unsure if this is intentional.

**Comment by Mithion** [comment]
The render type for the arcane spellbook is intentional.
