### ISSUE TITLE
Mages that mind their own business [config suggestion, not bug]

### ISSUE THREAD

**Issue by Darkmega18** [Mithion/ArsMagica2#1091]
Just an option for a configurable "improvement". Because I have terrible terrible OCD when it comes to creeper craters I always find I hear explosions and all sorts of anarchy going on outside when I get above the magic level required to spawn mages because they attack skellies and whatever else have you and then they end up fighting each other. This wouldn't bother me if my skellies didn't have a chance of having explosive arrows, and they didn't have a chance to smacking a creeper right next to my base cause the mages get too excited and then having the creeper inadvertently open my wall and let the bullshit pour in. I normally find myself turning off the mages, but then I miss out on magic duels with dark mages. Would you be able to make a setting that makes the light mages not spawn but keeps the dark mages OR makes the light mages ultra passive and not attack stuff unless attacked first.

Because in my pack theres usually a high volume of mobs cause of the world generation type and as such brawls end up breaking out and destroying the landscape around me without me doing anything and it's annoying as balls to sometimes hear a massive outbreak of various explosions and then go outside to see the place just wrecked. I don't want to have to set them to zero like in my other pack.

**Comment by Bahzur** [comment]
Skellies have a chance to spawn with explosive arrows? O_o
Is that modded?

**Comment by Mithion** [comment]
That's why the spawn weight settings are there, which you already know about.
Even if light mages still attack dark mages, (or retaliate), then there's a chance of something getting caught in the crossfire.

You can also turn off mob griefing, problem solved.

I don't see the point in adding this config; if this is something you really want, you can make a small mod to alter the mages' AI.

**Comment by Darkmega18** [comment]
@bahz, yeah, it's a mine and blade battle gear thing. Among other arrows like diamond arrows that ignore armor values, leeching arrows that give weakness and life steal and arrows that set fires where they land. The explody ones are just a small explosion, only capable of taking out trees and other soft materials, but they're still annoying cause of the bonus knockback and collateral damage that can cause brawls to break out easier.

@mithion: alright. I had a feeling that'd be your view on it. and I suppose I could turn off the mob griefing since it's single player I'm getting this happening in. but in a pvp setting which this modpack has in mind for that'll nullify bullshit like a creeper inundation attack with soul shards, but guess it depends on what the agreed setting are at the time then, since theres always another 100 ways to annihilate someone in my pack. :P

**Comment by ZephaniahNoah** [comment]
@Mithion I'm using Mine & Blade Battlegear 2 ver: 1.0.5.3 and /gamerule mobgreifing flase didn't work.
BUT!
@Darkmega18 You can disable skeletons from spawning with explosive arrows in the config.

"skeleton customarrow spawn rate" {
    D:explosive=0.0
}

**Comment by Mithion** [comment]
That just likely means that M&B mobs don't subscribe to the mob griefing rule.  I'm glad you were able to find a workaround though!

**Comment by ZephaniahNoah** [comment]
@Mithion Me too! They were such a pain...
