### ISSUE TITLE
Enderman still attack on 100% Enderaffinity

### ISSUE THREAD

**Issue by Bahzur** [Mithion/ArsMagica2#1092]
Like title says. The compendium states the opposite, enderman should not attack when your enderaffinity is 100%, but looking at them still aggros them.

**Comment by Mithion** [comment]
I'll see if I can get this to work - it's been problematic and hit and miss from version to version ever since I added it.

If not, I'll have to come up with something else for ender affinity that they can do.

**Comment by Bahzur** [comment]
Ok thx. Any news on the batteriecharge bug?

**Comment by Mithion** [comment]
Not under this issue there isn't ;)

**Comment by Bahzur** [comment]
;P

**Comment by Mithion** [comment]
Ender affinity no longer attempts to prevent endermen from attacking, instead offering other benefits.

Changed in 1.4.0.009 dev
