### ISSUE TITLE
Swift Swim has no effect

### ISSUE THREAD

**Issue by MooseChip** [Mithion/ArsMagica2#1093]
Made a simple Self | Swift Swim spell and, if it has any effect, I'm not noticing it at all. I tried messing with the potion ID's, and then running AM2 by itself in a new world, no change. Love this mod though, thanks for all your work on it~

**Comment by Bahzur** [comment]
Afaik Mithion already fixed that for the next version, see here: #1074

**Comment by Mithion** [comment]
Found out swift swim actually does do something, it's just balanced too low without any buff power modifiers, so the speed increase is negligible.

Makes it a much easier fix.

**Comment by Mithion** [comment]
Corrected in 1.4.0.009 Dev
