### ISSUE TITLE
Enderaffinitie's Nightvision activates just by touching blocks

### ISSUE THREAD

**Issue by Bahzur** [Mithion/ArsMagica2#1095]
Almost everytime i hit the edge to another block or stand in a corner between two blocks or use stairs, the Enderaffinity Nightvision activates regardless of lightlevel. That constant blinking...

Im getting epileptic here, man. :(

**Comment by Mithion** [comment]
It's getting the light level at your head and using that to determine if NV needs to activate.
I could make it an average of the 9 blocks around it, but that could be subject to just as many issues.

**Comment by Bahzur** [comment]
I have another idea: add a small timer, about a second or two. If the lightlevel still is below, activate nightvision. That way bumping into block (a one block high edge also is enough unfortunately to activate it at the moment) wont do much i believe.

**Comment by Bahzur** [comment]
Regarding your not-a-bug label, i would still consider this a bug, because: Theirs nothing but the sun above me, and i still get nightvision often by just stepping a block up or down.

**Comment by Mithion** [comment]
It's not a bug, the light level at your head is below the light threshold, as designed.  If the world is reporting that light level at that block, it's not my problem.
What we're talking about is an enchancement.

**Comment by Bahzur** [comment]
I can try to make a video to show you what i mean. Im in the open, **nothing** is above me, its broad daylight (as far as i know, as long as a block has direct contact to the sun, it has lightlevel 15?), i go a block up (or down) and get nightvision. My head is just 2 blocks above the ground, why would that block be below lightlevel 7? Sry if i confuse something here.

**Comment by Mithion** [comment]
Be that as it may, it isn't a bug with AM2 - it's just reacting to what the world tells it, so when the world somehow reports the light level as under seven at that point, it isn't an AM2 bug.

**Comment by Bahzur** [comment]
Oh ok. :(
Well, if its like that, then this would be an enhancement request. As i said, maybe a small timer (i dont have enough java&mod experience to determine if its difficult to do that) about a second or two that checks if the lightlvl is still below after the timercheck would prevent the constant activation of ender nightvision. Sry to bother you with that. ^^

**Comment by Mithion** [comment]
Not sure how I am going to go about it.  I may actually make it a keybind or something so you can toggle it at will instead of going by light level.

Plus, I want to give Ender Affinity some other ability...it seems to be lacking in comparison to the other affinity bonuses.  Maybe some sort of at will teleport.

**Comment by Bahzur** [comment]
Awesome! I really like the idea to make it toggleable! :D
Imho the ability to see in the dark at all times is already a very strong one (which was part of the reason why i went with ender). While the endermen aggro thing does not work atm, an at will teleport... well, i got enderaffinity by using Blink very often, its the way i travel in my world. Another teleport besides Blink, Random Teleport, Transplace and Recall would be i think a bit redundant... Well, the only thing im missing was a targeted teleport, e.g. i can exactly target the block i want to teleport to, which is like a better Blink. But thats just my opinion. ^^

On another note, imho the manacost for Blink is too low and it gives too much enderaffinity (i wanted enderaffinity, but it was way too easy to reach it with Blink). I can spam Blink all day with just magiclevel 24 to 31 (which i am now).

**Comment by Iivaitte** [comment]
a toggleable night vision sounds pretty good. To add onto your idea Mithion, maybe give the player the blink in place effect endermen have when shot with arrows.

**Comment by Bahzur** [comment]
I had that idea too, but thought after that it could cause more mischief than it helps; imagine that: You are on a 1 block edge (e.g. in a chasm) and are unaware of the skeleton on the other side that is aiming for your head right that moment. The arrow hits, instead of taking damage you get teleported 4 blocks infront of you, and, unfortunately, you were walking at that moment, and suddenly theres no block left infront of you after that teleport and you walk into a 30 block drop of death. Thats why i didnt suggest that.

**Comment by Mithion** [comment]
I've been brainstorming this for a while, and something that might be neat is a keybind that when you press it, if you're in the air, you teleport back to the place you were last on the ground, negating any fall damage.
I realize it adds another keybind, but I think it would be pretty helpful to be able to "blink" back to the top of the cliff you just fell off of instead of splattering all over the ground at the bottom.  Or blink back to the safe ledge after being shot by the aforementioned skeleton ;)
There's also the option that the NV and return blink could be the same key, with NV being a Sneak+KB and the blink being just the KB itself.

**Comment by TherminatorX** [comment]
I :+1: that

**Comment by Bahzur** [comment]
Totally approve all of that too! :+1:

**Comment by Mithion** [comment]
Ender affinity has been changed as per the above suggestions.
Corrected in 1.4.0.009 Dev.

**Comment by Bahzur** [comment]
Mithion for the win!!!
