### ISSUE TITLE
Rift does not save contents on exiting "The End"

### ISSUE THREAD

**Issue by justicesays** [Mithion/ArsMagica2#1096]
As per the subject, I placed several items from my inventory in the rift and removed some others while in "The End".
When I exited the end via the portal I discovered my rift contents were identical to those before I entered, such that I was missing some items and had duplicated others.

**Comment by Mithion** [comment]
Please include all information required here:
http://pastebin.com/29r0Nhe0

**Comment by justicesays** [comment]
Sorry, just raised it at work when I had a spare moment. 
Here are the details.
I'm using the latest Ars Magica .0008 release,
This was on a multiplayer server.
It's repeatable

I also have 
1.7.10_AM2-1.4.0.008.jar                       MobiusCore-1.2.3_1.7.10.jar
AdminCommandsToolbox-0.0.2a_1.7.10.jar         NewDungeons-0.3(1.7.10).jar
AnimationAPI-1.7.10-1.2.4.jar                  Opis-1.2.3_1.7.10.jar
Automagy-1.7.10-0.19.1.jar
ChickenChunks-1.7.10-1.3.4.16-universal.jar    sampler-1.16.jar
CodeChickenCore-1.7.10-1.0.4.29-universal.jar  Thaumcraft-1.7.10-4.2.3.4.jar
extrautilities-1.2.1.jar                       twilightforest-1.7.10-2.3.3.jar
fastcraft-1.19.jar

1.7.10:
Baubles-1.7.10-1.0.1.10.jar  CodeChickenLib-1.7.10-1.1.1.99-universal.jar

**Comment by justicesays** [comment]
![2015-02-23_22 26 08](https://cloud.githubusercontent.com/assets/10358888/6339125/b06d0166-bbab-11e4-87fd-20c24427392b.png)
![2015-02-23_22 25 54](https://cloud.githubusercontent.com/assets/10358888/6339126/b08acc6e-bbab-11e4-8050-311c80df1efd.png)
![2015-02-23_22 25 33](https://cloud.githubusercontent.com/assets/10358888/6339127/b0a34c9e-bbab-11e4-88f1-b3e73a5f9f87.png)
![2015-02-23_22 25 23](https://cloud.githubusercontent.com/assets/10358888/6339128/b0ab20a4-bbab-11e4-8daa-2402860575a1.png)
![2015-02-23_22 24 48](https://cloud.githubusercontent.com/assets/10358888/6339129/b0c461a4-bbab-11e4-8197-48f9d6227f6f.png)

As you can see the cobblestone I put in the rift in the end is no longer there after returning to the overworld.

**Comment by Mithion** [comment]
This pertains to certain events not being thrown when leaving the end.  A player technically "dies" when leaving the End, but the respawn event is never thrown when spawning in the overworld.

This is the trigger that causes AM2 to load the rift/properties/etc back in.  Since it never happens, the data is never re-loaded and is therefore lost.

The entire system will need to be re-architected for this to work.

**Comment by EoD** [comment]
Is this related to #479 ?

**Comment by LemADEC** [comment]
In AM1, Rift was a well known dup bug in other dimension because of this. Did we found out what's causing it?

**Comment by jjtParadox** [comment]
This issue has been resolved and should be marked as closed.

**Comment by Mithion** [comment]
Corrected by #1231
