### ISSUE TITLE
Ritual of Corruption (Monsterspawner) does not work

### ISSUE THREAD

**Issue by Bahzur** [Mithion/ArsMagica2#1097]
As title says. Version still .008, AM2-only environment.
I tried that ritual first on my survival server, where it didnt work, then tested it in singleplayer with AM2 only. The same ritual (with the sunstone and firespell instead) works on the obelisk, i generated a black aurem. At first i tried it with Touch+Rift to activate it, then in the testenvironment also with Projectile+Rift, and as that didnt work, Projectile+Astral Distortion and Self/Projectile+Life Tap. I also triplechecked if i did draw the runes right and candles.
If you need, i can generate you a log, but there is no error poping up i think.

**Comment by Mithion** [comment]
http://pastebin.com/29r0Nhe0

**Comment by Bahzur** [comment]
Sry, description comming, clicked to fast on enter.

**Comment by Mithion** [comment]
kk, np

**Comment by Bahzur** [comment]
Description updated.

**Comment by justicesays** [comment]
I've collected several monster spawners using this ritual with touch+rift, in AM .0008
Monster focus and Ender essence as the components,
Main issue with touch+rift was casting it directly on the spawner without picking up the components...

**Comment by Bahzur** [comment]
i tried it in every way i could, and i used the items you mentioned. I triplechecked the runes and candles... what am i doing wrong?

**Comment by Bahzur** [comment]
Scratch that... i found my mistake - i dont know why i didnt do that mistake when i made the black aurem... *sigh* Thats embaressing.

**Comment by Mithion** [comment]
Hey, I don't mind...less digging into it for me :P

**Comment by Bahzur** [comment]
^^
