### ISSUE TITLE
Runes are destroying blocks and creating ghost duplicates 

### ISSUE THREAD

**Issue by mineguy46** [Mithion/ArsMagica2#1098]
I think the rune shape might need some attention. The following issues happen regardless of the exact spell but for this example I am using rune in shape group one, then touch --> light in the bottom.

 First of all; (and this might be intentional) the range from which you can cast the rune seems to be a little too far, it extends slightly past the normal block placing range; which is odd considering how little range the touch shape has. Additionally, I thought that in previous versions projectile-->rune would create a rune where the projectile lands, but instead it creates a rune where I am looking when the projectile lands.

Secondly; placing a rune on a block that has another block on top of it (by casting the spell on the side of the block) will always destroy the other block.

Thirdly; Occasionally when you cast a rune spell, it will create a ghost duplicate of itself directly adjacent to itself. This duplicate has no effect, stepping on it doesn't trigger the spell, but the "real" rune is unaffected. It's not just a visual de-sync because it can be broken and still takes up the block. It only seems to happen when A) You cast the spell at just the right angle (looking slightly downwards) or B) you drag your cursor along the ground as the spell is cast. Using the latter I was  even able to create ghost runes that were not adjacent to the original. As well as multiple ghost runes in one cast.

Fourthly; I think someone already posted about this, but the runes just float there when you break the block underneath them.

Finally; Why does it take so long for the runes to break? It takes the same amount of time it takes to break stone bare-handed. I've tried pouring water on them, that didn't work, and as mentioned in the last point, breaking the block underneath them doesn't do anything. Is there a special tool or spell you are supposed to use? I even tried casting dispel on them, the only ways to get rid of them seem to be stepping on them, blowing them up, or slowly punching them to death.

**Comment by Mithion** [comment]
1.) Rune is much deeper in the tree and activates differently - that's why it is so much different.
2.) This I will have to check
3.) It's a clientside block and is related to the way MC syncs object positions - the code runs clientside and creates the rune at a different location than at the server.  This can be fixed by disabling rune creation clientside (disabling the actual block set).
4.) This I don't really care about
5.) Runes are intentionally hard to break.  It's meant that if you set them, some other player can't just one-punch them into nothing or simply dispel them away.

**Comment by Mithion** [comment]
In 1.4.0.009 Dev, runes no longer replace blocks as indicated in point 2, and no longer creates the ghost images.

Closing as fixed in 1.4.0.009
