### ISSUE TITLE
Fling doesn't work on self in a contigency spell.

### ISSUE THREAD

**Issue by Darkmega18** [Mithion/ArsMagica2#1100]
Yeah. Testing out spell combinations ran into this one while making a spell someone was trying to do on the forum. did it, but the fling in the spell meant to be used to get you into the air and out of harm doesn't apply and so I ended up BBQing myself in a flame zone I left behind as per the spell the guy was meant to be making that I was testing/trying to get work out of curiousity.

now, it does work if you put it into a self portion in the same contigency THEN fling, but thats using up an extra spell writing slot when the contigency is a self spell to begin with...

**Comment by Mithion** [comment]
Contingency spells need a way to target.  The spell combination [Contingency][Fling] will intentionally do nothing.  You need [Contingency][Self][Fling].

**Comment by Darkmega18** [comment]
actually. thats what it was. the contingency was self casted on me and when it's in with a load of spells to fling myself and heal me a bunch of health then featherfall down the fling doesn't activate I'm thinking because I've always been knockback'd by an attack and that cancels the momentum that I should've got from fling. since it works flawlessly if I manual cast it when it's not a contingency. Sorry, forgot to outright say the whole spell.

it goes Contingency health, self, fling, shield, slowfall, heal, Heal modifier x3. I get hit enough to make it activate, the fling doesn't but the rest does.

**Comment by Mithion** [comment]
Ah, that's different - I understand now.
I'll look into it, but if it is in fact the attack cancels out the momentum gained, then there isn't much I can do about it (within a reasonable effort to change it while still not breaking all the other spells people use it for).

**Comment by Darkmega18** [comment]
I see. I figure it might be the flashflinch or the momentum override cause they're both activating at once. since I gotta take the hit and the knockback first to be able to activate the spell so it's not a thing of activating the spell first so I take that knockback otherwise it's be like predicting the attack instead. >_> oh well, atleast I can still use fling as a vertical boost jump, like I did earlier. :D

**Comment by Mithion** [comment]
You could also move the fling into a short zone after the self and fling everything else away from you.  The slowfall would keep them in the air long enough for you to get out of there.

**Comment by Darkmega18** [comment]
Well the full Phoenix fire spell is the one I posted on the forums. It's a bit long to have two zones going simultanously to fling. But I suppose I could fling everything in the phoenix zone but that means it'll get tossed up with me, but atleast it'll fall back to the ground. so that sorta makes a cool sorta volcano zone eruption updrafty sorta effect with the upwards soaring phoenix bit. Although that means I have to take a tick of my own fire damage to get the launch unless I make the instant-cast version. >_<

**Comment by Mithion** [comment]
FWIW, I managed to figure out the issue here - the fling is in fact applying, but an unmodified fling doesn't add enough velocity to be noticeable.

I upped the strength of fling a little bit, but to really see the benefit you should add some velocity modifiers to the spell grammar.  Then you'll see it take effect.

Closing as resolved in 1.4.0.009 Dev.

**Comment by Darkmega18** [comment]
I seeee. well now I know.
