### ISSUE TITLE
Contigency cannot be cast outside of creative while using shield parts among others.

### ISSUE THREAD

**Issue by Darkmega18** [Mithion/ArsMagica2#1101]
In my testing and having come across the unable to fling self in contingency, I've also come across a bug where when a contigency health spell contains mana shield anywhere in it it cannot be cast on self outside of creative mode. I can provide the forge log of my session, but if you just need to know the mods included it's the same list of mods from the mixed up potions ID issue I submitted. Said modpack is also up as a hidden modpack on technic launcher for testing it with people, I could send that so you can try it first hand aswell...

**Comment by Mithion** [comment]
Mana shield is a silver skill and must be actively known as well as in your primary tree in order to cast it.  Otherwise it won't work.

**Comment by Darkmega18** [comment]
That I did not know. So that's probably why it doesn't pop when out of creative cause I've never know it outside creative. >_> alright, thanks.

**Comment by Mithion** [comment]
Yup, Silver Skills were meant to make it a decent choice when playing on a server with skill tree locking set, and give some powerful endgame spells.
