### ISSUE TITLE
Regeneration doesn't apply when used after heal in a spell.

### ISSUE THREAD

**Issue by Darkmega18** [Mithion/ArsMagica2#1102]
I've got a self, heal, regeneration spell that doesn't apply the regeneration. When applied by itself it does work but when comboed it doesn't. BUT I just noticed that it works when applied first and then you heal. I'm guessing thats not completely intended? (although it's sorta low priority now that I know how it works but i initially thought it wasn't working at all. :V)

PS: sorry for the flood of mini-bugs/queries. I just run into stuff while playing with different combos >_<

**Comment by Mithion** [comment]
Heal and Regen have a shared cooldown and can't be applied at the same time.  It was added to prevent players from spamming them and becoming more or less invincible as long as they had mana.

**Comment by Darkmega18** [comment]
After seeing tofski do it infront of the enderguardian some time back I think I understand why.... So you either have to go with over time long heals or instant big heals? hmm...
also did the mana cost of them go up? cause you can hardly cast two hits of heal at level 1 up to around level 6. D:

**Comment by Mithion** [comment]
Yes, the mana cost did go up - another balancing change.
However, with mana potions it isn't that big of a deal.  They got majorly buffed in what they do.

**Comment by Darkmega18** [comment]
Ahhh, the bane of my existence... Balance changes. no offense of course. Since I just gotta deal and work with it. :P and yeah, I like the mana potions giving the regen and the instant mana. Very useful. and with being able to generate resources on a whim from other resources in my modpack using aethercraft, they're super good. :D
