### ISSUE TITLE
Disappearance of data following a crash if dead in Nether

### ISSUE THREAD

**Issue by Tictim** [Mithion/ArsMagica2#1105]
If my character is dead in Nether, the server console is dead with the message 'Internal Server Error'.  When I re-enter the server after rebooting it, I find that somethings are missing like some data from Ars Magica (e.g., magic level and the magics that I've learned from Occulus) and hunger gauge.

Meanwhile, items or other information like Thaumcraft research data was not affected and still there.

And if I went to Nether without Magic Data of Ars Magica and died in there, the data didn't disappear.

Please check this phenomenon.

**Comment by Bahzur** [comment]
I remember diying in the nether once, with version .007 or .008 on my dedicated srever, but nothing wrong happened there...

**Comment by Mithion** [comment]
If you quit without respawning that will happen, which would also happen if the server stopped.

**Comment by Bahzur** [comment]
Just to clarify: Did your death in the nether cause the crash?

**Comment by Tictim** [comment]
to Bahzur: No, it doesn't seem to be crashed because there is no crash log created. The server just finished itself, and when I reboot it the data has disappeared.

**Comment by Tictim** [comment]
to Mithion: Even though I try to re-spawn after dying, the button won't be activated and the server is gone soon.

**Comment by Mithion** [comment]
Just tried dying in the nether in dev - no crash, and respawning kept the data perfectly.
Sounds like a server problem to me.

Bottom line, if the server shuts down while you are dead, the data cached for respawn isn't saved.  This isn't something I am going to fix, as it can be remedied using the admin commands if it happens, and the only real time it occurs is 
1.) a ragequit in singleplayer, where...well my answer to that is "don't".  Servers will keep the cache there until they shut down, so this one is somewhat less of an issue.
2.) a crash, which you solve, then use the admin commands to restore the data.
