### ISSUE TITLE
Experience bar issue

### ISSUE THREAD

**Issue by Bahzur** [Mithion/ArsMagica2#1107]
Just a minor visual thing:
With the smart xpbar enabled (only pops up when you get xp), being alone on the server everything is fine. But as soon as someone else joins, the xpbar gets a little derpy: Casting something with a Self shape (i think it only happened with self, im not sure though) causes the xpbar from the other one to pop up and viceversa. But the actual xp is still earned by the caster himself.

**Comment by Bahzur** [comment]
Paying more attention to the xpbar i noticed that there are many occasions where the xpbar does not pop up, even if im alone. I didnt recognize a pattern to this other issue yet.

**Comment by Darkmega18** [comment]
I thought the XP just never turns up sometimes cause theres not a visible different in the bar for it to come up to show you that different when casting some things or you just got no xp at all cause of the xp fall off for spell spam?

**Comment by Mithion** [comment]
Sometimes XP gains are shown in the same bar, and XP isn't sync'd to clients on demand - only once every 10 seconds or so.  That can explain the delay, and why it doesn't come up.

The other issue is with LAN games - packets designed to go to a player are sometimes redirected to the LAN host.  This doesn't happen in SMP, so I assume it's a Forge issue.

**Comment by Bahzur** [comment]
Actually this is happening on a Forge SMP server, not a LAN host. Didn't host a LAN server yet...
