### ISSUE TITLE
[v1.4.0.008] Crash -- ArrayIndexOutOfBoundsException (TileEntityCelestialPrism)

### ISSUE THREAD

**Issue by SethWilliamson** [Mithion/ArsMagica2#1108]
Crashed after purifying an Obelisk. Game crashes when trying to enter world.
```
java.lang.ArrayIndexOutOfBoundsException: 266
	at net.minecraft.entity.EntityLivingBase.func_70670_a(EntityLivingBase.java:688)
	at net.minecraft.entity.player.EntityPlayerMP.func_70670_a(EntityPlayerMP.java:890)
	at net.minecraft.entity.EntityLivingBase.func_70690_d(EntityLivingBase.java:642)
	at am2.blocks.tileentities.TileEntityCelestialPrism.func_145845_h(TileEntityCelestialPrism.java:135)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```
Log:  http://slexy.org/view/s204dXdNgO

AM2 -- 1.4.0.008
Forge -- 1.7.10-10.13.2.1291

**Comment by TherminatorX** [comment]
does this happen w/o Optifine?

**Comment by SethWilliamson** [comment]
This gets more interesting...

With AM2 and Optifine, I can get to the menu, but loading the world crashes (log in OP.) Note that I had progressed a bit in AM2, so it wasn't unplayable up until the out of bounds entity issue. I can create a new world and play there for a bit too.

I disabled Optifine (and FastCraft) to test for you.  It crashes before I can even get to the menu. Log: http://slexy.org/view/s21Wp91dKp

```
java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    net/minecraft/client/renderer/EntityRenderer.func_78480_b(F)V @123: iload_3
  Reason:
    Type top (current frame, locals[3]) is not assignable to integer
  Current Frame:
    bci: @123
    flags: { }
    locals: { 'net/minecraft/client/renderer/EntityRenderer', float, integer }
    stack: { 'net/minecraft/client/renderer/EntityRenderer', float }
```

I have 312 mods installed so finding the exact culprit might be a nightmare; however, I next disabled AM2 and the game and that world load fine (naturally with all the AM2 content gone.) I haven't bothered testing an instance with just AM2 since there are tons of players happily playing it, I figured I could safely assume it works fine stand-alone. My best (uneducated) guess is that it is having an ugly interaction with another mod. 

Since Mine & Blade was the most recent to load there before the crash, I tried disabling that too but the only change is it crashed 5 lines earlier, right after "Sound engine started," so it wasn't M&B.

I've tested again Java 7 & 8 in case that would make a difference. No Change.

**Comment by TherminatorX** [comment]
Since you have so many mods installed, try taking 50 out at a time, putting them in different folders to make sure you know which ones are removed. One you can get it to work, the offending mod is in the most recent exclusion.

After that, remove everything else but AM2 and put those 50 back in. Repeat the above procedure with smaller and smaller amounts until you find the issue.

**Comment by Mithion** [comment]
Check your potion ID configs - sounds to me like they're messed up.

**Comment by Mithion** [comment]
The optifine thing has been posted several times on the forum with a fix - optifine in the root of the mods folder, not in a subfolder, with "optifine" somewhere in the filename.

**Comment by Mithion** [comment]
#1074 see the solution there to fix the buffs (this crash happened because the potion ID config is wrong)
