### ISSUE TITLE
Frost slow makes the field of view spaz out.

### ISSUE THREAD

**Issue by Darkmega18** [Mithion/ArsMagica2#1112]
exactly what it said on the tin. got shot with an ice spell from a mage, screen starting spazzing out for around 30 seconds while the frost slow buff was on me despite the buff being at 0 the entire but not going off. am I having another potion ID mix up? does anyone else get this when they get frostslowed?

edit: Huh, ok? But this time I I made an nei potion with frostslow for 10 seconds on it and applied it, I didn't spaz out. wot?

**Comment by Bahzur** [comment]
I guess that was a client/server desync, like the same what occasionally happens with the double-tap w in earlier Minecraftversions.

**Comment by Mithion** [comment]
Frost slow now properly applies across the network.
Corrected in 1.4.0.009 Dev.
