### ISSUE TITLE
Openblocks Luggage compatibility issue

### ISSUE THREAD

**Issue by arnol372** [Mithion/ArsMagica2#1113]
I recently updated from 1.7.10_AM2_1.4.0.006 to 1.7.10_AM2-1.4.0.008 in a modpack I'm using. I noticed that the Luggage item from Openblocks no longer renders an icon in NEI, inventory, or when the item is tossed out into the world. It operates like normal when placed.

I searched Openblocks' issue tracker and found this report which mentions AM2: https://github.com/OpenMods/OpenBlocks/issues/611

I don't know if you are already aware of this, but I thought I'd mention it.

**Comment by dmportella** [comment]
i can confirm that this is the case, i noticed this n the mod pack in technik launcher called realms of mianite

**Comment by clifftrials** [comment]
I can also confirm this issue. Requesting fix. OpenBlocks author says it's not fixable on their end. Here is a link of what it looks like (3rd item) http://tinypic.com/r/soo206/8

Thanks!

**Comment by Mithion** [comment]
This has been corrected in 1.4.0.009 dev
