### ISSUE TITLE
amuicfg requires extra permissions when using Bukkit

### ISSUE THREAD

**Issue by sandalle** [Mithion/ArsMagica2#1114]
We recently updated to Cauldron with Forge 1307 (from just Forge), which includes Bukkit mods (we're using default Bukkit settings with no Permission plugins). Before this, all players on [Modderation: Permabanned](http://www.technicpack.net/modpack/modderation-permabanned-edition.449941) could use the /amuicfg, but after only OPed players can (see https://github.com/mechaet/ModderationConfigs/issues/6 ). [This](http://www.rerolled.org/showthread.php?5083-ReRolled-Minecraft-Server-IV&s=835b13d24cef5a7a1ca37410177f686b&p=641496&viewfull=1#post641496) forum post has some information on which permissions need to be added, but for a client-side command, no extra permissions should be required, correct? I think #126 was trying to mention this, but did not go into any explanations.

Other UI commands (e.g. "/statuseffect config" from [bspkr's Status Effect HUD](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1282347-bspkrs-mods-armorstatushud-directionhud)) continue to function fine and do not require special permissions.

Can /amuicfg be made to not require special permissions?

**Comment by Mithion** [comment]
I'm not sure what bukkit bases its permission nodes on, but I can give it a go, sure.

**Comment by sandalle** [comment]
[Bukkit Vanilla Permissions](http://wiki.bukkit.org/Vanilla_permissions) in case that helps narrow down where Bukkit might be conflicting. Let me know if there are any commands/debugging you want me to run to help. Thank you for looking into it, we're really enjoying Ars Magica 2. :)

**Comment by sandalle** [comment]
Using [PermissionEx](http://dev.bukkit.org/bukkit-plugins/permissionsex/) Bukkit plug-in we were able to run the following for now:
````
/pex group default add am2.commands.configureamuicommand
````

Though it'd be nice to not need server-side changes to run a client-side command. :)
