### ISSUE TITLE
Fishing Focus not working

### ISSUE THREAD

**Issue by hagsly** [Mithion/ArsMagica2#1115]
I have tried multiple configurations to try and get the fishing focus to get fish and I am not having any luck. I have the fishing focus supplied with etherium. It has a 3x3 area underneath with water and the water is over 2 blocks deep(although I have also tried with only 2 blocks). The focus is in the habitat and I tried it with lightning flicker filled habitats and with out. I tried with an adjacent inventory and without and I have tried with a redstone signal and without. Any info on this would be awesome. Thanks!

**Comment by Mithion** [comment]
Just tested it and it works as intended.

Couple of things to keep in mind:

1.) The fishing focus takes a long time to do an operation (~5 minutes) - it's meant to set it and forget it, so you won't see anything until that time passes.
2.) It requires 500 etherium per operation.  Etherium isn't drained until the operation tick (see note 1)
3.) I recommend setting up a chest next to it so it has a place to export the fish.
4.) If the UI Text is green, then it's configured in the right way
5.) If it has a redstone signal, that effectively shuts it off so that it won't run.  This is true for any flicker habitat.
6.) The water has to be 3x3 like you have it, but also at least 3 blocks deep.  Make sure that this is your setup.

**Comment by Aminity** [comment]
Hello, I tried the mentioned above, yet still after several hours I have 0 fish in multiple set ups. I ran out of idea's of what I could possibly still be doing wrong. So a screenshot for a correct setup would be appreciated.

I have tried it above a 3x3x3 pit of water as well as above the ocean without any results ( powered with all 3 etherium types). Currently trying a settup where it is submerged in water, but I doubt thats going to be the solution as far as I have been.

**Comment by Mithion** [comment]
Was the UI text green?

**Comment by Aminity** [comment]
Yes the UI text was green. When I get home later today I shall upload some screenshots of how I have it set up at the moment.

**Comment by Aminity** [comment]
![2-has etherium](https://cloud.githubusercontent.com/assets/13078401/15227482/c65a1eca-1887-11e6-8bed-ad00b6097ef7.jpg)
![3-lightningflicker has etherium](https://cloud.githubusercontent.com/assets/13078401/15227484/c855361a-1887-11e6-9cbf-4732a787046c.jpg)
![4-has obvious3x3x3 access](https://cloud.githubusercontent.com/assets/13078401/15227488/ca7e6042-1887-11e6-8915-e21d5374b20e.jpg)
![5-correct support flicker](https://cloud.githubusercontent.com/assets/13078401/15227491/cc5aa934-1887-11e6-88f9-b31d3cc0fda0.jpg)
![6-correct fish focus](https://cloud.githubusercontent.com/assets/13078401/15227494/ce3a1cb2-1887-11e6-918a-b825ceb9021a.jpg)

**Comment by Aminity** [comment]
So as the images show, it has the correct flickers, the needed etherium, the right focus, plenty of space, its even submerged in water. Yet no fish while I can confirm that power is being used over time.

**Comment by jjtParadox** [comment]
Are you using ArsMagica in a modpack? If so, what mods are you using alongside it?

**Comment by Aminity** [comment]
I haven't made the modpack myself, a friend made the pack which he runs on his server and he put in Ars Magica 2 for me and I am the only one who really uses ars magica 2, so I don't know what most of the names are but here is a screenshot of the mod folder.

I also noticed today that the keystone gate doesn't respond to the evil book like I thought it would, it just opened the gate normally linking to the next gate in the network rather then going to the secret world.
![modpacklist](https://cloud.githubusercontent.com/assets/13078401/15268811/f0b86edc-19eb-11e6-9ab2-12b6a7c002ae.png)

**Comment by jjtParadox** [comment]
The evil book's been disabled (there's another way to get a hellcow summon).

Can you get the fishing focus to work using just AM2?

**Comment by Aminity** [comment]
I have tried it with a new profile, with only AM2 and the AnimationApi in the mods folder ( else it wouldnt start the game ) and after setting up a 3x3x3 water tank in dirt and all of the stuff mentioned before directly above that it is not producing any fish after powering it for over 10 minutes ( does drain power )
