### ISSUE TITLE
Sound loop?

### ISSUE THREAD

**Issue by wizard1399** [Mithion/ArsMagica2#1117]
Hey, 

Not sure if this is a bug or not, but I was trying to create a modpack and having some trouble getting Minecraft to load up correctly.  One of the things I noticed in the game output window of the launcher was:
 File arsmagica2:sounds/spell/loop/none.ogg does not exist, cannot add it to event arsmagica2:spell.loop.none

Figured I should at least let you know.

**Comment by Mithion** [comment]
Thanks :)

This isn't something to worry about - it's a warning that spells with no affinity won't have a sound loop...which is intentional.  However the warning is built as generic so that it notifies on all of them.
