### ISSUE TITLE
Keybinding names need localization

### ISSUE THREAD

**Issue by DonnerVarg** [Mithion/ArsMagica2#1118]
I noticed the names for the category and keybindings need localization.
key.am2.category
key.AuraCustomization
key.CastingMode
key.SpellBookNext
key.SpellBookPrev
key.ToggleManaDisplay

(I'm using AM2 1.4.0.008)

**Comment by Xyphius** [comment]
Added en KeyBindings. Fixed in 1.4.0.009-Dev
