### ISSUE TITLE
Silver Skills

### ISSUE THREAD

**Issue by MrWiik** [Mithion/ArsMagica2#1119]
I have made the exact right combo used it so many time still don't unlock starstrike

**Comment by Mithion** [comment]
Silver skills work fine, so it's one of two possibilities:
1.) You can only learn a silver skill if it's in your primary tree (the one you took your first point in), and it isn't offense
2.) You have the combination wrong

**Comment by MrWiik** [comment]
can i reset my points and redo

**Comment by Mithion** [comment]
You could try using /respec to do so, yep.
