### ISSUE TITLE
Everstone not maintaining facade

### ISSUE THREAD

**Issue by Kaiser6012** [Mithion/ArsMagica2#1121]
To start, I am playing using the Crack Pack, if this helps at all.

My main problem is that everstone isn't behaving at all as I expected, or, as I believe, intended. To start, everstone seems to not be as "sticky" with the illusionary parts as it should be - right clicking a block onto a block of everstone makes it appear like said block, but doing the same to an adjacent everstone block reverts the first to it's normal appearance. Placing a block on to the everstone appears to resolve the issue, making the block stay on the facade even when working on other adjoining everstones.

But then, when I enter a Compact Machine, or when I try to attach a Player Sensor from Malasis Doors onto a block of everstone and walk through a door, ALL the everstone on the building reverts to blank. More annoyingly, it appears the everstone still believes it has a facade, because right clicking will place a block and the everstone will be as described above after step 2.

Am I doing something wrong? Am I going to have to redesign my buildings when I come back from the Nether every time, or is there some way I can fix this?

**Comment by Mithion** [comment]
What version of AM2 are you running?

**Comment by Usernamelah** [comment]
On AM 1.4.0.008,
Happens to me too, using blocks like stone bricks variations, wools I think can also do this, I think other blocks except the most basic, like cobblestone, wood. Using blocks mentioned, if you place everstone next to each other, then try to use stone brick for example, the next one you try to facade will revert the first everstone block, then after awhile all revert back to everstone, the blocks still think that they are in facade like above mentioned.

Also using stained glass, crash the game, crash log is as follow:
http://pastebin.com/PN6JSrd5

**Comment by Mithion** [comment]
Corrected in 1.4.0.009 (Dev)
