### ISSUE TITLE
When changing username all progress resets

### ISSUE THREAD

**Issue by tuskiomi** [Mithion/ArsMagica2#1122]
Reccomend changing to a UUID system, if possible.

**Comment by Mithion** [comment]
Progress of what kind?  compendium?  Skills/Spells?  Affinity?  All of the above?

**Comment by tuskiomi** [comment]
Everything, that is, except my spells that i made.

--- Original Message ---

**Comment by Gunner76th** [comment]
Please define how you are changing your username, as I personally am curious about this. Do you mean just within the world via some bukkit plugin or possibly some forge mod, or are you referring to changing your username that is registered with Mojang entirely?

**Comment by jjtParadox** [comment]
Been digging through this, and while some data is temporarily stored under username in memory, it's supposed to be saved to the player's .dat file, which is UUID based anyway.

I believe having a player's display name changed while they are logged on (through commands or bukkit or a mod) is what causes this issue, but any name changing outside of that is properly handled.

I'm not entirely certain of this, but I believe that changing dimension or dying and respawning fixes this issue, as the data is saved to the player's .dat file then reloaded under the player's new username.

I'll make a pull request anyway to change how player data is stored in memory.
