### ISSUE TITLE
Texture

### ISSUE THREAD

**Issue by MrWiik** [Mithion/ArsMagica2#1123]
There's no way of changing to the much better looking textures

**Comment by Mithion** [comment]
Do you mean via a resource pack?  Or some other means?  I know lots of people use texture packs with AM2.

**Comment by MrWiik** [comment]
Like mianitethey have the older more hires textures

**Comment by MrWiik** [comment]
like this http://prntscr.com/6i7llq

**Comment by jawdylawdy** [comment]
"Something Something Something Complaining About Textures

Just don't. I can't stress enough how little I care."

- From the MC Forums post ;)

**Comment by Mithion** [comment]
That's more or less true lol.

However.  If you take an earlier version of the mod, and open the jar with 7-zip, you can copy the old textures into the new jar.  As long as they have the same names (which they will), it should work.

**Comment by MrWiik** [comment]
I know but i cant find any downloads for that version
