### ISSUE TITLE
Compendium unlock failure

### ISSUE THREAD

**Issue by Diegge** [Mithion/ArsMagica2#1126]
If you start in a new world and make a compendium, only the shape bar with 3 shapes (projectile, touch, self), the components bar(empty) and the modifier bar(empty) will be unlocked. This is definitely since patch 1.4.0.008.

**Comment by Mithion** [comment]
That's intentional and in fact has been that way for several versions.

**Comment by Diegge** [comment]
I've tested this with version 1.4.0.007 and the compendium shows the guides and the other bars. 
And why is it intented?

**Comment by Hades99** [comment]
If you don't like it go to the config and turn off staged compendium

On Saturday, March 21, 2015, Diegge <notifications@github.com> wrote:

> I've tested this with version 1.4.0.007 and the compendium shows the
> guides and the other bars.
> And why is it intented?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mithion/ArsMagica2/issues/1126#issuecomment-84284059>.
>


-- 
Eli

**Comment by Diegge** [comment]
Ah, okay.
