### ISSUE TITLE
Invisible Liquid  Etherium

### ISSUE THREAD

**Issue by xOoren** [Mithion/ArsMagica2#1127]
I can't see the Liquid Etherium.
Help me please.
![2015-03-21_15 43 09](https://cloud.githubusercontent.com/assets/11586303/6765445/05a7d4be-cfe1-11e4-964a-7dc21bed9be3.png)

**Comment by TherminatorX** [comment]
Are you using OptiFine?

**Comment by xOoren** [comment]
Yes why?

**Comment by Hades99** [comment]
*sigh* as a general tip always mention optifine and fastcraft when
submitting bug reports if you are using them.  Now, try removing optifine
to see if that fixes your problem.

On Sunday, March 22, 2015, xOoren <notifications@github.com> wrote:

> Yes why?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mithion/ArsMagica2/issues/1127#issuecomment-84583878>.
>


-- 
Eli

**Comment by xOoren** [comment]
Thank you.
I can see the liquid etherium without optifine.
But it isn't possible to see the liquid etherium with optifine?

**Comment by Mithion** [comment]
Optifine generally changes how rendering works and isn't generally supported - all I can suggest is to try a different version/feature set of optifine and see if that fixes it.
That or mess around with your render settings in-game until it shows up.

**Comment by jawdylawdy** [comment]
Hint: Fastcraft is infinitely better than Optifine, since it does many and more of the same things Optifine does with less bugs.
