### ISSUE TITLE
Armor Imbuements

### ISSUE THREAD

**Issue by WyvernArchmage** [Mithion/ArsMagica2#1129]
Something about armor imbuements has gone terribly wrong.
When I go into my single-player world, everything works as it should. With Void Thaumaturge robes, protection IV, physical and magical protection damage, and magic shield III, I am nearly invincible.

This is as it should be, end-game.

On the multiplayer server, however (and we have tested the AM2 config, even reset it completely), the imbuements seem to have a negative effect - the resistance ones, anyways.
When I put fire damage resistance onto the armor, it makes me take double, sometimes triple the damage from lava. When I have physical protection on, I take 3x-4x the damage I should, being killed in one hit by things that without said "resistance" would take 3 and upwards hits.
In addition to all of this, the magic shield "buff" makes me take more of all types of damage - mobs hit through the armor as if it wasn't there, when combined with the resistances.

I have absolutely no clue (neither does the rest of the staff team) as to why this is happening.
There is also no crash, but I could force one if you think a log would help you determine the cause.

Main mods installed:
Ars Magica 2 + Animation API
Bibliocraft
Biomes `O Plenty
Botania
Thaumcraft (with add-ons - could Forbidden Magic be causing this somehow?)
Metallurgy
Tinker's Construct
Twilight Forest
(modpack is Valkyriacraft http://www.technicpack.net/modpack/scourgecraft.37 <-- full modlist)

**Comment by Bahzur** [comment]
Really strange. I also have a SMP server with a friend, and didnt experience that. Ill look out for that bug and maybe test specifically for that.

**Comment by WyvernArchmage** [comment]
If you find out it's a mod causing it / which one, it would help a lot (can't take down our server 80 times :p)

**Comment by Bahzur** [comment]
On my server theres no Botania or Metallurgy, the other mods i do have (your listed mainmods). Looking through the whole list, maybe its your mod CosmeticArmor?
Also, to test it, make another server on your own pc with the same setup and test it there plugging the mods out and in to find out.

**Comment by Mithion** [comment]
I haven't been able to replicate this at all - have you made any progress on identifying if it's a specific incompatibility with another mod?

**Comment by WyvernArchmage** [comment]
Unfortunately no.
I have a feeling it's either Hardcore Ender Expansion or Forbidden Magic. FM is the only one that directly touches AM2 iirc, and HEE works offline, as does AM2. Online, HEE is broken, and so is AM2...

**Comment by Mithion** [comment]
Well that still narrows it down - I'll focus my testing on those two mods when I get some development time again.

**Comment by Mithion** [comment]
I can't replicate this at all - and in looking at the damage reduction code:

event.ammount *= 0.85f;

There's no way that would increase damage, and it's the only point at which the imbuement does anything.  I'm going to close this as can't replicate, but if you find a way to reliably replicate the issue in the future, feel free to comment here and I or Xyphius will re-open this issue.
