### ISSUE TITLE
Single Player World Crash, Warding Candle

### ISSUE THREAD

**Issue by ArielFaye** [Mithion/ArsMagica2#1131]
Accidentally clicked the warding candle on a red stone ore block. Ever after the single player world crashes right after launch. I am terrible at reading these things so any help would be greatly appreciated. Just hate when a world goes poof.. /hugs Ariel

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 3/29/15 7:59 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427)
	at am2.items.ItemCandle.func_77653_i(ItemCandle.java:174)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427)
	at net.minecraftforge.client.GuiIngameForge.renderToolHightlight(GuiIngameForge.java:583)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:154)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427)
	at am2.items.ItemCandle.func_77653_i(ItemCandle.java:174)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427)
	at net.minecraftforge.client.GuiIngameForge.renderToolHightlight(GuiIngameForge.java:583)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:154)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['ArielFaye'/408, l='MpServer', x=-11.95, y=5.62, z=-15.30]]
	Chunk stats: MultiplayerChunkCache: 95, 95
	Level seed: -4959463499243012507
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
	Forced entities: 115 total; [MoCEntityFly['Fly'/550, l='MpServer', x=2.03, y=48.92, z=-120.44], MoCEntityFly['Fly'/551, l='MpServer', x=11.23, y=49.92, z=-118.50], MoCEntityWerewolf['Werewolf'/555, l='MpServer', x=-97.94, y=35.92, z=51.75], MoCEntityAnt['Ant'/567, l='MpServer', x=-92.04, y=62.92, z=-96.95], MoCEntityFly['Fly'/564, l='MpServer', x=-105.41, y=59.92, z=-88.01], MoCEntityAnt['Ant'/560, l='MpServer', x=27.50, y=46.92, z=-120.91], MoCEntityFly['Fly'/575, l='MpServer', x=16.65, y=66.92, z=-139.21], MoCEntityAnt['Ant'/574, l='MpServer', x=-37.13, y=33.92, z=-128.56], MoCEntityFly['Fly'/517, l='MpServer', x=-17.98, y=45.59, z=-105.19], MoCEntityWerewolf['Werewolf'/518, l='MpServer', x=0.78, y=19.92, z=-109.41], MoCEntityAnt['Ant'/524, l='MpServer', x=16.69, y=47.92, z=-107.26], EntityMiniGhast['Mini Ghast'/527, l='MpServer', x=-71.38, y=34.19, z=64.19], MoCEntityAnt['Ant'/523, l='MpServer', x=24.56, y=47.92, z=-105.50], Entity_SpecialCreeper['Creeper'/529, l='MpServer', x=67.50, y=37.92, z=62.50], MoCEntityAnt['Ant'/540, l='MpServer', x=-0.08, y=50.59, z=-122.50], MoCEntityFly['Fly'/537, l='MpServer', x=-59.84, y=68.03, z=-98.91], MoCEntityFly['Fly'/539, l='MpServer', x=-6.36, y=34.92, z=-121.58], EntityTFNagaSegment['unknown'/866, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityTFNagaSegment['unknown'/867, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityTFNagaSegment['unknown'/868, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityTFNagaSegment['unknown'/869, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityTFNagaSegment['unknown'/870, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityTFNagaSegment['unknown'/871, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityTFNagaSegment['unknown'/872, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityTFNagaSegment['unknown'/873, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityTFNagaSegment['unknown'/874, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityTFNagaSegment['unknown'/875, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityTFNagaSegment['unknown'/876, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityTFNagaSegment['unknown'/877, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityTFNagaSegment['unknown'/3250, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityTFNagaSegment['unknown'/3251, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityTFNagaSegment['unknown'/3248, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityTFNagaSegment['unknown'/3249, l='MpServer', x=0.60, y=-0.08, z=0.60], MoCEntityAnt['Ant'/579, l='MpServer', x=-135.44, y=58.94, z=-79.91], EntityTFNagaSegment['unknown'/3254, l='MpServer', x=0.60, y=-0.08, z=0.60], MoCEntityFly['Fly'/580, l='MpServer', x=-135.17, y=59.29, z=-79.64], EntityTFNagaSegment['unknown'/3255, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityTFNagaSegment['unknown'/3252, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityTFNagaSegment['unknown'/3253, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityTFNagaSegment['unknown'/3256, l='MpServer', x=0.60, y=-0.08, z=0.60], MoCEntityAnt['Ant'/587, l='MpServer', x=-80.47, y=57.92, z=-131.59], EntityTFNagaSegment['unknown'/3247, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityTFNagaSegment['unknown'/3246, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityTFNagaSegment['unknown'/3245, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityMiniGhast['Mini Ghast'/441, l='MpServer', x=-25.13, y=18.47, z=54.59], MoCEntityMediumFish['MediumFish'/442, l='MpServer', x=-24.19, y=43.00, z=57.70], MoCEntitySmallFish['SmallFish'/443, l='MpServer', x=-24.88, y=43.00, z=57.85], MoCEntityFishy['Fishy'/444, l='MpServer', x=-20.16, y=43.00, z=57.85], EntityMinecartChest['entity.MinecartChest.name'/447, l='MpServer', x=-77.50, y=19.50, z=-25.50], EntityMiniGhast['Mini Ghast'/432, l='MpServer', x=-57.68, y=49.95, z=20.24], MoCEntitySnake['Snake'/433, l='MpServer', x=44.73, y=60.00, z=21.49], EntityMooshroom['Mooshroom'/434, l='MpServer', x=47.41, y=67.00, z=21.31], EntityHungryZombie['Hungry Zombie'/435, l='MpServer', x=-5.66, y=30.00, z=-74.75], Entity_SpecialZombie['Zombie'/436, l='MpServer', x=-5.41, y=30.00, z=-75.72], EntityMooshroom['Mooshroom'/437, l='MpServer', x=-5.97, y=61.00, z=-78.72], EntityMiniGhast['Mini Ghast'/438, l='MpServer', x=-15.73, y=17.94, z=53.55], EntityItem['item.item.ghastTear'/439, l='MpServer', x=-30.75, y=15.13, z=48.88], EntityMiniGhast['Mini Ghast'/425, l='MpServer', x=-33.23, y=100.66, z=26.79], EntityMiniGhast['Mini Ghast'/424, l='MpServer', x=3.84, y=109.40, z=28.61], EntityItem['item.item.rottenFlesh'/427, l='MpServer', x=2.13, y=12.13, z=-59.88], EntityMiniGhast['Mini Ghast'/426, l='MpServer', x=-53.20, y=29.16, z=-0.06], EntityMooshroom['Mooshroom'/429, l='MpServer', x=6.50, y=65.00, z=-48.69], Entity_SpecialCreeper['Creeper'/428, l='MpServer', x=15.38, y=32.00, z=-50.03], EntityClientPlayerMP['ArielFaye'/408, l='MpServer', x=-11.95, y=5.62, z=-15.30], EntityMooshroom['Mooshroom'/430, l='MpServer', x=32.66, y=69.00, z=-30.38], EntityItem['item.item.ghastTear'/417, l='MpServer', x=-15.03, y=14.13, z=7.88], Entity_SpecialCreeper['Creeper'/419, l='MpServer', x=17.38, y=18.00, z=-14.00], EntityMiniGhast['Mini Ghast'/418, l='MpServer', x=-16.50, y=16.21, z=6.77], EntityMooshroom['Mooshroom'/421, l='MpServer', x=-0.53, y=62.00, z=29.53], Entity_SpecialCreeper['Creeper'/420, l='MpServer', x=16.47, y=19.00, z=-6.91], EntityMooshroom['Mooshroom'/423, l='MpServer', x=11.19, y=69.00, z=16.94], EntityFireZombie['Fire Zombie'/422, l='MpServer', x=6.41, y=34.00, z=-46.66], MoCEntityFly['Fly'/479, l='MpServer', x=3.09, y=47.00, z=-83.63], Entity_SpecialCreeper['Creeper'/476, l='MpServer', x=7.53, y=26.00, z=-88.00], Entity_SpecialSpider['Spider'/477, l='MpServer', x=8.88, y=17.00, z=-90.72], EntityDoomCreeper['Doom Creeper'/474, l='MpServer', x=-27.36, y=11.00, z=-90.36], EntityHungrySpider['Hungry Spider'/475, l='MpServer', x=-16.06, y=63.00, z=-95.97], EntityDeathCreeper['Death Creeper'/473, l='MpServer', x=-83.44, y=19.00, z=-27.06], MoCEntityFishy['Fishy'/470, l='MpServer', x=-9.15, y=23.00, z=71.85], Entity_SpecialSpider['Spider'/468, l='MpServer', x=47.22, y=61.00, z=-74.06], EntityMiniGhast['Mini Ghast'/469, l='MpServer', x=41.57, y=89.52, z=53.32], MoCEntityAnt['Ant'/466, l='MpServer', x=-62.75, y=56.00, z=-72.03], Entity_SpecialSkeleton['Skeleton'/467, l='MpServer', x=33.18, y=40.00, z=-74.69], MoCEntityAnt['Ant'/464, l='MpServer', x=-57.50, y=43.00, z=-78.59], MoCEntityFly['Fly'/465, l='MpServer', x=-63.22, y=56.17, z=-74.25], Entity_SpecialZombie['Zombie'/463, l='MpServer', x=-48.53, y=5.11, z=-76.90], EntityWitch['Witch'/462, l='MpServer', x=-51.16, y=6.00, z=-73.66], EntityMiniGhast['Mini Ghast'/461, l='MpServer', x=-68.10, y=43.09, z=47.72], EntityItem['item.item.ghastTear'/460, l='MpServer', x=-73.88, y=37.13, z=42.88], EntityItem['item.item.ghastTear'/459, l='MpServer', x=-70.13, y=40.13, z=40.53], EntityMiniGhast['Mini Ghast'/455, l='MpServer', x=-59.37, y=2.71, z=59.16], Entity_SpecialZombie['Zombie'/454, l='MpServer', x=-44.92, y=6.00, z=-70.58], EntityMiniGhast['Mini Ghast'/453, l='MpServer', x=-41.25, y=9.15, z=57.00], EntityMooshroom['Mooshroom'/452, l='MpServer', x=34.72, y=69.00, z=-63.31], EntityMooshroom['Mooshroom'/451, l='MpServer', x=-63.47, y=62.00, z=-61.72], EntityMinecartChest['entity.MinecartChest.name'/450, l='MpServer', x=-63.13, y=11.34, z=-59.63], EntityMiniGhast['Mini Ghast'/449, l='MpServer', x=-57.24, y=87.11, z=35.83], EntityMiniGhast['Mini Ghast'/448, l='MpServer', x=-55.03, y=47.22, z=46.60], EntityMooshroom['Mooshroom'/504, l='MpServer', x=-54.81, y=68.92, z=-88.88], Entity_SpecialCreeper['Creeper'/505, l='MpServer', x=32.25, y=20.00, z=-80.72], MoCEntitySilverSkeleton['SilverSkeleton'/506, l='MpServer', x=41.72, y=43.92, z=-95.94], Entity_SpecialEnderman['Enderman'/507, l='MpServer', x=67.81, y=60.92, z=38.13], MoCEntityFly['Fly'/503, l='MpServer', x=-48.50, y=36.92, z=-94.19], Entity_SpecialSkeleton['Skeleton'/498, l='MpServer', x=50.50, y=47.92, z=52.50], Entity_SpecialSkeleton['Skeleton'/499, l='MpServer', x=51.50, y=47.92, z=56.50], EntityMiniGhast['Mini Ghast'/493, l='MpServer', x=-78.50, y=45.51, z=60.10], EntityMiniGhast['Mini Ghast'/492, l='MpServer', x=-71.89, y=42.85, z=59.06], EntityMiniGhast['Mini Ghast'/494, l='MpServer', x=-74.14, y=53.38, z=52.12], EntitySmallSpider['Small Spider'/489, l='MpServer', x=17.72, y=19.00, z=-92.34], EntityHungryZombie['Hungry Zombie'/488, l='MpServer', x=-38.30, y=10.12, z=-84.73], EntityMiniGhast['Mini Ghast'/491, l='MpServer', x=-67.01, y=32.93, z=62.19], Entity_SpecialSkeleton['Skeleton'/484, l='MpServer', x=-87.68, y=20.00, z=-43.66], Entity_SpecialZombie['Zombie'/487, l='MpServer', x=-44.72, y=11.00, z=-92.75], Entity_SpecialZombie['Zombie'/486, l='MpServer', x=-33.84, y=11.00, z=-82.72], EntityMiniGhast['Mini Ghast'/483, l='MpServer', x=-36.17, y=86.15, z=64.48]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.10.2
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 1290985672 bytes (1231 MB) / 2130051072 bytes (2031 MB) up to 2130051072 bytes (2031 MB)
	JVM Flags: 5 total; -Xms2048m -Xmx2048m -XX:+CMSClassUnloadingEnabled -XX:+CMSPermGenSweepingEnabled -XX:PermSize=128m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 54, tcache: 78, allocated: 1, tallocated: 15
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 51 mods loaded, 51 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MobiusCore{1.2.3} [MobiusCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	arsmagica2{1.4.0.008} [Ars Magica 2] (1.7.10_AM2-1.4.0.008.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bspkrsCore{6.14} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ArmorStatusHUD{1.27} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.27.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DirectionHUD{1.23} [DirectionHUD] ([1.7.10]DirectionHUD-client-1.23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	StatusEffectHUD{1.26} [StatusEffectHUD] ([1.7.10]StatusEffectHUD-client-1.26.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioCraft{1.8.2} [BiblioCraft] (BiblioCraft[v1.8.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1004-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.5].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AWWayofTime{v1.2.0b} [Blood Magic: Alchemical Wizardry] (Blood Magic-v1.2.0b(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Botania{r1.3-134} [Botania] (Botania r1.3-134.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.16-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MoCreatures{6.3.0} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	EnderStorage{1.4.5.27} [EnderStorage] (EnderStorage-1.7.10-1.4.5.27-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Waila{1.5.5} [Waila] (Waila-1.5.5_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-439.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForbiddenMagic{1.7.10-0.53} [Forbidden Magic] (Forbidden Magic-1.7.10-0.53.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GraveStone{2.10.2} [GraveStone] (GraveStone 2.10.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Growthcraft{2.1.0a} [Growthcraft] (growthcraft-core-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar] (growthcraft-cellar-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Growthcraft|Apples{2.1.0} [Growthcraft Apples] (growthcraft-apples-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Growthcraft|Bees{2.1.0} [Growthcraft Bees] (growthcraft-bees-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Growthcraft|Fishtrap{2.1.0a} [Growthcraft Fishtrap] (growthcraft-fishtrap-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Growthcraft|Grapes{2.1.0} [Growthcraft Grapes] (growthcraft-grapes-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Growthcraft|Hops{2.1.0} [Growthcraft Hops] (growthcraft-hops-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Growthcraft|Rice{2.1.0a} [Growthcraft Rice] (growthcraft-rice-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	HopperDuctMod{1.3.2} [Hopper Ducts] (hopperductmod-1.7.10-1.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	JABBA{1.1.4} [JABBA] (Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MapWriter{2.1.2} [MapWriter] (MapWriter-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mystcraft{0.11.0.00} [Mystcraft] (mystcraft-1.7.10-0.11.0.00.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Roguelike{1.3.5} [Roguelike Dungeons] (roguelike-1.7.10-1.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SpecialMobs{3.0.3} [Special Mobs] (SpecialMobs-1.7.10-3.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TConstruct{1.7.10-1.6.0.build611} [Tinkers' Construct] (TConstruct_mc1.7.10_1.6.0d40.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TwilightForest{2.3.2} [The Twilight Forest] (twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	witchery{0.20.6} [Witchery] (witchery-1.7.10-0.20.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce GT 650M OpenGL Engine GL version 2.1 NVIDIA-10.2.1 310.41.15f01, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Iivaitte** [comment]
update your forge version

**Comment by TherminatorX** [comment]
You should be able to get the NBT data of the item with an editor(via the player data). Give us a screenshot of the branch containing the item, and delete it so that your world may work again.

**Comment by ArielFaye** [comment]
Did some further testing, it only crashes when this item is in the hotbar slot and selected. I managed to drop it by pressing q repeatedly before crash, however when I logged on again my magnet ring sucked it back up and it crashed again. Ariel

![screen shot 2015-04-01 at 6 46 04 pm](https://cloud.githubusercontent.com/assets/10967922/6954373/e31f00c2-d89e-11e4-8e38-b46986754349.png)

**Comment by ArielFaye** [comment]
Oddly am unable to use NBTExplorer to delete the item, it just doesn't seem to want to save my changes. Managed to drop it again though and world is working again. If you need anything else just let me know. Ariel

**Comment by TherminatorX** [comment]
You need to edit the world file with MC not running, and save after you finish with the changes. Otherwise, this will not edit the world.

Sidenote: you can drop items from your inventory by hovering over them and pressing your drop key.

**Comment by Mithion** [comment]
We weren't able to replicate this issue, the warding candles worked fine.  So what we did was put in some code to prevent this from happening in the future.

Calling this fixed in dev version 1.4.0.009.
