### ISSUE TITLE
Support a more recent Forge

### ISSUE THREAD

**Issue by ameuret** [Mithion/ArsMagica2#1136]
Official recommended Forge version is  9.11.1.953 which can not be downloaded (too old). Current Forge versions (for 1.7.10 and 1.7.2) do not see the AnimationAPI ZIP in the mods folder.

**Comment by Mithion** [comment]
You shouldn't have an animationAPI zip, you should have an AnimationAPI jar - newer forge versions should work just fine.  I'm running an instance with latest forge without issue.

**Comment by Mithion** [comment]
Try this download link, it should work for you:
http://adf.ly/377779/animationapi-v124-mc1710
