### ISSUE TITLE
AM2 Compendim weirdness

### ISSUE THREAD

**Issue by rmrocks01** [Mithion/ArsMagica2#1137]
Today I changed my name on mojang.com and it reset my compendium progress but did not reset my oculus, I have tryed everything but it wont unlock the tabes for shapes, components, and modifyers. If it is possible could you give me a compendium unlocks file with everything unlocked because I don't need it staged on servers anyway. Thanks!

**Comment by Mithion** [comment]
Provided you are running 1.4.0.008, you can run:
/unlockcompendiumentry ALL

That'll open everything up.  Or, you can disable staged compendium via AM2.cfg.
