### ISSUE TITLE
Suggestion: Runed Doors

### ISSUE THREAD

**Issue by jawdylawdy** [Mithion/ArsMagica2#1138]
I know that suggestions are out of the question for 1.7.10 releases (as far as I'm aware), but in the spirit of putting new ideas into the head(s) of Mithion's successor(s), I figured why not put this here.

The idea is a door that's based on the rune system. Runes as they stand now will activate a spell effect when an entity touches them/comes into their AoE. I figured it would be cool to sort of mash the rune system with the keystone system. If a spell effect is applied to the door (such as fire damage), the door will open and allow an entity to pass through. After that, it will close. Witchery does something similar to this with the mystic branch's Alohamora effect, but AM2 could have much cooler stuff for it.

(shhhhh don't look directly at the rambling, just put this idea in your back pocket)

**Comment by Mithion** [comment]
I had an idea sort of similar to that for a block that emitted a redstone signal when struck with the correct spell parts - it's a really neat concept to extend that to a keystone door specifically.  Though maybe not a keystone door, maybe a different door entirely (so you could do one or the other)?

**Comment by Mithion** [comment]
Added during dev stream on Apr. 25 :)
