### ISSUE TITLE
AM2 Mod Compatibility Issues and other misc. buggs

### ISSUE THREAD

**Issue by rmrocks01** [Mithion/ArsMagica2#1143]
Hi Mithion! I would like to know if you could fix the incompatibility with AM2 and the Witchery mod. I am running a private server on a custom mod pack and am compileing a modpack with both mods, however I have noticed that on other packs (The Crack Pack) AM2 Potion effects are all screwed up. For example, while standing next to a obolisk, black arum, or celestial crystial, Insted of getting the mana regen effect, you get the witchery floating effect. For more examples, When using the regen spell, you get witchery's "Grotesque" insted. There are many more potion effect examples I could give but I feel 2 will be sufficent.

As for the other misc. bugs, If I open a keystone on that pack and close it, the server has "internal Errors" and kicks me if I try to open it agian. Not so sure about this last one, as it may just be me screwing something up, but gateway animations might be screwed.

The only reason I didn't go to the Wichery mod author is that I know that you're always quick with your replies and I don't want to keep my playerbase waiting. Thank You Mithion :smile:

**Comment by InfinityRaider** [comment]
This means you have potion ID conflicts, all of which can be fixed in the config.

**Comment by rmrocks01** [comment]
please explain how I can achive this

**Comment by InfinityRaider** [comment]
First use NEI to create a dump of all used potion ID's, then go into the config folder there look for the witchery and the AM2 configs and look at the potion id's that are identical, change either of them to a value that is not used (this is why you have the potion ID dump).
