### ISSUE TITLE
SoulBound items disappear after death.

### ISSUE THREAD

**Issue by alilograpi** [Mithion/ArsMagica2#1144]
So my issue basically is that of items disappearing after a player's death (I'm playing on my server). In singleplayer though , Items do not vanish. Can I fix this somehow ?

**Comment by Qendivardo** [comment]
Are you playing on a Cauldron server? In some circumstances, Cauldron doesn't trigger a PlayerRespawnEvent when you respawn in a different dimension than you died in, triggering only a PlayerChangedDimensionEvent instead. This breaks AM2's soulbinding.

**Comment by border999** [comment]
Any possible method of repairing this bug. God knows the people on Mianite need it fixed.

**Comment by Mithion** [comment]
This is related to the issue #1096 and progress will be tracked there.
