### ISSUE TITLE
Divine Intervention Spell Crash in other mod dimensions

### ISSUE THREAD

**Issue by Usernamelah** [Mithion/ArsMagica2#1146]
After you play for awhile, and while playing in the other mod dimensions(TF dimension in this case), using divine intervention to get back to the vanilla dimension would crash the game, but when logging back in you should be transported back to the Overworld, I noticed that the crash report changes sometimes(but the same method to replicate), might be something wrong with the other mod or if it something that can be changed, hope this helps.

Two of the different saved crash logs are below:(I think there's only 2 variances)
java.util.ConcurrentModificationException http://pastebin.com/FJbFBVFz
java.lang.NullPointerException: Exception generating new chunk http://pastebin.com/JE7bubdK

**Comment by Mithion** [comment]
I really have no idea how dimension transfers are supposed to work (or how Mystcraft does them so well).

Everything I've tried so far hasn't worked to solve this problem.
I'll keep trying though.

**Comment by jjtParadox** [comment]
I've been messing around with some of the dimension transfer stuff, and I noticed Divine Intervention defers the dimension transfer, while Ender Intervention triggers it the moment it is cast. I also noticed I could never get the game to crash from using Ender Intervention. Is the deferred dimension transfer for a reason? Was it fixing anything?

**Comment by Mithion** [comment]
The deferred dimension transfer was an attempt to fix a CME.
It defers the actual transfer until Tick End currently, but it might need to happen at a different point in the tick cycle.  Like I said, I never really got dimension transfers fully.

**Comment by DoomFruit** [comment]
I've tested this on the server I run and I haven't seen any crashes when going from the Deep Dark (Extra Utilities), the moon (Galacticraft) or Hoanna (EssentialCraft 3) to the overworld when using Divine Intervention. Nobody's been to the Twilight Forest yet, so I can't test that one out.

For reference, we're using a version of AM2 built from source nearly a month ago.

**Comment by jjtParadox** [comment]
I've found the crash to be intermittent, and it can even happen by traveling between the overworld and the nether.

To fix this, I believe it is possible to trigger the dimension transfer in the same part of the game tick as ender portals (I knew exactly which tick label it used some time ago, but then life got busy and I've forgotten it, but it shouldn't be hard to dig up again).

**Comment by Mithion** [comment]
Yeah this one I have tried all kinds of things, but I'm just not sure when to actually do the transfer.  I've tried deferring until next tick start, next tick end, immediate - the bug has been very persistent.

**Comment by jjtParadox** [comment]
Found it! Ender portals are ticked as part of the world tick, closer to the end phase of the WorldTickEvent. Have you tried ticking it specifically with the world tick?

**Comment by Mithion** [comment]
not sure - tried so many things I can't fully remember.  Probably not.  Worth a shot though!

**Comment by Bogdan-G** [comment]
judging by the dialogue you find a solution?

**Comment by Mithion** [comment]
Not yet - there's a good idea to try here though.

**Comment by jjtParadox** [comment]
I'm back! Sorry for the delay, but #1380 should be a fix for this. One step closer to the release!

**Comment by Mithion** [comment]
Man, looks like I really was close.
Are the profiler blocks in DimensionUtilities necessary?

**Comment by jjtParadox** [comment]
Since your code matches how vanilla Minecraft does dimension transfers with a small tweak inserting your teleporter, and it runs at almost the same area of the game tick, it makes sense to include entities sent via magic with all the other entities being moved around dimensions.

**Comment by Mithion** [comment]
Makes sense.  Just wanted to make sure it was intentionally left in and not a leftover of debugging.
