### ISSUE TITLE
Spell Mismatch Bug?

### ISSUE THREAD

**Issue by Usernamelah** [Mithion/ArsMagica2#1148]
Got another bug, don't know if this is intentional but the spell slow and freeze causes the same effect?

I thought slow should be the same with the vanilla slow debuff, but it seems with slow spell is the same like the freeze where you can see snow particles, and the icon is snow as well

**Comment by TherminatorX** [comment]
Check your potion IDs, I believe.

**Comment by Usernamelah** [comment]
Hmm, I left the potion IDs on default,
and when I look for the ID list, there's only the ID for freeze ("frostslow") and no config for just slow, could this be the problem, or they are just calling for the same ID?

**Comment by kotoroshinoto** [comment]
how does one check the potion IDS, and if they dont match properly how does one fix this?

**Comment by Mithion** [comment]
Slow should cause the vanilla slow effect, and freeze should cause frost slow.  Essentially they do the same thing, but frost slow additionally affects your mana regen and burnout reduction.

I'd have to check dev to make sure that it isn't simply assigning the wrong buff.

**Comment by Usernamelah** [comment]
I tried this in a world where this is the only mod that is installed, also I was curious if this was a version bug, so I also tried in version 1.6.4 just to see if this was the case, looks like the same is happening in 1.6.4

**Comment by Mithion** [comment]
Potion ID conflicts have been resolved in 1.4.0.009 Dev.

The mapper has been made more intelligent, and also extends the potion ID array to the full 255.
