### ISSUE TITLE
Regeneration Bug with MineChem

### ISSUE THREAD

**Issue by KananaPancake** [Mithion/ArsMagica2#1152]
I had created a private modpack a little while ago which included two other large mods along with Ars Magica: MineChem and Blood Magic.  I thought that having the MineChem Penicillin would assist my Blood Magic endeavors with the Regeneration IV.  However I came across a bug/conflict with the Regeneration in that it would apply Regen, but of a different kind.  This one had a green plus sign on the heart and didn't act like normal Regen with the fast health gain.  After some testing I found that the sole cause was with Ars Magica 2(Removing it resolved the issue and having it with MineChem only caused it again). I am currently using all most updated versions (as of April 27, 2015).  I hope that this issue is resolvable as the Regen not working isn't a necessity but is a pretty nice help with BM. If any addition information is wanted and can be provided, I would be happy to oblige.

**Comment by TherminatorX** [comment]
Sounds like a potion ID conflict

**Comment by KananaPancake** [comment]
But its supposed to be the vanilla Regeneration, I believe.  Or do you mean there is an issue where it is calling the incorrect method to apply the potion effect?

**Comment by TheMonkey78** [comment]
Just do /effect yourname 10 99999 4 to give yourself the effect when you need it. Meth is also broken with conflicts, though that could be Witchery or some other mod.

**Comment by Mithion** [comment]
Resolved as part of the fix for #1163.
