### ISSUE TITLE
Forge (The Spell) not respecting Metadata

### ISSUE THREAD

**Issue by Solar-Tiger** [Mithion/ArsMagica2#1154]
So I was just testing some Ars Magica 2 1.4.0.008 (Sorry, couldn't edit title) spells, and one in particular was the forge spell (to smelt blocks without harvesting them) and noticed it didn't respect anything that had metadata, not even its own blocks. This was all in SSP.

Example: Make a for spell-be it projectile, beam, touch-and use it on say, Sunstone Ore. Now you think you'd get Sunstone back (which I don't think is possible but roll with it) but you'll end of getting Vinteum Dust... Or you could try it on Chimerite and get... Vinteum.

It was all tested in an instance with just Ars Magica 2 and Animation API using Forge 1387. I also tested with other modded ores and got similar results: Zinc Ore became Copper Ingots, Orichalcum Ore from Metallurgy became Promethium Ingots, etc.

Not sure if this was posted before, but not even having compatibility with itself is why I'm posting this in the first place. This was done in creative, so I could have been doing something wrong/things work differently in creative, but I'm not sure.

~Solar_Tiger

**Comment by Xyphius** [comment]
Fixed in Version 1.4.0.009 Dev
