### ISSUE TITLE
Bibliocraft + Arsmagica 2

### ISSUE THREAD

**Issue by Iivaitte** [Mithion/ArsMagica2#1158]
I don't know if this is the correct place to report this, but I feel like I should let you know anyway.

place a broom connected to a bibliocraft bookcase. drop a spellbook, Book now dupes to fill the entire bookshelf and wont stop until broom is taken away.

Bibiliocraft  1.9.1
AM 1.4.0.008
forge 10.13.2.1291

**Comment by TherminatorX** [comment]
This doesn't happen with a vanilla chest, or with some other modded inventory?

**Comment by Iivaitte** [comment]
Its the first time I ever saw this behavior with the broom, Ill try it with a normal chest some time later today or tomorrow.

**Comment by Iivaitte** [comment]
Sorry for the Delay, it only seems to happen with the bibliocraft bookshelf.
Should I report it to them?

**Comment by TherminatorX** [comment]
Link them to this issue and we'll see if they provide some input.

**Comment by Iivaitte** [comment]
going to try newer bibiliocraft, and attempt to recreate the issue.

**Comment by Mithion** [comment]
What happened when you updated?  Did it solve the issue?

**Comment by jjtParadox** [comment]
I was not able to replicate this but with the latest Bibliocraft and the latest dev AM2, I think it's safe to say this has been resolved.

**Comment by Iivaitte** [comment]
I'm sorry, I haven't been playing Minecraft since Ark came out.
Now I'm back and the people I'm playing with have opt out of ars magica :(

I'm sorry about the inconvenience.

**Comment by Webber88** [comment]
what does the broom do?

**Comment by jjtParadox** [comment]
(Apologies for the late reply)

The Magic Broom just picks up all nearby items dropped on the ground and puts them into an inventory it was assigned to.

As for the bug, I believe this has been fixed.

**Comment by Mithion** [comment]
Closing as resolved in dev.
