### ISSUE TITLE
Visual Glitch

### ISSUE THREAD

**Issue by muzak23** [Mithion/ArsMagica2#1159]
When starting minecraft, if you change the window size too much the text will become distorted and you will not be able to read it. It will just be weird, random characters.

**Comment by muzak23** [comment]
hihihi
{b} ihihihi {/b}

**Comment by muzak23** [comment]
The glitch is actually all blocks, too. All the textures are messed up.

**Comment by TherminatorX** [comment]
This is only with AM2 installed? Sounds more like a vanilla/Forge issue.
I'm 98.2% sure Mith doesn't mess with the title screen.

**Comment by jawdylawdy** [comment]
It's because you have your GUI settings on Auto rather than Normal.
