### ISSUE TITLE
Possible memory leak on world change

### ISSUE THREAD

**Issue by NolanSyKinsley** [Mithion/ArsMagica2#1161]
I have been tracking down a memory leak that happens on dimension change, it increases the memory usage in the main heap by ~30mb each time I warp back to the main world. I took some heap dumps and the only thing I found out of place is multiple worldclient instances being spawned linked to ars magica 2's crafting altar. Here is an image of jprofiler showing what I am seeing after several teleports in and out of the main dimension: http://i.imgur.com/ftxY6gc.png I can send the heap dumps if you need them.

**Comment by NolanSyKinsley** [comment]
Here is a copy of a memory dump when it is symptomatic of the memory leak https://www.dropbox.com/s/jvogyhftgx84agz/latest.hprof.tar.gz I have also made an issue over on the MFR github as I have no clue what is actuall causing it. https://github.com/skyboy/MineFactoryReloaded/issues/445

**Comment by EoD** [comment]
@NolanSyKinsley As skyboy/MineFactoryReloaded#445 has been fixed, can we close this bug?

**Comment by Mithion** [comment]
Yep, I believe so.
