### ISSUE TITLE
Haste spell, making tree logs and leaves, under players feet.

### ISSUE THREAD

**Issue by Commander-Rug** [Mithion/ArsMagica2#1165]
The swiftness spell, when used leaves logs of tree's and some leaves floating in the air. never seen this before and its very annoying.

the trees appear under your feet, and stop you dead in your tracks, if you can imagine its like running at full speed then stopping in a half second flat, comletely useless for the spell.

no crash reports. will try to find something from the logs/reports generated.

**Comment by TherminatorX** [comment]
What is the full setup of the spell?

**Comment by Commander-Rug** [comment]
i have tried it with the 'leap' ability, and 'leap' , 'gravity well' , and 'feather fall' also i have made one with just switness on its own. to diagnose the problem, its always the switfness part that causes the trees.

**Comment by Commander-Rug** [comment]
quick update, played around wih the problem a little more and found that the trees it creates are only MC vanilla trees (any kind) and witchery trees (also any kind though it prefers rowan). i really dont know whats happening with this as the only thing in the console while under the effectsis this: 

"[B#301]  [13:27:43] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.inventory.GuiInventory
[B#301]  [13:27:43] [Client thread/INFO] [inventorytweaks]: net.minecraft.inventory.ContainerPlayer"

OR for creative:
"[B#301]  [13:26:57] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.inventory.GuiContainerCreative
[B#301]  [13:26:57] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.inventory.GuiContainerCreative$ContainerCreative"

Also a point to note is the spell gives the player a buff/debuff... wither for leap and haste for haste.
iso when you open your iventory/tab out while under the effects and in creative only it closes your inventory/chat or 'esc' menu and tabs you back in!? its really weird!!

any assitance that can be ofered is greatly appreciated!

**Comment by Zieg777** [comment]
I had a similar problem with flight. Its because you have potion effect IDs overlapping. I had to install dragonAPI to allow more than 128 potion effects. My guess is its overlapping with witchery's "Sprouting" potion effect

**Comment by username7** [comment]
Yeah, that's it.  Just a simple and "fun" potion id conflict.

**Comment by Commander-Rug** [comment]
thanx for the info, will make a note of that mod for 'next time' if we do it, but the mod builder and i decided last night to just remove the mod, it was intefering with too much, and getting half of it to work was far too much trouble!

thanx for the info anyway!
