### ISSUE TITLE
Self, shield, reflect, durationx3, kills players

### ISSUE THREAD

**Issue by Commander-Rug** [Mithion/ArsMagica2#1168]
had a player on our server crete the spell in the description above, spell lasts for around 6 mins and gives a nice buff, but it kills the player slowly, dont know what mod its interferring with, however im begining to suspect that these buffs are being messed with from another mod and its got something to do with buff ID's or something!? (see my other post : https://github.com/Mithion/ArsMagica2/issues/1165 for some context)

in addition to killing the player, it doesnt reflect or shield anything, im at a lose for this one and nothing i can see previously posted relates. sorry if there is something else out there and i missed it!

**Comment by jawdylawdy** [comment]
Try to reproduce this with only AM2 + vanilla.

**Comment by Zieg777** [comment]
Check your potion IDs. NEI can give an ID dump that may help. It's applying AM2's effect as well as probably something from witchery.

**Comment by Commander-Rug** [comment]
thanx for your help, this is the same result as the other post i was struggling with, buff/potion ID conflicts!! yay..... 

long story short however the mod desginer and i decided to just remove the mod rather than try to struggle through with the mountain of problems it was causing us!
