### ISSUE TITLE
Arcane Compendium Text overlapping

### ISSUE THREAD

**Issue by silver2256** [Mithion/ArsMagica2#1169]
Hello! Im playing FTB Infinty 1.3.4, with AM2 and some other mods installed. When I look at the Arcane Compendium all the text is overlapping and jumbled making it unable to read. I have no clue how to fix this, can anyone help?
Mod List: 
Floating Ruins
Treecapitator
Ars Magica 2
Advanced Solar Panel
Agricraft
AnimationAPI
AOBD
Applied Energistics
Archimedes Ships
Aroma1997Core
Aroma Backup
Atum
bdlib
Bibliocraft
Big Reactors
Binnie Mods
Biomes O Plenty
Blood Magic
Botania 
Buildcraft
Carpenters Block 
ChickenChunks
Chisel 
Chocolate Quest
CoFHCore
ComputerCraft
Custom Main Menu
Decocraft
denseores
Digimobs
DoomlikeDungeons
Draconic Evolution
dungeon pack
Enchanting Plus
EnderIO
Ender Storage
Ender Tech
Ender Zoo
Extra Tic
Extra Utilities 
Fastcraft
Fast Leaf Decay
Forbidden Magic
Forestry
Fossils Archeology Revival 
Funky Locomotion
Gendustry
Gravi Suite
hats
hats stand
Headcrumbs
IC2 Nuclear COntrol
iChunutil
IndustrialCraft
InfinBows
INpure Core
Inventory Tweaks
Iron Chest
Jabba
Journey Maps
logistic Pipes
Magic Bees
Mantle
MineFactory Reloaded
MineTweaker3
Mobius COre
MrCrayfishFurnitureMod
Mystcraft
Natura
Neiaddons
NEI Intergrations
Nether Ores
Not Enough Items
Not Enough keys
Not Enough Resources
Open Blocks
Open Mods Lib
Open Peripheral
Otaku Craft
Pam's Harvestcraft
Pneumatic Craft
ProjectRed
P¥Railcraft
RedstoneArsenal
ResourceLoader
RF Tools
Ruins 
Runic Dungeons 
Simply Jetpacks
Solar Expansion
Springboards
Steve's Carts
Tinkers Construc
Thaumcraft
Thermal Expansion
The weed mod
Translocator
Twilight Forest 
WAILA
WAWLA 
Witchery

**Comment by TherminatorX** [comment]
Does it work without Fastcraft? If not, do you still have this issue when only AM2 (and AnimationAPI) is installed?

**Comment by silver2256** [comment]
Sorry for the late response, however it does not work still without fastcraft but there is no issue when it is only AM2 and Animation API is installed. So I am assuming that one of the other mods is causing a problem. Do you have any idea which mod it might be or would I have to go through each mod individually?

**Comment by Mithion** [comment]
Make sure to check your UI size as well (try alternate ones under vanilla MC settings) - it sounds like your scale is all off and the font renderer is having trouble figuring it out.
