### ISSUE TITLE
OptiFine 1.7.10 HD B7 + AM2 1.4.0.008 crash MC launcher

### ISSUE THREAD

**Issue by EoD** [Mithion/ArsMagica2#1171]
If I install AM2 with either OptiFine_1.7.10_L_B6 or OptiFine_1.7.10_HD_B7 the game crashes on the forge loading screen (during or after 3/7): https://gist.github.com/EoD/e5303d9e52ca87fd26f6

Once I remove AM2, the game works just fine.

**Comment by Mithion** [comment]
don't put optifine in a subfolder - AM2 can't detect it and adjust the ASM accordingly.

**Comment by EoD** [comment]
Oh, thanks a lot. This fixed the issue.

Could you add this to the forums post maybe? I was looking for it, but I couldn't find anything 1.7.10-related to OptiFine.

**Comment by Mithion** [comment]
Good idea.  I'll make sure to add it to the FAQ.
