### ISSUE TITLE
[Request] Modifiers apply after components 

### ISSUE THREAD

**Issue by CrowAU** [Mithion/ArsMagica2#1175]
Example, having haste + buff power + buff power + leap + buff power + duration x3 
Applies 3 levels of buff power, 3 levels of duration to haste but only 1 level of buff power and 3 levels of duration to leap.

Not sure if this is possible to do, but it'd be neat to have the option to do spells that way.

**Comment by Mithion** [comment]
The spell system isn't designed to work that way.
