### ISSUE TITLE
Essence Bag and Arcane Essence

### ISSUE THREAD

**Issue by NaturesFox** [Mithion/ArsMagica2#1178]
Whenever Arcane Essence is placed into the Essence Bag Inventory and that inventory is closed, all Arcane Essence that was in the bag are replaced empty slots upon reopening the bag. As far as I can tell, this is only the case with Arcane Essence.

Currently running 1.7.10_AM2-1.4.0.008

![essancebag1](https://cloud.githubusercontent.com/assets/11971957/8010721/7aa07be2-0b80-11e5-9fab-13964a123077.png)

![essancebag2](https://cloud.githubusercontent.com/assets/11971957/8010720/7a9d7640-0b80-11e5-9e36-30190a7ee037.png)

**Comment by Mithion** [comment]
This has been corrected in 1.4.0.009 Dev
