### ISSUE TITLE
Railcraft and dig spell issue

### ISSUE THREAD

**Issue by Keyarose** [Mithion/ArsMagica2#1179]
When using the basic dig spell (Touch|Dig) on Railcraft quarried block stairs no item is dropped.  When using a pickaxe they do drop.

Versions
Railcraft 9.6.1.0
AM2 1.4.0.008

**Comment by TherminatorX** [comment]
#1055

**Comment by EoD** [comment]
Same happens with snow half slabs from Railcraft.

**Comment by Mithion** [comment]
This has been corrected in 1.4.0.009 Dev
