### ISSUE TITLE
Ender Affinity: Losing hearts is buggy

### ISSUE THREAD

**Issue by Nathipha** [Mithion/ArsMagica2#1180]
AM2: 1.4.0.008
Forge: Tested with 1291 and 1408
On a server.

If your depth in the Ender Affinity is high enough, you lose 2 hearts if you're standing in water and 2 additional hearts if the block, you're standing on, gets hit by direct sunlight - which is normal and intended.
But: If you change the dimension while being affected by this, the hearts are gone (like you lose hearts, when you're in morph) and and the lower health becomes your new 100% health. You also can't regenerate them - NEI's "regenerate player", eating a golden apple, getting a beacon that gives you the "regeneration" buff, drinking a healing/health potion, using an AM2 spell,... don't change anything. You only get them back by dying.

I already tested these "portals":
- Nether portal: Okay, since you're standing under obsidian, when you change dimension
- Spawned in nether portal at day: Causes the bug.
- Twilight Forest portal: Causes the bug, unless you put blocks above it, before you walk in
- Deep Dark (Extra Utilities): -"-
- Spectre Key (Random Things): Causes the bug if you use it during the day outside.
- The End portal: Unless you dig out the area above it, you're fine.

The Twilight Forest and the Spectre Dimensions are both dimensions that are stuck with an eternal day, so after going into one of these dimensions, while affected by the lowered health, you lose additional hearts if you walk into the sunlight there. If you then go back into the overworld, the 2 hearts you lost in the other dimension, are now also gone. So it's possible to get down to just 6 hearts by simply going into the Twilight Forest/Spectre Dimension and then travelling back into the Overworld. There, the sunlight and water still affect you, so you can get even lower.

As for the End: As long as you stay on the main island, you're fine. If you leave it (e.g. for Hardcore Ender Expansion stuff), you randomly lose 2 hearts because of the sun every now and then. I haven't been able to find out, what biomes there are causing this, though.

The modpack I'm currently playing has Tinkers Construct (1.8.5), too and with that you can get additional hearts by crafting heart canisters. This way you can get up to 40 hearts in total (10 red, 10 yellow and 10 green heart canisters, the latter ones you can only spawn in). I currently have 30 hearts (without the green heart canisters) and while everything is fine inside my house, I lose up to 6 hearts because of Ender Affinity outside at day (even though it should be only 2).

Temporary "fix": Build a roof above every portal and your spectre box and don't use the spectre key unless you're standing under something - even though that won't change anything if you should forget it.

**Comment by Mithion** [comment]
This has been corrected in 1.4.0.009 Dev.
All modifiers are removed on dimension changed and immediately re-applied upon arrival.
