### ISSUE TITLE
Floating buff from Obelisk triggers anti-flying in 1.7.10 SMP

### ISSUE THREAD

**Issue by turntekGodhead** [Mithion/ArsMagica2#1181]
(Server is running AM2-1.4.0.008)

I discovered that walking near my Obelisk, when it has essence stored in it, gave me a buff (I think it was called Floating?) that kept me levitated 2 squares above any solid block below me. 

However, I was doing this on my SMP server, and it tripped the anti-flying detection, so I got booted after a few seconds. 

I switched to creative while the buff wore off as a work-around, and have since moved my obelisk to a more out-of-the-way location. 

Is this a known issue?

**Comment by InfinityRaider** [comment]
Its a potion id conflict

**Comment by turntekGodhead** [comment]
Huh, would not have thought to check that. I am seeing potion conflicts in my config. I'll resolve them. Thanks!
