### ISSUE TITLE
Particle Emitter Ghost Block/Reappearing Block

### ISSUE THREAD

**Issue by Jeebruh** [Mithion/ArsMagica2#1183]
I've run into an issue with the particle emitter causing strange block placement/breaking issues. Upon placing a particle emitter somewhere and breaking it, it seems to reappear randomly at the same spot (it seems to be happening upon chunk reload but I'm not 100% certain on that). When it reappears it breaks instantly and without smashing particles, with the stone-breaking sound rather than the normal glass-shattering sound. After breaking this "ghost block", placing blocks in the spot it was in will cause it to transform into a particle emitter (the placed block pops back into my inventory).

Running AM2 1.4.0.008, Minecraft 1.7.10 and Forge version 1355.

**Comment by Mithion** [comment]
This has been corrected in 1.4.0.009 Dev
