### ISSUE TITLE
[1.6.4] Ars Magica conflicting with Morph

### ISSUE THREAD

**Issue by sysm789** [Mithion/ArsMagica2#1186]
When i want to go through hole size in one block I'm getting damage. The bug is present only for little mobs. 

In the version without mod AM 2 player takes the size of a chicken. In the version with mod AM 2 player does not change its size.
Look at the pictures. 

Bug in AM
![h8nxey6](https://cloud.githubusercontent.com/assets/13038690/8339946/e60e712a-1ac3-11e5-9544-1b0c0b7c7d46.png)
shout be
![2ovbzhp](https://cloud.githubusercontent.com/assets/13038690/8339953/ee81253c-1ac3-11e5-946a-59cb51768c43.png)

Mod is excellent! Thanks to the author for his work.

Sorry for my bed english.

**Comment by Mithion** [comment]
1.6.4 is no longer supported.  1.4.0.009 for 1.7.10 has better support with Morph.
