### ISSUE TITLE
Command: /SetSpellKnown

### ISSUE THREAD

**Issue by Aconitasi** [Mithion/ArsMagica2#1187]
hello, i've the same problem of this guy: https://github.com/Mithion/ArsMagica2/issues/480
i'm using AM2 version 1.4.0.008 and i can't find the SetSpellKnow command! How can i editi what spells a Player has unlocked in the Oculus?
Thanks

**Comment by Mithion** [comment]
I actually just found this bug while testing something else last night, and have already fixed it.
The command wasn't properly registered, so MC didn't recognize it.
It will release with 1.4.0.009.

Currently the only way is to download their data file and edit the known components manually.
