### ISSUE TITLE
Occulus Unusable Black Screen

### ISSUE THREAD

**Issue by NecroNile** [Mithion/ArsMagica2#1189]
Hello,

I added ArsMagica to a mod pack I made and am using by myself. Everything has been working so far, I gathered up the items to make a compendium, made one, and got my level 1 wizardy thing above the vanilla levels. I made an Occulus and opened it to a blank black screen. I can mouse around the screen and find some of the things to click, but its completely unusable. I haven't had any crash so I can't post any crash log, obviously, but I will post pictures to show you whats going on. I'll also give you a list of the mods I'm using so you can determine if its a mod incompatibility that may be known that I can't find documentation on. I looked all over the net and on here and I can't find anyone else mentioning this issue.

![javaw 2015-06-26 16-49-58-708](https://cloud.githubusercontent.com/assets/12779846/8387349/d49f64c2-1c25-11e5-87a6-d64729cfdbc7.jpg)
![javaw 2015-06-26 16-49-52-691](https://cloud.githubusercontent.com/assets/12779846/8387348/d49c7b36-1c25-11e5-8e2c-8ff1b1dd615d.jpg)
![mods](https://cloud.githubusercontent.com/assets/12779846/8387361/e0793ba6-1c25-11e5-9440-ba7c28ff79e7.png)

Inside the 1.7.10 folder there is: bspkersCore, Baubles, CodeChickenLib, commons-codec, commons-compress, and ForgeMultipart. Inside the Carpenters Blocks folder there is a .zip file for cached resources.

If you need any extra information I'll be more than happy to help. I was pretty excited to play this mod and now I can't. :'(

Thanks,
Nile

**Comment by Mithion** [comment]
It's probably the shaders mod - when you see stuff like this, first thing you want to do is disable graphics overhaul mods like optifine, shaders, etc.

It could also be Journeymap.

**Comment by NecroNile** [comment]
I removed both Journeymap and Shaders (wasn't even using that one) to no avail.

**Comment by Hades99** [comment]
fastcraft?

On Fri, Jun 26, 2015 at 5:01 PM, NecroNile <notifications@github.com> wrote:

> I removed both Journeymap and Shaders (wasn't even using that one) to no
> avail.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mithion/ArsMagica2/issues/1189#issuecomment-115902836>
> .
>



-- 
Eli

**Comment by NecroNile** [comment]
Removing fastcraft didn't help either.

**Comment by Mithion** [comment]
Can you try an instance with *just* am2 and animapi?  see if it happens there.
That will confirm if it is in fact a conflict with another mod.

If it works, then start adding the mods in small groups until the issue appears, then remove some from the most recent group until you find the culprit.

If not, we'll look more into it.

**Comment by NecroNile** [comment]
I figured it out. The Show Durability mod caused the conflict. I did as you suggested, Mithion. I added almost all my mods before I got to Show Durability. The incompatibility doesn't happen until you put on armor though, as shown in the pictures.

![javaw 2015-06-27 11-08-04-573](https://cloud.githubusercontent.com/assets/12779846/8392580/342ea244-1cbd-11e5-9c8f-c2049bb2f08c.jpg)
![javaw 2015-06-27 11-08-13-465](https://cloud.githubusercontent.com/assets/12779846/8392579/342cd4e6-1cbd-11e5-8479-86f78736e290.jpg)

Just figured I'd let you guys know so maybe you can find a way to work with whoever made Show Durability. I know Ars Magica has its own form of showing armor durability so I'm not really going to be using Show Durability anymore. Thanks for your help.

**Comment by TherminatorX** [comment]
Also, SD seems rather redundant. You can see durability in vanilla by pressing F3 and "H" at the same time. However, this is only when you hover over items in inventories.

**Comment by Mithion** [comment]
Closing as resolved.
