### ISSUE TITLE
Occulus Glitch - Doesn't open

### ISSUE THREAD

**Issue by Restioson** [Mithion/ArsMagica2#1190]
My friends and I are having trouble opening the occulus.I can, but they crash on opening it.
Crashlog:
        ---- Minecraft Crash Report ----        
        // Uh... Did I do that?        
            
    Time: 6/15/15 1:57 PM        
    Description: Unexpected error        
            
    java.lang.NullPointerException: Unexpected error        
    	at am2.guis.GuiSkillTrees.func_73866_w_(GuiSkillTrees.java:106)        
    	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:255)        
    	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:797)        
    	at am2.proxy.ClientProxy.openSkillTreeUI(ClientProxy.java:188)        
    	at am2.blocks.BlockOcculus.func_149727_a(BlockOcculus.java:64)        
    	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:326)        
    	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1435)        
    	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1941)        
    	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)        
    	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)        
    	at net.minecraft.client.main.Main.main(SourceFile:148)        
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)        
    	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)        
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)        
    	at java.lang.reflect.Method.invoke(Unknown Source)        
    	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)        
    	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)        
            
            
    A detailed walkthrough of the error, its code path and all known details is as follows:        
    ---------------------------------------------------------------------------------------        
            
    -- Head --        
    Stacktrace:        
    	at am2.guis.GuiSkillTrees.func_73866_w_(GuiSkillTrees.java:106)        
    	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:255)        
    	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:797)        
    	at am2.proxy.ClientProxy.openSkillTreeUI(ClientProxy.java:188)        
    	at am2.blocks.BlockOcculus.func_149727_a(BlockOcculus.java:64)        
    	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:326)        
    	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1435)        
            
    -- Affected level --        
    Details:        
    	Level name: MpServer        
    	All players: 1 total; [EntityClientPlayerMP['Diablo58264'/18802, l='MpServer', x=189.70, y=85.26, z=233.30]]        
    	Chunk stats: MultiplayerChunkCache: 244, 253        
    	Level seed: 0        
    	Level generator: ID 00 - default, ver 1. Features enabled: false        
    	Level generator options:         
    	Level spawn location: World: (144,64,252), Chunk: (at 0,4,12 in 9,15; contains blocks 144,0,240 to 159,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)        
    	Level time: 1181 game time, 1181 day time        
    	Level dimension: 0        
    	Level storage version: 0x00000 - Unknown?        
    	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)        
    	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false        
    	Forced entities: 38 total; [EntityBat['Bat'/22186, l='MpServer', x=177.56, y=21.89, z=252.75], EntityBat['Bat'/22187, l='MpServer', x=171.22, y=47.36, z=258.41], EntityBat['Bat'/22201, l='MpServer', x=206.25, y=37.45, z=290.75], EntityBat['Bat'/22200, l='MpServer', x=263.78, y=22.00, z=235.22], EntityBat['Bat'/22206, l='MpServer', x=201.70, y=44.80, z=279.96], EntityBat['Bat'/22205, l='MpServer', x=209.59, y=37.48, z=290.16], EntityBat['Bat'/22204, l='MpServer', x=197.42, y=43.62, z=276.50], EntityDryad['Dryad'/18700, l='MpServer', x=126.50, y=72.00, z=228.72], EntityDryad['Dryad'/18701, l='MpServer', x=127.50, y=71.00, z=229.50], EntityDryad['Dryad'/18711, l='MpServer', x=152.50, y=82.00, z=194.50], EntityDryad['Dryad'/18710, l='MpServer', x=152.50, y=82.00, z=193.50], EntityPig['Pig'/18709, l='MpServer', x=150.19, y=79.00, z=220.53], EntityPig['Pig'/18708, l='MpServer', x=149.50, y=80.00, z=218.50], EntityPig['Pig'/18707, l='MpServer', x=149.81, y=81.00, z=211.09], EntityPig['Pig'/18706, l='MpServer', x=151.50, y=78.00, z=222.50], EntityPig['Pig'/18719, l='MpServer', x=164.69, y=86.00, z=190.53], EntityPig['Pig'/18718, l='MpServer', x=165.50, y=80.00, z=184.50], EntityPig['Pig'/18717, l='MpServer', x=162.50, y=80.00, z=185.50], EntityPig['Pig'/18716, l='MpServer', x=165.47, y=81.00, z=185.50], EntitySheep['Sheep'/18715, l='MpServer', x=163.03, y=81.00, z=191.50], EntitySheep['Sheep'/18714, l='MpServer', x=164.53, y=81.00, z=191.16], EntitySheep['Sheep'/18713, l='MpServer', x=168.28, y=81.00, z=199.88], EntitySheep['Sheep'/18712, l='MpServer', x=163.50, y=81.00, z=196.50], EntityDryad['Dryad'/18724, l='MpServer', x=173.50, y=81.00, z=190.50], EntityDryad['Dryad'/18720, l='MpServer', x=165.50, y=80.00, z=211.50], EntityDryad['Dryad'/18721, l='MpServer', x=167.50, y=80.00, z=210.50], EntityDryad['Dryad'/18722, l='MpServer', x=171.66, y=70.00, z=261.06], EntityDryad['Dryad'/18723, l='MpServer', x=174.50, y=81.00, z=191.50], EntityPig['Pig'/18751, l='MpServer', x=245.47, y=66.00, z=248.22], EntityPig['Pig'/18750, l='MpServer', x=241.50, y=67.00, z=251.50], EntityPig['Pig'/18752, l='MpServer', x=246.81, y=66.00, z=249.53], EntityPig['Pig'/18753, l='MpServer', x=246.50, y=66.00, z=252.50], EntityBat['Bat'/18805, l='MpServer', x=185.22, y=21.00, z=160.31], EntityClientPlayerMP['Diablo58264'/18802, l='MpServer', x=189.70, y=85.26, z=233.30], EntityBat['Bat'/18876, l='MpServer', x=203.48, y=27.00, z=216.18], EntityBat['Bat'/18877, l='MpServer', x=194.25, y=20.00, z=290.41], EntityBat['Bat'/18880, l='MpServer', x=122.94, y=18.56, z=297.44], EntityBat['Bat'/18885, l='MpServer', x=192.25, y=28.25, z=274.75]]        
    	Retry entities: 0 total; []        
    	Server brand: fml,forge        
    	Server type: Integrated singleplayer server        
    Stacktrace:        
    	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)        
    	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)        
    	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)        
    	at net.minecraft.client.main.Main.main(SourceFile:148)        
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)        
    	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)        
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)        
    	at java.lang.reflect.Method.invoke(Unknown Source)        
    	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)        
    	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)        
            
    -- System Details --        
    Details:        
    	Minecraft Version: 1.7.10        
    	Operating System: Windows 8.1 (amd64) version 6.3        
    	Java Version: 1.7.0_67, Oracle Corporation        
    	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation        
    	Memory: 306929584 bytes (292 MB) / 684965888 bytes (653 MB) up to 4260102144 bytes (4062 MB)        
    	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:-OmitStackTraceInFastThrow -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xms256M -Xmx4096M -XX:PermSize=256M        
    	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used        
    	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95        
    	FML: MCP v9.05 FML v7.10.113.1384 Minecraft Forge 10.13.3.1384 Optifine OptiFine_1.7.10_HD_B7 13 mods loaded, 13 mods active        
    	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available        
    	FML{7.10.113.1384} [Forge Mod Loader] (forge-1.7.10-10.13.3.1384-1.7.10-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available        
    	Forge{10.13.3.1384} [Minecraft Forge] (forge-1.7.10-10.13.3.1384-1.7.10-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available        
    	AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available        
    	CodeChickenCore{1.0.3.26} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available        
    	NotEnoughItems{1.0.3.66} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.66-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available        
    	AnimationAPI{1.2.3} [AnimationAPI] (AnimationAPI-1.7.10-1.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available        
    	arsmagica2{1.4.0.008} [Ars Magica 2] (1.7.10_AM2-1.4.0.008.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available        
    	DamageIndicatorsMod{3.2.0} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available        
    	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (Archimedes-Ships-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available        
    	ExtraUtilities{1.2.4a} [Extra Utilities] (extrautilities-1.2.4a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available        
    	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available        
    	ReiMinimap{1.7.10} [Rei's Minimap] (ReiMinimap-1.7.10-3.6(1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available        
    	Launched Version: 1.7.10        
    	LWJGL: 2.9.1        
    	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.3379, Intel        
    	GL Caps: Using GL 1.3 multitexturing.        
    Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.        
    Anisotropic filtering is supported and maximum anisotropy is 16.        
    Shaders are available because OpenGL 2.1 is supported.        
            
    	Is Modded: Definitely; Client brand changed to 'fml,forge'        
    	Type: Client (map_client.txt)        
    	Resource Packs: []        
    	Current Language: ~~ERROR~~ NullPointerException: null        
    	Profiler Position: N/A (disabled)        
    	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used        
    	Anisotropic Filtering: Off (1)

**Comment by Restioson** [comment]
Please help. Issue not resolved yet

**Comment by TherminatorX** [comment]
Have everyone update Forge and disable Fastcraft and Rei's. See if that does anything.

**Comment by Restioson** [comment]
We have tried (on one person's computer) only using AM2 and Animation-API yet this does not solve the problem. We haven't tried updating forge yet; maybe that will help.
Thanks,
Restioson

**Comment by EoD** [comment]
@Restioson Did updating forge fix the issue?

**Comment by Restioson** [comment]
Unfortunately, I have been unable to test this as my friends would not let me as of yet ;) I will definitely keep trying xD

**Comment by c62624** [comment]
I don't have this issue.

**Comment by Restioson** [comment]
Sorry for wait!

Fixed by updating
