### ISSUE TITLE
Client crash after disarm spell!

### ISSUE THREAD

**Issue by omia** [Mithion/ArsMagica2#1196]
Both clients Crash after hitting player with disarm-spell!
More Info: If pvp is on the caster(person) crashes and the "castet on person" dropes the item!
Crash-report: http://pastebin.com/8zm3LrbG

**Comment by TherminatorX** [comment]
Dupe issue #1048

"Corrected in 1.4.0.009 Dev"

**Comment by jjtParadox** [comment]
Just tested and this issue has already been resolved.
