### ISSUE TITLE
Magician's Workbench doesn't open and can't be broken. 

### ISSUE THREAD

**Issue by AshenFlames** [Mithion/ArsMagica2#1197]
So I recently re-entered my world and found that my Magician's Workbench will not open and, for some reason, can't be broken even in creative mode. Before I last left the world I only just used it to craft a couple blank runes and stored some cobble in them. Closing Minecraft and restarting does not change a thing. I am using the 1.7.10 version. Any suggestions?

**Comment by Mithion** [comment]
Did you put a keystone combination to lock it?  That will prevent it from opening/breaking unless you have a keystone with the matching combo.

Try running /recoverkeystone and then right clicking the bench.  it should tell you what the combo was.

**Comment by AshenFlames** [comment]
Ok thanks, I was just fiddling with the slots and I placed a blank rune in one of the slots next to my inventory, not realizing that would force it to lock.

**Comment by jjtParadox** [comment]
This issue can probably be closed, but it does lead to an idea of somehow telling a player that a block is locked, like a chat message or a particle effect.

**Comment by Mithion** [comment]
Yeah, that's a good idea.  Closing this as the actual issue was resolved, and adding a clue to indicate what is going on will be opened as a new suggestion.
