### ISSUE TITLE
Dupe bug Arcane Deconstructor

### ISSUE THREAD

**Issue by raymondhardy** [Mithion/ArsMagica2#1199]
The Arcane Deconstructor checks the item when it is first placed in not right before it breaks the item. When the item is switched out it without removing the first item that was put into the deconstructor. To test this put in a diamond block. Then before the block is broken take a stick and click on the diamond block. The block will be swapped for the stick. The result is 1 stick = 9 diamond.  This could be solved by adding a check of the item id right before the item is destroyed.

**Comment by LemADEC** [comment]
Issue can be reproduced by deconstructing a spell in SSP and SMP with am2-1.4.0.008

**Comment by jjtParadox** [comment]
This issue has been resolved and should be marked as closed.

**Comment by Mithion** [comment]
Corrected by #1234
