### ISSUE TITLE
Dupe bug void storage

### ISSUE THREAD

**Issue by raymondhardy** [Mithion/ArsMagica2#1200]
This bug is caused by the end. Can only be done once the dragon is killed. Enter the end with item in your void storage. Empty items from the storage. Leave the end using the portal. Look in void storage and see all your items still in there as well as your inventory.

**Comment by jjtParadox** [comment]
This issue has been resolved and should be marked as closed.

**Comment by Mithion** [comment]
Corrected by #1231
