### ISSUE TITLE
Rituals not correct unlocked

### ISSUE THREAD

**Issue by krakel** [Mithion/ArsMagica2#1202]
Normaly rituals will be unlock with level 15. On my game, I reached level 16 and no ritual entry was showed at the compendium. Also the related entries on all obelisk ended on goggles. I got no exception. All other entries was enbabled correctly.

**Comment by Mithion** [comment]
Duplicate issue.
Tracking in #1256

**Comment by ThatOneTraitor** [comment]
Short term answer

AM2 Configs:

Staged Compendium = False
That will make it so you unlock all your compendium entries instantly,
