### ISSUE TITLE
Penicillin - Minechem Not Working

### ISSUE THREAD

**Issue by manaziraman** [Mithion/ArsMagica2#1203]
I've created Penicillin in a single player world. It is supposed to give the player regeneration 4. But Instead of giving me Regeneration 4 it gives me a Heart with a green plus. I have Ars Magica, Witchery and Thaumcraft installed. Changing the Ars Magica potion regeneration Id to 100 gives me sun scorched. How can I fix this?

**Comment by Iivaitte** [comment]
install dragonapi

**Comment by Mithion** [comment]
Duplicate.  
Tracking in #1212.

**Comment by Iivaitte** [comment]
yeah, sorry about late response, I am just returning to MC.
Anyway, last time I checked installing dragonapi seems absolutely necessary when you have witchery, blood magic and/or ars magica in the same pack.

At this point it belongs in  every pack.
