### ISSUE TITLE
AM2 Moo Moo Farm Dimention bug

### ISSUE THREAD

**Issue by rmrocks01** [Mithion/ArsMagica2#1205]
I have constructed a working gateway full to the brim with dark erthium and when I right click on it with a evil-looking book, it opens as a open network gateway rather then a red hell cow portal. 

(As a side question, does the new dev read these?)

**Comment by Iivaitte** [comment]
yes, moo moo dimension is disabled currently iirc

**Comment by rmrocks01** [comment]
Any way to renable it?

**Comment by jawdylawdy** [comment]
Nope. It's not just disabled, it doesn't exist.

**Comment by jjtParadox** [comment]
This should be closed since the Moo Moo Farm was intentionally removed, unless @Mithion has plans to put it back in.

**Comment by Mithion** [comment]
The Moo Moo Farm dimension was in fact removed, but there is still a way to get a hell cow as a summon.
