### ISSUE TITLE
Divine Intervention Bug

### ISSUE THREAD

**Issue by rmrocks01** [Mithion/ArsMagica2#1206]
I started a new world, used ender intervention to ger to the nether, then used divine intervention to go back to overworld spawn, which crashed my game. anso when you use either ender or divin intervention, you get stuck 1 blick into the floor.

**Comment by LemADEC** [comment]
We can't help you without crash logs...

**Comment by Mithion** [comment]
Closing this bug and tracking the issue in #1146
