### ISSUE TITLE
Ars Magica crash on startup

### ISSUE THREAD

**Issue by HalPvp** [Mithion/ArsMagica2#1208]
I am loading up my game, and the game crashes at step 7 in forge's startup. When i remove Ars Magica, it loads perfectly. Here is my crash log
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 7/25/15 11:28 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: am2/guis/GuiArcaneCompendium
	at am2.proxy.tick.ClientTickHandler.renderTick_Start(ClientTickHandler.java:281)
	at am2.proxy.tick.ClientTickHandler.onRenderTick(ClientTickHandler.java:322)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_15_ClientTickHandler_onRenderTick_RenderTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:335)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:999)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: am2.guis.GuiArcaneCompendium
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	... 15 more
Caused by: java.lang.OutOfMemoryError: PermGen space
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.10.4
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 213257912 bytes (203 MB) / 457105408 bytes (435 MB) up to 5359992832 bytes (5111 MB)
	JVM Flags: 1 total; -Xmx5G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 29 mods loaded, 29 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1492} [Minecraft Forge] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCHIJA	AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) 
	UCHIJA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJA	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.4.83} [Not Enough Items] (notenoughitems-1.7.10-1.0.4.83.jar) 
	UCHIJA	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) 
	UCHIJA	AnimationAPI{1.2.4} [AnimationAPI] (animationapi-1.7.10-1.7.10-1.2.4.jar) 
	UCHIJA	arsmagica2{1.4.0.008} [Ars Magica 2] (1.7.10_AM2-1.4.0.008.jar) 
	UCHIJA	FLabsBF{4.1.2} [Better Furnaces] (1710betterfurnacesv412-4.1.2.jar) 
	UCHIJA	DamageIndicatorsMod{3.2.3} [Damage Indicators] (1710damageindicatorsmod-323-3.2.3.jar) 
	UCHIJA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJA	CoFHCore{1.7.10R3.0.0RC7} [CoFH Core] (cofhcore-1.7.10-3.0.0rc7.jar) 
	UCHIJA	ThermalFoundation{1.7.10R1.0.0RC7} [Thermal Foundation] (thermalfoundation-1.7.10-1.0.0rc7.jar) 
	UCHIJA	ThermalExpansion{1.7.10R4.0.0RC7} [Thermal Expansion] (thermalexpansion-1.7.10-4.0.0rc7.jar) 
	UCHIJA	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHIJA	iChunUtil{4.0.0} [iChunUtil] (iChun-Util-Mod-1.7.10.jar) 
	UCHIJA	IC2{2.2.756-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.756-experimental.jar) 
	UCHIJA	InfernalMobs{1.6.0} [Infernal Mobs] (InfernalMobs-1.7.10.jar) 
	UCHIJA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (mantle-1.7.10-0.3.2.jenkins184.jar) 
	UCHIJA	Morph{0.9.1} [Morph] (Morphing-Mod-1.7.10.jar) 
	UCHIJA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJA	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (tconstruct-1.7.10-1.8.2.jar) 
	UCHIJA	ThermalDynamics{1.7.10R1.0.0RC7} [Thermal Dynamics] (thermaldynamics-1.7.10-1.0.0rc7.jar) 
	UCHIJA	TMechworks{0.2.12.95} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.12.95.jar) 
	UCHIJA	WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar) 
	UCHIJA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-10.6.31' Renderer: 'Intel HD Graphics 4000 OpenGL Engine'
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.0RC7-211
	ThermalFoundation: -[1.7.10]1.0.0RC7-62
	ThermalExpansion: -[1.7.10]4.0.0RC7-141
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	ThermalDynamics: -[1.7.10]1.0.0RC7-98
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BC:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10-Forge10.13.4.1492-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel HD Graphics 4000 OpenGL Engine GL version 2.1 INTEL-10.6.31, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [ocdpack187113693.zip]
	Current Language: English (UK)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by jjtParadox** [comment]
This isn't an issue with Ars Magica, as your JVM is running out of PermGen space. Try running with the command line parameter `-XX:MaxPermSize=128m`.

**Comment by Mithion** [comment]
Closing as JVM Flags Issue.

**Comment by YuNoGuy123** [comment]
This is happening to me and this "-XX:MaxPermSize=128m" didnt help
