### ISSUE TITLE
Addon usability improvement

### ISSUE THREAD

**Issue by kayila** [Mithion/ArsMagica2#1211]
I'd love to make an addon which uses some of the blocks and such from am2, but I'm having difficulty getting it to run in my dev/deobfuscated environment. Is there any chance a deobfuscated jar could be released so i can do proper testing in my environment? Thanks!

**Comment by Mithion** [comment]
If you drop CodeChickenCore into your dev environment's mods folder, it will deobf mods at runtime and allow you to use them.

**Comment by kayila** [comment]
You guys just gave me a piece of information which I was unable to find via google. Thanks for the tip, this is solved for me!
