### ISSUE TITLE
Keystone Kicks Players

### ISSUE THREAD

**Issue by manaziraman** [Mithion/ArsMagica2#1215]
Every time I open a Keystone it kicks me from the server. It says internal server error

**Comment by jjtParadox** [comment]
We need a little more information on this, can you read http://pastebin.com/29r0Nhe0 and get back to us?

Specifically, item # 3 helps us the most, but all the items are helpful.

**Comment by Mithion** [comment]
I'm unable to replicate this in any tests.  Client, server, and LAN all work fine for me - has anyone else been able to replicate this?

**Comment by jjtParadox** [comment]
No luck over here.

**Comment by jjtParadox** [comment]
We can probably safely close this, for if it does pop up a bug report with more information can be filed.
