### ISSUE TITLE
Dig spells delete Thermal Expansion machines

### ISSUE THREAD

**Issue by whitepyros** [Mithion/ArsMagica2#1217]
Whenever a player uses a dig spell on a thermal expansion machine i doesnt drop as its supposed to it instead just deletes the machine, havent tested with other machines such as ender io yet

AM2 version: 1.4.0.008
Thermal expansion version: 4.0.3B1-218

**Comment by LemADEC** [comment]
There's a configurable blacklist in the configuration file:
    # Comma-separated list of block IDs that dig cannot break.  If a block is flagged as unbreackable in code, Dig will already be unable to break it.  There is no need to set it here (eg, bedrock, etc.).  Dig also makes use of Forge block harvest checks.  This is mainly for fine-tuning.
    S:dig_blacklist=

**Comment by jjtParadox** [comment]
I believe this issue has been fixed, unless there was a different reason @Mithion added this to the milestone.

**Comment by Mithion** [comment]
Quite possibly - when creating the milestone I just added any still open issues that need to be fixed before a release candidate could be generated.

This one was fixed by #1239.
