### ISSUE TITLE
[v1.4.0.008] Journal Restores All Spent XP on Shift-Right-Click

### ISSUE THREAD

**Issue by Eunomiac** [Mithion/ArsMagica2#1218]
Whenever I spend XP for any purpose, the next time I attempt to store (not retrieve, oddly enough) experience in my Journal, the Journal immediately gives me back all of the XP I just spent.

For example:  
* At level 32, I spend 30 levels to enchant something, putting me at level 2.
* Then, I shift-right-click with my Journal to store those 2 levels... but, instead of storing (and *losing*) the XP, I immediately jump back *up* to level 32.
* After this one-time refund, I can store XP in the Journal just fine---the bug only happens the *first* time I try to store XP after spending it.
* But I don't want to cheat, so I remove the extra levels (say, with the "/xp -30L" command, or by enchanting a Book then voiding it):  I'm back at level 2...
* ... until I shift-right-click with my Journal, and jump right back up to level 32 again.

The *only* way I've found to get rid of those levels permanently is to store them in a second Journal---using it as a sort of "trash can" for the excess XP.

Important note:  I'm currently playing the [Hubris modpack] (http://forum.feed-the-beast.com/threads/1-7-10-hubris-v1-5-0-hqm-270-quests-magic-dungeons-dimensions-exploration-now-listed.79259/) (FTB Launcher, pack code 'Hubris'---a list of included mods can be found [here](http://forum.feed-the-beast.com/threads/1-7-10-hubris-v1-5-0-hqm-270-quests-magic-dungeons-dimensions-exploration-now-listed.79259/)), just in case mod interactions are at fault---but I was able to reproduce the issue using only vanilla and Ars Magica components, by performing the following steps immediately after logging into a fresh SSP world:

1. Via NEI's "Cheat" mode, I spawned in a Book & Quill, an Arcane Essence, a (vanilla) Enchantment Table, a stack of Bottles o' Enchanting, and a Book.  *(At no point did I go into Creative Mode, just in case that interferes with XP/the Journal)*
1. I crafted the Journal with the Book & Quill + Arcane Essence (rather than spawning it in directly, just in case)
1. I smashed the Bottles o' Enchanting, which brought me to level 22
1. I used the Enchantment Table to enchant the Book with a level 5 enchantment, dropping me to level 17.
1. I Shift+Right-Clicked the Journal... and immediately jumped back up to level 22.

**Comment by Xentax5** [comment]
I have same problem with journal... it is definitely bugged. I use shift right click and it changes my level from 12 to 43. So Journal is now best XP copying item ever :D

**Comment by Eunomiac** [comment]
> I have same problem with journal... it is definitely bugged. I use shift right click and it changes my level from 12 to 43.
Are you playing AM2 as part of a modpack?  If not, would you be able to [pastebin](http://pastebin.com/) a list of the mods you're using?  Just in case this is a problem caused by interactions with other mods, it might be helpful to the developers to compare your mods to mine :)

**Comment by jjtParadox** [comment]
This issue has been resolved and should be marked as closed.

**Comment by Mithion** [comment]
Corrected by #1237
