### ISSUE TITLE
My game crashes on startup heres the crash report

### ISSUE THREAD

**Issue by skywalker4** [Mithion/ArsMagica2#1223]
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 8/30/15 7:33 PM
Description: Initializing game

java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    net/minecraft/client/renderer/EntityRenderer.func_78480_b(F)V @381: iload_2
  Reason:
    Type 'net/minecraft/world/World' (current frame, locals[2]) is not assignable to integer
  Current Frame:
    bci: @381
    flags: { }
    locals: { 'net/minecraft/client/renderer/EntityRenderer', float, 'net/minecraft/world/World', integer }
    stack: { 'net/minecraft/client/renderer/EntityRenderer', float }
  Bytecode:
    0x0000000: 2ab4 00db b404 2e13 0430 b604 352a b400
    0x0000010: 989a 0026 b804 3ab8 043f bb04 4159 2ab4
    0x0000020: 00db b704 424d 2a2c b500 efb2 0448 2cb5
    0x0000030: 044b 2a04 b500 98b8 044e 2ab4 00db b401
    0x0000040: a54d 2cc6 0072 b804 51c6 006c 1304 5313
    0x0000050: 0453 1304 55b6 045b 1304 5d13 045f b604
    0x0000060: 5b4e bb01 2459 b701 252d b601 2b13 0461
    0x0000070: b601 2bb8 0451 b601 2bb6 0132 3a04 bb04
    0x0000080: 6359 bb01 2459 b701 2513 0465 b601 2b19
    0x0000090: 04b6 012b 1304 67b6 012b b601 32b7 0469
    0x00000a0: 3a05 2ab4 00db b404 6db6 0473 1905 b604
    0x00000b0: 7901 b804 7c2a b400 dbb4 028b c104 8099
    0x00000c0: 0011 2a2a b400 dbb4 028b c004 80b7 0484
    0x00000d0: 2ab4 009a 2ca5 001d 2ab4 009a 2cb8 048a
    0x00000e0: b804 8d2a 09b5 00a0 2a03 b500 a22a 2cb5
    0x00000f0: 009a b804 909a 0009 b804 9399 0007 04a7
    0x0000100: 0004 03b3 0498 b204 9cb8 049f b604 a52a
    0x0000110: b403 f499 0008 2a23 b704 a72a b400 dbb4
    0x0000120: 042e b604 aab8 04af 3e1d 9a00 3d2a b400
    0x0000130: dbb4 017f b404 b299 0030 2ab4 00db b401
    0x0000140: 7fb4 04b5 9900 0a04 b802 9a9a 001c b800
    0x0000150: ca2a b400 cc65 1404 b694 9e00 142a b400
    0x0000160: dbb6 04ba a700 0a2a b800 cab5 00cc 2ab4
    0x0000170: 00db b404 2e13 04bc b604 352a 231c b804
    0x0000180: c03d 2ab4 00db b404 c399 00cf 1d99 00cb
    0x0000190: 2ab4 00db b404 c7b6 04cc 2ab4 00db b401
    0x00001a0: 7fb4 0187 1301 886a 1301 8962 3804 1704
    0x00001b0: 1704 6a17 046a 1301 8a6a 3805 2ab4 00db
    0x00001c0: b404 c7b4 04cf 8617 056a 3806 2ab4 00db
    0x00001d0: b404 c7b4 04d2 8617 056a 3807 0436 082a
    0x00001e0: b400 dbb4 017f b404 d599 0006 0236 082a
    0x00001f0: b400 dbb4 017f b401 8499 004d 2a59 b401
    0x0000200: 8c17 0662 b501 8c2a 59b4 0195 1707 62b5
    0x0000210: 0195 232a b401 9966 3809 2a23 b501 992a
    0x0000220: b401 9317 096a 3806 2ab4 0197 1709 6a38
    0x0000230: 072a b400 dbb4 01a1 1706 1707 1508 866a
    0x0000240: b604 d9a7 0015 2ab4 00db b401 a117 0617
    0x0000250: 0715 0886 6ab6 04d9 2ab4 00db b404 2eb6
    0x0000260: 04aa 2ab4 00db b404 dc9a 0245 2ab4 00db
    0x0000270: b401 7fb4 036c b304 debb 04e0 592a b400
    0x0000280: db2a b400 dbb4 0142 2ab4 00db b401 45b7
    0x0000290: 04e3 3a04 1904 b604 e636 0519 04b6 04e9
    0x00002a0: 3606 b804 ec15 0568 2ab4 00db b401 426c
    0x00002b0: 3607 1506 b804 ef15 0668 2ab4 00db b401
    0x00002c0: 456c 6404 6436 082a b400 dbb4 017f b404
    0x00002d0: f236 092a b400 dbb4 01a5 c600 c22a b400
    0x00002e0: dbb4 042e 1304 f4b6 0435 2ab4 00db b604
    0x00002f0: f799 0017 2a23 2ab4 04f9 1304 fa15 096c
    0x0000300: 8561 b604 fea7 0009 2a23 09b6 04fe b201
    0x0000310: 1399 002c 2ab4 0108 c600 1a11 1702 b803
    0x0000320: 65b8 03b6 b803 682a b401 0823 b605 01b8
    0x0000330: 03c6 2ab4 00db b601 3c04 b605 062a b805
    0x0000340: 0bb5 04f9 2ab4 00db b404 2e13 050d b605
    0x0000350: 102a b400 dbb4 017f b403 b999 000d 2ab4
    0x0000360: 00db b402 8bc6 002a 1102 0413 01c1 b805
    0x0000370: 142a b400 dbb4 046d 232a b400 dbb4 028b
    0x0000380: c600 0704 a700 0403 1507 1508 b605 182a
    0x0000390: b400 dbb4 042e b604 aaa7 0033 0303 2ab4
    0x00003a0: 00db b401 422a b400 dbb4 0145 b805 1c11
    0x00003b0: 1701 b803 65b8 0368 1117 00b8 0365 b803
    0x00003c0: 682a b605 1f2a b805 0bb5 04f9 2ab4 00db
    0x00003d0: b402 8bc6 00db 1101 00b8 0522 0336 0ab2
    0x00003e0: 0525 b602 5099 0030 b205 2907 bd00 0459
    0x00003f0: 032a b400 dbb4 028b 5359 0415 07b8 052f
    0x0000400: 5359 0515 08b8 052f 5359 0623 b805 3453
    0x0000410: b805 3836 0a15 0a9a 0012 2ab4 00db b402
    0x0000420: 8b15 0715 0823 b605 3eb2 0541 07bd 0004
    0x0000430: 5903 2ab4 00db b402 8b53 5904 1507 b805
    0x0000440: 2f53 5905 1508 b805 2f53 5906 23b8 0534
    0x0000450: 53b8 0538 57a7 0059 3a0a 190a 1305 43b8
    0x0000460: 0549 3a0b 190b 1305 4bb6 054f 3a0c 190c
    0x0000470: 1305 51bb 000d 592a b705 54b6 055a 190c
    0x0000480: 1305 5cbb 000b 592a 1507 1508 b705 5fb6
    0x0000490: 055a 190c 1305 61bb 0009 592a 1904 b705
    0x00004a0: 64b6 055a bb05 6659 190b b705 69bf 2ab7
    0x00004b0: 056c 2ab7 056f 2ab4 00db b401 7fb4 0572
    0x00004c0: 2ab4 00ba 9f00 1f2a 2ab4 00db b401 7fb4
    0x00004d0: 0575 b500 bc2a 2ab4 00db b401 7fb4 0572
    0x00004e0: b500 ba2a b400 dbb4 017f b405 7299 001b
    0x00004f0: 2a2a b400 dbb4 042e b405 782a b400 dbb4
    0x0000500: 042e b405 7bb7 057f 2ab4 00db b401 7fb4
    0x0000510: 0582 9900 0e2a b400 dbb4 017f 04b5 0575
    0x0000520: b1                                     
  Exception Handler Table:
    bci [988, 1109] => handler: 1112
  Stackmap Table:
    same_frame(@55)
    append_frame(@181,Object[#1150])
    same_frame(@208)
    same_frame(@242)
    same_frame(@254)
    same_frame(@258)
    same_locals_1_stack_item_frame(@259,Integer)
    same_frame(@283)
    append_frame(@334,Integer)
    same_frame(@359)
    same_frame(@366)
    full_frame(@495,{Object[#2],Float,Object[#1150],Integer,Float,Float,Float,Float,Integer},{})
    same_frame_extended(@582)
    full_frame(@600,{Object[#2],Float,Object[#1150],Integer},{})
    full_frame(@776,{Object[#2],Float,Object[#1150],Integer,Object[#1248],Integer,Integer,Integer,Integer,Integer},{})
    same_frame(@782)
    same_frame(@818)
    same_frame(@829)
    same_frame(@872)
    full_frame(@903,{Object[#2],Float,Object[#1150],Integer,Object[#1248],Integer,Integer,Integer,Integer,Integer},{Object[#1135],Float})
    full_frame(@904,{Object[#2],Float,Object[#1150],Integer,Object[#1248],Integer,Integer,Integer,Integer,Integer},{Object[#1135],Float,Integer})
    same_frame(@911)
    same_frame(@924)
    same_frame(@972)
    append_frame(@1045,Integer)
    same_frame(@1065)
    full_frame(@1112,{Object[#2],Float,Object[#1150],Integer,Object[#1248],Integer,Integer,Integer,Integer,Integer},{Object[#1066]})
    full_frame(@1198,{Object[#2],Float,Object[#1150],Integer},{})
    same_frame(@1251)
    same_frame(@1288)
    same_frame(@1312)

	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:502)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:502)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 56525128 bytes (53 MB) / 274436096 bytes (261 MB) up to 1038876672 bytes (990 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:-OmitStackTraceInFastThrow -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xms256M -Xmx1024M -XX:MetaspaceSize=128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 Optifine OptiFine_1.7.10_HD_U_B7 85 mods loaded, 85 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291-universal.jar) Unloaded
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291-universal.jar) Unloaded
	AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) Unloaded
	appliedenergistics2-core{rv2-stable-1} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded
	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) Unloaded
	NotEnoughItems{1.0.4.80} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.80-universal (1).jar) Unloaded
	VeinMiner_coremod{0.27.1_build.unknown} [Core mod] (minecraft.jar) Unloaded
	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) Unloaded
	arsmagica2{1.4.0.008} [Ars Magica 2] (1.7.10_AM2-1.4.0.008.jar) Unloaded
	ae2stuff{0.2.1.22} [AE2 Stuff] (AE2STUFF-0.2.1.22-MC1.7.10.jar) Unloaded
	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) Unloaded
	appliedenergistics2{rv2-stable-1} [Applied Energistics 2] (APPLIEDENERGISTICS2-RV2-STABLE-1.jar) Unloaded
	bdlib{1.7.1.71} [BD Lib] (BDLIB-MC1710-1.7.1.71.jar) Unloaded
	BigReactors{0.4.3A} [Big Reactors] (BIGREACTORS-0.4.3A.jar) Unloaded
	Botania{r1.7-208} [Botania] (Botania r1.7-208.jar) Unloaded
	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) Unloaded
	chisel{1.5.7} [Chisel] (Chisel-1.7.10-1.5.7.jar) Unloaded
	CoFHCore{1.7.10R3.0.2} [CoFH Core] (COFHCORE-[1.7.10]3.0.2-262.jar) Unloaded
	ComputerCraft{1.74} [ComputerCraft] (ComputerCraft1.74.jar) Unloaded
	EnderIO{1.7.10-2.0.5.214} [Ender IO] (EnderIO-1.7.10-2.0.5.214.jar) Unloaded
	ExtraUtilities{1.2.5} [Extra Utilities] (extrautilities-1.2.5.jar) Unloaded
	flansmod{4.8.0} [Flan's Mod] (Flans Mod-1.7.10-4.8.0.jar) Unloaded
	F2L{1.7.10b} [Flesh2Leather] (Flesh2Lether [1.7.10b].jar) Unloaded
	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded
	JABBA{1.1.4} [JABBA] (Jabba-1.1.4_1.7.10.jar) Unloaded
	magicalcrops{4.0.0_PUBLIC_BETA_3} [Magical Crops] (magicalcrops-4.0.0_PUBLIC_BETA_3.jar) Unloaded
	malisiscore{1.7.10-0.11.3} [MalisisCore] (MALISISCORE-1.7.10-0.11.3.jar) Unloaded
	malisisdoors{1.7.10-1.7.1} [Malisis' Doors] (MALISISDOORS-1.7.10-1.7.1.jar) Unloaded
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2 (1).jar) Unloaded
	Mekanism{8.1.5} [Mekanism] (Mekanism-1.7.10-8.1.5.246.jar) Unloaded
	MekanismGenerators{8.1.5} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.5.246.jar) Unloaded
	MekanismTools{8.1.5} [MekanismTools] (MekanismTools-1.7.10-8.1.5.246.jar) Unloaded
	minechem{5.0.5.394} [Minechem] (Minechem-1.7.10-5.0.5.394.jar) Unloaded
	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MINEFACTORYRELOADED-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MINEFACTORYRELOADED-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MINEFACTORYRELOADED-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MINEFACTORYRELOADED-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MINEFACTORYRELOADED-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MINEFACTORYRELOADED-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MINEFACTORYRELOADED-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MINEFACTORYRELOADED-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MINEFACTORYRELOADED-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MINEFACTORYRELOADED-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MINEFACTORYRELOADED-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MINEFACTORYRELOADED-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MINEFACTORYRELOADED-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MINEFACTORYRELOADED-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MINEFACTORYRELOADED-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MINEFACTORYRELOADED-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MINEFACTORYRELOADED-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MINEFACTORYRELOADED-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MINEFACTORYRELOADED-[1.7.10]2.8.0-104.jar) Unloaded
	powersuits{0.11.0.177} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.177.jar) Unloaded
	Morph{0.9.1} [Morph] (Morph-Beta-0.9.1.jar) Unloaded
	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) Unloaded
	numina{0.4.0.100} [Numina] (Numina-0.4.0.100.jar) Unloaded
	MapWriter{2.1.2} [MapWriter] (OPIS-1.2.5_1.7.10.jar) Unloaded
	Opis{1.2.5} [Opis] (OPIS-1.2.5_1.7.10.jar) Unloaded
	harvestcraft{1.7.10i} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10i.jar) Unloaded
	ProjRed|Integration{4.7.0pre5.89} [ProjectRed Integration] (ProjectRed-1.7.10-Integration.jar) Unloaded
	ProjRed|Transmission{4.7.0pre5.89} [ProjectRed Transmission] (ProjectRed-1.7.10-Integration.jar) Unloaded
	ProjRed|Core{4.7.0pre5.89} [ProjectRed Core] (ProjectRed-Base-1.7.10.jar) Unloaded
	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.394.jar) Unloaded
	SirenMod{2.2.01} [TheRealMcrafter's Siren Mod (Version 3.0.0)] (SirenMod-3.0.0.jar) Unloaded
	TConstruct{1.7.10-1.8.3.build919} [Tinkers' Construct] (TConstruct-1.7.10-1.8.3b.jar) Unloaded
	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded
	ThermalDynamics{1.7.10R1.0.0} [Thermal Dynamics] (THERMALDYNAMICS-[1.7.10]1.0.0-122.jar) Unloaded
	ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion] (THERMALEXPANSION-[1.7.10]4.0.1-182.jar) Unloaded
	ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (THERMALFOUNDATION-[1.7.10]1.0.0-81.jar) Unloaded
	ttCore{MC1.7.10-0.1.1-76} [ttCore] (TTCORE-MC1.7.10-0.1.1-76.jar) Unloaded
	VehicularMovement{1.1.0} [VehicularMovement] (VehicularMovement-1.1.0.jar) Unloaded
	VeinMiner{0.27.1_build.unknown} [Vein Miner] (VeinMiner-1.7.10_0.27.1.unknown.jar) Unloaded
	VeinMinerModSupport{0.27.1_build.unknown} [Mod Support] (VeinMiner-1.7.10_0.27.1.unknown.jar) Unloaded
	Waila{1.5.10} [Waila] (WAILA-1.5.10_1.7.10.jar) Unloaded
	WailaHarvestability{1.1.2} [Waila Harvestability] (WAILAHARVESTABILITY-MC1.7.X-1.1.2.jar) Unloaded
	wailaplugins{MC1.7.10-0.0.1-15} [WAILA Plugins] (WAILAPLUGINS-MC1.7.10-0.0.1-15.jar) Unloaded
	wawla{1.2.1} [What Are We Looking At] (WAWLA-1.2.1_1.7.10.jar) Unloaded
	witchery{0.22.0} [Witchery] (witchery-1.7.10-0.22.0.jar) Unloaded
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded
	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) Unloaded
	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) Unloaded
	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) Unloaded
	MrTJPCoreMod{1.1.0.27} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.27-universal.jar) Unloaded
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GT 720/PCIe/SSE2 GL version 4.5.0 NVIDIA 355.60, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Icexist** [comment]
Does your game crash with just Ars Magica active and no other mods? Does it crash with Ars Magica removed?

**Comment by technonine** [comment]
Can confirm this bug, also did the test above and it doesnt crash with just ars magica and animation API, for convenience sake I'll see if I can find the mod combination that gives it.

**Comment by skywalker4** [comment]
Thank you you have helped a lot
