### ISSUE TITLE
[Code] Should we pick a formatting or style guideline?

### ISSUE THREAD

**Issue by jjtParadox** [Mithion/ArsMagica2#1226]
Purely personal preference, but I have noticed some inconsistent formatting here or there and have been very tempted to use InteliJ's auto-formatter to clean it up a little.

As far as I've noticed, most of the code is spaced with tabs, there is no space before or after brackets in code, and the left bracket is on the same line as the method/loop/conditional. A formatter template can be crafted from these conditions if wanted, otherwise we could pick a more official guideline for code.

Should we use a guideline?

**Comment by LewisMcReu** [comment]
Personally I believe we could all just use our own format and have our IDE format for us whenever we want. I know the Eclipse shortcut heart.

**Comment by Mithion** [comment]
That's a bad idea - a consistent format is necessary in a collaborative project.
My usual formatting is based pretty much around what the original comment states; a formatter template would work fine for me.

**Comment by Kolatra** [comment]
It is quite easy to create a settings file for IDEA and Eclipse that people could be required to use before submitting code.

**Comment by jjtcomkid** [comment]
I'll make a pull request of code the formatter outputted so we can review it and make modifications if necessary

**Comment by jjtcomkid** [comment]
Whoops looks like one of my other commits from a different pull request sneaked into the cleanup one, I'll try to fix that

**Comment by jjtParadox** [comment]
An IntelliJ IDEA template has been added to the repository, just waiting for Mithion to update the readme before closing this.

**Comment by EoD** [comment]
One suggestion: Could you add spaces before brackets? An if like the following is harder readable without it
```
if ( x == true){
    ...;
}
```
vs
```
if ( x == true) {
    ...;
}
```

Also, as some people use Eclipse it might be good to add styling guidelines for Eclipse too.

**Comment by Mithion** [comment]
I prefer no space before the bracket, it's how I've always learned and I find it more readable myself.

**Comment by Mithion** [comment]
The readme.md has been updated.
