### ISSUE TITLE
Infinity Orbs aren't getting removed when used

### ISSUE THREAD

**Issue by TerdyTheTerd** [Mithion/ArsMagica2#1229]
When I right click an infinity orb, the chat mesage appears, but it doesnt remove the orb from my inventory, so I can just keep using it. Looking at the source I can see 

	private ItemStack doGiveSkillPoints(EntityPlayer player, ItemStack stack, SkillPointTypes type){
		if (ExtendedProperties.For(player).getMagicLevel() > 0){
			SkillData.For(player).incrementSpellPoints(type);
			if (player.worldObj.isRemote){
				switch (type){
				case BLUE:
					player.addChatMessage(new ChatComponentText(StatCollector.translateToLocal("am2.tooltip.infOrbBlue")));
					break;
				case GREEN:
					player.addChatMessage(new ChatComponentText(StatCollector.translateToLocal("am2.tooltip.infOrbGreen")));
					break;
				case RED:
					player.addChatMessage(new ChatComponentText(StatCollector.translateToLocal("am2.tooltip.infOrbRed")));
					break;
				default:
					return stack;
				}
			}
			stack.stackSize--;
			if (stack.stackSize < 1){
				player.inventory.setInventorySlotContents(player.inventory.currentItem, null);
			}
		}else{
			if (player.worldObj.isRemote){
				int message = player.worldObj.rand.nextInt(10);
				player.addChatMessage(new ChatComponentText(StatCollector.translateToLocal("am2.tooltip.infOrbFail" + message)));
			}
		}
So the first part is working, it changes the messages depending on what type of orb it is, the third part works because it actually displays the message, but that middle part, stack.stackSize, isn't working because the item isn't getting removed. I would clone this repo and build a new branch but my knowledge is very limited, any help would be appreciated because if the orbs don't get removed Ill have to remove the mod :(

**Comment by Zsashas** [comment]
Why would you have to remove the whole mod because of this? If it's single-player, just toss them in lava after using them if it bothers you that much, until it's fixed.

**Comment by TerdyTheTerd** [comment]
Well when you are running a server or its part of a modpack its a problem when a player gets one orb and they suddenly have infinite points. It seems to just be some weird nonreplicable on my machine only type thing, I had a friend test it and his worked just fine so I unistalled/reinstalled java, minecraft and technic, and they still didn't disappear until i picked up a compendium, then they worked properly. After creating a new world though and picking up a compendium they proceeded to not work(although differently than the first time, this time the orb would get removed only to pop back up in my inventory a second later). Since this seems like a very rare local issue and not the mods I'll close it

**Comment by Mithion** [comment]
I understand.  If you find a way to more reliably replicate this, please do re-open the issue (or create a new one).

Thanks!
