### ISSUE TITLE
Crash when using disarm spell

### ISSUE THREAD

**Issue by ExDomino** [Mithion/ArsMagica2#1238]
When a player on my server used the disarm spell, it imediately crash but nothing append. Pvp is disabled on my server. Crashlog here: http://pastebin.com/1F2HLtsM

It's apparently related to #1048. Minecraft version: 1.7.10, ArsMagica2 version: 1.4.0.008.
Edit: Apprently fixed on 009, we will wait for the fix.

**Comment by jjtParadox** [comment]
Same as #1196, tested and resolved.
