### ISSUE TITLE
Contributors list uses usernames, not UUIDs

### ISSUE THREAD

**Issue by jjtParadox** [Mithion/ArsMagica2#1244]
I was digging through issue #1122 and found a lot of player information is stored by username, including your contributors list (DGSVNT352.txt on your website).

The issue with using usernames is now MCers can change their username through Mojang. Because of this you should use the player UUID, which never changes even when username changes.

You should also update your contributors list to use UUIDs, in the unlikely case that one of them decides to change their username.

(If you need to PM me, I'm on twitter https://twitter.com/jjtParadox)

I plan on making a fix for #1122 soon, unless @DoomFruit already has one in the works.

**Comment by Mithion** [comment]
The contributors list and code surrounding it I will take care of myself - don't worry about this one.

**Comment by jjtParadox** [comment]
Any update on this issue? This appears to be relatively low priority, so I'm not certain if this should be included in the 1.4.0.009 milestone.

**Comment by Mithion** [comment]
This has been completed by commit 2cd3f46ba495ca16df61796d5f7e8164756472d7
