### ISSUE TITLE
[Question] Burnout

### ISSUE THREAD

**Issue by Bellwar** [Mithion/ArsMagica2#1245]
Sorry if this shouldnt go here but didnt find better place to ask.

I wanted to ask if burnout need to be that hight and fast gained i just dont feel its good when after first two uses of spell i just have full burnout. I mean its nice idea but i think atleast the starting (didnt get so far for now) i feel so pushed down because the burnout and cost of things after that.

So i would like to talk about it so i can get why it is so easy to get burnout

**Comment by Mithion** [comment]
Burnout replaced spell cooldowns - basically spells had cooldowns in between when they could be cast, and the time was based on the complexity of the spell as well as what was in it.

General consensus was that the cooldowns were too limiting, and it was more fun to be able to spam spells like crazy.

So, I devised a system that would allow you to spam spells if you wanted to, but at a cost.  That became burnout.

If you're finding burnout is too limiting, try making some mana potions.  They will make a huge difference as they now apply a mana regeneration buff after drinking them that will continue to help counter burnout.

**Comment by Bellwar** [comment]
Well i under stand it but i think at the start when you have one maybe two spells it doesnt make sens make bigger mana pool and same for burnout what i feel its i dont get more mana for more casting i just get more mana so i can cast same amout for the burnout maybe make the burnout scale on start slower so its no so bad or make it go burnout away faster, but maybe its just my first feel and i will get on it and i understand what you ment with thx for the explanation. :)

**Comment by Mithion** [comment]
It's early game, you're a fledgling mage at that point - it's supposed to be difficult.
Magic is a little harder to control and it takes more focus, but through training you will find it becomes much easier.

Like I said, potions.  If you're looking to slow down burnout gain, there's always the tier 1 armor imbuements to do so as well.

**Comment by Bellwar** [comment]
ooooo I got it now... yeah now it looks good can wait how it would feel in later levels

**Comment by Mithion** [comment]
Excellent :)  I'm going to close this question as answered.  Feel free to ask any others at::

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292222

That's the place for general help and discussion.
