### ISSUE TITLE
[Suggestion] Can we finally get a fix for soulbound items disappearing in other dimensions

### ISSUE THREAD

**Issue by TerdyTheTerd** [Mithion/ArsMagica2#1250]
To start off with no I don't have a lot of experience with java so I am unable to to do this myself, but could someone else with greater knowledge than me fix the soulbound items disappearing if you die in another dimension, like dimensions added by other mods. I would assume since this is now open source it wouldn't be that hard for someone to make a pull request(I would try but I'm not experienced with setting up the dev work-spaces from github with the other requires libraries)

**Comment by jjtParadox** [comment]
This was fixed by #1231 and will be in the next version of Ars Magica.

**Comment by TerdyTheTerd** [comment]
I thought I saw that in the changed source, I thought it was specifically for the end, but wow this is great news
