### ISSUE TITLE
Maybe bug, arcane compendium not unlocked

### ISSUE THREAD

**Issue by Bellwar** [Mithion/ArsMagica2#1253]
I know the compendium is going to give me new text when i got the item or theres anything about calefactor, no thing about wrench, im level 13 no boss. No word about essence refiner. Am i missing some type of block or why im just much more in, then my book?

I know i can unlock it but i want go step by step when i see a lot of new things in it.

**Comment by Mithion** [comment]
Unlocks generally happen under 3 conditions:

- You right click the block for the compendium (that will unlock it if it isn't already)
- You pick up the block/item from the ground
- You craft the predecessor item in the tree (this is the one that seems hit and miss)

- You reach certain magic levels (this is more for bosses only)

Shapes/Components/Modifiers are based on the skill trees and seem to work well.  The part that's sometimes-bugged is the staged compendium based on crafting.

**Comment by Bellwar** [comment]
Yeah i got on level 15 inlays with water and earth boss and why i dont have furnace or wrench that so early what am i missing? Do you have any idea?

**Comment by Mithion** [comment]
You unlock the crystal wrench when you craft/use an Obelisk, Celestial Prism, Black Aurem or a Crystal Marker.  Likely the first thing you'll get is the Obelisk, which you unlock when you craft/interact with a Crafting Altar.

**Comment by Bellwar** [comment]
Ok so obelisk opened me 12 things and there was no word about obelisk before :( So maybe i was doing wrong something before. Im just worried i will not open everything at the end game :/ Now im thinking (something like suggestion) if you could make something like next locked things so you know where you stuck in book. But its easy to say, when even i who suggested it cant imagine how to do it :/ but would like this option to be there so nobody get stuck.

**Comment by Mithion** [comment]
This more comes down to three things:

1.) Getting compendium unlocks to fire properly when an item is crafted or picked up.  Interact on blocks is working fine, but the other two don't always fire properly.

2.) Expanding the links between items in the Compendium, or defining a new way to mark progression.  All unlocking is controlled via the "relatedentries" in the compendium.  This controls what is displayed in the compendium at the bottom of a page.  When you unlock something in the Compendium, all of it's related entries unlock as well.  It may make more sense to have another section, "unlocks", which directly controls what unlocks vs what is shown as related items.

3.)  The compendium storage system is inadequate.  I should have stored it in either an IExtendedEntityProperties class or in the entity's persistent NBT (this would make more sense for something like compendium progress).

**Comment by Mithion** [comment]
New tickets have been opened to enhance this functionality - I'm going to close this and track the individual progress there.
