### ISSUE TITLE
API for mana network

### ISSUE THREAD

**Issue by LemADEC** [Mithion/ArsMagica2#1280]
As part of my WarpDrive mod, players are able to move their base around. Since Mana network isn't saved with blocks, all blocks connections are lost when they are moved.
To address that requirement, I propose to add an API that would allow to 'read' the current connection & mana levels of an ArsMagica2 block, and 'apply' it back after the blocks have been moved.

**Comment by jjtParadox** [comment]
I think you'll find [`am2.power.PowerNodeRegistry`](https://github.com/Mithion/ArsMagica2/blob/master/src/main/java/am2/power/PowerNodeRegistry.java) and [`am2.blocks.tileentities.TileEntityAMPower`](https://github.com/Mithion/ArsMagica2/blob/master/src/main/java/am2/blocks/tileentities/TileEntityAMPower.java) to be useful, as those both manage mana power levels and mana connections.

**Comment by LemADEC** [comment]
So I guess I need to
- call getDataCompoundForNode(),
- get the vectors in there,
- adjust vectors to new coordinates,
- call setDataCompoundForNode()
and that would cover both the power level and the blocks connection.
Did I get that right?

**Comment by jjtParadox** [comment]
I'm personally not extremely familiar with the power network, but make sure the methods you are calling are properly deleting and saving the data to NBT, as it's possible for ghost data to linger after nodes are adjusted if you use the wrong methods.

**Comment by LemADEC** [comment]
When a PoweredBlock is removed, onDeath() is called from here https://github.com/Mithion/ArsMagica2/blob/master/src/main/java/am2/blocks/PoweredBlock.java#L44
to here
https://github.com/Mithion/ArsMagica2/blob/master/src/main/java/am2/blocks/tileentities/TileEntityAMPower.java#L38
effectively removing it from the registry.

However, when a tile entity is removed, Minecraft first sets it to null in the world, then call invalidate(). Hence, when a block is effectively removed, it's too late and a ghost Power network will remain.
Removing tile entity first is typically used to prevent items dropping during removal (mining block, explosives, etc. in other mods).
I'll forcefully remove the network in my mod, but I would suggest you fix it in there too, assuming I didn't miss something :).

**Comment by jjtParadox** [comment]
Would a solution be to insert the following into TileEntityAMPower?

````java
@Override
public void invalidate(){
	if (worldObj != null && !worldObj.getTileEntity(xCoord, yCoord, zCoord).equals(this)){
		onDeath(worldObj);
	}
	super.invalidate();
}
````

**Comment by LemADEC** [comment]
Yes, except that in all cases, you need to call onDeath().

```
@Override
public void invalidate() {
    if (worldObj != null) {
        onDeath(worldObj);
    }
    super.invalidate();
}
```
We might get some console spam from the registry since, in some cases, we will remove twice.

**Comment by jjtParadox** [comment]
I don't like console spam, especially if it's at the "error" level, so I added a check to see if the chunk had node data in it in the first place before removal.

**Comment by LemADEC** [comment]
ok, my mod now supports moving ArsMagica2 power networks, thanks!

**Comment by Mithion** [comment]
Closing this as resolved.
