### ISSUE TITLE
Witchwood forests do not spawn witchwood trees

### ISSUE THREAD

**Issue by DoomFruit** [Mithion/ArsMagica2#1284]
For whatever reason, every single witchwood forest biome I've encountered has been completely devoid of witchwood trees, being populated only with white-leaved oak trees. I see this in both a pure dev environment and in a fully modded setup, so it's not caused by a clash with some other mod.

**Comment by Mithion** [comment]
I'm not seeing this - can you post some more information about your setup?
Is there anything that you're doing as part of your tests that could allow this to be replicated?

**Comment by Zsashas** [comment]
The Witchwood Forests I've found have had a few Witchwood Trees, but not very many. I assumed there were only supposed to be a few, and the rest white oaks.

**Comment by Mithion** [comment]
https://github.com/Mithion/ArsMagica2/blob/master/src/main/java/am2/worldgen/BiomeWitchwoodForest.java

No oaks.  That's why this is so weird.

It could be that the small witchwood tree is generating with oak blocks instead of witchwood log blocks though.

**Comment by DoomFruit** [comment]
Just tested it again using the most recent source (my potion ID fix branch, but there's nothing worldgen-related in there which is different to the master fork), and absolutely no witchwood trees visible.

Generate a world with seed 267697100046533758 and teleport to -1655, 75, 810. That'll put you in a witchwood forest biome populated entirely with white oak trees and a few red flowers.

**Comment by Mithion** [comment]
It's kind of hard to describe, but are the oak-witchwood trees relatively small ones?  Do they still have witchwood leaves?  If you fly around can you see any giant trees?  If so, are they generated properly?

**Comment by DoomFruit** [comment]
They're all small "witchwood" trees and none of them have any kind of witchwood components, leaves or otherwise. In this biome, I see precisely one large witchwood tree, at (-1600, 785) - this one generates properly, as do the large witchwood trees which randomly appear in other biomes.

**Comment by Mithion** [comment]
Alright.  What if you change:

```java
	@Override
	public WorldGenerator getRandomWorldGenForGrass(Random rand){
		return rand.nextDouble() > 0.9f ? hugeTree : smallTree;
	}
```

to remove the small tree check and just return huge tree?  If you re-generate the world and then teleport to those coordinates, does it generate properly?

**Comment by DoomFruit** [comment]
Nope. It's still populated with bleached oak trees (and the singular large witchwood at -1600, 785).

**Comment by DoomFruit** [comment]
I have a few suspicions about what's causing it (namely, a lack of over-ride for the WorldGenAbstractTree func_150567_a() function). I'll take a look at that later on, along with WitchwoodTreeSmall.java (which appears to be a work in progress).

**Comment by DoomFruit** [comment]
Yes, that did indeed fix the problem. I'll submit a PR with these changes.

**Comment by jjtParadox** [comment]
This was fixed with the above pull request.

**Comment by jjtParadox** [comment]
@Kolatra *ping*
