### ISSUE TITLE
Spell book scrolling

### ISSUE THREAD

**Issue by Bellwar** [Mithion/ArsMagica2#1287]
I found a but about moving in scroll book i was able to switch by X and Z (but Z on my kyeboard is not next to a X there is Y) so i change ingame controls to Y so i can move back in spell book and after time i noticed it scroll not back but same direction as X 

playing the latest Ars magica on For the Love of Adventure

**Comment by jawdylawdy** [comment]
Somewhat related to this, attempting to use Telekinesis or Attract in a spellbook doesn't work at all. I can't adjust the range because holding Shift causes me to open the spellbook. It's unfortunate, because those are two of my favourite spells.

**Comment by Mithion** [comment]
@jawdylawdy please open your comment as a separate issue.  It is unrelated to this one.

**Comment by Bogdan-G** [comment]
This question was left unresolved?

**Comment by Bellwar** [comment]
Well it looks like it is solved but not fixed in release its just added to milestone.

**Comment by Bogdan-G** [comment]
@Bellwar a lot of time has passed, but there is no version 1.4.009.

**Comment by Bellwar** [comment]
I hope one day there will be :D

**Comment by jjtParadox** [comment]
I've done some testing, and the main issue of this thread (keyboard buttons both scrolling in the same direction) has been fixed. I have a small fix in the works for shift+scroll wheel scrolling sometimes "breaking" away from the spell book. #1302 is still open, however, but I do have a fix in mind that I should be able to implement soon.

@Mithion I would recommend closing this issue and consider adding #1302 to the update milestone, as keeping this issue open may be confusing for some.

**Comment by Mithion** [comment]
Closing as recommended.
