### ISSUE TITLE
Chrono anchor works strangely after crossing dimensions

### ISSUE THREAD

**Issue by jjtParadox** [Mithion/ArsMagica2#1289]
If I cast chrono anchor, travel to another dimension, then wait for it to wear out, chrono anchor teleports me to the XYZ I was at when I cast chrono anchor, even when that original coordinate was in a different dimension.

In my test I was teleported above a pool of lava after I went from the overworld to the nether.

Should going across dimensions cancel the chrono anchor effect? Or should the chrono anchor effect go off when a player attempts to transfer to another dimension, canceling the transfer?

**Comment by Mithion** [comment]
Chrono anchor should be removed on dimension transfer
