### ISSUE TITLE
[Bug] Contingency Death does nothing !

### ISSUE THREAD

**Issue by ExDomino** [Mithion/ArsMagica2#1300]
On my server, player that used the spell Contingency Death haven't noticed nothing special when they die. What is the real effect of that spell?

**Comment by Mithion** [comment]
It cancels the death event, and works fine if you're using a Forge server.
AM2 does not support Cauldron/MCPC+/etc. 

If you're using those and run into problems, it needs to be replicated in a pure forge environment.

**Comment by ExDomino** [comment]
When you said it cancel the death event, what do you mean? Because if it's only the death event that is cancelled, you will dead in many situations. For example: a zombie hit you when you have 1 half-hearth, you don't die because of the death event is cancelled, but almost instantely after, the zombie hit you again and you die! What's exactly the goal of the Contingency Death in this case?

**Comment by Mithion** [comment]
My mistake, I was thinking Chrono Anchor.
It's a contingency spell that triggers when you die.  It cannot be used to prevent your death.

You might use it to mark the location and then use a soulbound spell book with recall in it to teleport back to where you died, or cause a massive AoE to take down whatever killed you.

It's of limited use, but I wouldn't call it useless.  If your players want something more designed to keep them alive, I would go with Contingency: Health, which will trigger when your health is low.  Combined with a healing effect, this can do quite a bit.

**Comment by ExDomino** [comment]
Thanks! ^^

**Comment by jjtParadox** [comment]
Good to know this has been figured out :smile:

Should we close this issue?

**Comment by Mithion** [comment]
Closing as resolved.
