### ISSUE TITLE
Hide technical blocks from NEI and Creative tabs

### ISSUE THREAD

**Issue by Adaptivity** [Mithion/ArsMagica2#1306]
NEI API has a special function for that (API.hideItem). However, you'll need to implement NEI API first.
List of blocks to hide:
1) Mage Light (mageTorch)
2) InvisibleUtility (invisibleUtility)
3) item.null.name (SpellComponent)
4) Keystone Door (keystoneDoor) Don't confuse with Keystone Door item. It's just door block which have no real uses and have no texture in world.
5) Spell-Sealed Door (spellSealedDoor) Same as above.
6) Witchwood Slab (witchwoodDoubleSlab) Double slabs shouldn't be available in NEI.
These items/blocks also available in Creative but they shouldn't as they do nothing.

**Comment by Mithion** [comment]
Why would the Arcane Compendium want to be hidden in NEI...?

**Comment by Adaptivity** [comment]
... for some reason Arcane Compendium have no texture in my AM2 version (it was built against this commit https://github.com/Mithion/ArsMagica2/commit/6c5e551401284222931f25e8d98fc581c44ccf4a as I remember). So, this I thought it's different item since it's has no texture. Removed from the list.
