### ISSUE TITLE
Binding bugged

### ISSUE THREAD

**Issue by Webber88** [Mithion/ArsMagica2#1312]
the binding is bugged its impossible to bind stuff and is there a way to make the swords better then 6(or7) attack dmg or dmg by binding i mean stuff like bound sword bound hoe bound axe etc

**Comment by jjtParadox** [comment]
"Its impossible to bind stuff" is a bit vague, can you explain what you're trying to do and what you're expecting to happen? Are you trying to make a binding spell, are you trying to increase the damage of the swords, or are you doing something else?

**Comment by Webber88** [comment]
sry i mean the bound armoury such as a bound sword bound axe bound hoe bound pick bound shovel those stuff and iv tried for so long and i havent been able to get it to work

**Comment by Webber88** [comment]
it wont bind when i try creating a binding spell.

**Comment by jjtParadox** [comment]
Make sure you're using the binding catalyst, not just a previously bound weapon.

Can you possibly attach screenshots of your attempt to make the binding spell?

**Comment by Webber88** [comment]
sure

**Comment by Webber88** [comment]
wait i think i just found my problem

**Comment by jjtParadox** [comment]
Yeah, a shape needs to come after the binding part like you've stated.
