### ISSUE TITLE
Battlemage Armor,... + Void Damage

### ISSUE THREAD

**Issue by Nathipha** [Mithion/ArsMagica2#1314]
Version: 1.4.0.008

I already reported this bug on the minecraftforums (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292222-ars-magica-2-version-1-4-0-008-updated-february-6?comment=9078) but I also wanted to report it here, so "sorry" in advance if you've already fixed it in the meantime:

Battlemage armor, Earth Armor and propably the Water Orbs, Ender Boots, Magitech Goggles and the Antenna of the Fire Guardian too (though untested) take damage when you fall into the Void. Battlemage armor then always breaks and you lose it (so no matter if it's soulbound or not) and even the Earth Armor gets down to very low durability.

**Comment by Mithion** [comment]
I'd say the armor should take damage, but for void damage it should stop at 1 and not actually break the armor.

**Comment by Nathipha** [comment]
Sorry, forgot to post your answer from the thread:
