### ISSUE TITLE
Spells having issues (Accidentally entered twice)

### ISSUE THREAD

**Issue by Bgf3** [Mithion/ArsMagica2#1315]
I created a touch light spell however no light source appears even though it shows an animation. I also created a projectile dig spell however it breaks a random block around me instead of shooting a projectile at the block I wish to break. I am using other mods and do not understand what is happening?

**Comment by jjtParadox** [comment]
Can't help you with the dig spell not working correctly, but sometimes Morph or other shape changing stuff screws with projectiles. With the touch light spell, you need to be within 1 or 2 blocks you want to cast the light on. The touch spell part does not have as great of a reach as the player.

**Comment by jjtParadox** [comment]
@Bgf3 any update?

**Comment by Kolatra** [comment]
Closing until further information is provided.
