### ISSUE TITLE
Issues with spells

### ISSUE THREAD

**Issue by Bgf3** [Mithion/ArsMagica2#1316]
I first created a touch light spell which had an animation but no visual effect. Nothing had happened, then I created a projectile dig spell ehich has an animation but just breaks a random block around me. I am using mods but I am not quite sure if it is a conflict or Ars magica issue. It could just be me...

**Comment by jjtParadox** [comment]
What version of AM2 are you using and what mods do you have installed?

**Comment by Bgf3** [comment]
I am using all of the mods below
1.7.10_AM2-1.4.0.008
Morph-Beta-0.92
Ichun Util- 4.00
Craft Guide-1.6.8.2-forge
AnimationAPI-1.7.10-1.2.4
Reis-Minimap-Mod-1.7.10
Reliquary-1.2
Ridablespiders-1.4-1.7.10

**Comment by jjtParadox** [comment]
Are you morphed while trying to cast these spells? Morph and AM2 have conflicts that can usually go unnoticed until someone mixes the two.

**Comment by Bgf3** [comment]
No, however I can remove the mod and see if the spells will work without
it. Would I need to recreate the spells after removing the mod or use the
same ones?

**Comment by Bgf3** [comment]
No, but I can remove the mod and test the spells again.

**Comment by jjtParadox** [comment]
Yeah that would help trace down the culprit.

**Comment by Bgf3** [comment]
I removed the morph mod and recreated the spells. They now work perfectly,
thanks you for your help.
