### ISSUE TITLE
Request: Config to set frequency of skill point acquisition

### ISSUE THREAD

**Issue by Zsashas** [Mithion/ArsMagica2#1318]
Basically, be able to set whether skill points are granted every level instead of every two.

**Comment by Mithion** [comment]
Why would this be needed?  That's the point of infinity orbs, to grant additional skill points.

**Comment by Zsashas** [comment]
To control the rate of progress on servers without having to spawn in extra orbs.

**Comment by Mithion** [comment]
I see.  Would that actually be enough though?  There are other factors too, like at what level you get green orbs instead of blue, etc.

Or would just every x levels be sufficient?

**Comment by Zsashas** [comment]
That would probably be enough, and keeping the current level ranges for the types.

**Comment by Shahelion** [comment]
I fixed the issue with orbs generating (not sure how) and added recipes to make them in emergencies. More than enough.
