### ISSUE TITLE
True Sight Causes Sprout

### ISSUE THREAD

**Issue by Kiara-Liam** [Mithion/ArsMagica2#1320]
Hi,
I made a simple True Sight Spell (Self+True Sight). Whenever i cast this Spell,
I get the effect "Sprout" (random Wood Blocks spawning below me).

MC Version: 1.7.1
Forge: 10.13.4.1448

Sincerly
Kiara-Liam

**Comment by jjtParadox** [comment]
Are you using any other mods with AM2?

**Comment by Kiara-Liam** [comment]
ok, yeah, stupid me, had witchery with it, which conflicts, and in standard AM2.cfg on a server the IDs aren't listed. Thx a lot

**Comment by Kiara-Liam** [comment]
If Someone else hast potion ID conflicts with witchery and thaumcraft and Bloodmagic installed, the following should do the trick:
potions {
    I:agility=77
    I:astraldistortion=78
    I:burnoutredux=79
    I:charmed=80
    I:chronoanchor=81
    I:clarity=82
    I:entangled=83
    I:featherfall=84
    I:flight=85
    I:frostslow=123
    I:fury=124
    I:gravitywell=125
    I:haste=126
    I:illuminated=91
    I:leap=92
    I:levitation=93
    I:magicshield=94
    I:manaboost=95
    I:manaregen=96
    I:manashield=97
    I:regeneration=98
    I:scramblesynapses=99
    I:shrunken=127
    I:silence=118
    I:spellreflect=119
    I:swiftswim=120
    I:truesight=121
    I:waterbreathing=122
    I:waterygrave=29
}

**Comment by jjtParadox** [comment]
Thanks for the config :)

This issue can now probably be closed since we've figure it out.

**Comment by Kiara-Liam** [comment]
jup thx for the help again
