### ISSUE TITLE
Iguana Tinker Tweaks (2.1.5) can't change AM2 (1.4.0.008) ore's mining levels

### ISSUE THREAD

**Issue by dualinfinities** [Mithion/ArsMagica2#1323]
ITT has a config which allows overriding of mining levels. This config does not work with AM2 ores despite using the minetweaker names, which are effective with other ores.
An ineffective config variable for AM2 Sunstone Ore:
I:"arsmagica2:vinteumOre:3"=5
An effective variable for RFTools Dimensional Shard Ore:
I:"rftools:dimensionalShardBlock:0"=5
An effective variable for BOP Ender Amethyst Ore:
I:"BiomesOPlenty:gemOre:0"=9
As you can see, there is no syntax difference between the two. Do you register your ores differently than normal?

**Comment by jjtParadox** [comment]
The AM2 Ores override the `getHarvestLevel()` method to always return 2, so ITT's method of setting harvest level doesn't work.

This is a rather easy fix to do on AM2's side, but ITT might want to consider adding a method of overriding `getHarvestLevel()` so it can be compatible with more mods.

**Comment by dualinfinities** [comment]
What?! How is that a helpful thing to do? What could possibly require that to be done?! I'm seriously confused.

**Comment by jjtParadox** [comment]
Sorry for being confusing, I'm suggesting this  should also be posted to the Iguana Tweaks github as a suggestion.

**Comment by dualinfinities** [comment]
I was talking about locking the harvest levels, sorry for making you think YOU were confusing me.

**Comment by jjtParadox** [comment]
Oh my bad I see what you're talking about :P

It's mostly for convenience in writing the code for the AM2 ores so that extra functions don't have to be attached to the chain following the constructor of the ores.

**Comment by bonii-xx** [comment]
You're effectively breaking the forge harvestlevel API. Go change your hardcoded method overrides to a setHarvestLevel(2) in the blocks constructor. :P
