### ISSUE TITLE
Bandwidth issue 100kbps -> 2000kbps

### ISSUE THREAD

**Issue by doomguy4** [Mithion/ArsMagica2#1325]
When I use AM2 on my server with the following other mods bandwidth per user increases from ~150kbps to ~2000kbps

I have tested and confirmed this by removing AM2 seeing bandwidth drop then adding it back again and seeing it rise

1.7.10-dynamicswordskills-1.6.5.jar 
304.ItemPhysic Full 1.2.1 mc1.7.10.jar 
331.CreativeCore v1.3.4 mc1.7.10.jar 
additionalpipes-4.6.1.jar 
AdvancedMachinesAS-1.7.10.jar 
AnimationAPI-1.7.10-1.2.4.jar 
antiqueatlas-4.2.7-1.7.10.jar 
appliedenergistics2-rv2-stable-10.jar 
AquaticAbyss-1.7.10-1.1.1.jar 
Aroma1997Core-1.7.10-1.0.2.15.jar 
AromaBackup-1.7.10-0.0.0.5.jar 
Artifacts-1.1.3.jar 
autofood-59.0.0.jar 
AutoSapling-1.1.jar 
BattleTowers-1.7.10.zip 
Baubles-1.7.10-1.0.1.10.jar 
bdlib-1.9.2.104-mc1.7.10.jar 
BetterAnvil-4.0.0.0-alpha-1.jar 
betterrain-1.7.2-1.7.10_0.15.zip 
BloodMagic-1.7.10-1.3.3-7.jar 
Bookshelf-1.7.10-1.2.0.jar 
Botania r1.7-221.jar 
BowInfinityFix-1.7.10-rv0.jar 
buildcraft-7.0.23.jar 
Chisel2-2.5.1.44.jar 
CodeChickenCore-1.7.10-1.0.7.47-universal.jar 
CoFHCore-[1.7.10]3.0.3-303.jar 
CoFHLib-[1.7.10]1.0.3-175.jar 
ComputerCraft1.74.jar 
connectedglass-59.0.2.jar 
CustomMobSpawner 3.3.0.zip 
CyanosLootableBodies-1.7.10-backport_1.3.6.jar 
DeadlyWorld-1.7.10-1.0.2.jar 
DeathCounter-5.0.0.jar 
DoomlikeDungeons-1.8.7-MC1.7.10.jar 
DragonAPI 1.7.10 V8g.jar 
DrZharks MoCreatures Mod v6.3.1.zip 
dungeonpack-1.7.10-1.0.jar 
dynamictanks2-1.1.05.jar 
EnchantingPlus-1.7.10-3.0.2-d.jar 
EnderCore-1.7.10-0.1.0.23_beta.jar 
endermanage-1.1.jar 
endermanage-meddleapi-1.0.jar 
EnhancedPortals_1.7.10-universal-3.0.12.jar 
Et Futurum-1.4.2.jar 
EvilCraft-1.7.10-0.8.9.jar 
ExpandedRedstone 1.7.10 V8a.jar 
extrabiomesxl_1.7.10-3.16.2.jar 
Farseek-1.0.9.jar 
Forge SSP SMP -0 Rotten Flesh HC 1.7.2 1.7.10.jar 
Forge_GuiLibv1.0.7.2.zip 
Galacticraft-Planets-1.7-3.0.12.357.jar 
GalacticraftCore-1.7-3.0.12.357.jar 
gilded-games-util.jar 
GraviSuite-1.7.10-2.0.3.jar 
Guide-API-1.7.10-1.0.1-20.jar 
iChunUtil-4.2.2.jar 
immibis-core-59.1.2.jar 
industrialcraft-2-2.2.774-experimental.jar 
legendgear-1.7.10-2.b.2.1.jar 
liquid-xp-59.0.1.jar 
MicdoodleCore-1.7-3.0.12.357.jar 
MineTweaker3-1.7.10-3.0.10.jar 
MobiusCore-1.2.5_1.7.10.jar 
ModTweaker2-0.9.3.jar 
ModularForcefieldSystem-1.7.10-3.0-ALPHA-7.jar 
NaturalAbsorption-1.7.10-1.2.1.jar 
NEIIntegration-MC1.7.10-1.0.12.jar 
NewDunU V1.8.5.zip 
NotEnoughItems-1.7.10-1.0.5.118-universal.jar 
NotEnoughResources-1.7.10-0.1.0.106.jar 
NOVA-2015-09-09-universal.jar 
OreDictionaryConverter-1.6.1.jar 
rancraftpenguins-1.7.10q.jar 
ReactorCraft 1.7.10 V8f.jar 
Revamp-1.3.1.jar 
Ridiculous World-0.4.jar 
roguelike-1.7.10-1.3.6.3.jar 
RotaryCraft 1.7.10 V8g.jar 
secretroomsmod-1.7.10-4.7.1.413.jar 
Snow Golem 1.7.10-1.6.1.jar 
SolarFlux-1.7.10-0.8b.jar 
StalkerCreepers-1.7.10.zip 
StevesWorkshop-0.5.1.jar 
Streams-0.1.5.jar 
Sync-4.0.0.jar 
TallDoors-1.7.10-0.5.2.jar 
TheErebus-0.3a.jar 
Waila-1.5.10_1.7.10.jar 
WAILA-features-1.7.10-0.0.5.jar 
WailaHarvestability-mc1.7.x-1.1.2.jar 
WAILAPlugins-MC1.7.10-0.1.2-21.jar 
Waterproof 1.0-1.jar 
weaponmod-1.14.3.jar 
WholeTreeAxe-1.1.9-MC1.7.10.jar 
witchery-1.7.10-0.24.1.jar 
WR-CBE-1.7.10-1.4.1.9-universal.jar 
Ztones-1.7.10-2.2.1.jar 
[1.7.10] SimpleCore API v1.1.0.jar

**Comment by jjtParadox** [comment]
Is the bandwidth increase present with just AM2 installed? Helps to know if it's specific to AM2 or if it's a mod interaction issue.

**Comment by doomguy4** [comment]
With only AM2 and animation API Bandwidth it normal.
Here is a link to the private modpack I am using (its 160MB)
http://www.humenet.net/Minecraft/HumeMod1710k.zip

**Comment by jjtParadox** [comment]
Hmm so some combination is causing bandwidth issues... What are you using to measure bandwidth?

**Comment by doomguy4** [comment]
I am using Task Manager
Here is an image of the bandwidth issue http://www.humenet.net/Minecraft/Minecraft73468.png
New is with AM2, Old is without AM2

It fluctuates so much in New because I am hitting the upload bandwidth cap on my connection which causes a Netty exception when connection from outside, when connecting locally it is not an issue.

[22:02:29] [Netty IO #1/ERROR] [FML/]: NetworkDispatcher exception
java.io.IOException: An established connection was aborted by the software in your host machine
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_51]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_51]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_51]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_51]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:249) ~[NioSocketChannel.class:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:680) [AbstractChannel$AbstractUnsafe.class:?]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:266) [AbstractNioChannel$AbstractNioUnsafe.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:488) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEventLoop.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]

**Comment by LemADEC** [comment]
did you check with Opis which packets are using up the bandwidth?
do you have a clean world with other mods blocks/entities nearby when testing?
Can you try without the ItemPhysic, Reika's and Opis mods (including their related libraries)?

**Comment by jjtParadox** [comment]
This has most likely been resolved by #1348, but if it's still an issue we can still work on this.

**Comment by LemADEC** [comment]
yes, you can close this one, if it still happens we'll need fresh logs anyway :)

**Comment by jjtParadox** [comment]
@Kolatra could you close this one?
