### ISSUE TITLE
Picking up Liquid etherium with dispenser results in water Bucket

### ISSUE THREAD

**Issue by Kiara-Liam** [Mithion/ArsMagica2#1326]
Hi,
I tried to automate my obelisks to a certain degree, and tried it via picking up a Liquid Etherium
block with a dispenser and a empty bucket. Unfortunatly, the dispenser only returns Water buckets.

**Comment by EoD** [comment]
The bug is in https://github.com/Mithion/ArsMagica2/blob/master/src/main/java/am2/blocks/liquid/BlockLiquidEssence.java#L21 . 

The code in Bootstrap.java returns a water bucket if the fluid-material is water:
```java
               if (Material.water.equals(material) && l == 0)
                {
                    item = Items.water_bucket;
                }
                else
                {
                    if (!Material.lava.equals(material) || l != 0)
                    {
                        return super.dispenseStack(source, stack);
                    }

                    item = Items.lava_bucket;
                }
```

I will think about it.

**Comment by Kiara-Liam** [comment]
Sad =(
Tested with differnt other mods, same problem there
So with vanilla (hopper, chestcarts, dispenser) no automation possible
with different mods there are a few options(Liquid transposer, IC2 pump)
Since the Obelisk only accepts items, and not liquids directly, the Liquid etherium
has to be packed into a bucket.
May it be possible, to give a obelisk the option to use Liquids directly?
but thx for the reply

**Comment by jawdylawdy** [comment]
Buildcraft floodgates should transfer just fine, if you have it available in the mean time.

**Comment by Kiara-Liam** [comment]
Jup, buildcraft floodgates transfers it, but I wanted to 1) Stick as much as possible to vanilla (exept pipes usw.) and 2) I wanted the liquid in a bucket, since the obelisk only accepts Items, and not liquids directly. I wanted to automate this to power a portal underground, so the daylight obelisk wouldn't work.

**Comment by jawdylawdy** [comment]
Oops. I was thinking about the old-as-dirt thing where the etherium was placed under the rune. Ignore me :P
