### ISSUE TITLE
Arcane compendium shows different entrys when different clients are used

### ISSUE THREAD

**Issue by Kiara-Liam** [Mithion/ArsMagica2#1330]
Hi there,
Today I recognized, that for my two clients (I play sometimes on different computers, but on the same server with the same account) the entries in the compendium differ. At one client, i dont have the pages for the spells (forms, modifiers and so on) and on the other computer I`m missing the multiblock strucktures. Since AM stores player specific files on the server, shouldn't the entrys be the same?

**Comment by Mithion** [comment]
AM2 stores compendium unlock data clientside.
See #1257 

Closing as duplicate, as the fix will be tracked there.
