### ISSUE TITLE
Placing Item Frame near essencecauses instant crash

### ISSUE THREAD

**Issue by DRockLee** [Mithion/ArsMagica2#1334]
I had placed the item frame a block above a large pool of essence, and even before I put a book in the game just crashed
.
https://www.dropbox.com/s/xytqxxp67p7x7hl/fml-client-latest%20-%20Copy.txt?dl=0

I checked the issues for anything similar, and there was one but it looked like the cause of the crash was different, just judging from the comments (I can't access their crash log they submitted).

**Comment by EoD** [comment]
I was not able to reproduce this. How precisely did you place the item frame a block above the large pool? Do you happen to have a screenshot?

**Comment by LemADEC** [comment]
Is it systematic ?

**Comment by jjtParadox** [comment]
According to that crash log, somehow a null snuck its way into the list of frames to be updated by AM2. I can't figure out _how_, but according to that crash log it did. So, I'm making a PR to add a null check to the list of frames to be updated by AM2.
