### ISSUE TITLE
[Version 1.4.0.008] Disarm bug (Client Crash)

### ISSUE THREAD

**Issue by MrAttoAttoAtto** [Mithion/ArsMagica2#1338]
I am playing on a MP modded server with a few mods including Ars. When I try to use my disarm spell on my friend it crashed my client and theirs (we were the only ones on the server*). Note: It works on normal mobs, it only crashes with players. (So it does not happen in SP)

Crash report: 

http://pastebin.com/TvsfTm2H (minecraft launcher)

Sorry for using your time to probably have an easy fix! (I think it is something to do with animations)
Also I saw in your rules for writing a bug report that I needed to include the crash report for "ForgeModLoader-client-0.log" but my file named that (but it has a 2 instead of a 0) was latest updated in 2014 so I'm not sure what to do for that... (sorry)

*EDIT: it crashes everybody on the server :P

**Comment by jawdylawdy** [comment]
I believe this is a known bug, and unless I'm quite mistaken, it's fixed in .009.

**Comment by MrAttoAttoAtto** [comment]
Thank you (since it has been fixed i am closing the issue)
