### ISSUE TITLE
Thaumcraft Error

### ISSUE THREAD

**Issue by MrBretze** [Mithion/ArsMagica2#1340]
log: http://openeye.openmods.info/crashes/90600ed9c3356229e6d6bc01e0ee0d43

When I uninstall AM2, Thaumcraft no longer crash

**Comment by Zsashas** [comment]
Could you post a regular crash report? (Not an openeye one)

**Comment by MrBretze** [comment]
http://paste.pirmax.fr/#80c168.makefile yes this

**Comment by MrBretze** [comment]
It is correct ?

**Comment by Zsashas** [comment]
There appear to be quite a few mods erroring there. Just about every mod that has TC interaction...

Wait, are you using the special Win10 version of Minecraft? Supposedly that doesn't have the same support for modding as the normal version.

**Comment by Shadows-of-Fire** [comment]
Attempt running without MultiMC. I've seen crashes that derive directly from it, and it's mentioned in the stacktrace.

**Comment by jjtParadox** [comment]
@MrBretze any update? If not, this issue should be closed due to inactivity and broken log links.

**Comment by jjtParadox** [comment]
@Kolatra *poke*
