### ISSUE TITLE
Large bandwidth usage increasing with AM2

### ISSUE THREAD

**Issue by LemADEC** [Mithion/ArsMagica2#1341]
Without AM2 installed on the server, my client use ~4kB/s of download bandwidth.
With AM2 installed on the server, my client use ~20kB/s of download bandwidth, in the same place.
In some location I'm capping at ~70kB/s.
It appears, that it increase of ~1kB/s per passive mob surrounding me.
I didn't try with aggressive zombies.
This is with official version am2-1.4.0.008.
It doesn't happen with just AnimationAPI-1.7.10-1.2.4.
According to Opis, there's a lot of entity properties going through the network.
Removing all minimaps didn't help.

Any idea what's going on?
Any configuration I could change to fix that?

**Comment by EoD** [comment]
Probably a duplicate #1325.

**Comment by LemADEC** [comment]
In that other ticket he said there was no issue with just AM2/AnimationAPI.

**Comment by EoD** [comment]
Hmmm, I see. This is very odd.

**Comment by LemADEC** [comment]
According to Opis, there's a shear amount of entities going around:
S20PacketEntityProperties	747,80 packet/s	30,474 KiB/s	1,608 MiB
S14PacketEntity$S15PacketEntityRelMove	691,40 packet/s	5,402 KiB/s	362,609 KiB
