### ISSUE TITLE
[info] AM2 dev not work

### ISSUE THREAD

**Issue by Bogdan-G** [Mithion/ArsMagica2#1346]
Hello. The current version is compiled by date of commit bf5b97ea75e5ba8936b06eef5b9dacca35847c7a. 
Only AM2 and animationapi 1.2.4, forge 1448, mod configs they have been removed before starting.
fml-log: http://paste.ubuntu.com/13496357/
gradle 2.0 log: http://paste.ubuntu.com/13496403/
Who else works it works but me?

**Comment by LemADEC** [comment]
Looks like you're running client code on server side. Probably a start option issue.

**Comment by Bogdan-G** [comment]
LemADEC, but I run on the client))

**Comment by LemADEC** [comment]
I compile in my dev space with Java 7 to debug the mod and have no issue.
How did you compile your version? Did you actually obfuscate the mod?
Did you try with the official version, see if you environment works?

**Comment by Bogdan-G** [comment]
1) dowload source in folder
2) start console msysgit, move in folder
4) use gradle 2.0
3) enter console: gradle jar (or gradle clean jar), wait
4) in dir .\build\libs is a file AM2-1.4.0.009.jar, it is not present anywhere else.

**Comment by Bogdan-G** [comment]
presently problem is solved :D
