### ISSUE TITLE
BUG: Inscription Table Spell Making

### ISSUE THREAD

**Issue by JukeDesigns** [Mithion/ArsMagica2#1353]
Whenever i try making a spell (before the crafting alter) i can add projectile but then nothing else. for example when i am making Projectile Dig when i add dig the dig disappears so i cant actually make the spell. btw other than that its a great mod

**Comment by JukeDesigns** [comment]
Would you like me to make a video showing you the problem? it would only be like 2 seconds long

**Comment by Mithion** [comment]
Let's try a couple basic things first - make sure that components go in the **grey** bar at the bottom.  The **brown** squares are for shape groups (shapes and modifiers only).  There's information on all of this in the compendium under getting started -> Spell Crafting 101.

**Comment by JukeDesigns** [comment]
can you add me on skype so its a little easier to talk? my skype is codude147

**Comment by JukeDesigns** [comment]
Okay that worked my bad xD
