### ISSUE TITLE
1.2.0.022 (1.6.4) Items Randomly Vanishing when leaving The End.

### ISSUE THREAD

**Issue by street1841** [Mithion/ArsMagica2#1354]
I see that this is fixed in the 1.7.10 Version but the pack I am currently playing is on 1.6.4.  Is there any chance of this getting fixed or is the 1.6.4 version abandoned?

Replicate: 
1. Have Soulbound Item / Arcane Spell Book
2. Leave the End VIA Portal
3. Notice Soulbound Items missing, and or Spell Book Empty

PS: Any way to stop batteries and everything else that requires to stop resetting / Emptying?

**Comment by malignantMystic** [comment]
1.6.4 is not being developed.

And no, but I think it's fixed in .009

**Comment by jjtParadox** [comment]
This issue will be closed for the reasons Mystic outlined (Even if we wanted to update 1.6.4 we couldn't, as the code history only goes back to 1.7.10)

@Kolatra *ping*
