### ISSUE TITLE
Shrink doesn't move view, see through world, clicking is misaligned from where you aim

### ISSUE THREAD

**Issue by Aeroxia** [Mithion/ArsMagica2#1357]
When you use shrink, it tries to bring the view down, but immediately goes back up and stays there.  It seems like you're not even shrunk, but you can see it when you use F5.  You won't suffocate in 1x1 spaces, but your head/view is in the block above you and you see through the world.  Your targetting is as if you were shrunk, so it doesn't hit where you're aiming (unless it's like straight down which is the same either way)..

I have this going on with just these:
1.7.10_AM2-1.4.0.008
AnimationAPI-1.7.10-1.2.4
Forge 10.13.4.1558

**Comment by StephenV25** [comment]
Having the exact same issue, happens every time with shrink self
1.7.10_AM2-1.4.0.008
AnimationAPI-1.7.10-1.2.4
using ftb infinity 2.3.5 for reference incase it's a conflict
i'll check back here for a few days incase there is something i can do on my end to help.

**Comment by malignantMystic** [comment]
Known issue, fairly certain that it's fixed in dev(?)

**Comment by Mithion** [comment]
This has been fixed in dev.
