### ISSUE TITLE
Dark Mage Spawn Black listing

### ISSUE THREAD

**Issue by TheDeanoRama** [Mithion/ArsMagica2#1359]
I have a problem in TolkienCraft II with Dark Mages spawning. I know this is an issue with 
Minecraft Comes Alive (MCA) and has been resolved in version 5 but Tolkiencraft is using a 4x version. 

Essentially what happens is a Dark Mage spawns in near the town and takes the server down with a tic  loop.

Ars has a black list for spawns:
S:Appropriation_Mob_Blacklist=

I dug through the crash log and came up with:
S:Appropriation_Mob_Blacklist=am2.entities.EntityDarkMage

Sadly this has zero effect and dark mages still spawn. What is the correct syntax for black listing dark mages in ars?

**Comment by TheIcyOne** [comment]
Appropriation is a spell component that picks up an entity or block and allows you to place it again later, that config setting just prevents mobs being targeted by it.

Are you able to use commands to autokill the mage?

**Comment by jjtParadox** [comment]
Under the `mobs` category of the config, there is a setting for `I:MageSpawnRate`. Try setting that to 0, as that may prevent mages from spawning.

**Comment by Mithion** [comment]
@jjtParadox is correct, spawn weight of 0 disables spawns entirely.

**Comment by jjtParadox** [comment]
@Kolatra assuming this is fixed, this can be closed
