### ISSUE TITLE
Mana Creeper damage scales, no cap

### ISSUE THREAD

**Issue by Zsashas** [Mithion/ArsMagica2#1362]
Situation:

World: Superflat
Armor: Botania Terrasteel, heavily enchanted, and 10 levels total of Thaumcraft Runic Shielding
Mage Level: 99
Hearts: 30 (Terrasteel 10 + Zelda Sword Skills 10 + Vanilla 10)

A single Mana Creeper got a bit too close, and the Mana Vortex killed me in a single shot. Normally, they don't even do any damage to me at all, despite my habit of wandering around in something like Thaumaturge's Robes which offer very little armor. My level is usually rather low at the times I encounter Mana Creepers (lvl 0-10). By the time my mage level is higher, I can often keep all mobs far away from me, so I haven't encountered this before.

There is no reason that it should have one-shot me, unless the damage scales with mage level and has no proper damage cap.

**Comment by EdwinMindcraft** [comment]
There is a cap : 100

**Comment by Zsashas** [comment]
Still, shouldn't having Magic Protection enchantments help at least a bit? Getting OHKO'd in full high-tier stuff doesn't really make much sense, especially from something that doesn't even do a full heart of damage when you first encounter it.

**Comment by Mithion** [comment]
It's intentional. Mana creepers are intended to be a late game threat to mages. The vortex's damage is based on how much mana it can steal. It's also pure physical damage so most armor should help, as would the physical damage resist imbuements. 

There are also tons of spells that can help: fling, flight, shield, haste, leap, blink, mark/recall, etc.

**Comment by Mithion** [comment]
Also if it is still something you just don't want to deal with, you can set their spawn rate lower in the config file for more rarity or to 0 to disable them entirely. That feature requires version. 008+
