### ISSUE TITLE
Inscription Table rendering  crash.

### ISSUE THREAD

**Issue by vagaprime** [Mithion/ArsMagica2#1363]
Just had a crash reported through my tracker in my pack so once again not sure what the players where doing when the game crashed.

https://github.com/MageTech-gate/Release/issues/3

**Comment by jjtParadox** [comment]
This has been fixed in dev. I recommend telling your players to not break AM2 blocks while they are "working", as that's when that bug would come up.

**Comment by Mithion** [comment]
Closing as corrected in dev.
