### ISSUE TITLE
Crash Report Please Help

### ISSUE THREAD

**Issue by skywalker44** [Mithion/ArsMagica2#1365]
http://pastebin.com/S4XWenm6

**Comment by Zsashas** [comment]
What were you trying to Disarm?

**Comment by skywalker44** [comment]
I was trying to disarm my friend to test the spell

**Comment by Zsashas** [comment]
Disarm works well enough on mobs (some, at least) but on players it will cause a crash every time.

**Comment by skywalker44** [comment]
Ok is the mod creator fixing that anytime soon or no?

**Comment by Zsashas** [comment]
It's a known issue.
