### ISSUE TITLE
[License Clarification]Distributing compiled versions in packs

### ISSUE THREAD

**Issue by DrasticDemise** [Mithion/ArsMagica2#1369]
@Mithion I *know* the license specifically states I can distribute any medium of the mod as long as credit is given, but I still feel the need to get explicit permission. I am looking to use the mod in its current state on the Repository for my mod packs, not the latest update in February. Is this acceptable to you, and if so, where would you like me to clarify that it is not an official release?

**Comment by Mithion** [comment]
Yeah mate, that's not a problem.  Just make sure you state that it's a development build.  When you build it, change the version to 1.4.0.009-dev or something like that.

Makes for great testing! :)

**Comment by DrasticDemise** [comment]
Alright, thank you!
