### ISSUE TITLE
Mana batteries don't keep power when broken anymore

### ISSUE THREAD

**Issue by Stalkstalks** [Mithion/ArsMagica2#1374]
Since the days where the 1.6 builds of AM2 had issues with mana networks resetting, I've taken to transferring stored power to mana batteries and then stashing them until I need to draw power from them. They used to drop with a tag regarding how full they are and what sort of essence is stored.

Now when I break them and place them again, they revert to being empty.

(This happens with a dev version I built today)

**Comment by TheIcyOne** [comment]
There appears to be some code built to show a battery's charge in item form. I'll have a look into getting it working again when I get a chance.
