### ISSUE TITLE
Tarmaroot? Using the latest dev version 

### ISSUE THREAD

**Issue by ChilledDayz** [Mithion/ArsMagica2#1375]
I've spent 3 hours searching still can't find any.

**Comment by ChilledDayz** [comment]
I've gone back to the current release and I find tarmaroot with no problems.

**Comment by ChilledDayz** [comment]
Is it possible that the curse launcher could cause a problem with a mod or should I try to change my forge version. I can use the grow spell to get to get tarmaroot it just doesn't seem to spawn naturally.

**Comment by TheIcyOne** [comment]
It's working for me on the current dev version with latest forge, although they are quite rare.

**Comment by ChilledDayz** [comment]
Okay thanks for the response, maybe I'll keep trying and rebuild using the the latest forge.

**Comment by ChilledDayz** [comment]
Can't believe how rare a resource tarma root is, it actually seems worse in the dev version

**Comment by Mithion** [comment]
That's the point of dev versions - you have the code!

Try changing the worldgen, change the config to be more frequent, put log messages if you don't believe it's spawning, etc.

**Comment by ChilledDayz** [comment]
Sorry Mithion, I'm pretty new to doing this sort of thing. I'm not sure how to put log messages but I'll find out on Google how to do this. So I can be of more use to you and the other devs.

**Comment by TheIcyOne** [comment]
They way I personally tested tarma root generation for you was by writing a line to the console with System.out.println with the flower type and coordinates whenever one was generated, in /am2/worldgen/AM2FlowerGen.Java. I would have just put a giant, flashing message on the screen but I haven't touched java for years.

**Comment by TheIcyOne** [comment]
If you do just want a chat message, maybe take a look at how Mithion did the chat messages for Mana Batteries.

**Comment by Mithion** [comment]
Nothing to apologize for - it was just a suggestion :)

@TheIcyOne has the right idea, though I would just stick to console messages instead of chat.  I have a feeling more of those things are being generated than you think.  IIRC correctly, you can use:
```
if (plantBlock == BlocksCommonProxy.tarmaRoot)
    FMLLog.info("message goes here");
```
you need decision logic along with your log message to determine if it's tarma root as the function is generic and is used to generate all the AM2 flowers.

**Comment by Mithion** [comment]
Put that code inside the block:
```
if (par1World.isAirBlock(i1, j1, k1) && (!par1World.provider.hasNoSky || j1 < 255) && this.plantBlock.canGrowOn(par1World, i1, j1, k1)){
				// put the code right here
				par1World.setBlock(i1, j1, k1, this.plantBlock, this.plantBlockMeta, 2);
			}
```

**Comment by ChilledDayz** [comment]
Thanks for your patience with me on this guy's I do really appreciate it :-)

**Comment by ChilledDayz** [comment]
you were right Mithion, more were generating than I thought. I guess I was just very unlucky when caving lol. Thanks for the help.
