### ISSUE TITLE
Spell "projectile lightning damage" does nothing

### ISSUE THREAD

**Issue by ExDomino** [Mithion/ArsMagica2#1376]
A player on my server noticed that the spell "projectile lightning damage" does nothing and does not cost any mana. It is normal? I didn't disabled any spell in the config. Thanks.

**Comment by TheIcyOne** [comment]
Possibly related to https://github.com/Mithion/ArsMagica2/issues/1155

**Comment by ExDomino** [comment]
We don't have Gany's Surface on our server.

**Comment by TheIcyOne** [comment]
What version of AM2 are you using? A modlist may also be handy.

**Comment by jjtParadox** [comment]
I am unable to replicate this bug in the latest Ars Magica.

@ExDomino, we're ( @Kolatra ) probably going to close this, but feel free to re-open it if you're still having the issue and can provide a few more details.
