### ISSUE TITLE
[1.4.0.008] Constant saving of Power Node Entries causing memory leaks

### ISSUE THREAD

**Issue by callous4567** [Mithion/ArsMagica2#1377]
Hello!

I'm new to all this bug reporting, much less Github. Either ways, the issue is that I have had a butt tonne of memory leaks on my world and it seems to be linked to Ars Magica 2 (per some threads I googled, supposedly AM2 causes the leaks to do with Chunk Loading, etcetera).

Every time the AM2 power entries are saved, the world leaks memory seemingly enough.

To reproduce : 
- Set up Chicken Chunks loader with Mana Batteries and AM2 Setup in vicinity 
- Enable chunk loader (Chicken chunks)
- Restart Server

Link to fml-server-latest.log (whole) : 
https://drive.google.com/file/d/0BxDhqkUPGOFCWFQ0cG1xZnV4eHM/view?usp=sharing

Link to fml-server-latest.log (part where lag starts occurring :  
http://pastebin.com/1Wu73Qwu

(I had to put the fml full log as a file on Drive; you can still view it however, but you would need to scroll to the bottom. I'm not sure on which part you want) 

I read through the guide to making a good report, and that's all I have to give :(
Please help if you can :) 

-Sebastian 

Morning Edit : 
I left the server online overnight; it crashed within half an hour apparently.
http://pastebin.com/DW0UbkZC
The memory leaks kept happening and it seems to have ran out of memory.

**Comment by callous4567** [comment]
Thought I found a fix by removing Chicken Chunks; Ars still spams the console after a few minutes followed by memory leaks.

**Comment by callous4567** [comment]
Okay. So it is still happening, even with the config set to FALSE for the saving and instead for just caching it in memory. It still says it saves the Power Node Entries, and it happens more than once every second or two. Causes memory to die and presumably the leaks too (No AM2, no leaks)

**Comment by jjtParadox** [comment]
Hmm... I've heard this can also happen with mods that deal with dimensions, but I know something you can do that will really help out.

[This guide](http://ae-mod.info/Profiling/) was originally written for Applied Energistics CPU profiling, but it can be applied to almost any situation. In our case, profile using the "Memory" button instead of the "CPU" button, and instead of recreating lag spikes, just let the profiler run while the world is leaking.

Upload the final file to dropbox or similar, then link it here.

**Comment by callous4567** [comment]
Hi!

I forgot to close this post. Sorry for the inconvenience;

Even though it kept spamming it (after being disabled) it wasn't the root cause of the lag, the root cause was infact caused by the infamous Chicken Chunks which constantly caused lag when it was paired with AM2.

Thanks for the help; if I ever get another AM2 related issue i'll be sure to follow a better format and put the profiling up first alongside everything else :)

**Comment by jjtParadox** [comment]
No problem, and you actually did a rather good job with this format :smiley:

And no worries about profiling anything and everything, profiling is just for when things cause lag or memory issues. Most of the bugs you'll find are when things crash or don't work as expected, and usually exactly what you posted is enough for us to figure out what's wrong.
