### ISSUE TITLE
[Suggestion] Release Dev version, postpone current milestones

### ISSUE THREAD

**Issue by Zieg777** [Mithion/ArsMagica2#1378]
Hear me out here.

I am constantly seeing people ask on Reddit if AM2 is "as buggy as always". Almost all of the replies are relating to: Power system dropping out, Dispelling on legs crashing, and a couple other problems. All of these are currently fixed (power system is much better at least) in the dev version. Many people are simply not using the mod in their packs because "we're waiting until the next version". I feel that interest is waning simply because to someone that doesn't look at github, nothing has been done to fix their problems for a year. By pushing out a new version with the current dev version, it could spark more interest in the mod, and potentially some new developers could work on it to fix the current milestones.

I know everyone asks "When is the next update?" "Will this ever update?" "Is Mithion dead?" "AM2 is discontinued". The dev version is rather stable, but nobody is going to put it in a pack in a dev state. Even the dev version on here is more stable than what is currently released.

**Comment by bookerthegeek** [comment]
An updated dev version does have a chance of going onto our server. This has been requested by our players but denied due to a lack of updates. Seeing a proper see dual of releases and fixs alleviates server administration fears for sure.

**Comment by Sunconure11** [comment]
This would be a good idea.

**Comment by Mithion** [comment]
k

**Comment by Bogdan-G** [comment]
for example, I went to the practice used dev versions, or versions compiled from source.

**Comment by jjtParadox** [comment]
I just posted a fix for a milestone (#1380) and the other two milestones are either minor or fixed. I will continue working on bugs around here as I have time, and hopefully an update can come soon.

**Comment by Mithion** [comment]
I'll update the milestone and we can see where we are at.

**Comment by bookerthegeek** [comment]
Thank you. People have been clamoring for this to be included.

**Comment by Kolatra** [comment]
Version has been released.
