### ISSUE TITLE
Need Help setting up dev version

### ISSUE THREAD

**Issue by Mandrid001** [Mithion/ArsMagica2#1379]
I've been trying to get the dev version working all day so I can play on my own server again. I accidentally imbued my leggings with the dispel imbuement which now prevents me from getting on it, and i already know that this known issue with the current version has been fixed in the dev version. Could I get some specific guidelines as to how to get it up and running? Also would allow me to help test the mod in the state it is in.

**Comment by TerdyTheTerd** [comment]
Pretty simple actually, on the code page of this github simply download the zip (upper right) then extract the zip wherever you wish to work on it. Once extracted open up the folder "ArsMagica2-master" then open up the folder inside until you get several files, one of which will be called "gradlew.bat". Open a command prompt here by either shift+righ click then open command prompt, or use windows search for command prompt, then type "cd (location of gradlew.bat)". Once you have the command prompt opened in the right location simply type <code>gradlew setupDecompWorkspace</code> this will take a minute, once it says its finished type <code>gradlew build</code> This will place a compiled version in the builds > libs folder. If you have issues with this I went ahead and compiled a version with all the recent commits included, [here](https://www.dropbox.com/s/838eshmh4t4ig6q/AM2-1.4.0.009.jar?dl=1)

**Comment by Mandrid001** [comment]
Terdy you are a savior I tried doing that exact thing earlier today and it said that the process failed. Thank you so much for including the already compiled version with your post, hopefully this can solve my issue. Thank you so much once again! :D

**Comment by Kolatra** [comment]
Closing as you were able to download it successfully. Have fun. :)
