### ISSUE TITLE
[Changelog] Getting a changelog together

### ISSUE THREAD

**Issue by jjtParadox** [Mithion/ArsMagica2#1385]
Hey everyone!

Thought it would be a good idea to get a changelog going since after the open sourceing lots of changes have been made and bugs have been smashed.

I've put together a prototype changelog over on the wiki (https://github.com/Mithion/ArsMagica2/wiki/Changelog) and did my best to add as much as possible on it.

Some of the changes (Like @EoD's tarma root tweaks #1309, @DoomFruit's dig tweaks #1239, and @LemADEC's _huge_ pull request #1348) were a little hard for me to decipher. If anyone has a better sense of what those changes were, then any clarification is much appreciated!

The changelog is currently open to everyone, so if I missed anything, said something wrong, somehow typed something upside down, etc, it can be changed, and contributions are very wecome :smiley: 

Many thanks for helping out!

**Comment by EoD** [comment]
Hey @jjtParadox. Are you on freenode by any chance? I could explain it to you in detail if you are interested.

Basically I fixed and expanded the growth of flowers with the grow component and I change some of the hardcoded requirements into generic (more-like-vanilla) minecraft methods such that mods can use it easier.

**Comment by jjtParadox** [comment]
I'm not on freenode now, but I might consider grabbing an IRC client later and hopping on.

However, I think I got a better understanding of your changes, so thanks!

**Comment by LemADEC** [comment]
Good idea to propose digested change logs!

Here's a few comments on the current wiki page:
1- (typo)
 Fixed: Ars Magica no longer eats bandwith
 -> Fixed: Ars Magica no longer eats bandwidth
2- (missing)
 Added: arcane reconstructor deactivation when out of power
3- (missing)
 Added: missing textures for creative only spell components
4- (reformulation)
 Update: Less CPU load in some cases
 -> Updated: various CPU load improvements
5- (missing)
 Fixed: disarm component no longer crashes client in SMP
6- (missing)
 Fixed: appropriation component no longer crashes dedicated servers
7- (missing)
 Fixed: Optifine, Thaumcraft and DragonAPI are now properly detected
8- (general)
 Since we're saying "Fixed", we should say "Updated" or "Improved" or "Changed" for the others logs.

**Comment by jjtParadox** [comment]
Added! Thanks for the input.

We may want to settle on a formal changelog format later, but for now I think it's looking good :smiley:

**Comment by Mithion** [comment]
I made a slight formatting change.  With proper headers, you don't need to prefix each line with Updated: or Fixed:

**Comment by jjtParadox** [comment]
I like it.

**Comment by Bogdan-G** [comment]
"/AMUICFG command is now purely client-side" - This is where the change has been made? Version 6ddb3835a4df6fbe816251aaced832b687789c02 running on the KCauldron still sends the server configuration.

**Comment by jjtParadox** [comment]
That was fixed with #1264, but I'm not fully understanding the "server configuration" you're talking about.

**Comment by Bogdan-G** [comment]
@jjtParadox the player comes to the server, the server sends the configuration. In the config sent in mod AM2, specify a different location of the interface.

**Comment by jjtParadox** [comment]
AM2 doesn't have code to send configurations to clients. I just tested this with a client having one config and a server having another, and the client's GUI position settings were used. Does KCauldron somehow send mod configs to clients?

**Comment by Bogdan-G** [comment]
@jjtParadox builds: 1492.152,1614.176, all unnofficials.

**Comment by jjtParadox** [comment]
I'm not seeing that happen on my end. Currently running the latest version of KCauldron with just AM2. KCauldron has the default AM2 configs, including default GUI positions. Client has different GUI positions that are saved into the client config. Client joins server, and GUI is just how the client left it.

One condition that might happen is that you're accidentally running KCauldron and AM2 out of the same working directory, thus the server and client are loading the same config file.

If you're still having an issue, screenshots or a screen recording would be very helpful in troubleshooting this.

**Comment by Mithion** [comment]
Only certain config settings are sent to clients.  The GUI settings are not among them.

**Comment by Mithion** [comment]
For specific reference:
`@SubscribeEvent
public void onPlayerLogin(PlayerLoggedInEvent event){
	[...]
	int[] disabledSkills = SkillTreeManager.instance.getDisabledSkillIDs();

	AMDataWriter writer = new AMDataWriter();
	writer.add(AMCore.config.getSkillTreeSecondaryTierCap()).add(disabledSkills);
	writer.add(AMCore.config.getManaCap());
	byte[] data = writer.generate();

	AMNetHandler.INSTANCE.syncLoginData((EntityPlayerMP)event.player, data);
		
	[...]
}`

Only disabled skills and the mana cap are sent down to clients upon login.

**Comment by Bogdan-G** [comment]
@jjtParadox hmm, I double-checked, there is no problem, but it was, I believe that the events which affect it.

**Comment by jjtParadox** [comment]
So someone's making a [texture pack for AM2](https://www.reddit.com/r/feedthebeast/comments/438wdz/a_wip_thaumcraftthemed_texture_pack_for_ars/) to theme it similar to Thaumcraft. Judging by the comments, it would probably be a good idea to do a reddit (and other social media) post of the changelog once we finish the update. @Mithion, would you like the honors?

**Comment by Kolatra** [comment]
If he doesn't want to, I will. :P

**Comment by ChilledDayz** [comment]
I've actually been working on textures for am2, but these look great.

**Comment by jjtParadox** [comment]
Cool! Do you have any screenshots?

**Comment by ChilledDayz** [comment]
Yes I'll post what I've done so far when I'm next on my pc. I've been trying to added some consistency. I've just done the lectern and the inscription table so far but I'm still not happy with the inscription table yet.

**Comment by jjtParadox** [comment]
I also recently reached out to D3miurge over on the minecraft forums to see if he wanted to help out with tweaking and updating some of his AM2 textures, so hopefully that will prove fruitful :smiley:

**Comment by ChilledDayz** [comment]
That's a great idea, hopefully you hear from him. It would be nice to give the textures an overhaul for the next release :-)

**Comment by ChilledDayz** [comment]
I think the reddit page for the mod is really good idea. As it seems a lot of people don't even realise that the mod is still being developed. It would also be a great place to discuss new features. I have a few ideas myself but I feel like posting them here is the wrong place.

**Comment by jjtParadox** [comment]
We're open to suggestions being put into the "issues" section, but I do understand it isn't the best way to organize things (actual bugs tend to take precedence over and crowd out enhancements).

**Comment by jjtParadox** [comment]
(Hence this changelog discussion being in the "issues" section)

**Comment by ChilledDayz** [comment]
Maybe reddit is the best way to go then seems like it really help keep the features and bugs separate.

**Comment by jjtParadox** [comment]
Possibly, but we should probably wait for @Mithion to get back and give his opinion on things before we do anything :stuck_out_tongue_winking_eye:

**Comment by jjtParadox** [comment]
(Also, that AM2 Thaumcraft texture pack was opened for download https://www.reddit.com/r/feedthebeast/comments/43cmyx/update_thaumagica_a_thaumcraftthemed_ars_magica/)

**Comment by ChilledDayz** [comment]
What are your thoughts on the thaumcraft themed texture pack? I mean the textures are great but I don't think AM2 should look like any other mod.

**Comment by jjtParadox** [comment]
I've always liked Thaumcraft's aesthetic style, but other mods pull off a good aesthetic style too. Thaumcraft's textures also look really good next to lots of other blocks, which is hard to pull off. I do agree AM2 should have it's own area to fit into, though.

**Comment by ChilledDayz** [comment]
I'll try to post my screenshots of my textures in a bit.

**Comment by jjtParadox** [comment]
A thing I just thought about is Thaumcraft has it's own unique textures for everything in that mod, as almost none of it is crafted with vanilla blocks. Ars Magica, however, has an entire crafting altar based around (mostly) vanilla blocks. Would it look the best for Ars Magica to take on a look of "Vanilla + Magic", or should it still try to have it's own major aesthetic style?

**Comment by ChilledDayz** [comment]
It's something that I've thought about too. I've been thinking about modelling some assets to revamp the multi block structures like the crafting alter. To try and give it a more unique look.

**Comment by jjtParadox** [comment]
Just to note, D3miurge's [license](http://www.minecraftforum.net/members/D3miurge) for his textures doesn't allow modification (one of the reasons I reached out to him), but not all AM2 textures are his. If you're making entirely new works, you should be good :smiley:

**Comment by ChilledDayz** [comment]
Yeah I downloaded his textures so I know what are his. As I want to avoid any problems with copying

**Comment by Mithion** [comment]
I wouldn't want to see AM2 be assimilated into the visual style of another mod.  I think it would be better to go for a vanilla style with a magical flair.  Since other mods textures are usually designed with vanilla in mind, a style along those lines could go very well with just about anything.

So, I'll put a link to the TC-like textures on the OP for sure, but I won't be making them default.

**Comment by Mithion** [comment]
Also, I don't have a problem with doing a reddit for the changelog.  I plan to post it on curse and MCF too.

I don't even have a reddit account though (been on that site only a handful of times).  If someone else wants to take that up, that's fine - I just ask they do their best to ensure accuracy! :)

**Comment by jjtParadox** [comment]
Probably just a copy+paste of the changelog would suit for the reddit post, as well as something describing what's been happening over here and something asking for ideas and possibly bug reports.

**Comment by jjtParadox** [comment]
As for the textures, I completely agree with Mithion, but it's still cool to see others working on AM2 stuff :smiley:

**Comment by ChilledDayz** [comment]
Here's my screenshot of the lectern and WIP of the inscription table. This is for my personal AM2 pack as I don't think there that great.
![img_20160130_184104](https://cloud.githubusercontent.com/assets/15843482/12697723/ed13cb8a-c781-11e5-9a80-46208e52881d.JPG)

**Comment by TheIcyOne** [comment]
I really like the Lectern, although the book on top does like a little out of place.

**Comment by ChilledDayz** [comment]
Not what I could as I don't think the book is an AM2 texture. I think it uses the enchanting table book from minecraft although I could be wrong.

**Comment by Mithion** [comment]
You are correct.

**Comment by ChilledDayz** [comment]
Yeah I thought it was.

**Comment by Kolatra** [comment]
If somebody wants to provide me with something to post, I can post it ASAP.

**Comment by jjtParadox** [comment]
I think the changelog's all good, but we should wait for the actual update to happen before you post it. Your post should probably have the changelog (and a link to it), a short description of what's been going on over here for the past year (possibly crediting some of the contributors), a link to the update, and possibly ask for bugs and suggestions to be posted in that reddit thread (we don't want to flood the issues page just yet).

It's been a year since the last update, so likely a loud minority (read: two or three angry people) will be angry about the delay, but a gentle reminder that we've been updating this in our free time and asking for nothing in return would probably be appropriate. The FTB community will take care of the rest.

We may also want to mention where we hope to go with things (adding features, balancing things, making things better in general), and that currently we have no plans for 1.8 as AM2 is a HUGE mod and we're still smashing bugs on our end.

**Comment by Kolatra** [comment]
I know someone that was planning on porting the mod actually.

But yeah I'll wait for the update but I'll write out the post and all of that because it'll be lengthy. I will be crediting the contributors, and I'll ask for suggestions and all of that to be in the thread.

**Comment by jjtParadox** [comment]
I saw the ProjectE dev mention he'd be up for porting the mod to 1.8, and since this mod is open source that is certainly very possible.

**Comment by ChilledDayz** [comment]
It seems that some of the bigger mods are now porting the 1.8, but with 1.9 around the corner is it really worth porting to 1.8?  What are your thoughts on this?

**Comment by LemADEC** [comment]
There's no Forge for a 1.9 that isn't released, get back on earth :)

**Comment by Kolatra** [comment]
1.9 is not even out yet, but we won't be seeing a moddable 1.9 for quite a while longer, and even longer for packs.

**Comment by ChilledDayz** [comment]
here's an update on my texture pack for AM2 added changes to MC as well.
![2016-02-01_16 37 22](https://cloud.githubusercontent.com/assets/15843482/12724209/cd14fa00-c904-11e5-851b-c0236b589e63.png)
![2016-02-01_16 37 55](https://cloud.githubusercontent.com/assets/15843482/12724210/cd1ad63c-c904-11e5-8762-df33ef40869b.png)

**Comment by Mithion** [comment]
Looks good!

I think a port to 1.8 should happen for 2 reasons: 
1.) For those that play 1.8, it would make a version available
2.) 1.8 is a huge change and it would be good to get a stable baseline before moving to 1.9

**Comment by ChilledDayz** [comment]
That makes sense as blocks and models change. Json files and metadata were taken out. How bad would porting am2 be?

**Comment by Mithion** [comment]
Nightmarish would be an understatement.

**Comment by ChilledDayz** [comment]
Oh that explains why a lot of mod authors have avoided it for so long

**Comment by jjtParadox** [comment]
I recall hearing that Forge recently changed the way .json block models work so that modders didn't need to rewrite quite as much (so it's more similar to 1.7.10). As for the issue with the lectern book texture, should AM2 check if a custom AM2 lectern book texture is available then fall back to the vanilla texture?

**Comment by jjtParadox** [comment]
I found the [thread](https://www.reddit.com/r/feedthebeast/comments/42w60t/18x_megathread/) where I heard about Forge's change. I think now we don't need to use .json files at all!

Now it's a question of what we need to change to get AM2 working on 1.8. Time to google some porting tutorials...

**Comment by williewillus** [comment]
I've started a little bit at https://github.com/williewillus/ArsMagica2

Not sure if I can sustain it though given school, lots of things need redoing (especially all the ASM), but having done several ports now I have a pretty comfortable feel for the json system (which we will need to use)

**Comment by jjtParadox** [comment]
Oh wow that's awesome!

Yeah most of us have a life too (I disappeared for a few months and just recently showed up again), so we completely understand :smiley: 

Do you possibly have a list of things that need updating, so we can try and help out?

**Comment by williewillus** [comment]
Pretty much anything is fair game (though the rendering I kinda wanna figure out because I find it fun :P), try to keep changes focused on just one area of the code instead of everywhere

**Comment by jjtParadox** [comment]
Just make sure we can understand whatever wizardry the rendering is :stuck_out_tongue_winking_eye:

Also @Mithion, what else needs to be done before *.009 can be released?

**Comment by Mithion** [comment]
1.) https://github.com/Mithion/ArsMagica2/issues/1244
I need to finish this.

2.) We should go through the issues list and close out any that are resolved, as well as tag them properly. @Kolatra will be able to assist with the actual closing and tagging in addition to myself.

**Comment by jjtParadox** [comment]
Great! I can do some testing for issues that don't appear to have tests done yet.

**Comment by Webber88** [comment]
may i recomend waiting until summer vacation so that you guys are more free to work on transitioning to 1.8.0?

**Comment by jjtParadox** [comment]
There should be no problem with putting in work now, it just might take a pause when things get busy.

**Comment by jjtParadox** [comment]
#1244 is done!

@Kolatra let us know when you post that reddit post, and you can probably close this discussion once you do (but tag it since there's a lot of good stuff in here) :smiley:

**Comment by Kolatra** [comment]
Post is on Reddit: https://www.reddit.com/r/feedthebeast/comments/44tvix/1710_new_ars_magica_2_update/
