### ISSUE TITLE
Server vs. Client side configs.

### ISSUE THREAD

**Issue by bookerthegeek** [Mithion/ArsMagica2#1388]
So here is the situation. There use to be the situation where client side configs would not respect server side configs. So.... If I disabled a spell on the server, clients that modified their configs would be able to change the config and still have access to the spell on the server. I would love to test if this is still an issue, and will test extensively as soon as we get a dev version released. :)

**Comment by jjtParadox** [comment]
I just tested, and I can confirm that configs are synced.

Just to note, all spell parts are always available to players in creative, even when a part is disabled.

**Comment by ThatOneTraitor** [comment]
The only configs that dont change (to my knowledge) are the witchwood leaves particle disabling and staged compendiums, except for that its the server-side configs that decide the others

**Comment by jjtParadox** [comment]
To quote Mithion,

> Only disabled skills and the mana cap are sent down to clients upon login.

**Comment by bookerthegeek** [comment]
Thank you for testing this. One step closers to adding this. :)

Now all we need is a jar file......

**Comment by TheIcyOne** [comment]
Is a manual build out of the question @bookerthegeek ?

**Comment by bookerthegeek** [comment]
... I'm stupid and don't know how to easily make/compile it. :)


Actually I've never needed to run a mod newer then the published dev/release builds. And the only reason time frame is important here is we are going to have to reset our current server asap due to issues. (Backups exist, but corruption extends into thise)

As this mod has worldgen, it is something we need before we generate the world.

**Comment by Mithion** [comment]
This mod supports retroactive worldgen.  You can add the worldgen for it in at any time.  Simply set the config flag B:EnableRetrogen=true to enable it.  It will disable itself automatically after the first run.

**Comment by bookerthegeek** [comment]
:) Nice to know. I don't personally have much mage experience, but many of our players are. They also love to break mods so.... expect bug reports. Muahahaha 

Still leaves the issue of my ignorance, but I'll get Google to help me out tonight.

**Comment by TheIcyOne** [comment]
Haven't compiled a dev build for a while, but the command "gradlew.bat build", run from the command line from the folder downloaded from the code page should place a jar file in the builds folder, which I believe is then usable like any other mod.

**Comment by bookerthegeek** [comment]
.... pretend I've never actually every compiled a jar file.....

**Comment by TheIcyOne** [comment]
No access to my PC at the moment, so as close to correct as I can remember:
1. Download the .zip of the mod from githhub https://github.com/Mithion/ArsMagica2/archive/master.zip
2. Extract this file wherever you want it.
3.  The extracted folder should contain a file called gradlew.bat. If it doesn't, it's probably in a subfolder.
4. Navigate to the folder with gradlew.bat inside using the command line.
5. Run the command "gradlew.bat build"
6. This should create a folder called "builds", which will contain the mod .jar. This can then be placed in the /mods/ folder of your instance.

Part of me feels like I missed a stage. If this doesn't work, I'll run through it in reality tomorrow and update.

**Comment by bookerthegeek** [comment]
Yep, you forgot something....

` Cannot find System Java Compiler. Ensure that you have installed a JDK (not just a JRE) and configured your JAVA_HOME system variable to point to the according directory.`

Now time to go download JDK... only 187MB. Only a 20min download. :((

**Comment by bookerthegeek** [comment]
@TheIcyOne 
Thank you very much... Now to go test.

**Comment by TheIcyOne** [comment]
My apologies, I forgot I had a JDK installed :3

**Comment by johnfg12** [comment]
@bookerthegeek so if all gos well we can be expecting this soon ? also im going to play around with the mod too :P i love this mod

**Comment by johnfg12** [comment]
also really off topic wow gradle makes it quicker to compile :D

**Comment by bookerthegeek** [comment]
Soon @johnfg12. But no more here as I'm sure we are annoying the good people.
