### ISSUE TITLE
[Recommendation] Use GitHub's release feature for upcoming releases

### ISSUE THREAD

**Issue by jjtParadox** [Mithion/ArsMagica2#1390]
GitHub has a handy [releases](https://help.github.com/articles/creating-releases/) feature that can host binary files for users to download. Currently, AM2 uses dropbox and a mirror to host files. Dropbox has bandwidth limitations, and right now I can't get the mirror to load.

Because of this, I recommend that AM2 also use GitHub for the next release (especially since issue #1244 is the last issue in the *.009 milestone).

**Comment by Mithion** [comment]
I'm not all that worried about dropbox - I have the 250GB per day limit.

**Comment by jjtParadox** [comment]
Oh didn't know that was a thing :stuck_out_tongue_winking_eye:

It might still be helpful to tag a release so that the commit the release is built against is easily identifiable.

**Comment by jjtParadox** [comment]
Closing as *.009 has been released
