### ISSUE TITLE
[Question] What is going to be added/fixed before .009

### ISSUE THREAD

**Issue by ThatOneTraitor** [Mithion/ArsMagica2#1392]
I use a custom modpack and i've asked the server owners if they could use the dev version. Before the add the new version they want to know if there are any major bugs, and what else is going to be added before its a full release. (I couldn't find a list of things going to be updated so sorry if there is one and im just blind)

**Comment by Zieg777** [comment]
https://github.com/Mithion/ArsMagica2/wiki/Changelog

It's about 5 rows below this post on the issues page

**Comment by ThatOneTraitor** [comment]
Does anyone know what is stopping it from being a full release?

**Comment by malignantMystic** [comment]
Because it's still being developed?

**Comment by jjtParadox** [comment]
Mithion just needs to fix one last thing on his end before we fully release this version, and he's working on it now.

**Comment by ThatOneTraitor** [comment]
Just out of curiosity, what is it that Mithion is updating? sorry if im asking too much, but the server owners that host the pack i play want to be careful when it comes to AM2 because of when all the spellbooks got wiped and they had to undo the update, after that they just want to be careful

**Comment by jjtParadox** [comment]
It's similar to an update checker and has almost no effect on gameplay or even how data is stored.

You can even do some testing on your own if you like, that'll help the server owners make sure nothing goes wrong.

**Comment by ThatOneTraitor** [comment]
Ok, thanks a ton, ill just Link this to them ;) Thanks a ton!
