### ISSUE TITLE
Moo Moo farm gateway not working

### ISSUE THREAD

**Issue by ThatOneTraitor** [Mithion/ArsMagica2#1396]
I've tried to Use a gateway to go to the moo moo farm, i used the evil looking book on it, yet when it opens its a blue portal and when i try to go through it i just get sent back to the next gateway in the network (the same one because i'm the only one with a gateway on the server) Using dev Version 0.009

**Comment by jjtParadox** [comment]
The moo moo farm was removed a version or two ago. However, there is still a way to get hell cows as a summon. Hint: you need to do something similar to unlocking silver spell parts.

**Comment by ThatOneTraitor** [comment]
...... *Sigh* time to spend forever trying to figure out another secret ;-;

**Comment by jjtParadox** [comment]
I believe Mithion wanted to reimplement things at one point, but we can certainly address things on later updates.

If you can read code at all, you can also find how to summon the hell cow ;)

**Comment by ThatOneTraitor** [comment]
well. time to find out how to read code.

**Comment by jjtParadox** [comment]
I'll help you out a little: a hell cow is strong and mighty, but it doesn't belong in the world. Any summoned hell cow is simply a distortion, a shadow from another realm.

**Comment by ThatOneTraitor** [comment]
yeah, i tried astral distortion, didnt work thouhg

**Comment by TheIcyOne** [comment]
I personally prefer "Rend the stars to summon a deadly myth."
You are on the right lines with astral distortion, however.

**Comment by ThatOneTraitor** [comment]
From my VERY basic code reading, i think its pretty much saying

"If astral distortion with damage modifiers is cast, summon hellcow"
Thats all i can gather from the code

`	}else if (clazz == EntityCow.class){
			if (SpellUtils.instance.modifierIsPresent(SpellModifiers.DAMAGE, stack, 0) && SpellUtils.instance.componentIsPresent(stack, AstralDistortion.class, 0)){
				return EntityHellCow.class;
			}`

**Comment by TheIcyOne** [comment]
Which file was that code located in?

**Comment by ThatOneTraitor** [comment]
Summon.java

**Comment by ThatOneTraitor** [comment]
so.... what am i missing?

**Comment by jjtParadox** [comment]
You need to use a cow phylactery when you craft the summon spell.

**Comment by ThatOneTraitor** [comment]
oh, ty

**Comment by ThatOneTraitor** [comment]
FINALLY Got it. just didnt add the damage modifier
