### ISSUE TITLE
Question Regarding Gateways and Rituals

### ISSUE THREAD

**Issue by malignantMystic** [Mithion/ArsMagica2#1399]
A while back, when ArcanaCraft was still a thing, I recall having some issues with one of the rituals. Specifically the one that allowed you to teleport to a gateway using its rune code. The problems I had with it are as follows:
- You needed to drop the runes in a specific order (which makes sense, but is not a terribly elegant way of doing it)
- If the runes stacked, the ritual would fail

Now I'm not entirely sure whether the rituals have changed or been removed or whatever else, but I do have to question what could be done specifically with this issue.

Personally, I think it might be a good idea to have it use the Keystone itself. Rather than dropping individual runes, you would drop your Keystone (with the code inside), and the ritual would consume the runes and leave you a blank Keystone. Not sure how possible that is, but it's sort of the best solution I could think of.

**Comment by Mithion** [comment]
That or make the rituals so that no runes are duplicated, meaning they can't stack.
The order part never really bothered me - rituals are precise and time consuming by nature :)

**Comment by jjtParadox** [comment]
@malignantMystic if you recommend more changes to rituals, feel free to open an issue with any suggestions you have. Thanks!
