### ISSUE TITLE
1.4.0.009, Affinity 75% nightvision bug?

### ISSUE THREAD

**Issue by Alpharious** [Mithion/ArsMagica2#1413]
After I downloaded that version my nightvision does not trigger like before with that I mean that I does not trigger at all. Should trigger when I have reached 75%. I am at 100% and nightvision does not trigger anywhere. No affinty works for me, no buffs, no nothing, it's completely broken.

**Comment by TheIcyOne** [comment]
You have the ender affinity, yes?

**Comment by Alpharious** [comment]
Yes I have the ender affinity at 100%.

**Comment by Mithion** [comment]
Ender affinity's night vision doesn't trigger automatically anymore.  Once above the threshold, you can trigger it manually at any time by pressing the 'X' key.

**Comment by Alpharious** [comment]
Does not work. Pressing X makes me "jump" half a block straight up in the air and these purple stuff appears http://i.imgur.com/sCkCN4w.png 

I dont have less HP in water or in daylight. Nightvision does not work, nothing from the affinity works. There is something broken in the update.

**Comment by Mithion** [comment]
It is in fact working - you're just activating the other ability that ender affinity gives.  
Ender affinity got a bit of a buff.

If you're falling, pressing X will teleport you back to the last place you were on the ground and negate all fall damage.  Useful if you accidentally fall down a ravine (or get pushed).

I checked the code, and sneak+X should toggle the night vision for you.  My apologies for not being clearer before.

**Comment by Alpharious** [comment]
Have you removed losing max health from water weakness and sunlight weakness? Because I dont lose max health anymore.

**Comment by Alpharious** [comment]
Oh and thanks for the help! You had no information posted about chaning how to activate the affinity abilites or did I miss that somewhere?

**Comment by Mithion** [comment]
I didn't remove those effects...they should still be active, but with the way they work, your health should still *look* full, just the underlying numbers of max HP will be lowered.  If you have a way to visualize the numeric values, I would check that.  Otherwise, this issue should be re-opened.

Not sure where the affinity changes are documented, it's something that should be checked though.  I'll add them to the changelog on the wiki for sure though.
