### ISSUE TITLE
Spell Creation issue 1.4.0.009

### ISSUE THREAD

**Issue by Jeffrey2911** [Mithion/ArsMagica2#1415]
after creating the buff power unlock spell in the inscription table and casting it. the spell doesnt give the normal buffs and instead gives legendary mana restoration, charm, chrono anchor,astral distortion, and taint poison debuffs instead.

**Comment by jjtParadox** [comment]
What are the "normal buffs"? What exactly are the spell recipes you're using?

**Comment by Jeffrey2911** [comment]
self - haste,slowfall,swift swim, gravity well, and leap

**Comment by ThatOneTraitor** [comment]
may be an id conflict between the potion effects?? just a guess btw(if anyone has seen my posts you know that im like a child trying to build a rocket when it comes to reading code)

**Comment by Zieg777** [comment]
Sounds a lot like mismatched IDs. Are you on a server? If so, make sure your potion IDs match. If single player, check the AM2 config to make sure there aren't duplicate IDs

**Comment by Jeffrey2911** [comment]
ok i now have made a self chrono anchor shield spell. The spell itself seems to work as intended but instead of it having the name for chrono anchor and shield i get unnatural hunger and flight

**Comment by jjtParadox** [comment]
Yeah that almost certainly is mismatched IDs. Are you playing on a server or in singleplayer?

**Comment by Jeffrey2911** [comment]
i was playing on a server thanks alot i managed to solved the issue.

**Comment by jjtParadox** [comment]
Oh great! Then if you don't mind, could you close this issue? Helps clean things up :smiley:
