### ISSUE TITLE
Factorization/AM2 conflict?

### ISSUE THREAD

**Issue by rob5251** [Mithion/ArsMagica2#1419]
Not really sure if this has to be fixed on Ars Magica's end or Factorization at this point, but I figured I'd at least report it here.

I thought at first this was purely an issue with Factorization, but after some searching I found people were saying it could be a conflict between the two mods.

This was a crash log from it occurring to someone on my server:
crash-report: http://pastebin.com/vLFsJLmr
fml-client: http://pastebin.com/HuPGPKtV

This is a crash log from someone else using just Factorization and AM2 together to reproduce the same crash.
crash-report: http://pastebin.com/QDg4JFJb

Like I said not really sure what end it has to be fixed on, but I wanted to make you at least aware as I didn't see the issue reported on the github.
Sorry for the bother if it's not an issue to be fixed on your end.

**Comment by jjtParadox** [comment]
Found [this](https://www.reddit.com/r/feedthebeast/comments/44fcte/ars_magica_spell_effects_crash/) reddit post with the same issue. Comments are mostly blaming Optifine or mismatched potion IDs. Can you double check that Optifine or incorrect potion IDs are not causing the issue?

**Comment by rob5251** [comment]
I'm not using Optifine, but I'll have to double check for potion ID conflicts.
The issue occurred by simply exploring the map for the guy on my server though, he wasn't using anything at the time.

**Comment by jjtParadox** [comment]
Well it is possible the Charm spell has something to do with it, it's just a little difficult to see right now.

**Comment by rob5251** [comment]
I would have figured that setting the sortRenderes to false in the factorization config would stop it from crashing, but it was still the same error.

This issue did not occur for players on my server the first few times they summoned the water guardian, then it decided to start happening. When I tested it locally on my own computer I was able to get the crash to happen as soon as I spawned one (using a spawn egg). Reconnecting to the server does not fix the issue, removing factorization was the only way I could fix it at this time.

**Comment by jjtParadox** [comment]
I'm poking around with factorization, and I'm getting very confused... According to the code, that config line should have turned off the render sorter all together. It's client side only and requires a restart to take effect, but that's what it does.

**Comment by rob5251** [comment]
I honestly have no idea, when I tested it I set the option to false on the server and the client.

**Comment by jjtParadox** [comment]
Just talked with neptunepink over at #factorization, and he just did a [bugfix release](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1284592-factorization-0-8-107) fixing this issue :smiley:

**Comment by rob5251** [comment]
Glad you could get it worked out :+1: 
I ended up removing factorization from my pack regardless, neat mod, but I had other mods in my pack that duplicated most functionality so it was kind of pointless and no one was using it on my server.
At least this will fix the issue for others who wish to use these two mods together, so that's good news. :)
