### ISSUE TITLE
[Suggestion] etherium slimes 

### ISSUE THREAD

**Issue by ChilledDayz** [Mithion/ArsMagica2#1426]
Just thought I'd post this idea here to see what you think. If you can make it that large etherium lakes have a chance to spawn etherium slimes. The slimes that they drop could be crafted with vintium dust to make something to burnt in the obelisk, maybe something between vintium dust and liquid etherium for the amount of power you get. You could also replace the normal slime balls in other Am2 recipes.

**Comment by ThatOneTraitor** [comment]
seems very... blue slime copy-like.......

**Comment by malignantMystic** [comment]
If you think Tinkers' Construct is the first mod (or game, or literally any other form of fiction) to have slime enemies emerging from X liquid, you are very much mistaken.

**Comment by ChilledDayz** [comment]
Saying that though vintium is pretty much a free source of power. I've got stacks of the stuff just from cooking up cobblestone to build with. I do get what you're saying though. :-)
