### ISSUE TITLE
stability

### ISSUE THREAD

**Issue by johnfg12** [Mithion/ArsMagica2#1438]
im currently working on a pack for a large sever im just checking is this stabilile enough to put on a sever with 40+ people also is there any big bugs in the current build on the fourms that i should be aware of?

**Comment by jjtParadox** [comment]
The *.009 release fixed [a lot](https://github.com/Mithion/ArsMagica2/wiki/Changelog) of bugs, but the [issues page](https://github.com/Mithion/ArsMagica2/issues) should be a good list of bugs in the current ArsMagica version, just make sure to check the discussion of each issue to see if there are any developments with that issue.

**Comment by johnfg12** [comment]
i was just checking to make sure there isnt any huge issues i should know thanks :D
