### ISSUE TITLE
Arcane Compendium texture not replaced by texturepack

### ISSUE THREAD

**Issue by BlackSoldierB** [Mithion/ArsMagica2#1439]
I am using the PureDBCraft texturepack.
After updating to 1.4.0.009 the texture of the arcane compendium is no longer replaced.

Reverting to 1.4.0.008 fixes this issue.

**Comment by jjtParadox** [comment]
The arcane compendium texture name was probably changed, just rename the texture in the texturepack to arcanecompendium.png (caps matters).

If that fails, let us know.

**Comment by BlackSoldierB** [comment]
Yeah, changing the caps fixed it.
