### ISSUE TITLE
witchwood biome/tree spawn rate

### ISSUE THREAD

**Issue by johnfg12** [Mithion/ArsMagica2#1443]
would it be possible to have the spawn rate for both witchwood biome and witchwood trees configurable in AM2 config this would help with balence for other mod and sever usage

thanks 
johnfg12

**Comment by jjtParadox** [comment]
The witchwood forests already have a rarity set in the config setting `I:Witchwood_Forest_Biome_Rarity`, but the individual trees do not currently have a rarity setting.

**Comment by johnfg12** [comment]
is there any chance we could get one ;)
