### ISSUE TITLE
Summoning Fire Guardian

### ISSUE THREAD

**Issue by jwkim930** [Mithion/ArsMagica2#1445]
I cannot summon fire guardian. I threw about 6 water essenses but it it not summoned.

**Comment by TheIcyOne** [comment]
Would you be able to post an image of the setup you are using to summon the guardian?

There should be a circle of gold inlays with coal blocks underneath, in the nether.

**Comment by jwkim930** [comment]
![2016-03-04_16 33 16](https://cloud.githubusercontent.com/assets/17604947/13542246/0b7a9e18-e227-11e5-9ece-fa95480a4ef4.png)
put nothing
![2016-03-04_16 33 20](https://cloud.githubusercontent.com/assets/17604947/13542247/0b7dcce6-e227-11e5-8f78-37ec05f48d9a.png)
put 1 water essence
![2016-03-04_16 33 22](https://cloud.githubusercontent.com/assets/17604947/13542249/0b833b90-e227-11e5-8d7a-4bfea53e7114.png)
put 2 water essence
![2016-03-04_16 33 23](https://cloud.githubusercontent.com/assets/17604947/13542248/0b828272-e227-11e5-88dc-3d3825f6f54a.png)
put 3 water essence
![2016-03-04_16 33 25](https://cloud.githubusercontent.com/assets/17604947/13542250/0b8f6140-e227-11e5-99e6-68d631e430de.png)
put 4 water essence
![2016-03-04_16 33 26](https://cloud.githubusercontent.com/assets/17604947/13542251/0b91dace-e227-11e5-9b39-5a4848ec9869.png)
put 5 water essence
![2016-03-04_16 33 28](https://cloud.githubusercontent.com/assets/17604947/13542252/0b94318e-e227-11e5-84ce-072f9177b4ac.png)
put 6 water essence
![2016-03-04_16 33 30](https://cloud.githubusercontent.com/assets/17604947/13542253/0b974e28-e227-11e5-9f20-5ca454ed2226.png)
put 7 water essence
![2016-03-04_16 33 36](https://cloud.githubusercontent.com/assets/17604947/13542254/0ba10aee-e227-11e5-9180-114b1b021418.png)
put 8 essence

I heard I need to put 2~4 water essences but I cannot summon it with 8 essences.

**Comment by TheIcyOne** [comment]
That lava block needs to be a coal block, I believe.

**Comment by jwkim930** [comment]
u mean obsidian block?

**Comment by TheIcyOne** [comment]
Wait, what version of AM2 are you using?

I assumed it was the latest build.

**Comment by jwkim930** [comment]
![2016-03-04_17 15 10](https://cloud.githubusercontent.com/assets/17604947/13542978/a02a504e-e22c-11e5-824c-6848936a197c.png)
it's 1.4.0.009

**Comment by TheIcyOne** [comment]
In that case, you do need the coal block, which is made from 9 coal in a crafting grid.

**Comment by jwkim930** [comment]
I used coal block that time. Obsidian looks like
![2016-03-04_17 19 05](https://cloud.githubusercontent.com/assets/17604947/13543044/355576a8-e22d-11e5-8ac8-1b6142e170ec.png)
this

**Comment by TheIcyOne** [comment]
No, the coal block is used in place of the lava now.

**Comment by jwkim930** [comment]
oh, it works now. Thanks

**Comment by TheIcyOne** [comment]
No problem :)

**Comment by jjtParadox** [comment]
@Kolatra *ping*
