### ISSUE TITLE
UBCOreifier/Ars Magica2 Issue

### ISSUE THREAD

**Issue by O13SC3N3** [Mithion/ArsMagica2#1461]
Minecraft 1.7.10
Forge: 1614
Java 8 (77)

Integrating Ars Magica2 in a decently stable modpack utilizing UBC and UBC Ore Register

The Following is Posted to the Console Logs on Startup, Haven't dived full into a created world yet.

http://pastebin.com/raw/mHw0Gbhu

Posted at both. @Mithion and @Zeno410

**Comment by Zsashas** [comment]
Yeah, that's definitely an Underground Biomes issue.

**Comment by jjtParadox** [comment]
@Kolatra *ping*
