### ISSUE TITLE
Spell book next[X] and switch groups[C](switch casting mode?) key's not working  (V. 1.4.0.009)

### ISSUE THREAD

**Issue by dudeawsomeness1** [Mithion/ArsMagica2#1464]
I tried to bind these keys to my mouse but it wasn't working right, so I switched them back to normal but when I press X or C they don't work. P.S. This is in a modpack if that matters.

**Comment by jjtParadox** [comment]
Can you recreate the bug with just AM2 installed? Really helps narrow down the cause of the issue.

**Comment by Webber88** [comment]
Are the keys conflicting with anything?

**Comment by dudeawsomeness1** [comment]
They were but I changed one and it still wouldn't work

**Comment by dudeawsomeness1** [comment]
I played with only AM2 and I found out that it wouldn't switch because put them in the same group. But I couldn't do the next spell thing until I changed it to not conflict.
I went to the modpack switched some keys, fixed my spell, and it seems to work now. Once I get back from a trip i'll try to bind it to my mouse again see what happens.

**Comment by jjtParadox** [comment]
@dudeawsomeness1 any update for this issue?

**Comment by dudeawsomeness1** [comment]
@jjtParadox I don't think I've tried it yet but the normal keys work and the mouse should work fine, I'll get on tomorrow and use the mouse.

**Comment by ThatOneTraitor** [comment]
The mouse works, The problem was the X and C keys, the problem is resolved.
