### ISSUE TITLE
"Player Rune Code"

### ISSUE THREAD

**Issue by ThatOneTraitor** [Mithion/ArsMagica2#1466]
Ive heard about these from the arcane compendium. im not sure how to get a players rune code, it says use true sight but i dont know what to do, cast it on them, on me and look at them etc

**Comment by malignantMystic** [comment]
A player has to divulge their rune code to you. To see your own, give yourself True Sight, press F5, and look at the code above your head.

**Comment by jjtParadox** [comment]
The code is also visible in the inventory screen above the character.

**Comment by malignantMystic** [comment]
With True Sight active, I assume? Because if not, clearly I'm blind.

**Comment by jjtParadox** [comment]
Yes, that should be how it works (true sight + f5 or inventory screen).

**Comment by jjtParadox** [comment]
Since this discussion is probably finished, it can probably be closed (@Kolatra).
