### ISSUE TITLE
Add a config option to merely disable Witchwood Forest generátion

### ISSUE THREAD

**Issue by Robijnvogel** [Mithion/ArsMagica2#1468]
[not very high priority]
The current config setting:
```
    # Disable this if you prefer the witchwood forest to not generate
    B:Enable_Witchwood_Forests=false
```
seems to prevent the biome from registering at all, not only disabling Overworld generation, but also making it impossible to use the biome in other-than-default biome generators.

I'd suggest having a boolean complete disable **and** a biome generation weight integer (like Thaumcraft has) instead.

**Comment by TheIcyOne** [comment]
`# Sets how rare witchwood forests are.  Lower is more rare.
    I:Witchwood_Forest_Biome_Rarity=6`

Set that to 0, it will not be added to worldgen.

**Comment by Robijnvogel** [comment]
... did I just completely miss that?
