### ISSUE TITLE
Crash while fighting Air Guardian

### ISSUE THREAD

**Issue by adamk33n3r** [Mithion/ArsMagica2#1472]
Here is the crash report: http://pastebin.com/pmP3mM6B

`NoSuchMethodError: net.minecraft.block.Block.func_149637_q()`

**Comment by EdwinMindcraft** [comment]
You should say that this issue was on a server...
Anyway it must be a server side missing method.
I'd say isBlockNormalCube.

**Comment by adamk33n3r** [comment]
Doesn't even single player have a server too? Didn't think that would have mattered. Although if you could figure out it was a on a server then maybe I didn't need to ;)

So what does that mean to me? Is the version of Forge that I'm using just not compatible?

**Comment by EdwinMindcraft** [comment]
Well the server jar doesn't contains everything the client jar does, you could try reverting to 1492 and see if it works

**Comment by adamk33n3r** [comment]
Oh......you're referring to forge not am2. I'm sorry. I understand now. My b! Ya I can try that out later.

**Comment by adamk33n3r** [comment]
I've done a bunch more testing on my current version and it didn't happen again. So unless you have an idea of what could cause that method to be called. I suppose we'll just deal with it when it happens again. Thanks!
