### ISSUE TITLE
Crash when loading into Single Player world ~250 mods

### ISSUE THREAD

**Issue by VenomFrog** [Mithion/ArsMagica2#1476]
Cannot load SP world without a crash when ThaumicExploration is installed. I dont know if this goes with ThaumicExploration, or Ars magica. 

TE Worked till I added AM2, and the only fix was either remove AM2 or TE. 

I fixed any potion/biome/enchantment ID's so thats not the case.

http://pastebin.com/9J6rPGw0

**Comment by jjtParadox** [comment]
There was some vague issue a while ago about ThaumicExploration doing weird stuff with Ars Magica when a world was loaded, but at the time it only threw warnings. Can't tell if this is related, and it needs further investigation.

**Comment by EdwinMindcraft** [comment]
Definitely, it's the ThaumicExploration boot event that errors.

**Comment by VenomFrog** [comment]
Removing TE works, just will miss having it! Thanks everyone!
