### ISSUE TITLE
animationAPI not found by fml

### ISSUE THREAD

**Issue by YviraSenpai** [Mithion/ArsMagica2#1477]
I have installd am2 and the API and tried everything like restarting my laptop and moving all other mods out and that kind of stuff but it keeps saying.

forge mod loader has found a problem with your minecraft installation 
the mods and versions listed below could not be found

AnimationAPI : any

I only found this in logs:  Mod Ars Magica 2 is missing a pack.mcmeta file, substituting a dummy one
and [arsmagica2/]: Parsed dependency info : [AnimationAPI] [AnimationAPI] []
[17:59:00] [Client thread/DEBUG] [FML/]: Examining file am2_api_v1.4.0.007.zip for potential mods
[17:59:00] [Client thread/DEBUG] [FML/]: The mod container am2_api_v1.4.0.007.zip appears to be missing an mcmod.info file

pleas help me with this prob

**Comment by kostanakis** [comment]
Maybe you should try [this](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1289836-animationapi-animate-your-entities-v1-2-3) version of AnimationAPI? It really works.

**Comment by YviraSenpai** [comment]
thnx i will try

**Comment by ThatOneTraitor** [comment]
@YviraSenpai Can you Close this issue please? ^.^
