### ISSUE TITLE
Ars Magica 2 Data Reset

### ISSUE THREAD

**Issue by xSable** [Mithion/ArsMagica2#1484]
So anytime any player on my server leaves the nether or the end (or any dimension) via /home or some form of teleport command, they get there data reset.

I know I saw this issue saying it was resolved in 1.2, however I am using:
AM2 1.4.0.009
Minecraft 1.7.10
Forge 1.7.10 - 10.13.4.1614

So maybe it's a conflict with another mod or plugin that I am completely unaware of, but no amount of searching has found me an answer or workaround.

Maybe this bug isn't as fixed, or maybe I misunderstood what you meant by "Issue Resolved."

Either way, any help or fix is appreciated.

EDIT: DIDN'T NOTICE THE OTHER TOPIC RELATED TO SPECIFICALLY THIS ISSUE, PLEASE CLOSE.

**Comment by jjtParadox** [comment]
@Kolatra *poke*
