### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by Akarmiru** [Mithion/ArsMagica2#1488]
Hey, I'm sorry to ask such a foolish question but I was curious. How do I use the Ars Magica 2 1.8.9 Version and do I need forge and the animation api? Is the animation api updated? I couldn't find any information on this. Thanks in Advanced,

Akarmiru

**Comment by jjtParadox** [comment]
The ars magica 1.8.9 version is still in development and is basically a hollowed out shell mod. It's not ready for use (and probably doesn't work anyway), so stay with 1.7.10.

**Comment by Akarmiru** [comment]
Aww okay, thanks anways =)

**Comment by jjtParadox** [comment]
Mind closing this issue?
