### ISSUE TITLE
Self Spells aren't doing anything

### ISSUE THREAD

**Issue by kingofrunes** [Mithion/ArsMagica2#1489]
Ars Magica 2 1.4.0.009
Forge 10.13.4.1614

On a multiplayer server I crafted 3 different self spells but right clicking them does nothing.

Tried:

Self - Slowfall
Self - Heal - Regeneration
Self - Slowfall - Haste - Swift Swim

All of them when right clicking use no mana and no effect is applied.

Projectile - Heal works fine though so I have wonder if something is up with the Self shape.

**Comment by ThatOneTraitor** [comment]
does the spell have a mana cost of 0.00?

**Comment by ThatOneTraitor** [comment]
im guessing the spell is incomplete, if it took mana and didnt do anything, that would mean the effect isnt applying properly however, if its no mana no effect, the spell was made wrong,

**Comment by kingofrunes** [comment]
The spell is complete, I followed the instructions of the book to the letter, twice in fact. I'll be uploading a video shortly to demonstrate this.

**Comment by kingofrunes** [comment]
https://youtu.be/Vtt_oyJSOKk

It's possible the recipe it thinks it has doesn't match with what's programmed.

**Comment by ThatOneTraitor** [comment]
I'll watch it when i can, doing irl stuff right now, probobly gonna do it in 2-3 hours

**Comment by ThatOneTraitor** [comment]
Dont put 2 selfs in, that messes with it.

**Comment by kingofrunes** [comment]
That explains a lot of things actually. I never realized I only had to put the main symbol in the brown box. Now I feel really stupid. Thanks, I'll go ahead and close this then.
