### ISSUE TITLE
Buff Spells Error and New Single World Error

### ISSUE THREAD

**Issue by Wildwayne14** [Mithion/ArsMagica2#1502]
Hi, I honestly don't know why this is happening and my knowledge of this is a when it happens sort of thing. I have googled for 2 days to no avail. This is a very small (4 people) server. So lets start with the basics.
List of Mods: http://pastebin.com/VwMcfZg6 
Forge Version:1.7.10-Forge10.13.2.1230
Using 009 of AM2
We did a bunch of testing to see what happens. Haste, Regeneration, True Sight, and Shield crash on use. 
Here is the error: http://pastebin.com/VhybPJib , it is the same for them all.
 
Second Issue, starting a new single player game crashes before I can load in. It happens for different blocks I think, so far we have had the crash report below for, Desert Nova, Tarma root, and Cerublossom.

http://pastebin.com/SaWLVxkj

Any help is very much appreciated!

**Comment by ThatOneTraitor** [comment]
for issue 1. check through your configs, its probobly a potion ID conflict. To fix that, get [this](http://mods.curse.com/mc-mods/minecraft/229978-extended-potions) mod and it'll let you have 4096 id slots. with this you can fix the conflicts.

**Comment by Wildwayne14** [comment]
Ok, I will try that and get back to you!

**Comment by jjtParadox** [comment]
Your first crash looks like a potion ID conflict and your second crash looks like you're using an old forge version that's having trouble with Ars Magica. We currently build on forge version 10.13.4.1492, which is newer than the forge version you've listed. Updating forge should fix the second crash you have. Thanks for the thorough crash report!

**Comment by Wildwayne14** [comment]
Thank You both for your help!! Extended Potions fixed the buff spells and updating forge fixed the single player issue!! So thanks a million!

**Comment by ThatOneTraitor** [comment]
No prob, mind closing this though?

**Comment by jjtParadox** [comment]
@Kolatra you can close this.
