### ISSUE TITLE
[1.4.0.009] Arcane spellbook crashing my game

### ISSUE THREAD

**Issue by EnderOreNinja07** [Mithion/ArsMagica2#1526]
I was just messing around in my base making a new spell and I finished it and was about to put it in my arcane spellbook (u get for killing the arcane guardian). When I put my spell in and started sprinting before closing the book I crashed and when I tried to log in again I crashed. Now I spammed number 2 where I had my pickaxe and it worked I could get into the world but when I switched to the arcane spellbook I crashed again. I logged back in and did the same thing spammed number 2 and opened my inventory and hovered over the book it said Unnamed 4425 and now all my spells are gone and I have to throw it away! - It still crashed my game

**Comment by EnderOreNinja07** [comment]
Ok it only happens if u put a spell in!

**Comment by TheIcyOne** [comment]
Can you post the crash reports?

**Comment by EnderOreNinja07** [comment]
its ok I got it fixed I had the new ars magica but the old api and changing back to the old ars magica 1.4.0.008 fixed it

**Comment by ThatOneTraitor** [comment]
can you close this then?

**Comment by EnderOreNinja07** [comment]
oh sorry forgot to close it
