### ISSUE TITLE
White Rune Issue

### ISSUE THREAD

**Issue by Undamned** [Mithion/ArsMagica2#1529]
I've noticed an issue with the white rune, although the issue seems more isolated as it's an issue withing a server I'm in; the recipe won't craft a white rune, instead it'll show as if it does, but dropping it will prove otherwise. I've tried this on my client alone and it worked, but other runes will still work on the server so I'm so sure as to what the issue is.

**Comment by ThatOneTraitor** [comment]
First of all, just to be sure. Update forge, animationapi and AM2. this tends to fix alot of bugs

**Comment by jjtParadox** [comment]
Any update on this issue?

(@Kolatra)

**Comment by Kolatra** [comment]
Been over a month, if there is an update, it can be reopened.
