### ISSUE TITLE
Crash while exploring in the End

### ISSUE THREAD

**Issue by Zsashas** [Mithion/ArsMagica2#1530]
No idea what triggered this, I was just exploring in the End, running away from the dragon. I was just landing on an endstone blob when it froze then crashed. Something about Max Mana, although I haven't even started AM2 in this world yet. (I don't even have an item frame :P)

https://gist.github.com/Zsashas/56d75d7b537f5af092bfc5b94cda8923

**Comment by renadi** [comment]
Could this be the bug that made Chylex say they don't provide support running Hardcore Ender Expansion and AM2?  Sounds like it's trying to check the mana of one of their mobs.

**Comment by Zsashas** [comment]
No idea. How do you reference someone? @Chylex?

**Comment by renadi** [comment]
Apparently so, looks like it links to them.

**Comment by Zsashas** [comment]
Welp, just happened again, exactly the same. I can't even tell what entity is triggering this.

**Comment by Mithion** [comment]
@renadi is correct - am2 and hardcore ender expansion are not compatible. You will need to uninstall one of them or this will continue to happen. Sorry :(

**Comment by Zsashas** [comment]
Do you know what is causing this, though? Like is it one of the HEE bosses or something?

**Comment by renadi** [comment]
-- Entity being ticked --
Details:
	Entity Type: HardcoreEnderExpansion.EnderEye (chylex.hee.entity.boss.EntityMiniBossEnderEye)
	Entity ID: 372399
	Entity Name: Ufredr, the Ender Eye
	Entity's Exact location: -375.50, 99.84, -198.50
	Entity's Block location: World: (-376,99,-199), Chunk: (at 8,6,9 in -24,-13; contains blocks -384,0,-208 to -369,255,-193), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
Stacktrace:
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)

I don't know enough about HEE to say, but it has a name so it could definitely be a boss.

**Comment by TheIcyOne** [comment]
Pretty sure those are the ones which spawn on the floating towers.

**Comment by Zsashas** [comment]
Oh ok so it is the boss mob. Won't happen very often at least, then.

**Comment by jjtParadox** [comment]
Weird, I wasn't able to re-create this bug. Stuck HCE in my dev environment, launched it, hunted down an ender eye in creative mode and killed it without crashing.

Anyone else able to replicate this?

**Comment by Zsashas** [comment]
Well, I was in survival mode, maybe that makes a difference.

**Comment by Zsashas** [comment]
https://github.com/chylex/Hardcore-Ender-Expansion/issues/189#issuecomment-226949707

**Comment by chylex** [comment]
Delete (backup) HEE config and try again.

**Comment by Zsashas** [comment]
It just occurred to me that this did not happen with version 008 of AM2, it's only been with 009.

**Comment by jjtParadox** [comment]
This has been fixed in a 1.8 version of HEE.

**Comment by Zsashas** [comment]
Confirmed fixed in the latest 1.7.10 version of HEE. Woo.

**Comment by jjtParadox** [comment]
Great! Mind closing the issue? Many thanks :smile:

**Comment by Zsashas** [comment]
I forgot that I was the one that opened it lol.
