### ISSUE TITLE
[Question] Can i add a translations?

### ISSUE THREAD

**Issue by KAN-RYU** [Mithion/ArsMagica2#1537]
Can i add a translations? for my main language, korean.

**Comment by ThatOneTraitor** [comment]
Sure, translations would be appreciated, make a fork of the repository and then make a korean language text file, add the translations in the same format in the other language files, then make a pull request, We'll check over it and then an editor will add it into the mod!

**Comment by jjtParadox** [comment]
@KAN-RYU you still want to add translations?

(@Kolatra you know what to do)
