### ISSUE TITLE
Leap spell not working properly + Crash upon using Slow fall

### ISSUE THREAD

**Issue by Thebigvee** [Mithion/ArsMagica2#1542]
Hey everybody,

firstly I apologize because I'm not really capable of programming, but the Ars Magica bug report led me here, so here I am. 
As of title, the Leap Spell does not work properly. Either I use it as a Self spell or as a Projectile it gives the target the effect Chrono Anchor. While some people suggested that it was a potion ID conflict, I've taken a look at the dumps and the IDs are different (namely 41 for Chrono Anchor and 49 for Leap). I can't understand what's the problem here.

Also yesterday I made a new spell, a Self spell with Slow Fall as effect. As soon as I tried to use it I crashed and I can't log into the server anymore. Here's the hastebin for the crash error:

http://hastebin.com/irakigebaq.coffee

I'm not using a modpack, we're using a combination of mods dowloaded singularly.

Thanks in advance!

**Comment by N7shadow2000** [comment]
You are currently using ars magica [1.4.0.008]. Upgrade it to ars magica [1.4.0.009] this can solve many problems. Then try to replicate the crash in a singelplayer world.

**Comment by ThatOneTraitor** [comment]
Ok, a few things

008 isnt being worked on anymore, if it were ab ug it'd have to be updated to 009 anyway
It has to do something with potion ID's
we'll need the forge crash log to find an exact log, not just the one you provided, there should be a folder called crashes, FML-Latest should be the one you send

If you can get the log it can be looked into more. ty in advance :)

**Comment by jjtParadox** [comment]
Any update with this issue?

If not, this should be closed for inactivity (@Kolatra)
