### ISSUE TITLE
Crash upon entering end

### ISSUE THREAD

**Issue by Enderspider546** [Mithion/ArsMagica2#1544]
If I have ever opened the arcane compendum and then go into the end my world will crash. How do I fix this, I will list all of my mods under here. I really like ars magica and I dont want to play without it, please help!!

**Comment by malignantMystic** [comment]
1) Make absolutely certain you can reproduce this (with and without other mods)
2) Explain in detail the circumstances (armour you're wearing, significant items in your inventory, potion effects, etc.)
3) Provide a mod list
4) Provide the crash log

Without that, we can't really help you. Screenshots/videos are infinitely more helpful than saying "please help"

**Comment by Enderspider546** [comment]
it happened 3 times, and I recreated it after in a creative world

the first 3 times i had armor and tools from both tinkers construct and divinerpg on
but in the creative world I only had the arcane compendum

mod list:
-divinerpg
-ars magica 2
-animation api
-appliedenergistics
-archimedes ships
-bibliocraft
-carpenters blocks
-chisel mod
-chocolatequest
-codechickencore
-damage indicators mod
-ender IO
-ex nihilo
-extratic
-extrautilities
-galacticraft core/planets/micdoodlecore
-magicalcrops
-tconstruct mantle/tconstruct
-metallurgy 4 /metallurgy core
-more witches
-not enough items
-openblocks/openmodslib
-twilight forest

crash log:
-- Head --
Stacktrace:
	at com.chocolate.chocolateQuest.builder.BuilderHelper.getRandomNBTMap(BuilderHelper.java:498)
	at com.chocolate.chocolateQuest.builder.BuilderTemplate.generate(BuilderTemplate.java:54)
	at com.chocolate.chocolateQuest.WorldGeneratorNew.generateBigDungeon(WorldGeneratorNew.java:150)
	at com.chocolate.chocolateQuest.WorldGeneratorNew.generateSurface(WorldGeneratorNew.java:100)
	at com.chocolate.chocolateQuest.WorldGeneratorNew.generate(WorldGeneratorNew.java:62)
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1055)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.<init>(PlayerManager.java:370)
	at net.minecraft.server.management.PlayerManager.func_72690_a(PlayerManager.java:97)
	at net.minecraft.server.management.PlayerManager.func_72683_a(PlayerManager.java:138)
	at net.minecraft.server.management.ServerConfigurationManager.func_72375_a(ServerConfigurationManager.java:240)
	at net.minecraft.server.management.ServerConfigurationManager.transferPlayerToDimension(ServerConfigurationManager.java:505)
	at net.minecraft.server.management.ServerConfigurationManager.func_72356_a(ServerConfigurationManager.java:492)
	at net.minecraft.entity.player.EntityPlayerMP.func_71027_c(EntityPlayerMP.java:529)
	at net.minecraft.block.BlockEndPortal.func_149670_a(SourceFile:62)

-- Block being collided with --
Details:
	Block type: ID #119 (tile.null // net.minecraft.block.BlockEndPortal)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (295,69,963), Chunk: (at 7,4,3 in 18,60; contains blocks 288,0,960 to 303,255,975), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
Stacktrace:
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:870)

-- Entity being checked for collision --
Details:
	Entity Type: null (micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP)
	Entity ID: 301954
	Entity Name: Enderspider546
	Entity's Exact location: 100,00, 49,00, 0,00
	Entity's Block location: World: (100,49,0), Chunk: (at 4,3,0 in 6,0; contains blocks 96,0,0 to 111,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0,00, 0,00, 0,00
Stacktrace:
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:803)
	at micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP.func_70091_d(GCEntityPlayerMP.java:62)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:341)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(SourceFile:63)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@141399c2
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 489826536 bytes (467 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 36 mods loaded, 36 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAAAAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAAAAAAA	AM2-Preloader{0.0.3} [AMCore] (minecraft.jar) 
	UCHIJAAAAAAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAAAAAAA	CodeChickenCore{1.0.1.8} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAAAAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAAAAAAA	NotEnoughItems{1.0.2.15} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.2.15-universal.jar) 
	UCHIJAAAAAAAAA	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAAAAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJAAAAAAAAA	arsmagica2{1.4.0.009} [Ars Magica 2] (1.7.10_AM2-1.4.0.009.jar) 
	UCHIJAAAAAAAAA	divinerpg{1.4.1.3} [DivineRPG] ([1.7.10][SMP]DivineRPG-1.4.1.3.jar) 
	UCHIJAAAAAAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJAAAAAAAAA	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (Archimedes-Ships-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) 
	UCHIJAAAAAAAAA	CarpentersBlocks{3.3.5} [Carpenter's Blocks] (Carpenter's Blocks v3.3.5 - MC 1.7.10.jar) 
	UCHIJAAAAAAAAA	chisel{1.5.6b} [Chisel] (Chisel-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.0.jar) 
	UCHIJAAAAAAAAA	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UCHIJAAAAAAAAA	exnihilo{1.38-49} [Ex Nihilo] (Ex-Nihilo-1.38-49.jar) 
	UCHIJAAAAAAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJAAAAAAAAA	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) 
	UCHIJAAAAAAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAAAAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAAAAAAA	Metallurgy{4.0.6} [Metallurgy 4] (Metallurgy-1.7.10-4.0.6.80.jar) 
	UCHIJAAAAAAAAA	ExtraTiC{1.4.5} [ExtraTiC] (ExtraTiC-1.7.10-1.4.5.jar) 
	UCHIJAAAAAAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.454.jar) 
	UCHIJAAAAAAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.454.jar) 
	UCHIJAAAAAAAAA	iChunUtil{4.0.0} [iChunUtil] (iChunUtil-4.0.0.jar) 
	UCHIJAAAAAAAAA	magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops] (magicalcrops-1.7.10_0.1 (1).jar) 
	UCHIJAAAAAAAAA	mwaw{1.7.10-0.0.7} [Elemental Witch Mod] (mwaw-0.0.7-1.7.10.jar) 
	UCHIJAAAAAAAAA	OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6.jar) 
	UCHIJAAAAAAAAA	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3.jar) 
	UCHIJAAAAAAAAA	Torched{4.0.0} [Torched] (Torched-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib crash transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Stencil buffer state: Function set: GL30, pool: internal, bits: 8
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [GCEntityPlayerMP['Enderspider546'/301954, l='New World', x=100,00, y=49,00, z=0,00]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by ThatOneTraitor** [comment]
Ok, from there i can take aguess and say its divineRPG, try removing that and see if it occurs

**Comment by Enderspider546** [comment]
it is not divinerpg, if i entered the end without ever opening the arcane compendum the crash didnt occur, and even without divinerpg the crash occured

**Comment by Enderspider546** [comment]
i am using ars magica 1.4.0.009 if that information is important

**Comment by TheIcyOne** [comment]
Do you have this issue with just AM2 and AnimationAPI installed?

**Comment by Enderspider546** [comment]
yes it still occurs, is there something special in the end with ars magica?

**Comment by ThatOneTraitor** [comment]
The ender guardian, thats pretty much it

**Comment by TheIcyOne** [comment]
Can you post the crashlog from when you crashed with just AM2 and AnimationAPI?

**Comment by jjtParadox** [comment]
Any update with this issue?

I believe Galacticraft and ChocolateQuest both may be causing part of this issue, but I can't determine without more crash logs.

@Kolatra, please close this when convenient

If you dig up crash logs, feel free to re-open this issue.
