### ISSUE TITLE
[1.4.0.009] Game crashes and makes a world unplayable

### ISSUE THREAD

**Issue by Asmodeus666** [Mithion/ArsMagica2#1555]
Please, help. After creating a new world after 5 minutes minecraft crashing. And after restarting the game, when I try to run this world, minecraft crashes immediately. Sorry for my bad english.

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 17.08.16 18:39
Description: Exception in server tick loop

java.lang.NoSuchFieldError: field_149433_c
    at net.minecraft.network.play.server.S1DPacketEntityEffect.<init>(SourceFile:24)
    at net.minecraft.entity.EntityTrackerEntry.func_73117_b(EntityTrackerEntry.java:436)
    at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:289)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:648)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_101, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 498107016 bytes (475 MB) / 1279332352 bytes (1220 MB) up to 2134114304 bytes (2035 MB)
    JVM Flags: 10 total; -XX:HeapDumpPath=ThisTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048M -Xms256M -Xmn128M -XX:+UseConcMarkSweepGC -XX:-UseAdaptiveSizePolicy -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseCMSInitiatingOccupancyOnly
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 40 mods loaded, 40 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAAAAAAAAAAAAAAAAA    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    AM2-Preloader{0.0.3} [AMCore](minecraft.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    BetterFonts{1.1.3} [BetterFonts](minecraft.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    NotEnoughItems{1.0.5.120} [Not Enough Items](NotEnoughItems-1.0.5.120.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    <DragonAPI ASM>{0} [DragonAPI ASM Data Initialization](minecraft.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    bspkrsCore{6.16} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.16.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI-1.2.4.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    appliedenergistics2{rv2-stable-10} [Applied Energistics 2](AppliedEnergistics2-rv2-Stable-10.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    arsmagica2{1.4.0.009} [Ars Magica 2](Ars-Magica-2-1.4.0.009.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    cookiecore{1.4.0} [Cookie Core](CookieCore-1.4.0-11.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    DamageIndicatorsMod{3.2.0} [Damage Indicators](DamageIndicators.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    ExtraUtilities{1.2.12} [Extra Utilities](ExtraUtilities-1.2.12.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    Mantle{1.7.10-0.3.2.jenkins191} [Mantle](Mantle-0.3.2b.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct](TConstruct-1.8.8.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    DragonAPI{1.0} [DragonAPI](DragonAPI-V15a.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    EnderIO{1.7.10-2.2.8.381} [Ender IO](EnderIO-2.2.8.381.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    extracells{2.3.3} [Extra Cells 2](ExtraCells-2.3.3b162.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    fastleafdecay{1.3} [Fast Leaf Decay](FastLeafDecay-1.3.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    MouseTweaks{2.4.4} [Mouse Tweaks](MouseTweaks-2.4.4.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    NEIAddons{1.12.14.40} [NEI Addons](NEIAddons-1.12.14.40.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools](NEIAddons-1.12.14.40.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2](NEIAddons-1.12.14.40.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany](NEIAddons-1.12.14.40.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry](NEIAddons-1.12.14.40.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables](NEIAddons-1.12.14.40.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo](NEIAddons-1.12.14.40.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    neresources{0.1.0.ManuallyBuilt} [Not Enough Resources](NotEnoughResources-0.1.0-121.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    RotaryCraft{1.0} [RotaryCraft](RotaryCraft-V15a.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    ReactorCraft{1.0} [ReactorCraft](ReactorCraft -V15a.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    ReiMinimap{1.7.10} [Rei's Minimap](ReisMinimap.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    StatusEffectHUD{1.27} [StatusEffectHUD](StatusEffectHUD-1.27.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    stepup{v.2.0.0-mc1.7.10} [StepUp](StepUp.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    TiCTooltips{1.2.5} [TiC Tooltips](TiCTooltips-1.2.5.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    witchery{0.24.1} [Witchery](Witchery-0.24.1.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAA    aobd{2.8.4} [Another One Bites The Dust](AOBD-2.8.4.jar) 
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    AE2 Integration: IC2:OFF, RotaryCraft:ON, RC:OFF, BC:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['TrueGrandMaster'/15505, l='Blackland', x=-232,30, y=69,48, z=-5,44]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by TheIcyOne** [comment]
Does this happen every time you create a new world?

**Comment by Zsashas** [comment]
I am experiencing this same issue, but I don't believe AM2 is causing it. It only started after I removed a few other mods. My crash reports are exactly the same.

**Comment by jjtParadox** [comment]
Does the crash happen if DragonAPI and the mods that depend on it are removed?

Of course, check for potion ID conflicts.

**Comment by Zsashas** [comment]
I found that the issue only happened when I tried moving some core mods into the 1.7.10 folder in the mods folder. Some already go in there automatically, but putting other coremods in there caused this to happen. OP, is this similar to your situation?
