### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by marioandluigi878** [Mithion/ArsMagica2#1574]
Just wondering is this ever gonna be updated would love to play around with this in the latest update thanks

**Comment by Sunconure11** [comment]
https://github.com/Growlith1223/ArsMagica2/tree/1.10.2

**Comment by marioandluigi878** [comment]
Download Link?

**Comment by Sunconure11** [comment]
A link to one of the versions was posted on IRC. I will see if I had bookmarked it later.

**Comment by Growlith1223** [comment]
im going to throw a download link up very soon(still getting used to github so excuse the delays)!
