### ISSUE TITLE
Server Crashing after a few minutes of playing after i uploaded the mod on an existing map

### ISSUE THREAD

**Issue by Tombraxis** [Mithion/ArsMagica2#1576]
I've got this error when i explore a non vistied part of my map which was generated before i pluoaded the mod in my mod pack. Can you help me ? :)

[crash-2016-11-15_22.55.03-server.txt](https://github.com/Mithion/ArsMagica2/files/593296/crash-2016-11-15_22.55.03-server.txt)

**Comment by jjtParadox** [comment]
Update forge to at least 1.7.10-10.13.4.1492

**Comment by Tombraxis** [comment]
i have 1558

**Comment by jjtParadox** [comment]
Nice! What did you do to solve the problem? 

(also could you close the issue? Helps keep things clean around here)

**Comment by Tombraxis** [comment]
i'm on OMGserv i installed the version 1647.201 of Cauldron 1.7.10

**Comment by Bogdan-G** [comment]
fake build cauldron? lel, KCauldron/Thermos/FFoKC work
