### ISSUE TITLE
[1.4.0.008] Game crashes on startup ATLauncher

### ISSUE THREAD

**Issue by JoshuaCF** [Mithion/ArsMagica2#1588]
Someone else had a very similar crash report to mine and the exact issue I'm having, however, he solved it himself but his explanation of it is short and I've no clue as to what it means. I'm hoping someone else can explain this for me. 

https://github.com/Mithion/ArsMagica2/issues/1564

This is the entire log from ATLauncher. A good portion at the beginning may be redundant, but better safe than sorry. This only happens with AM2 and to avoid conflicts with other mods, I removed all but AM2 and NEI with its dependencies.

[ATLauncher Log.txt](https://github.com/Mithion/ArsMagica2/files/753181/ATLauncher.Log.txt)

I put it in a .txt file because pasting it into the issue screwed up the formatting and made it hard to read.

**Comment by JoshuaCF** [comment]
Another thing, while this may be off topic, is the original creator of this mod done with it? Many of the 1.7.10 mods seem to be unupdated since the year I stopped playing MC.

**Comment by Orinion** [comment]
Minithion is busy, however this mod is getting continued [here](https://github.com/Growlith1223/ArsMagica2)

**Comment by TheIcyOne** [comment]
Looks like their solution was to move the files from the mods/1.7.10 folder to the mods folder.

**Comment by JoshuaCF** [comment]
I've figured out my issue. It isn't with the mod, but rather the launcher. ATLauncher's latest version of 1.7.10 forge isn't the right version, so I'm sorry for wasting time. I'll edit the title so anyone else having a similar issue with the launcher can see it. You have to manually install forge from the website.
