### ISSUE TITLE
Ars Magica hud overrides Tough As Nails hud

### ISSUE THREAD

**Issue by Hypsellis** [Mithion/ArsMagica2#1589]
Tough As Nails hud doesn't display more when Ars Magic is installed, Ars Magica hud overrides Tough As Nails hud. I tried to modify the position of the different bars of Ars Magica in the config, but I just understand nothing of the config for the hud positions, but there are so many thing with fucking long and incomprehensible floating numbers.

**Comment by Growlith1223** [comment]
mod version?

**Comment by Hypsellis** [comment]
Oh ok thanks for the info, about the armor duration hud, you should add the weapons duration currently held by the player, and the possibility to show the numeric values, and I suppose there are no support for Baubles.
What are the affinity, manashielding, continguency type and negative buffs ui ? I didn't find any informations about them.

**Comment by Growlith1223** [comment]
the buffs should be the 2 boxes in the middle of the screen, Affinities are bottom right, and top left is the second scrollbar(this only shows up if you're holding the spell book/arcane spell book), as for numeric values, numeric values is there for the mana/burnout bar but yea i may add a config option to also do numeric durabilitiy values as well

Also any new issues with 1.10, post them on my repo! i gotta update the curseforge description to also point to my repo lol or do somethin else, i feel bad messaging mithion about things like this xD

**Comment by Hypsellis** [comment]
What is the mana shielding bar just under the mana bar ? what about the contigency type hud ?

**Comment by Growlith1223** [comment]
the things underneath the mana bar are spell shapes/component icons when you hold a spell, it's to show you what the spell was made from

**Comment by Hypsellis** [comment]
I'm the owner of ULTRA, a huge modpack for 1.10.2, and I try to integrate Ars Magica inside, and your hud is so hard to integrate with the existent one. XD

**Comment by Growlith1223** [comment]
lol, ars magica takes up quite a bit of the screen honestly, i could be wrong on this but there could be a way of disabling parts of the gui, if not i might add that so users can disable things like the contingency piece of the hud, as an example

**Comment by Hypsellis** [comment]
What is the the contingency hud ?

**Comment by Hypsellis** [comment]
Still for the placement of the different hud, how many affinities can you have in same time, I have been able to get only two in same time. It's for knowing if I should put the affinity hud higher, because otherwise affinities display out of the screen at the bottom.

**Comment by xenxero1** [comment]
Contingency HUD, afaik displays active contingencies from AM2. Like if you cast a spell: Self -> Contingency: Fire -> Create water. You cast the spell, but it only adds the contingency (or trigger). That specific spell triggers when you get lit on fire. I assume the Contingency HUD displays all active triggers your magic is checking for (Death, fire, falling, ect)

As for affinities, I've only ever had 2, but there may be a way to get 3 with how the spread is. I wouldn't worry about it too much though, all affinities being displayed aren't needed, as they can be check anyway via the Occulus.

**Comment by Mithion** [comment]
Several of the GUI items can be disabled in the AMUICFG menu.  The ones that cannot are critical to being able to use AM2 effectively.

The magic UI elements should not appear at all to anyone who has yet to unlock magic.

The affinities only display the top two that you have, even though you can have more.  You can check an occulus to see the depth of all affinities.

The contingency HUD element only appears when you have a contingency spell active, and is used to indicate what type of contingency you.  Contingency spells are pre-cast spells that are applied when their condition is met.  Some conditions include: low health, taking damage, or falling (will trigger right before you hit the ground).  Any contingency spell will disappear when consumed (they're a one-shot).  You can only have one contingency spell active at one time.

**Comment by Hypsellis** [comment]
Thanks you all for the informations, sorry to bother you with that, it's really hard to integrate Ars Magic hud with Tough As Nails hud, The one Probe hudn JourneyMap hud, and Gethia hud. ^^'

**Comment by Hypsellis** [comment]
You should use relative position like Tough As Nails, The One Probe, JourneyMap...and not absolute position for the different huds. It causes the hud to always change of position depending of the size of the windows and the screen, and it's fucking annoying.

**Comment by Bogdan-G** [comment]
^ the absolute position can be harmful - part of the interface while scaling the window can disappear like
