### ISSUE TITLE
1.10.2 Ars Magica 2 Soulbound duplicates items

### ISSUE THREAD

**Issue by djoveryde** [Mithion/ArsMagica2#1597]
If a player dies their soulbound items (ie pick) will duplicate. Can't seem to disable soulbound or figure a way to fix the issue.

I am running latest forge with Sponge.

**Comment by TheIcyOne** [comment]
Is this no longer an issue?

**Comment by djoveryde** [comment]
The issue only seems to happen with the graves mod on a sponge forge server.
Changed it to the lootable bodies mod and it doesn't duplicate anymore.

Not sure if that shows there may still be an issue or not.

**Comment by TheIcyOne** [comment]
Could you post it on the 1.10 github here? https://github.com/Growlith1223/ArsMagica2/issues
This issue did occur with Sponge in 1.7, but this is the first I've heard of it for the 1.10 rewrite.

**Comment by xenxero1** [comment]
I can confirm this does happen. I don't use spongeforge or Graves (DrCyano's Lootable Bodies instead). It only seems to happen for me when travelling between the End and Overworld via portal. I'm assuming it has to do with the end portal putting you at respawn, something about simulating a death while keeping your items. What's concerning is that is reset my Arcane Spellbook's contents to a point a day before. I've been unable to find any significance to that point it reset me to, other than spells I had given away had appeared once more, and some higher tier spells I made were gone.
