### ISSUE TITLE
Ore Gen Config Request

### ISSUE THREAD

**Issue by bookerthegeek** [Mithion/ArsMagica2#1598]
I would like the ability to be able to individually control world generation. Specifically to whitelist dimensions things spawn in, and the ability to turn off generation completely for Essence and Ores while still keeping trees and mobs spawning in world.

I am using other mods to handle Ore generation 

Thank you. :)

**Comment by TheIcyOne** [comment]
#1446 solves this for 1.7.10, but hasn't been in a release version.
If you meant for 1.10.2, it would be preferable if this was posted in https://github.com/Growlith1223/ArsMagica2.

**Comment by bookerthegeek** [comment]
Thank you, I will. Forgot there were two different trackers.
