### ISSUE TITLE
Armor XP Imbuement isn't working

### ISSUE THREAD

**Issue by BTKira** [Mithion/ArsMagica2#1599]
I noticed after making my battlemage armor that it wasn't gaining any levels at all. Even though I'm level 23 normally, my armor set hasn't had any sort of increase in its xp gain. When I hold shift for details all it says is that it has 0 exp. Does anyone know what's wrong? I'd like to get it fixed, was really looking forward to adding power ups to the armor through the armor imbuement table.

**Comment by xenxero1** [comment]
Version?

**Comment by BTKira** [comment]
I'm using something called ATLauncher and downloaded a pack called "Crackpack". I can't figure out how to check the version of Ars Magica 2.

**Comment by xenxero1** [comment]
I thought crackpack disabled armor imbuement on purpose due to its over-powered nature.

If that's not the case, I don't believe older versions of ars magica are being updated anymore. Currenty 1.10 version is being worked on in https://github.com/Growlith1223/ArsMagica2

**Comment by BTKira** [comment]
Oh, that's a let down. Thank you for the info, and for helping!
