### ISSUE TITLE
Help with Compiling and building the mod

### ISSUE THREAD

**Issue by TataTawa** [Mithion/ArsMagica2#1601]
I'm a 1.7.10 player and I merged some newest bug fixed code in my forked repo  https://github.com/TataTawa/ArsMagica2

I have built a workspace and get the src in place, but I can't use gradle to build mod , as there is errors in src, seems to be some library like animationAPI .I put the animationAPI into mods folder and nothing happenned. Now what do I need to do ?

**Comment by TheIcyOne** [comment]
What version of AnimationAPI are you using?

**Comment by TataTawa** [comment]
I use the latest version in curse.com . animationAPI 1.2.4

**Comment by TheIcyOne** [comment]
When you're compiling with Gradle, you need the dev version of AnimationAPI from the forum thread here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1289836-animationapi-animate-your-entities-v1-2-3

**Comment by TataTawa** [comment]
Oh I got it . I think I also need to use Thaumcraft API in a way very similar to this one. Thanks a lot Icy 👍 @TheIcyOne
