### ISSUE TITLE
Witch Wood Trees

### ISSUE THREAD

**Issue by KisameSan2** [Mithion/ArsMagica2#1614]
Hi there,
Ive tried many options (Tinkers, draconic tools and even Vanilla Diamond axe) but for some reason it wont let me harvest the trees. the block brakes but i dont receive the wood or saplings from the tree.

**Comment by xenxero1** [comment]
version?

**Comment by KisameSan2** [comment]
i was playing on a server and forgot that i was in the original spawn chunks. flew around to try and see if that was the problem and it was. So problem self solved! XD

**Comment by xenxero1** [comment]
Ah ok, Would you mind closing the thread please?

**Comment by KisameSan2** [comment]
sure will do
