### ISSUE TITLE
Mana Battery Not Working

### ISSUE THREAD

**Issue by timkrieger** [Mithion/ArsMagica2#1616]
Mana battery does not store or pass etherium.  Using the crystal binder I am able to bind an obelisk to a mana battery, the mana battery to a consumer ( tested with : altar, reconstructor and calefactor ) the end device does not receive etherium, and the mana battery never stores any etherium for later use( mana battery does not change texture for the etherium it is supposed to be holding ).  Tested both obelisk and celestial prisim with same result. Tested with end devices out of range from provider and still receive success messages but no etherium moves through the mana battery.

Both bindings return success message and show appropriate animations.

Etherium does move if I replace the mana battery with an etherium conduit ( but the mana battery still does not function )

Tested using tolkiencraft III modpack.   Using ArsMagica2-1.10.2-1.5.0-18.jar,  minecraft 1.10.2 , forge versions 12.18.3.2239 & 12.18.3.2281.

I realized after filing initial bug report I should be more thorough in my testing and setup a new test using minecraft 1.10.2, forge version 12.28.3.2281, and ArsMagica2-1.10.2-1.5.0-18.jar
 - full creative battery is able to supply etherium and does change texture as expected, but is not accepting etherium from any appropriate etherium source including  another creative battery.

**Comment by renadi** [comment]
Mana battery needs redstone power.

I'll state again it might be wise to reverse this behavior. Lol

**Comment by timkrieger** [comment]
Sorry about the non-bug issue, I'll be sure to RTFM next time.
