### ISSUE TITLE
Shape groups, what's the point of having more than one?

### ISSUE THREAD

**Issue by Schafex** [Mithion/ArsMagica2#1617]
I see that you can have up to 5 shape groups with an upgraded inscription table, but i can't even seem to use the second one. (nor does anyone else from the looks of it)

I came back to AM2 to see that the spell customization changed a bit, i might just not know what i'm doing. I've watched some videos of example spells and whatnot, but they never use the second shape group. i put some shapes and modifiers in it, but they never seem to activate. Any explanation as to how they work would be helpful. (i can't seem to find the info i'm looking for anywhere)

**Comment by xenxero1** [comment]
There is a keybind for "Change shape group" or something along those lines. Its used so you can apply the same spell effect in different ways. Say, you set group1 to Projectile, and group2 to Rune>AoE with a spell effect of lightning. Pressing C (by default) will switch between these two, and the casting type will be displayed next to your mana bar. The projectile mode will function as a normal projectile, and when you switch with 'C', it will lay runes with aoe instead. It makes it so you can apply the same effect over different methods, and not need to make a new spell each time. Saves resources and hotbar slots.

**Comment by Schafex** [comment]
Ohhh, i guess that'd be useful if you're worried about magic consumption. Thanks! i feel kinda dumb for not looking at keybindings now.

**Comment by xenxero1** [comment]
No problem. One of the biggest uses of this (which il put out there for anyone who stumbles across this) is Self || Projectile | Buff/effect.

I use it for all spell effect or teleportation spells I make. Its such a useful utility to be able to have the option of giving your friend recall, then recalling yourself. At that point, the only extra cost overall is one extra snow ball, an arrow, and some V-dust. Extremely economical and utility-centric.
