### ISSUE TITLE
{Closed} May have found stolen assets in steam game 

### ISSUE THREAD

**Issue by Phonavis** [Mithion/ArsMagica2#1643]
Not sure if the spell icons are actually yours or from a free art site, but they're in a free game on steam http://store.steampowered.com/app/516510/Orake_2D_MMORPG/

2nd Screenshot you can see them, unsure if anything else is stolen

Screen shot of the screen shot in case you don't want to open the steam store - https://cdn.discordapp.com/attachments/166630061217153024/343612777690300417/unknown.png

Nvm, am retarded, assets were originally free anyways and part of a rpg pack, Disregard

**Comment by TheIcyOne** [comment]
For reference, the images are actually provided Public Domain from  [(http://www.alteredgamer.com/rpg-maker/100053-vx-custom-icons](http://www.alteredgamer.com/rpg-maker/100053-vx-custom-icons), as noted in the readme.md
