### ISSUE TITLE
Shrink causes continuous movement NW

### ISSUE THREAD

**Issue by ouroborus** [Mithion/ArsMagica2#1644]
I tried putting together a shrink spell with Self and Shrink. The effect causes me to move at approximately a walking pace in a northwest direction for the duration of the miniaturization (from beginning of shrink animation to end of un-shrink animation. It goes so far as to push me through objects, even into thick walls and terrain if cast while up against them.

Ars Magica 2
1.5.0-18

**Comment by TheIcyOne** [comment]
Please post 1.10.2 issues to https://github.com/Growlith1223/ArsMagica2/issues

**Comment by ouroborus** [comment]
https://github.com/Growlith1223/ArsMagica2/issues/380

**Comment by ouroborus** [comment]
https://github.com/Growlith1223/ArsMagica2/issues/380
