### ISSUE TITLE
(1.7.10) Playerdata issues

### ISSUE THREAD

**Issue by Galvarino** [Mithion/ArsMagica2#1646]
I've created my own 1.7.10 modpack with about 97 mods on ubuntu, AM2 included. Everything has been working smoothly until recently when I shut down my computer with minecraft open after leaving my game, (singleplayer) assuming that seeing the title screen meant everything was saved and nothing would be affected by a shutdown. I'm not sure what happened exactly, but my playerdata broke (not corrupt, just a little broken) and everything is back to how it would be as though I'd restarted the world. But the broken part is AM2's data. Everything in the occulus is unlocked. It gets even more strange when I try to delete the data so it creates a fresh file, because instead of doing so it somehow RECREATES ITSELF. I've checked to see if there are multiple data files, but there's only one so that's not the issue, and something is broken within the game. However from it's current state I can restore everything I had and continue the game as I normally would, but the occulus being entirely unlocked really sucks, since now there is no challenge or encouragement in AM2. So I went in with NBTexplorer to see if I could manually edit the occulus' data, but all I found was this
![image](https://user-images.githubusercontent.com/31280096/29623538-c027d848-87f4-11e7-821a-bf023a7dce50.png)
Ignoring the fact that it says I've unlocked nothing even though everything is unlocked, I just need to know where to edit the occulus. If you have any other solution based on what I've written suggestions are great, but considering how broken everything is it would probably just be better to edit the occulus.

Some additional info, the clear known spell parts and respec commands do nothing to fix this.

**Comment by TheIcyOne** [comment]
I can't remember how the AM2 player data worked in 1.7.10, but I have a feeling it was stored within the world NBT with other entities. There might be a file named "EntityExtension" or similar inside your save.

**Comment by Galvarino** [comment]
Where in the save would that be? I thought I knew but I didn't. If you mean in the main folder (outside any NBT) then no, but I assume you mean something else.

**Comment by Galvarino** [comment]
I managed to fix the recreation issue, I was being an idiot and forgot it was still in level.dat, but the occulus is still an issue. I even had to re-obtain the compendium to unlock it and all the components were unlocked once again. The respec and clear known spell parts commands still don't work.

**Comment by TheIcyOne** [comment]
I have a feeling the oculus data is also within the world save folder somewhere, although I have absolutely no idea where that might be.

**Comment by Galvarino** [comment]
Ok, I'll keep looking then. If you can, direct me to someone who knows where it is. Thanks for your help!

**Comment by TheIcyOne** [comment]
The only people I can think of who may know are jjtParadox and Mithion himself.

**Comment by Galvarino** [comment]
How can I get either of their attention?

**Comment by TheIcyOne** [comment]
Probably not worth bothering for Mithion, he tends to come back on occasion, I'll see if I can get to jjt.

**Comment by Galvarino** [comment]
Again thank you very much for your help. I still haven't found anything about the occulus except the bit in playerdata, but that doesn't seem to be the root of the problem since I've reset that.

**Comment by Galvarino** [comment]
So it turns out I'm just dumb. When in CREATIVE, you can use all components in the occulus. That feature should be explained somewhere :/ anyhoo thanks for your help!

**Comment by TheIcyOne** [comment]
That would certainly do it ;) 

I probably should've asked about that first.
