### ISSUE TITLE
Compatibility issue with Quantum Quarry.

### ISSUE THREAD

**Issue by Magi1053** [Mithion/ArsMagica2#1648]
In Extra Utilities 2 there is a Quantum Quarry, which basically creates a dimension (-9999) and mines ores out of it. However ever since installing AM2, the quantum quarry just returns AM2 items and some other junk. This is after running the quarry for 20m over 16k blocks in DIM-9999 https://i.imgur.com/wfgNr8j.png

**Comment by TheIcyOne** [comment]
Please post 1.10.2 issues to https://github.com/Growlith1223/ArsMagica2/issues

**Comment by xenxero1** [comment]
Just a thought, but if it retro-genned the ores, it might be filling in your old "quantum holes" with am2 ores, which the quarry might re-read and try to mine again. Might just need to give it some more time, or replace the biome filter to spawn a new chunk.

If that IS the issue, i'm not sure where to take it. I'd say open an issue then on the XU2 page, but I'm not sure if they can disable retroactive-generation inside their dimension.

**Comment by Magi1053** [comment]
After adding DIM-9999 to the gen blacklist in AM2 config and deleting/regenerating the world, the ore's respawned normally

**Comment by Magi1053** [comment]
Ore spawn is still not functioning properly
