### ISSUE TITLE
Are there any way to not allow Liquid Etherium pool generate on my map/world?

### ISSUE THREAD

**Issue by Lostpart** [Mithion/ArsMagica2#1658]
I want to use plot world, but this pool destroy the world, I'm wondering if there is a way to disable them.
Thank you

**Comment by jjtParadox** [comment]
You can disable worldgen for a dimension by adding that dimension ID to the blacklist in the config file.

E.g. disabling worldgen for the overworld:
```
S:worldgen_blacklist=<some pre-filled numbers>,0
```
