### ISSUE TITLE
[Suggestion] Add Pirate Speak into AM2

### ISSUE THREAD

**Issue by radzo73** [Mithion/ArsMagica2#1663]
Firstly,

1. Yes, Pirate Speak is a real language you can choose in your Languages setting
2. Yes, it's somewhat pointless (but mainly funny)
3. Yes, my version isn't done. 

[en_7S.lang.zip](https://github.com/Mithion/ArsMagica2/files/2172366/en_7S.lang.zip)

**Comment by TheIcyOne** [comment]
That would be best done in Growlith's repository, as he is the current maintainer.
