### ISSUE TITLE
Unfinished Spell Book

### ISSUE THREAD

**Issue by Likeabozz123** [Mithion/ArsMagica2#1666]
I have a problem with making spells I am unsure if I am doing it wrong or if it a bug.
http://prntscr.com/lgpivo

**Comment by waterclassifier** [comment]
Same bug here [https://imgur.com/a/ShIv6Ay](url)

Edit: After further testing, it seems like you get unfinished spell book when you take the spell book out of the inscription table by shift+click. Taking the spell book out by click the spell book and click empty slot get you working spell book

**Comment by Hyper-Miiko** [comment]
Did you tried to take it anyway?
