### ISSUE TITLE
Permission to make a Legacy Version

### ISSUE THREAD

**Issue by Minecraftschurli** [Mithion/ArsMagica2#1677]
@Mithion or the one responsible here
I love this mod and I find it sad that its pretty much dead. That's why I want to revive it as a Legacy version in MC 1.14.4 and up. So I'm asking here for permission to do so and to use the assets from the original.

**Comment by Mithion** [comment]
Go for it.  Open source is open source!  I'd love to see the mod updated, but I just don't have the time anymore.
