### ISSUE TITLE
See-Through/Invisible Hand (1st Person)

### ISSUE THREAD

**Issue by Peach774** [Mithion/ArsMagica2#259]
I'm getting this issue, which disappeared but has reappeared: http://imgur.com/BnaQv3S,LspMcO7,F89cxwC
fml log: https://www.dropbox.com/s/vvk71wlw7iovd1l/ForgeModLoader-client-0.log
sorry about dropboxing it, it was too big for pastebin.

**Comment by Mithion** [comment]
This isn't something that will be fixed in the final update.
