### ISSUE TITLE
Compatibility issues with Familiar mod.

### ISSUE THREAD

**Issue by Robotmenace** [Mithion/ArsMagica2#327]
I recently saw a mod, called "Familiars", that allows you to unlock and summon familiars as companions, and they give you different effects and what not. I was really looking forward to trying it, but I'm also a huge fan of Ars Magica. And the two seem to be incompatible. Upon trying to summon a familiar, I receive the following crash: http://pastebin.com/ejbKTv3y.

I have very, VERY little coding experience, but looking at the crash report, it seems like it possibly could be something like Ars Magica thinking the familiar is a player entity, and trying to assign a mana value to it. I'm not sure if that's what's going on, but it seems possible.

Is there any possible way around this? I realize it would be asking too much for an update to make these two mods compatible with one another, but if there were some sort of client side alteration I could make or something so I can play the two games together, that'd be great.

**Comment by usafphoenix** [comment]
[was going to post a crash/bug issue but found this, which is probably what was happening, except with a different mod. (entity issues causing crash when the two mods are installed together. both work fine separately, but AM2's hard-coded requirement makes everything break. 
Suggestion: include error-handling case that simply results in no action being taken if the entity hasn't been registered correctly. 
if entity-extended-property [blah blah] has mana, then [do all the stuff AM2]
else [do nothing. maybe post a message to debug or log stating "Mod:entityID/name is not registered properly for AM2. Spell cannot function. doing nothing."

**Comment by jjtParadox** [comment]
@usafphoenix, feel free to open a new issue referencing this one, helps keep the fixed things separate from the bugs.
