### ISSUE TITLE
Wierd Bug with Thermal Expansion? Please Help!

### ISSUE THREAD

**Issue by Lezux** [Mithion/ArsMagica2#433]
Whenever i mine  Ars Magica ores, i get the "invalid item" from thermal expansion. 
![2014-02-27_19 39 21](https://f.cloud.github.com/assets/5800311/2290808/2785464e-a02a-11e3-9c27-014075358e40.png)

Please help!

**Comment by Pdiddle** [comment]
I'm changing some Ars Magica Ids for something else... Where do I change them at? I've looked in the config and there isnt a place to change Ids.. Thanks for the help
