### ISSUE TITLE
Soulbound Items in the End / Hardcore Ender Dragon

### ISSUE THREAD

**Issue by moneyblind** [Mithion/ArsMagica2#479]
Approx. 1 month ago I died in the end to the dragon (Hardcore Ender Mod). I lost a full set of battlemage armour and earth armor that was soulbound. (Maybe they took too much damage and broke?)

The main concern was my soulbound Spellbook also was lost. No logs exist due to late reporting.

Additionally, unconfirmed by myself, Dragon was impervious to magic damage. (According to server admin)

**Comment by EoD** [comment]
We are using AM2-1.4.0.008 and the bug is still present. If you die while having/wearing Soulbound items, they disappear on respawning.
