### ISSUE TITLE
Murdered Player Rendering?

### ISSUE THREAD

**Issue by TherminatorX** [Mithion/ArsMagica2#519]
Why am I sliced up?
![2014-05-23_17 50 49](https://cloud.githubusercontent.com/assets/7256249/3072726/3a844084-e2cd-11e3-8b63-2bc0b29c5e67.png)

This happens with version 1.1.2b.
Other mods: NEI, CCC, and NEIPlugins(doubt source of issue)

Maximized window after loading world, and noticed my hand was missing a piece.

**Comment by Mithion** [comment]
This has been linked to intel graphics cards, and isn't something that will be fixed in the final update.
