### ISSUE TITLE
Arcane Compendium Missing Back Button

### ISSUE THREAD

**Issue by Hypna** [Mithion/ArsMagica2#536]
On the Earth Guardian page there is no back button. This makes it impossible to continue navigating the compendium. By logging out and returning some time later, the arcane compendium returns to the index.

![earthguardian](https://cloud.githubusercontent.com/assets/7924305/3315355/b0847426-f6f9-11e3-8b56-453f57d1f80a.jpg)

Forge log -> http://pastebin.com/H3421Aw1

**Comment by Mithion** [comment]
Linked to SEUS as inter-mod compat.  Since it's a visual issue only, it will not be fixed in the final update.
