### ISSUE TITLE
Conflict with Veinminer

### ISSUE THREAD

**Issue by SSFly** [Mithion/ArsMagica2#540]
Full server log is available at: http://rangecraft.org/files/logs/ForgeModLoader-server-0.log

The crash occurs when a player, using a pickaxe that has had the "self" spell placed up on it by shift clicking blocks. This conflicts with veinminer at some point.

Since your error is listed first in the stack trace, I'm reporting it to you. If you determine it to be an error with the way veinminer interacts with the world, I'll re-report it to their team.

Let me know if you need any further information. Thanks for the powerful mod!

**Comment by Mithion** [comment]
This has been corrected in 1.4.0.007 (dev).
