### ISSUE TITLE
Health and hunger transparency when using intel graphics chips

### ISSUE THREAD

**Issue by TherminatorX** [Mithion/ArsMagica2#575]
Hearts are blue, as well as the hunger bar.

Actually, it seems to be another render issue.
![2014-06-29_15 29 21](https://cloud.githubusercontent.com/assets/7256249/3424357/3b507700-ffcc-11e3-8829-22b123aa658e.png)
![2014-06-29_15 29 25](https://cloud.githubusercontent.com/assets/7256249/3424358/3e79c5d0-ffcc-11e3-8b5d-7ddce32c56bf.png)

Log to follow shortly.

Edit: I don't think this is the right log, but it's FML Client 0: http://pastebin.com/4Jk3u3Mi

**Comment by Mithion** [comment]
This is a purely visual bug, and isn't something that will be fixed in the final update.
