### ISSUE TITLE
Dryads Not Spawning

### ISSUE THREAD

**Issue by Strill** [Mithion/ArsMagica2#615]
So far I haven't seen any dryads in my world. Opis says there aren't any.  Strangely though, my world has almost 200 sheep, all of which are wild.  Dryad spawn rate is set to 5.

Opis entity list: (Flicker spawning was disabled in the config) http://imgur.com/J7cvBZS

**Comment by Mithion** [comment]
This has been altered in 1.4.0.007 (dev) and works the same as other creatures.
