### ISSUE TITLE
Charachter height not being properly reduced to one block space when appropriate...

### ISSUE THREAD

**Issue by ate0ate** [Mithion/ArsMagica2#638]
Something in AM2 seems to be conflicting with the crawl ability of Smart Moving. Usually while crawling the player's height is reduced to one block space, after installing AM2 this is no longer the case and while the player appears to be crawling, player height remains at two blocks. This did not happen in prior versions of AM2(pre 1.2) and removing AM2 returns behavior to normal.

Edit: Charachter height also seems off when sleeping in a bed or using an open blocks sleeping bag. (Player floats in air)

**Comment by Mithion** [comment]
This has been corrected in 1.4.0.007 (dev).  If, due to other mods the issue reappears, disabling the shrink component will disable all code in AM2 that alters the player's size.
