### ISSUE TITLE
Ritual reagents and spell activations disappear from compendium

### ISSUE THREAD

**Issue by Xerow** [Mithion/ArsMagica2#681]
The ritual reagents and activation spell disappear from the compendium's specific ritual pages when it is re-opened after being left on the page.  This is a repeatable bug.  I have the compendium fully unlocked in the config.

1.  Open the compendium.
2.  Structures > Rituals > Open any ritual page.
3.  Compendium shows normally.
![2014-07-05_16 03 24](https://cloud.githubusercontent.com/assets/4020820/3487765/05d59d10-04a1-11e4-8ef6-07f74f6d661f.png)
4.  Close the compendium (I use the escape key).
5.  Re-open compendium.  Reagents missing from the top right page.  Activation spell missing from the bottom right page.
![2014-07-05_16 04 32](https://cloud.githubusercontent.com/assets/4020820/3487768/2e4cf860-04a1-11e4-8d3f-596498ae4d70.png)

This seems to occur for all ritual spells.  Clicking "Back" and going re-opening the ritual page shows them normally again as a work-around.

**Comment by Mithion** [comment]
This has been corrected in 1.4.0.007 (Dev)
