### ISSUE TITLE
Zone and Wall spell shapes do not accept targeting shapes in lower spell crafting menu [1.2.0.018]

### ISSUE THREAD

**Issue by Ipkcle** [Mithion/ArsMagica2#709]
When I put the zone or wall shape in the lower spell creation menu meant for components, the"(zone or wall) is a principum shape and needs a targeting shape added after it in order to function" message remains even when I put another shape after zone or wall, and I am unable to create the spell. It works fine when the zone or wall shapes are in the upper boxes meant for shapes.

![2014-07-07_23 36 36](https://cloud.githubusercontent.com/assets/8098327/3505257/cb309c9a-0659-11e4-9304-bd7008576c68.png)
works

![2014-07-07_23 37 28](https://cloud.githubusercontent.com/assets/8098327/3505262/e9689276-0659-11e4-93a7-db1d84cf77c7.png)
doesn't work

**Comment by Mithion** [comment]
Corrected in 1.4.0.007 (dev).
