### ISSUE TITLE
Null Pointer with AtomicStrykers Necromancy Minions in latest AM versions

### ISSUE THREAD

**Issue by Darkmega18** [Mithion/ArsMagica2#710]
I posted on the minecraft forums but figured I'd make an account and everything just to make sure you see this and take a look.

Basically, Atomicstrykers Necromancy. You build a minion on a table, give it a soul and some blood, shift rightclick the table, boom, get some abomination minion made out of the parts you built it from. But with the latest AM2 it spawns, then within a second it crashes and gives me a nullpointer due to ticking entity cause of something AM2 is trying to get out of it. Below is the full on Forge read-out thingy I put onto my public dropbox... all 3 mb of it.

https://dl.dropboxusercontent.com/u/39619820/ForgeModLoader-client-0.log

I figure the new minions aren't getting some kind of NBT data or something you're meant to be injecting into everything to govern manas and burnouts and stuff, but there you go. I'll just... make sure not to make minions until we figure this out and go on to do something else with mob properties meanwhile. (like make a jailer skelly who drops random passive mobs... like Dryads who never seem to stick around like they used to, but thats another issue...)

**Comment by Mithion** [comment]
This has been tracked to an event that isn't firing through normal instantiation: 

Basically when an entity is created, usually a forge event of type EntityConstructing is fired.  If this doesn't happen, then AM2 can't do its setup for the entity, and when it tries to access the data (which isn't there)...boom.  

It isn't really something I can fix on my end without about 15,000 null checks, which I am not about to do.  The much easier solution would be to make sure that the Necromancy entities cause this event to be thrown.
