### ISSUE TITLE
(AM2 1.2.0.018) Errors in Arcane Compendium entries for Keystone Doors and Trapdoors

### ISSUE THREAD

**Issue by druha** [Mithion/ArsMagica2#714]
So there's a few.

Keystone Door entry:
1. Image is only the bottom half of the door.
2. On hover, the class name is shown.
3. There is no crafting recipe
![2014-07-08_21 30 19](https://cloud.githubusercontent.com/assets/6519841/3518798/25816062-0709-11e4-8c08-fc9da88d1b7d.png)

Keystone Trapdoor entry:
1. Image for the Keystone Door at the bottom of the page is only the bottom half of the door. 
2. On hover over the Keystone Door it shows the full class name. 
3. There is no crafting recipe
![2014-07-06_23 35 02](https://cloud.githubusercontent.com/assets/6519841/3518803/4e13f224-0709-11e4-8076-c7cadd428175.png)

**Comment by Mithion** [comment]
This has been corrected in 1.4.0.007 (dev).

**Comment by Cenirion** [comment]
Still no recipe for the keystone trapdoor (1.7.10_AM2-1.4.0.008.jar)
![trapdoor](https://cloud.githubusercontent.com/assets/16379085/11924659/2bb707b4-a7b4-11e5-8387-14c9e03b15e1.png)
