### ISSUE TITLE
(AM2 1.2.0.018) Crystal Foci have no crafting recipe in Arcane Compendium

### ISSUE THREAD

**Issue by druha** [Mithion/ArsMagica2#715]
Just like the title says, there's no crafting recipe listed in the Compendium.
![2014-07-06_23 39 04](https://cloud.githubusercontent.com/assets/6519841/3519038/f0c436e2-070d-11e4-8316-8f244dbeb3ae.png)

**Comment by Mithion** [comment]
This has been corrected in 1.4.0.007 (dev).
