### ISSUE TITLE
Crash when summoning the winter guardian.

### ISSUE THREAD

**Issue by Raisu4** [Mithion/ArsMagica2#749]
A few seconds after eating up the third snow golem, minecraft crashes and gives this crash report. One thing to note, though, is that when I load the map again it has spawned and the battle goes fine. Another thing to note is that I use a bunch of other mods, so it may or may not be a problem with them, but I don't know about that.
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 16/07/14 13:47
Description: Unexpected error

java.lang.NullPointerException
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:744)
	at net.minecraft.client.particle.EntityFX.func_70071_h_(SourceFile:116)
	at net.minecraft.client.particle.EffectRenderer.func_78868_a(EffectRenderer.java:70)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1961)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
	at net.minecraft.client.main.Main.main(SourceFile:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:744)
	at net.minecraft.client.particle.EntityFX.func_70071_h_(SourceFile:116)
	at net.minecraft.client.particle.EffectRenderer.func_78868_a(EffectRenderer.java:70)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Raisu4'/287, l='MpServer', x=140,14, y=66,62, z=275,50]]
	Chunk stats: MultiplayerChunkCache: 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (64,64,252), Chunk: (at 0,4,12 in 4,15; contains blocks 64,0,240 to 79,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1588024 game time, 505097 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 115 total; [EntityTurtlePart['entity.BetterDungeons.TurtleBossPart.name'/283, l='MpServer', x=94,06, y=30,00, z=416,88], EntityTurtlePart['entity.BetterDungeons.TurtleBossPart.name'/282, l='MpServer', x=95,44, y=30,00, z=417,47], EntityTurtlePart['entity.BetterDungeons.TurtleBossPart.name'/286, l='MpServer', x=94,13, y=30,00, z=414,06], EntityTurtlePart['entity.BetterDungeons.TurtleBossPart.name'/285, l='MpServer', x=96,88, y=30,00, z=416,94], EntityTurtlePart['entity.BetterDungeons.TurtleBossPart.name'/284, l='MpServer', x=96,94, y=30,00, z=414,13], EntitySkeleton['Skeleton'/15327, l='MpServer', x=210,50, y=55,00, z=289,41], EntitySkeleton['Skeleton'/15342, l='MpServer', x=170,50, y=19,00, z=316,50], EntityClientPlayerMP['Raisu4'/287, l='MpServer', x=140,14, y=66,62, z=275,50], EntitySkeleton['Skeleton'/4641, l='MpServer', x=220,50, y=19,00, z=229,50], EntityZombie['Zombie'/8571, l='MpServer', x=139,03, y=36,00, z=304,50], EntityBat['Bat'/51, l='MpServer', x=65,42, y=15,00, z=293,51], EntityPig['Pig'/58, l='MpServer', x=68,06, y=73,00, z=225,94], EntityBat['Bat'/14807, l='MpServer', x=98,66, y=56,98, z=281,25], EntityBat['Bat'/57, l='MpServer', x=86,59, y=42,10, z=226,41], EntityCreeper['Creeper'/62, l='MpServer', x=72,31, y=41,00, z=344,66], EntitySkeleton['Skeleton'/61, l='MpServer', x=74,50, y=41,00, z=340,50], EntitySkeleton['Skeleton'/60, l='MpServer', x=69,50, y=41,00, z=344,13], EntityPainting['Painting'/68, l='MpServer', x=81,06, y=26,00, z=327,00], EntityItemFrame['entity.ItemFrame.name'/69, l='MpServer', x=95,06, y=25,50, z=327,50], EntitySkeletonMele['Skeleton Archer'/70, l='MpServer', x=83,25, y=24,00, z=335,72], EntitySpecter['Specter'/71, l='MpServer', x=83,69, y=24,00, z=333,31], EntityItemFrame['entity.ItemFrame.name'/66, l='MpServer', x=93,06, y=25,50, z=334,50], EntityItemFrame['entity.ItemFrame.name'/67, l='MpServer', x=87,94, y=25,50, z=324,50], EntitySkeletonMele['Skeleton'/76, l='MpServer', x=85,00, y=24,00, z=348,88], EntitySkeletonMele['Skeleton Archer'/77, l='MpServer', x=86,09, y=24,88, z=348,84], EntitySpecter['Specter'/78, l='MpServer', x=83,78, y=24,00, z=343,28], EntitySkeletonMele['Skeleton'/79, l='MpServer', x=84,22, y=24,00, z=342,31], EntitySpecter['Specter'/72, l='MpServer', x=85,47, y=24,00, z=334,09], EntitySpecter['Specter'/73, l='MpServer', x=81,53, y=24,00, z=329,63], EntitySpecter['Specter'/74, l='MpServer', x=86,34, y=24,56, z=334,16], EntityItemFrame['entity.ItemFrame.name'/75, l='MpServer', x=93,06, y=25,50, z=340,50], EntitySkeletonMele['Skeleton'/84, l='MpServer', x=87,44, y=24,00, z=352,00], EntitySkeleton['Skeleton'/9544, l='MpServer', x=210,50, y=23,00, z=262,50], EntitySpecter['Specter'/81, l='MpServer', x=82,56, y=24,00, z=343,47], EntitySpecter['Specter'/80, l='MpServer', x=83,25, y=24,00, z=341,84], EntitySpecter['Specter'/83, l='MpServer', x=82,50, y=24,00, z=337,69], EntitySpecter['Specter'/82, l='MpServer', x=83,00, y=24,00, z=344,38], EntitySkeleton['Skeleton'/13670, l='MpServer', x=129,50, y=34,00, z=273,50], EntityItem['item.item.snowball'/15598, l='MpServer', x=135,53, y=64,13, z=293,91], EntitySkeleton['Skeleton'/9542, l='MpServer', x=209,50, y=23,00, z=269,50], EntitySkeleton['Skeleton'/9543, l='MpServer', x=208,50, y=23,00, z=268,50], EntityPig['Pig'/102, l='MpServer', x=96,50, y=67,00, z=223,94], EntityPig['Pig'/103, l='MpServer', x=105,78, y=71,00, z=240,84], EntitySkeleton['Skeleton'/13662, l='MpServer', x=147,50, y=26,00, z=238,50], EntityBat['Bat'/100, l='MpServer', x=90,43, y=42,74, z=219,38], EntityPig['Pig'/101, l='MpServer', x=101,47, y=67,00, z=228,66], EntityBat['Bat'/8706, l='MpServer', x=100,66, y=31,76, z=307,90], EntityItemFrame['entity.ItemFrame.name'/110, l='MpServer', x=100,50, y=25,50, z=346,06], EntitySkeletonMele['Skeleton Archer'/111, l='MpServer', x=111,59, y=24,00, z=338,50], EntityItemFrame['entity.ItemFrame.name'/108, l='MpServer', x=104,94, y=25,50, z=339,50], EntityItemFrame['entity.ItemFrame.name'/109, l='MpServer', x=96,50, y=25,50, z=346,06], EntityPig['Pig'/107, l='MpServer', x=109,06, y=64,00, z=335,59], EntityHecate['Hecate'/5692, l='MpServer', x=153,50, y=20,00, z=326,50], EntityHecate['Hecate'/5690, l='MpServer', x=157,50, y=20,00, z=325,50], EntityHecate['Hecate'/5691, l='MpServer', x=155,84, y=20,00, z=325,50], EntityZombie['Zombie'/114, l='MpServer', x=100,78, y=53,00, z=355,78], EntitySkeleton['Skeleton'/5689, l='MpServer', x=155,16, y=20,00, z=322,75], EntitySkeletonMele['Skeleton Archer'/112, l='MpServer', x=111,13, y=24,00, z=337,50], EntityZombie['Zombie'/7854, l='MpServer', x=26,76, y=-47,70, z=30,53], EntityCreeper['Creeper'/11768, l='MpServer', x=216,00, y=45,00, z=345,59], EntityItem['item.item.snowball'/13393, l='MpServer', x=134,75, y=64,13, z=289,13], EntitySkeleton['Skeleton'/141, l='MpServer', x=113,06, y=44,00, z=279,56], EntityItem['item.item.snowball'/17758, l='MpServer', x=132,31, y=64,13, z=290,25], EntityZombie['Zombie'/140, l='MpServer', x=120,50, y=36,00, z=266,50], EntitySpecter['Specter'/143, l='MpServer', x=116,50, y=24,00, z=338,16], EntityPig['Pig'/155, l='MpServer', x=131,66, y=69,00, z=318,13], EntitySkeletonMele['Skeleton'/144, l='MpServer', x=116,16, y=24,00, z=336,50], EntitySpider['Spider'/9369, l='MpServer', x=70,50, y=27,00, z=283,50], EntityZombie['Zombie'/3954, l='MpServer', x=-26,75, y=-41,62, z=37,95], EntityPainting['Painting'/177, l='MpServer', x=163,94, y=19,50, z=323,00], EntityBat['Bat'/8698, l='MpServer', x=205,75, y=45,10, z=322,56], EntityPig['Pig'/175, l='MpServer', x=171,53, y=64,00, z=317,66], EntityManaElemental['Mana Elemental'/174, l='MpServer', x=169,50, y=19,00, z=309,25], EntityBat['Bat'/8697, l='MpServer', x=196,92, y=44,48, z=321,84], EntityCreeper['Creeper'/163, l='MpServer', x=151,50, y=39,00, z=323,50], EntityWinterGuardian['Winter Guardian'/162, l='MpServer', x=151,31, y=25,00, z=312,72], EntityZombie['Zombie'/3904, l='MpServer', x=-31,53, y=-41,62, z=29,86], EntitySkeleton['Skeleton'/161, l='MpServer', x=159,50, y=23,00, z=300,50], EntityPig['Pig'/160, l='MpServer', x=156,25, y=77,00, z=224,50], EntityPig['Pig'/186, l='MpServer', x=168,03, y=68,00, z=336,13], EntityItemFrame['entity.ItemFrame.name'/187, l='MpServer', x=171,94, y=19,50, z=356,50], EntitySkeleton['Skeleton'/11786, l='MpServer', x=179,84, y=54,00, z=282,59], EntityZombie['Zombie'/11782, l='MpServer', x=210,66, y=19,00, z=232,34], EntityItemFrame['entity.ItemFrame.name'/178, l='MpServer', x=169,50, y=19,50, z=344,06], EntityZombie['Zombie'/11783, l='MpServer', x=217,50, y=14,17, z=226,08], EntityItemFrame['entity.ItemFrame.name'/179, l='MpServer', x=163,94, y=19,50, z=346,50], EntityPig['Pig'/176, l='MpServer', x=166,84, y=64,00, z=317,19], EntityPainting['Painting'/177, l='MpServer', x=163,94, y=19,50, z=323,00], EntityItemFrame['entity.ItemFrame.name'/205, l='MpServer', x=191,50, y=19,50, z=349,94], EntityItemFrame['entity.ItemFrame.name'/204, l='MpServer', x=176,50, y=19,50, z=346,06], EntityCreeper['Creeper'/201, l='MpServer', x=177,50, y=18,00, z=331,50], EntityBat['Bat'/200, l='MpServer', x=185,25, y=18,10, z=302,75], EntityPig['Pig'/197, l='MpServer', x=182,34, y=79,00, z=270,66], EntityEnderman['Enderman'/13544, l='MpServer', x=143,69, y=13,00, z=312,94], EntitySkeleton['Skeleton'/4825, l='MpServer', x=66,50, y=27,00, z=267,50], EntityBat['Bat'/220, l='MpServer', x=197,51, y=19,76, z=293,34], EntityZombie['Zombie'/4824, l='MpServer', x=207,50, y=26,00, z=285,50], EntityCreeper['Creeper'/4826, l='MpServer', x=70,50, y=27,00, z=272,50], EntityCreeper['Creeper'/8588, l='MpServer', x=103,41, y=30,00, z=294,94], EntityCreeper['Creeper'/4828, l='MpServer', x=151,94, y=11,00, z=295,53], EntitySpider['Spider'/217, l='MpServer', x=205,09, y=62,00, z=215,06], EntityPig['Pig'/218, l='MpServer', x=203,50, y=73,00, z=233,69], EntityPig['Pig'/219, l='MpServer', x=192,16, y=78,00, z=247,97], EntityZombie['Zombie'/208, l='MpServer', x=189,50, y=61,00, z=345,50], EntityPig['Pig'/209, l='MpServer', x=185,06, y=71,00, z=339,03], EntityPig['Pig'/210, l='MpServer', x=180,53, y=68,00, z=341,66], EntitySpider['Spider'/211, l='MpServer', x=177,34, y=18,00, z=351,97], EntityZombie['Zombie'/239, l='MpServer', x=204,70, y=11,00, z=272,30], EntityPig['Pig'/238, l='MpServer', x=208,06, y=72,00, z=242,88], EntityPig['Pig'/237, l='MpServer', x=218,50, y=71,00, z=233,31], EntityBat['Bat'/15453, l='MpServer', x=209,47, y=14,68, z=224,91], EntityPig['Pig'/236, l='MpServer', x=220,78, y=71,00, z=216,50], EntityPig['Pig'/249, l='MpServer', x=216,97, y=70,00, z=222,97], EntityPainting['Painting'/68, l='MpServer', x=81,06, y=26,00, z=327,00], EntityBat['Bat'/240, l='MpServer', x=211,25, y=22,10, z=280,75]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:440)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2312)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:863)
	at net.minecraft.client.main.Main.main(SourceFile:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

-- System Details --
Details:
	Minecraft Version: 1.6.4
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_55, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1379222072 bytes (1315 MB) / 1995964416 bytes (1903 MB) up to 1995964416 bytes (1903 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048M -Xms2048M
	AABB Pool Size: 11479 (642824 bytes; 0 MB) allocated, 1396 (78176 bytes; 0 MB) used
	Suspicious classes: FML and Forge are installed
	IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 63
	FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 25 mods loaded, 25 mods active
	mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{6.4.49.965} [Forge Mod Loader] (minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{9.11.1.965} [Minecraft Forge] (minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AM2-Preloader{0.0.1} [AMCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{0.9.0.9} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.6.1.9} [Not Enough Items] (NotEnoughItems-1.6.4-1.6.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DamageIndicatorsMod{2.9.2.4} [Damage Indicators] (1.6.4 DamageIndicatorsv2.9.2.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FLabsBF{4.0} [BetterFurnaces] ([1.6.4]BetterFurnacesV4.0.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bspkrsCore{v5.3(1.6.4)} [bspkrsCore] ([1.6.4]bspkrsCorev5.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TreeCapitator{Forge 1.6.4.r09} [Treecapitator] ([1.6.4]TreeCapitator.Forge.1.6.4.r09.Universal.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AnimationAPI{1.1.1} [AnimationAPI] (AnimationAPI v1.1.2 mc1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	arsmagica2{1.2.0.019} [Ars Magica 2] (AM2_1.2.0.019.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Backpack{1.28.37} [Backpack] (backpack-1.28.37-1.6.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BetterDungeons{2.4} [Chocolate quest] (BetterDungeons2091.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ChickenChunks{1.3.3.4} [ChickenChunks] (ChickenChunks-1.6.4-1.3.3.4-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DungeonPack{1.6.4} [DungeonPack] (DungeonPack 1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	eplus{1.16.5b} [Enchanting Plus] (EnchantingPlus-1.16.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	inventorytweaks{1.56} [Inventory Tweaks] (InventoryTweaks-MC1.6.2-1.56-b77.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MapWriter{2.0} [MapWriter] (mapwriter-1.6.4-2.0.17.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AS_Minions{1.7.9b} [Minions] (Minions_1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MoreSwordsMod{2.6.0} [More Swords Mod] (More Swords Mod 2.6.0 For 1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	PetBat{1.2.5} [Pet Bat] (Pet-Bat-Mod-1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AS_Ruins{11.0} [Ruins Spawning System] (Ruins_1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SS2{2 (build 2)} [Soul Shards 2] (SoulShards-2.0.15-universal-srg.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AS_UpdateCheck{1.1.1} [AtomicStryker Update Check Mod] (UpdateCheckerMod_1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Launched Version: 1.6.4-Forge9.11.1.965
	LWJGL: 2.9.0
	OpenGL: AMD Radeon HD 6670 GL version 4.2.12422 Compatibility Profile Context 13.152.0.0, ATI Technologies Inc.
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Pack: Default
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 2076 (116256 bytes; 0 MB) allocated, 334 (18704 bytes; 0 MB) used

**Comment by Mithion** [comment]
I had a real hard time replicating this one, but I believe I have this fixed in 1.4.0.007 (dev).
