### ISSUE TITLE
(1.2.0.021) (Minor) Still getting Compendium unlock every pickup

### ISSUE THREAD

**Issue by Reidlos65** [Mithion/ArsMagica2#788]
I still start the game load into the MP server and pick up a AM2 item and get the Unlocked a compendium multiple times, I currently have it on fully show in the config as well.  Is there a way to kinda reset this or fix it or is this still a bug?

**Comment by Mithion** [comment]
Based on the severity of the issue, this won't be fixed in the final update - in looking at the code it shouldn't be happening, but I don't have the time to delve into it.
