### ISSUE TITLE
[1.2.0.017] Casting Divine Intervention In the Nether Crashes my single player game

### ISSUE THREAD

**Issue by Mythofreak** [Mithion/ArsMagica2#798]
This crash occurs most times that i use divine intervention to leave the nether. I do not know if this affects the issue but I also run mystcraft and I also crash when I use divine intervention to leave those worlds. The Full Crash File Follows
========================================================================
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 7/27/14 5:25 PM
Description: Unexpected error

java.lang.RuntimeException: Already decorating!!
	at net.minecraft.world.biome.BiomeDecorator.func_76796_a(BiomeDecorator.java:188)
	at net.minecraft.world.biome.BiomeGenBase.func_76728_a(BiomeGenBase.java:371)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:573)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:258)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1253)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:153)
	at net.minecraft.server.management.PlayerInstance.<init>(PlayerInstance.java:43)
	at net.minecraft.server.management.PlayerManager.func_72690_a(SourceFile:208)
	at net.minecraft.server.management.PlayerManager.func_72683_a(SourceFile:240)
	at net.minecraft.server.management.ServerConfigurationManager.func_72375_a(ServerConfigurationManager.java:220)
	at net.minecraft.server.management.ServerConfigurationManager.transferPlayerToDimension(ServerConfigurationManager.java:489)
	at am2.utility.DimensionUtilities.doDimensionTransfer(DimensionUtilities.java:21)
	at am2.proxy.tick.ClientTickHandler.applyDeferredDimensionTransfers(ClientTickHandler.java:115)
	at am2.proxy.tick.ClientTickHandler.gameTick_End(ClientTickHandler.java:129)
	at am2.proxy.tick.ClientTickHandler.tickEnd(ClientTickHandler.java:321)
	at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
	at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:141)
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:367)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1970)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
	at net.minecraft.client.main.Main.main(SourceFile:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.biome.BiomeDecorator.func_76796_a(BiomeDecorator.java:188)
	at net.minecraft.world.biome.BiomeGenBase.func_76728_a(BiomeGenBase.java:371)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:573)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:258)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1253)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:153)
	at net.minecraft.server.management.PlayerInstance.<init>(PlayerInstance.java:43)
	at net.minecraft.server.management.PlayerManager.func_72690_a(SourceFile:208)
	at net.minecraft.server.management.PlayerManager.func_72683_a(SourceFile:240)
	at net.minecraft.server.management.ServerConfigurationManager.func_72375_a(ServerConfigurationManager.java:220)
	at net.minecraft.server.management.ServerConfigurationManager.transferPlayerToDimension(ServerConfigurationManager.java:489)
	at am2.utility.DimensionUtilities.doDimensionTransfer(DimensionUtilities.java:21)
	at am2.proxy.tick.ClientTickHandler.applyDeferredDimensionTransfers(ClientTickHandler.java:115)
	at am2.proxy.tick.ClientTickHandler.gameTick_End(ClientTickHandler.java:129)
	at am2.proxy.tick.ClientTickHandler.tickEnd(ClientTickHandler.java:321)
	at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
	at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:141)
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:367)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Mythofreak'/229, l='MpServer', x=-348.13, y=58.62, z=-14.14]]
	Chunk stats: MultiplayerChunkCache: 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 6722698 game time, 9434603 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 70 total; [EntityDarkling['Darkling'/773499, l='MpServer', x=-325.25, y=63.00, z=14.50], EntityHecate['Hecate'/773711, l='MpServer', x=-301.50, y=79.00, z=-17.50], EntityPigZombie['Zombie Pigman'/773502, l='MpServer', x=-331.38, y=66.00, z=5.70], EntityFireElemental['Fire Elemental'/773501, l='MpServer', x=-315.41, y=62.00, z=11.13], EntityPigZombie['Zombie Pigman'/777139, l='MpServer', x=-326.50, y=32.00, z=-3.50], EntityPigZombie['Zombie Pigman'/777138, l='MpServer', x=-327.44, y=32.00, z=10.06], EntityPigZombie['Zombie Pigman'/777137, l='MpServer', x=-316.77, y=58.00, z=-26.60], EntityFireBat['Firebat'/777136, l='MpServer', x=-396.38, y=90.97, z=16.23], EntityXPOrb['Experience Orb'/772527, l='MpServer', x=-342.25, y=77.25, z=-53.75], EntityXPOrb['Experience Orb'/772526, l='MpServer', x=-340.31, y=77.25, z=-51.63], EntityXPOrb['Experience Orb'/772525, l='MpServer', x=-342.81, y=76.25, z=-51.41], EntityFireBat['Firebat'/775911, l='MpServer', x=-314.83, y=36.74, z=-36.41], EntityHecate['Hecate'/777134, l='MpServer', x=-405.38, y=91.00, z=7.38], EntityFireBat['Firebat'/777135, l='MpServer', x=-397.64, y=89.06, z=32.70], EntityMagmaCube['Magma Cube'/775905, l='MpServer', x=-316.69, y=17.00, z=7.63], EntityHecate['Hecate'/777133, l='MpServer', x=-408.28, y=90.00, z=9.34], EntityHecate['Hecate'/775907, l='MpServer', x=-377.50, y=62.00, z=-48.50], EntityFlicker['Flicker'/772872, l='MpServer', x=-291.75, y=97.50, z=-38.53], EntityMagmaCube['Magma Cube'/776761, l='MpServer', x=-339.50, y=32.00, z=-63.53], EntityMagmaCube['Magma Cube'/776762, l='MpServer', x=-336.63, y=33.00, z=-63.56], EntityPigZombie['Zombie Pigman'/776764, l='MpServer', x=-335.50, y=33.00, z=-71.50], EntityFireBat['Firebat'/775912, l='MpServer', x=-317.99, y=33.00, z=-15.34], EntityPigZombie['Zombie Pigman'/776765, l='MpServer', x=-336.31, y=32.00, z=-72.38], EntityFireBat['Firebat'/775913, l='MpServer', x=-313.41, y=36.62, z=-39.57], EntityFlicker['Flicker'/775779, l='MpServer', x=-305.03, y=36.20, z=-47.23], EntityHecate['Hecate'/773712, l='MpServer', x=-297.50, y=79.00, z=-15.50], EntityFireElemental['Fire Elemental'/776132, l='MpServer', x=-397.50, y=80.00, z=-31.50], EntityFlicker['Flicker'/775772, l='MpServer', x=-383.56, y=66.50, z=-18.38], EntityBlaze['Blaze'/774013, l='MpServer', x=-28.79, y=-6.62, z=-24.66], EntityClientPlayerMP['Mythofreak'/229, l='MpServer', x=-348.13, y=58.62, z=-14.14], EntityPigZombie['Zombie Pigman'/777322, l='MpServer', x=-372.69, y=55.00, z=30.22], EntityFlicker['Flicker'/775773, l='MpServer', x=-385.22, y=66.50, z=-18.66], EntityWisp['Wisp'/776131, l='MpServer', x=-395.50, y=80.00, z=-25.50], EntityBlaze['Blaze'/775522, l='MpServer', x=-41.67, y=-5.81, z=-26.33], EntityFlicker['Flicker'/775765, l='MpServer', x=-395.50, y=65.50, z=-33.50], EntityPigZombie['Zombie Pigman'/776136, l='MpServer', x=-362.75, y=60.00, z=21.41], EntityPigZombie['Zombie Pigman'/776137, l='MpServer', x=-363.84, y=60.00, z=17.38], EntityPigZombie['Zombie Pigman'/776138, l='MpServer', x=-368.06, y=61.00, z=20.22], EntityFireBat['Firebat'/776139, l='MpServer', x=-352.41, y=66.46, z=21.10], EntityItem['item.tile.hellrock'/776858, l='MpServer', x=-313.63, y=74.13, z=-49.22], EntityFlicker['Flicker'/773568, l='MpServer', x=-314.67, y=65.81, z=10.93], EntityXPOrb['Experience Orb'/772899, l='MpServer', x=-297.47, y=78.25, z=82.19], EntityXPOrb['Experience Orb'/769686, l='MpServer', x=-315.06, y=76.25, z=57.81], EntityItem['item.tile.hellrock'/776862, l='MpServer', x=-313.22, y=73.13, z=-50.81], EntityFlicker['Flicker'/774127, l='MpServer', x=-293.50, y=96.50, z=-62.29], EntityPigZombie['Zombie Pigman'/776398, l='MpServer', x=-312.50, y=39.00, z=-92.50], EntityFireBat['Firebat'/777619, l='MpServer', x=-371.75, y=77.42, z=6.09], EntityXPOrb['Experience Orb'/777224, l='MpServer', x=-355.72, y=47.25, z=-15.72], EntityPigZombie['Zombie Pigman'/774355, l='MpServer', x=-277.09, y=78.06, z=-88.69], EntityFireElemental['Fire Elemental'/774353, l='MpServer', x=-298.50, y=65.00, z=20.50], EntityPigZombie['Zombie Pigman'/774044, l='MpServer', x=-286.50, y=90.00, z=44.53], EntityFlicker['Flicker'/776820, l='MpServer', x=-407.75, y=67.00, z=-50.63], EntityHecate['Hecate'/775572, l='MpServer', x=-326.53, y=77.00, z=-60.69], EntityXPOrb['Experience Orb'/770421, l='MpServer', x=-296.25, y=80.25, z=78.66], EntityHecate['Hecate'/775571, l='MpServer', x=-336.44, y=79.00, z=-77.06], EntityFireElemental['Fire Elemental'/773891, l='MpServer', x=-307.50, y=67.00, z=2.50], EntityFlicker['Flicker'/776824, l='MpServer', x=-406.78, y=68.88, z=-39.19], EntityPigZombie['Zombie Pigman'/776125, l='MpServer', x=-311.59, y=16.00, z=8.72], EntityFlicker['Flicker'/773793, l='MpServer', x=-299.03, y=77.57, z=6.02], EntityPigZombie['Zombie Pigman'/776430, l='MpServer', x=-347.50, y=61.00, z=18.50], EntityFlicker['Flicker'/776782, l='MpServer', x=-293.50, y=43.91, z=-39.41], EntityFireBat['Firebat'/772289, l='MpServer', x=-300.26, y=57.91, z=-27.74], EntityFlicker['Flicker'/774991, l='MpServer', x=-317.45, y=64.82, z=-13.34], EntityFireBat['Firebat'/776419, l='MpServer', x=-392.30, y=63.43, z=-17.00], EntityFireBat['Firebat'/776420, l='MpServer', x=-400.33, y=67.83, z=-62.93], EntityFireBat['Firebat'/776421, l='MpServer', x=-373.94, y=64.68, z=-25.65], EntityFireBat['Firebat'/776422, l='MpServer', x=-387.21, y=64.08, z=-32.91], EntityFireElemental['Fire Elemental'/773693, l='MpServer', x=-330.34, y=32.00, z=-13.19], EntityPigZombie['Zombie Pigman'/773692, l='MpServer', x=-323.50, y=62.00, z=33.50], EntityFireElemental['Fire Elemental'/773694, l='MpServer', x=-328.50, y=32.00, z=-8.16]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:440)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2312)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:863)
	at net.minecraft.client.main.Main.main(SourceFile:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

-- System Details --
Details:
	Minecraft Version: 1.6.4
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.7.0_65, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 508581208 bytes (485 MB) / 1007362048 bytes (960 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1024M
	AABB Pool Size: 7147 (400232 bytes; 0 MB) allocated, 862 (48272 bytes; 0 MB) used
	Suspicious classes: FML and Forge are installed
	IntCache: cache: 0, tcache: 34, allocated: 3, tallocated: 63
	FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 30 mods loaded, 30 mods active
	mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{6.4.49.965} [Forge Mod Loader] (minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{9.11.1.965} [Minecraft Forge] (minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AM2-Preloader{0.0.1} [AMCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{0.9.0.7} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.6.1.8} [Not Enough Items] (NotEnoughItems 1.6.1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DamageIndicatorsMod{2.9.2.3} [Damage Indicators] (1.6.4 DamageIndicatorsv2.9.2.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ChickenShed{1.1.2} [Chicken Shed] ([1.5+] ChickenShed (v1.1.2).zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DustModCore{v2.0} [Runic Dust Mod-Core] ([1.6.4] Runic Dust Mod Core v2.0.0a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DustDeco{v2.0} [Runic Dust Mod- Decorative Runes] ([1.6.4] Runic Dust Mod Decor Runes v2.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DustDefaults{v2.0} [Runic Dust Mod- Default Runes] ([1.6.4] Runic Dust Mod Default Runes v2.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Thaumcraft{4.1.0g} [Thaumcraft] (Thaumcraft4.1.0g.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DustThaum{v2.0} [Runic Dust Mod- Thaumcraft Addon] ([1.6.4] Runic Dust Mod ThaumRunes v2.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mod_ReiMinimap{v3.4_01 [1.6.2]} [mod_ReiMinimap] ([1.6.4]ReiMinimap_v3.4_01.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AnimationAPI{1.1.1} [AnimationAPI] (AnimationAPI v1.1.2 mc1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	arsmagica2{1.2.0.017} [Ars Magica 2] (AM2_1.2.0.017.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Autoutils{1.0.1} [Autoutils] (autoutils-1.6.4-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioCraft{1.5.4} [BiblioCraft] (BiblioCraft[v1.5.4].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AWWayofTime{v1.0.1g} [Blood Magic: Alchemical Wizardry] (Blood Magic v1.0.1g.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Chisel{1.5.0} [Chisel] (chisel-1.6.4-1.5.0fix.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThaumicTinkerer{2.3-140} [Thaumic Tinkerer] (ThaumicTinkerer-2.3-140.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForbiddenMagic{0.34} [Forbidden Magic] (ForbiddenMagic pr0.34.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	iChunUtil{2.4.0} [iChunUtil] (iChunUtil2.4.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Taigore_InventorySaver{3.3} [Inventory Saver] (InventorySaver_-_v3.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	inventorytweaks{1.56} [Inventory Tweaks] (InventoryTweaks-MC1.6.2-1.56-b77.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mystcraft{0.10.12.01} [Mystcraft] (mystcraft-uni-1.6.4-0.10.12.01.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NEIPlugins{1.1.0.6} [NEI Plugins] (NEIPlugins-1.1.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	witchery{0.14.0} [Witchery] (Witchery_0-14-0_164.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MSC{1.6.4.0} [Mob Spawn Controls] (MSC1v1.6.4.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThaumcraftMobAspects{1.6.X-1d} [Thaumcraft Mob Aspects] (thaumcraftmobaspects-1.6.X-1e-build2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Launched Version: 1.6.4-Forge9.11.1.965
	LWJGL: 2.9.0
	OpenGL: GeForce 310M/PCI/SSE2 GL version 3.3.0, NVIDIA Corporation
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Pack: Default
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 1773 (99288 bytes; 0 MB) allocated, 189 (10584 bytes; 0 MB) used

**Comment by Mithion** [comment]
To the best of my knowledge (ie 100+ dimension hops without an issue), this has been resolved in 1.4.0.007 (dev).
