### ISSUE TITLE
[1.2.0.022] Possible Clash With Optifine

### ISSUE THREAD

**Issue by irkedIsaac** [Mithion/ArsMagica2#805]
System info:
- Processor: Intel(R) Core(TM) i3-2130 CPU @ 3.40 GHz 3.40 GHz
- Installed Memory (RAM): 4.00 GB (3.89 GB usable)
- System type: 64-bit Operating System, x64-based processor

Issue info:
- When the Yogscast Complete Pack updated, I was forced to remove Optifine from my pack because the game refused to complete loading. I went through and tested by removing individual mods and it wasn't until I removed Ars Magica 2 (1.2.0.022) and the Animation API (1.1.2) that the game was allowed to load with Optifine. I tried installing the patch mentioned in the Ars Magica 2 thread, but the result was very much the same. My assumption is that this isn't an actual issue with Ars Magica 2, but probably with Animation API. However, as thehippomaster21 doesn't seem to have a bug tracker, I figured posting this here would likely be the next best thing.

Very sorry if this was the wrong place to put this, but as I can't deal with having the 3 FPS I get without Optifine, I needed to say it somewhere.

**Comment by AnkokuTeion** [comment]
im getting this exact issue in 1.7.10, I've tried patching optifine with the 1.6.4 patch but it isn't working. anyone know if there's a 1.7.10 version of it?

otherwise is there another way to fix it?

**Comment by jawdylawdy** [comment]
You don't need to patch Optifine in .008. Ars Magica will automatically detect Optifine if it's in the mods folder and adjust accordingly.

**Comment by nekoexmachina** [comment]
Why does ArsMagica detect the actual jar file instead of looking into list of loaded mods?

**Comment by bookerthegeek** [comment]
Why would it be loaded but not have an actual jar?

**Comment by nekoexmachina** [comment]
>Why would it be loaded but not have an actual jar?

Because I have mods in mods/1.7.10/<folderStructure>, and arsmagica does not detect it?
