### ISSUE TITLE
[1.2.0.22] - Magician's Workbench duplicates IC2 tools

### ISSUE THREAD

**Issue by TieSKey** [Mithion/ArsMagica2#820]
How to duplicate:
Use a recipe that requires a tool, like:
iron ingot + hammer (IC2)

Expected:  iron plate + hammer (with less durability)

Actual result:
iron plate + hammer not being damaged + a duplicate dropping to the floor.

It happens with gregtech tools too and I suspect any other one.
On multiplayer (didn't try in sp). Mod version 1.2.0.22 (it worked on 1.1.2b)

Log:
https://www.dropbox.com/s/9qkhocu2e9uegv5/ForgeModLoader-client-0.log

Offtopic:
Just my opinion but plz, consider focusing on the ars magica original and unique features like spell crafting, summoning, talent trees, etc. instead of adding yet another generic automation system. The flyckers thing seems interesting but most of us play with several mods at the same time and a lot of them add automation systems.

**Comment by Mithion** [comment]
This has been corrected in 1.4.0.007 (dev).
