### ISSUE TITLE
[1.2.0.022] Ritual of Recall to Gateway Crash

### ISSUE THREAD

**Issue by jawdylawdy** [Mithion/ArsMagica2#837]
I figured I should post this on the bug tracker so it's assuredly on your to-do list, but as you know from earlier today, when you attempt to perform the ritual of recall to gateway and you use a keystone code that is not valid, it crashes servers completely. Yay for bugs!

**Comment by Mithion** [comment]
this has been corrected in 1.4.0.007 (dev)
