### ISSUE TITLE
GUI: Spellbook Position

### ISSUE THREAD

**Issue by LazerusKI** [Mithion/ArsMagica2#844]
Just looked thorough the AM2.cfg GUI section, and noticed, that there is no line to change to position of your spellbook.
Also with amuicfg it was not possible in the 1.1 versions.
Since the position overlaps with some other mods, it would be nice if you could implement a function for that piece of your GUI.

**Comment by Mithion** [comment]
This has been added in 1.4.0.007 (dev).
