### ISSUE TITLE
[1.2.0.022] Summon spells - Exploded Creepers continue to count towards Summon cap.

### ISSUE THREAD

**Issue by Pureblade** [Mithion/ArsMagica2#854]
I had searched for this issue on the tracker and could not find any existing issues, apologies in advance if this issue has already been reported.

Summoning a Creeper and allowing it to explode will continue the creeper to count towards the maximum summons cap.

Reproduction steps (This assumes creative mode with Extra Summon talent):

1. Create a Projectile > Summon spell recipe in an Inscription Table.

2. Create the Projectile > Summon (Creeper) spell in the crafting altar.

3. Cast the spell on or near a hostile mob and let the Creeper explode.

4. Perform step 3 an additional two times. The third time you attempt to summon the Creeper the chat should say "You cannot have any more summons."

The same issue occurs with summoning Nitro Creepers, leading me to believe that the creeper exploding is not considered as the summoned creeper not being alive by Ars Magica 2.
The issue persists until the world is exited and loaded again.

This issue occurred while playing Single Player, I would assume the same issue occurs in Multiplayer.

Log File:
http://www.mediafire.com/?xcc9eek47qsas41

**Comment by Mithion** [comment]
This has been corrected in 1.4.0.007 (dev).
