### ISSUE TITLE
Ender Boots - Feature Requests

### ISSUE THREAD

**Issue by LazerusKI** [Mithion/ArsMagica2#883]
Based on this one here
https://github.com/Mithion/ArsMagica2/issues/879
I noticed a few more "missing" features.

- Very important: Sneak-Walking. Currently if you sneak you stop completely...and yeah...falling into the sky hurts, and when you have speed enchantments it happens a lot...
- Step Upside Down Stairs like normal Stairs
- Support for the Lightning Affinity or Boot Imbuements Step Assist
- Climbing Ladders upside down

also i noticed that you can sometimes fall through the "floor" but i think thats a problem with the Tinkers Construct hammer phantom-block bug, so nothing of interest.

**Comment by Mithion** [comment]
Due to the end of the mod's development, this won't be added.
