### ISSUE TITLE
Altar - Essence Problem

### ISSUE THREAD

**Issue by LazerusKI** [Mithion/ArsMagica2#888]
After a while i have just noticed what is causing the problems with the spell creations.
Description:
When creating a spell that need Essence, after pulling the lever, the altar wont accept the next show item.
When you look into the book, you will notice, that the Altar has skipped or switched the item after the Essence. so you need to look into the book manually to find out what to throw in next.
ALSO: it seems like this bug breaks the spell.
I jsut created a spell with 3 different shapes.
Projectile
Projectile Chain
Projectile Wave AoE
after crafting it in the altar, only the first normal projectile worked.
Cheating the same spell in worked without problems

**Comment by Mithion** [comment]
Corrected in 1.4.0.007 (dev)
