### ISSUE TITLE
[1.3.0.008] API conflicts

### ISSUE THREAD

**Issue by Malexion** [Mithion/ArsMagica2#889]
Just going to use this as an area for the current API conflicts I've run into, granted there are other issues in the logs posted.

So far:

- Can't register power types, crashes during startup, tried all phases pre, init, and post. Looks like a format exception?
  - Search for:
[18:15:36] [Client thread/ERROR] [FML]: Fatal errors were detected during the transition from POSTINITIALIZATION to AVAILABLE. Loading cannot continue
  - Snapshot of Code: http://pastebin.com/mquYZ6HA // Called in post
  - Console Log: http://pastebin.com/XBjY4SDg

**Comment by Mithion** [comment]
This has been fixed in 1.4.0.007 (dev).
