### ISSUE TITLE
[1.2.22] AOE not properly applying modifiers

### ISSUE THREAD

**Issue by elementalistic** [Mithion/ArsMagica2#891]
I'm using a quarry spell,
Project->Zone->Duration->Gravity (orange box)
AOE->Radius->Radius->Radius->Dig->Mining Power->Feather Touch (grey box)

And the dig will only have mining power applied to it.  I can remove all other modifiers but gravity and feather touch, and it still won't apply feather touch.  Same for Prosperity.  

Even a simple 
Orange; Projectile
Grey: Aoe->Dig->Feather Touch

Bugs out and doesn't apply feather touch

**Comment by EoD** [comment]
Sounds very much like bug #934 . You should try pressing the "C" key to change the cast mode.

**Comment by Mithion** [comment]
This has been corrected in 1.4.0.007 (dev).
