### ISSUE TITLE
[1.0.2.022] - Crafting altar explodes when loading during spell creation

### ISSUE THREAD

**Issue by fablichod** [Mithion/ArsMagica2#894]
Logging out while in the process of making some spells causes the crafting altar to explode when logging back in.

Details: Altar made of quartz and sunstone, should accept up to 13 shapes. Spell attempted was touch, dig, feather touch, mining power. Was throwing all the bits in up until I needed Earth essence. Went to storage, couldn't find any, logged out to take a break. Heard explosion when I logged back in, found crater where crafting altar used to be.

Made a test world in creative mode, built another quartz and sunstone altar, tried building the same spell, logged back out at the same point in the process, and the altar immediately exploded when logging back in.

Tested again with just touch dig and projectile light, no problems. Tested again with the same spell, logging out earlier in the process does not cause problems, but again got an explosion before earth essence. My understanding of the altar explosion mechanics lead me to believe that nothing about this particular spell should cause an explosion with my setup, unless there is something else besides number of components to a spell that causes it.

**Comment by Mithion** [comment]
This has been corrected in 1.4.0.007 (dev).  Thanks for the detailed reproduce explanation!
