### ISSUE TITLE
Issues when used with Morph

### ISSUE THREAD

**Issue by zloebl777** [Mithion/ArsMagica2#927]
When AM2 and Morph are installed together, there is an issue with player modeling and the player hitbox.  When Morphed into a form of a different size than the player form, the game still sees you as being two blocks tall.  This means that smaller forms (like bats) can fit into one block spaces, but will take suffocation damage.  This also means that the game thinks the player is looking somewhere they are not because it is assuming the player is two blocks tall.

This bug can be replicated with just AM2, iChunUtil, and Morph present in a world.  Removing AM2 fixes the issue with Morph.

This is reported on iChun's bug tracker here: https://github.com/iChun/Morph/issues/618

**Comment by Mithion** [comment]
The shrink spell now properly tracks your height in 1.4.0.007 (dev).
As a workaround (or if for some reason it still doesn't work), disabling the shrink spell via config will also prevent AM2's size modifying code from running.
