### ISSUE TITLE
Item duplication with Flicker Transport system

### ISSUE THREAD

**Issue by magius96** [Mithion/ArsMagica2#931]
Set an item transport habitat and 3 chests.  Put an import crystal on chest A.  Put both an Import and an export crystal on chest B.  Put an export clone or a set export crystal on chest C. (May also work with a regular export crystal)  If you use a set export crystal, set the crystal to the item you are duplicating.  Put 1 of the item into chest C.  Put a full stack of the item into chest A.

Doing this will duplicate at least half a stack of the item.  Putting more of the item into chest C, but with each item in it's own non-stacked square, can cause more to be duplicated at once.  Does not seem to duplicate with less than a full stack placed into chest A, or if you don't put single item stacks in chest C.

-------EDIT--------
One of my server members advises me that it's not chest B that's causing the issue.  Apparently he was able to reproduce the bug without chest B by adding stack size upgrades to the transfer.

**Comment by Mithion** [comment]
This has been fixed in 1.4.0.007 (dev).
