### ISSUE TITLE
Summon Spell Crash

### ISSUE THREAD

**Issue by Iivaitte** [Mithion/ArsMagica2#946]
Summoning any mobs causes crash 

List of mods installed - Forge 7.10.25.1208

Battlehear2 1.0.5.6
Advanced Genetics 1.5.7
Bibliocraft 1.7.5
Bibliowoods 1.7
BOP 2.1.0.943
buildcraft 6.0.17
chickencodecore 1.0.2.9
flintlock guns mod 1.7pre1
Galacticraft 1.7.3
growthcraft 2.1.0
industrialcraft 2.2.2.636
NEI 1.0.215
PamsHarvestcraft 1.7.10a
Tconstruct 1.7.0d4
Thaumcraft 4.2.0.0
Twilight Forest 2.3.2
universal electricty 4.0.0.50
Witchery 0.20.0

**Comment by vaIgarashi** [comment]
Got this exception in multiplayer with 009 version.
