### ISSUE TITLE
Experience Infusion bug

### ISSUE THREAD

**Issue by the-creamster** [Mithion/ArsMagica2#960]
Personally i've collected like 600+ levels in the past week that i've been playing on server and been progressing through magic levels(currently magic level 15), but haven't got a single experience point towards any single piece of armour i'm wearing for armour imbuement.

Also if u have morph on server/client the hitboxes are "offcenter", such that as a bat you should be 1 block high, but are actually 1.5 and to interact with a block/chest/machine in front of you; you need to aim the cursor below what you want to interact with. The same goes for each other non-player morph with varying degrees of aim adjustment and hitbox, as far as i've been told because of the "Shrink" spell effect and how it coded.

**Comment by Mithion** [comment]
This has been corrected in 1.4.0.007 (dev).
