### ISSUE TITLE
[BUG]About Blue Topaz recipes

### ISSUE THREAD

**Issue by shotoku** [Mithion/ArsMagica2#972]
If AM2 works with Greg's Tech, Blue Topaz from the Blue Topaz Ore will be transfered into Blue Topaz in GT's due to The Ore Dictionary in Forge Mod Loader,and cannot be used to recipe things in AM2 such as Occulus.Adding a new recipe may solve the problem,,I think

**Comment by Mithion** [comment]
All block/item crafting recipes have been re-tooled to use the ore dictionary entries.  Included are:
Vinteum Dust
Arcane Ash
Chimerite
Blue Topaz
Moonstone
Sunstone
