### ISSUE TITLE
Flicker transport network does not respect NBT values on stackable items

### ISSUE THREAD

**Issue by justicesays** [Mithion/ArsMagica2#984]
Using the .006 version, 
Item transport "set export" and "regulate export" flicker crystal cannot distinguish between items that are the same but with different NBT values, such as Thaumcraft Mana Beans or Essentia Vials. 
This isnt too bad if you want a somewhat indiscriminate item sorting system, but it also doesn't respect it when placing items into the target containers. Stackable items with differing NBT values will be added to the first available stack of the same base item , increasing that item type only, rather than starting a new stack or waiting until space is available.

Steps to reproduce
Item transport flicker focus, flicker habitat
chest with different stackable NBT value items (like mana beans) , less than a stack each.
one import crystal, one export crystal
one target chest
Connect up all the crystals and the target chest should only fill with one of the item types until the stack is complete.
To test the filtering bug, the same test but with a set export crystal on the target check and only one item type in the filer box will transport both item types, as well as merging the stacks as above.

**Comment by Mithion** [comment]
I have corrected this in 1.4.0.007 (dev).
