### ISSUE TITLE
Crash when attempting to view Vinteum Ore entry in Arcane Compendium

### ISSUE THREAD

**Issue by stephanstross** [Mithion/ArsMagica2#985]
When I attempt to view the vinteum ore entry, I get an IllegalStateException from the tesselator, saying that it's already tesselating. I'm not sure if it's the modpack, but the stacktrace appears to only go through native minecraft code and am2 libraries. The complete log is in the link below.
[https://www.dropbox.com/s/p2a9qd1s2q91211/fml-client-latest.log?dl=0](https://www.dropbox.com/s/p2a9qd1s2q91211/fml-client-latest.log?dl=0)

**Comment by Mithion** [comment]
This has been corrected in 1.4.0.007 (dev).
