### ISSUE TITLE
Crash when Ender Guardian is in the Void

### ISSUE THREAD

**Issue by Durpady** [Mithion/ArsMagica2#986]
Title explains most of it.  I was in Creative, and pushed it off the edge (since there were nothing but Endermen around, it didn't bother using an attack to jump back up).  I followed it down, expecting it to start taking Void damage, but right as (I expect) it was supposed to start taking damage... boom.

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 1/2/15 12:30 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at am2.proxy.CommonProxy.addDeferredTargetSet(CommonProxy.java:367)
	at am2.bosses.EntityEnderGuardian.func_70097_a(EntityEnderGuardian.java:149)
	at net.minecraft.entity.EntityLivingBase.func_70076_C(EntityLivingBase.java:1226)
	at net.minecraft.entity.Entity.func_70030_z(Entity.java:439)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:193)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:157)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:318)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1559)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
	at am2.bosses.AM2Boss.func_70071_h_(AM2Boss.java:161)
	at am2.bosses.EntityEnderGuardian.func_70071_h_(EntityEnderGuardian.java:85)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1995)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at am2.proxy.CommonProxy.addDeferredTargetSet(CommonProxy.java:367)
	at am2.bosses.EntityEnderGuardian.func_70097_a(EntityEnderGuardian.java:149)
	at net.minecraft.entity.EntityLivingBase.func_70076_C(EntityLivingBase.java:1226)
	at net.minecraft.entity.Entity.func_70030_z(Entity.java:439)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:193)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:157)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:318)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1559)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
	at am2.bosses.AM2Boss.func_70071_h_(AM2Boss.java:161)
	at am2.bosses.EntityEnderGuardian.func_70071_h_(EntityEnderGuardian.java:85)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: arsmagica2.BossEnderGuardian (am2.bosses.EntityEnderGuardian)
	Entity ID: 168623
	Entity Name: Ender Guardian
	Entity's Exact location: 45.09, 58.00, 50.88
	Entity's Block location: World: (45,58,50), Chunk: (at 13,3,2 in 2,3; contains blocks 32,0,48 to 47,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.29, 0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Minipete'/84, l='MpServer', x=51.85, y=-41.67, z=52.36]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 954555 game time, 954555 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 56 total; [EntityEnderGuardian['Ender Guardian'/168623, l='MpServer', x=45.09, y=58.00, z=50.88], EntityEnderman['Enderman'/178496, l='MpServer', x=22.03, y=61.00, z=16.63], EntityEnderman['Enderman'/174462, l='MpServer', x=77.44, y=57.00, z=-13.78], EntityEnderman['Enderman'/168625, l='MpServer', x=42.63, y=47.00, z=49.16], EntityItem['item.item.enderPearl'/168624, l='MpServer', x=35.16, y=60.13, z=59.22], EntityEnderman['Enderman'/168626, l='MpServer', x=55.69, y=46.00, z=59.78], EntityEnderman['Enderman'/178536, l='MpServer', x=51.66, y=47.00, z=66.16], EntityEnderCrystal['entity.EnderCrystal.name'/156683, l='MpServer', x=99.50, y=66.00, z=14.50], EntityEnderman['Enderman'/178431, l='MpServer', x=5.75, y=59.00, z=88.16], EntityEnderman['Enderman'/178430, l='MpServer', x=5.13, y=59.00, z=93.13], EntityEnderman['Enderman'/178428, l='MpServer', x=-1.47, y=59.00, z=85.66], EntityEnderman['Enderman'/178427, l='MpServer', x=-0.38, y=59.00, z=85.44], EntityEnderman['Enderman'/168479, l='MpServer', x=36.56, y=35.00, z=10.13], EntityEnderman['Enderman'/168553, l='MpServer', x=32.63, y=60.00, z=71.69], EntityEnderman['Enderman'/168552, l='MpServer', x=32.06, y=60.00, z=70.91], EntityEnderman['Enderman'/168555, l='MpServer', x=23.38, y=60.00, z=81.94], EntityEnderman['Enderman'/168554, l='MpServer', x=41.72, y=60.00, z=63.50], EntityEnderman['Enderman'/178566, l='MpServer', x=54.31, y=42.33, z=81.71], EntityEnderman['Enderman'/178567, l='MpServer', x=51.56, y=43.02, z=77.97], EntityEnderman['Enderman'/178565, l='MpServer', x=53.32, y=42.62, z=78.44], EntityEnderman['Enderman'/178435, l='MpServer', x=-1.75, y=59.00, z=91.50], EntityEnderman['Enderman'/178434, l='MpServer', x=0.54, y=60.00, z=84.77], EntityEnderman['Enderman'/168544, l='MpServer', x=57.84, y=37.00, z=76.28], EntityEnderman['Enderman'/178568, l='MpServer', x=53.50, y=42.00, z=79.50], EntityEnderman['Enderman'/178433, l='MpServer', x=-2.53, y=59.00, z=90.31], EntityEnderman['Enderman'/168547, l='MpServer', x=28.63, y=60.00, z=65.23], EntityEnderman['Enderman'/178432, l='MpServer', x=8.50, y=59.00, z=91.72], EntityEnderman['Enderman'/168549, l='MpServer', x=21.47, y=60.00, z=81.13], EntityEnderman['Enderman'/168548, l='MpServer', x=39.88, y=60.00, z=75.88], EntityEnderman['Enderman'/168551, l='MpServer', x=15.13, y=61.00, z=68.66], EntityEnderman['Enderman'/178436, l='MpServer', x=1.34, y=59.00, z=91.53], EntityEnderman['Enderman'/178582, l='MpServer', x=4.50, y=60.00, z=79.50], EntityEnderman['Enderman'/178581, l='MpServer', x=0.50, y=60.00, z=83.50], EntityEnderman['Enderman'/178580, l='MpServer', x=0.50, y=60.00, z=82.50], EntityEnderman['Enderman'/178585, l='MpServer', x=1.33, y=60.00, z=84.01], EntityEnderman['Enderman'/178584, l='MpServer', x=-3.43, y=60.00, z=81.34], EntityEnderman['Enderman'/171956, l='MpServer', x=42.44, y=58.00, z=96.97], EntityEnderman['Enderman'/168319, l='MpServer', x=48.09, y=57.00, z=103.41], EntityEnderman['Enderman'/171919, l='MpServer', x=25.31, y=61.00, z=17.41], EntityEnderman['Enderman'/176109, l='MpServer', x=79.22, y=36.00, z=-1.38], EntityClientPlayerMP['Minipete'/84, l='MpServer', x=51.85, y=-41.67, z=52.36], EntityEnderman['Enderman'/168443, l='MpServer', x=11.56, y=59.00, z=91.00], EntityEnderman['Enderman'/154810, l='MpServer', x=59.50, y=57.00, z=27.00], EntityEnderman['Enderman'/178218, l='MpServer', x=-14.44, y=59.00, z=82.00], EntityEnderman['Enderman'/149571, l='MpServer', x=41.63, y=60.00, z=61.97], EntityEnderman['Enderman'/149574, l='MpServer', x=44.59, y=59.00, z=29.69], EntityEnderman['Enderman'/168540, l='MpServer', x=52.47, y=57.00, z=91.03], EntityEnderman['Enderman'/149572, l='MpServer', x=35.28, y=60.00, z=56.75], EntityEnderman['Enderman'/178495, l='MpServer', x=23.12, y=61.00, z=16.56], EntityEnderman['Enderman'/176112, l='MpServer', x=79.69, y=36.00, z=-2.28], EntityEnderman['Enderman'/176113, l='MpServer', x=47.50, y=37.00, z=-10.44], EntityEnderman['Enderman'/176114, l='MpServer', x=48.50, y=37.00, z=-9.50], EntityEnderman['Enderman'/176115, l='MpServer', x=47.53, y=37.00, z=-11.25], EntityEnderman['Enderman'/169141, l='MpServer', x=18.59, y=60.00, z=71.44], EntityEnderman['Enderman'/169140, l='MpServer', x=41.94, y=60.00, z=65.03], EntityEnderman['Enderman'/169142, l='MpServer', x=31.09, y=60.00, z=66.28]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows Vista (amd64) version 6.0
	Java Version: 1.7.0_67, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 317472136 bytes (302 MB) / 714592256 bytes (681 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 16 mods loaded, 16 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1230} [Forge Mod Loader] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1230} [Minecraft Forge] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	arsmagica2{1.4.0.005} [Ars Magica 2] (AM2-1.4.0.006.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioCraft{1.8.1} [BiblioCraft] (BiblioCraft[v1.8.1][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AWWayofTime{v1.3.0} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.0-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Thaumcraft{4.2.2.1} [Thaumcraft] (Thaumcraft-1.7.10-4.2.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Botania{r1.3-148} [Botania] (Botania r1.3-148.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	craftguide{1.6.8.1} [CraftGuide] (CraftGuide-1.6.8.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForbiddenMagic{1.7.10-0.551} [Forbidden Magic] (Forbidden Magic-1.7.10-0.551.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mystcraft{0.11.0.00} [Mystcraft] (mystcraft-1.7.10-0.11.0.00.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	quiverchevsky{b57} [QuiverBow] (QuiverBow_1.7.2_b57.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TerrainControl{2.5.3} [Terrain Control] (TerrainControl.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	thaumicinfusion{3.8.1} [Thaumic Infusion] (ThaumicInfusion-1.7.10-3.83.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Launched Version: 1.7.10-Forge10.13.2.1230
	LWJGL: 2.9.1
	OpenGL: ATI Mobility Radeon HD 4570 GL version 2.1.8490 Release, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by TherminatorX** [comment]
I'm guessing this is because the Gaurdian is trying to fight the Void.

**Comment by Mithion** [comment]
And the void can't handle how bad it would lose.

**Comment by Mithion** [comment]
Corrected in 1.4.0.007 (dev).
