### ISSUE TITLE
Some sort of crazy lag (server problem)

### ISSUE THREAD

**Issue by v0xell** [Mithion/ArsMagica2#987]
I play on a server hosted by a friend, with a few other people. It's on the Direwolf20 modpack, but we added some other mods to it. I'm not the only one having trouble and this started when he added Ars Magica. 

Here's what happens: I log in, but can't open things or interact with anything. General lag, right? However, the owner and host of the server can see me moving, breaking things, opening chests, but i can't see him doing anything at all. This is very strange. 

Some things to note:
- We added it while we have a world already, so maybe it broke something in a chunk I've loaded (?)
- Biomes O Plenty and Millenaire is enabled.
- If we load a backup without Ars in it, I no longer lag that way.
- Unable to generate a new world, the server just crashes.

I don't have access to any files, but if you need them tell me and I'll try to get them from him.

Thanks !

**Comment by v0xell** [comment]
When we disable mobs, there is no lag.

**Comment by TherminatorX** [comment]
Might be those crazy Flickers, then. Turn the spawn rate down in the config.

**Comment by v0xell** [comment]
Nevermind, we gave up.

**Comment by Mithion** [comment]
It couldn't have been flickers, they no longer spawn naturally (you need to build the contraption to call them).

It's a shame you gave up, though I can understand the frustration.  I'm sorry it didn't work out.

If you ever decide to try again, I can't recommend enough that you use the mod Opis for profiling - it's absolutely fantastic, and will tell mod devs exactly (in almost all cases) where the lag is coming from.
