### ISSUE TITLE
Compatibility issue with Morph - Taking damage when morphed and Head height issue

### ISSUE THREAD

**Issue by Gunner76th** [Mithion/ArsMagica2#988]
So here is the issue, when you are morphed into just about anything, if you enter a hole or space that is the same height as you, you take damage. Example: Morph into a bat or wisp, enter a 1x1 hole, and start taking suffocation damage (This issue is not restricted to just 1x1 morps, but rather ANY morph in which the morph has a block height the same as the hole the player is in, IE morph of 2 high 1 wide, entering a hole of 2 high 1 wide results in suffocation, whereas the player not in morph can enter the same hole, and not take damage).. This also happens when morphed as a squid, and you swim up and touch a block above you. Based on discussions on irc.esper.net, it has been confirmed that it is an issue between Morph and Ars Magica 2, as removal of AR2 cause this issue to stop happening. As such, I am also posting this bug report to Ars Magica 2.

Java on Client: 1.7.0_u71
Client OS: Windows 7 x64
Java on Server: 1.7.0_u72
Server OS: Ubuntu 14.4
MC Version: 1.7.10
Forge version: 1277
List of mods: http://pastebin.com/W2DGArsZ

It should be noted that only Forge is being used on the server. No other "mod loading" methods are used other than straight forge 1277 (no bukkit, no cauldron, no anything else similar to the aforementioned methods).

**Comment by Gunner76th** [comment]
Link to cross posting on iChuns https://github.com/iChun/Morph/issues/662

**Comment by Gunner76th** [comment]
https://github.com/iChun/Morph/issues/618

**Comment by Mithion** [comment]
The shrink spell now properly tracks your height in 1.4.0.007 (dev).
As a workaround (or if for some reason it still doesn't work), disabling the shrink spell via config will also prevent AM2's size modifying code from running.

**Comment by Gunner76th** [comment]
Is there an projected release date for 1.4.0.007 as of yet?

**Comment by Mithion** [comment]
Hoping for later this week.

**Comment by Gunner76th** [comment]
Thank you, and thank you for all the work you have done so far on this mod.

**Comment by natedogith1** [comment]
I'd just like to mention, the stated workaround (disabling the shrink spell) didn't fix the issue.

**Comment by Mithion** [comment]
That's because the fix I mentioned above was added in a version that isn't out yet :)

**Comment by natedogith1** [comment]
Oh, it's just that I see "as a workaround" to mean "until a proper fix is out, you can do this" (this sounds a lot more sassy/sarcastic in my head than it's supposed to... :(    )

**Comment by Mithion** [comment]
Ah, I can see how that can come across. Sorry for the confusion. Most posts here require code changes and a new release to fix or even work around.
