### ISSUE TITLE
Crash with the latest Ars Magica 1.7.10

### ISSUE THREAD

**Issue by Neodark7** [Mithion/ArsMagica2#989]
Here the log pastebin.com/sKyUBPWU

**Comment by Mithion** [comment]
Log doesn't mention AM2 in the crash report...can you post the full log file?

**Comment by Neodark7** [comment]
java.lang.NullPointerException: Unexpected error
        at am2.proxy.tick.ClientTickHandler.gameTick_Start(ClientTickHandler.java:80)
        at am2.proxy.tick.ClientTickHandler.onClientTick(ClientTickHandler.java:303)

Not Ars Magica 2 ?

**Comment by Mithion** [comment]
LOL I didn't even see that.  My bad.

Either way, I still would like the full log file (FML-Client-Latest.log); it greatly helps in fixing the bug properly.  Please upload to pastebin or dropbox and post the link here.

**Comment by Neodark7** [comment]
yup but i relaunch the game so... :/
but normally it's in this https://www.dropbox.com/s/hgd5izglb7p8iwl/2015-01-06-7.log?dl=0

**Comment by Mithion** [comment]
Thanks - I'll take a peek.  I think it may be conflicting with another of the mods you have installed.

**Comment by Neodark7** [comment]
yeah i have maaaaany mods :/

**Comment by Mithion** [comment]
I see that!  This one might be tough to replicate.  Were you connecting to a server or running locally?

**Comment by Neodark7** [comment]
yup when connecting to my server, it's happened juste once, in my base i have just one thing related to Ars Magica, a liquid essence source

**Comment by Neodark7** [comment]
at the moment, don't blame me it's an early savegame :3

**Comment by Mithion** [comment]
Heh no worries.  Sometimes the mod is better started midgame too!
I'll keep you posted with what I find, and will try to fix (or at least catch so it doesn't crash) this error in 1.4.0.007

**Comment by Neodark7** [comment]
okay thank you :)

**Comment by v0xell** [comment]
Hi, it's v0xell. I noticed you are answering a few of the problems posted
after mine. I was wondering if there is a reason mine isn't answered, or if
you just haven't gotten to it yet. Thanks!

**Comment by Mithion** [comment]
Does this happen without Gany's Surface installed?  It seems to cause weird issues with AM2...not sure why.

**Comment by Neodark7** [comment]
hum it's just happen once so... :/ if i'm able to replicate that issue, i'll try to replicate without gany's surface, but for now i really don't know sorry

**Comment by Mithion** [comment]
It's all good - some of these can be tricky to track down.

**Comment by Mithion** [comment]
I'm going to close this for now, as without the additional information, I can't fix it in the final update.
