### ISSUE TITLE
Crash upon crafting a spell

### ISSUE THREAD

**Issue by Lokilotus** [Mithion/ArsMagica2#990]
Crashlog: http://pastebin.com/Zac2n2cz
Using AM2 v. 1.4.0.006, Forge v. 10.13.2.1277.
Description of Crash:

Creating the spell "Projectile/Touch: Physical Damage".

Researched required components (3 of them) within the Occulus. Created the spell in the Inscription Table. Taken book out of table, gathered required items. Placed book on lecturn; book appeared to be placed but remained in player hotbar and was able to be right-clicked and read.

Upon starting crafting process by tossing in a blank rune, 1 vinteum dust was requested. This was tossed into the Crafting Altar but was not accepted, and instead was drawn to the centre as per how it should be. No other items were accepted. Upon trying to break the Lecturn to cancel the crafting process, the game crashes.

Bug originally encountered on a server, but was confirmed within singleplayer too.

**Comment by TherminatorX** [comment]
Attempt this with 1.4.0.007

**Comment by Mithion** [comment]
1.4.0.007 hasn't been released yet, it's still in dev.

**Comment by Mithion** [comment]
This has been revealed to be an incompatibility with gany's surface.  Remove that, and it will work properly.
