### ISSUE TITLE
Unbreakable/unreplaceable entities

### ISSUE THREAD

**Issue by uladak** [Mithion/ArsMagica2#991]
First found issue: Mage lights. When destroyed, they are gone, however, once a block is attempted to be placed where the light was/the ground is right clicked, the mage light suddenly reappears. This makes the area completely unusable by any other blocks.

Particle emitters have the exact same effect as above. It also seems to not be able to be right clicked to access the usual GUI.

Second main issue is the Broken Power Links. They cannot be destroyed or re-linked by anything, and they cannot be replaced by any block attempted to be placed on the same spot. The only exception is running water into the broken link which destroys it, then placing a block. Once the block that replaced it is destroyed however, the broken power link comes back.

**Comment by Mithion** [comment]
Both of these issues have already been corrected in 1.4.0.007 dev.
