### ISSUE TITLE
Dying the spell book destroyed all my spells

### ISSUE THREAD

**Issue by ShadoDragon** [Mithion/ArsMagica2#992]
I am running the beta version of Ars Magica 2 (1.4.0.006.jar) for Minecraft 1.7.10. I had two spell books filled with spells. After I dyed them to customize them, both books were empty. It had destroyed all of the spells in both books

**Comment by Hades99** [comment]
this is a known bug, just remember to take out all your spells before you
die it or name it in an anvil or enchant it.

On Thu, Jan 8, 2015 at 12:05 AM, ShadoDragon <notifications@github.com>
wrote:

> I am running the beta version of Ars Magica 2 (1.4.0.006.jar) for
> Minecraft 1.7.10. I had two spell books filled with spells. After I dyed
> them to customize them, both books were empty. It had destroyed all of the
> spells in both books
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mithion/ArsMagica2/issues/992>.
>



-- 
Eli

**Comment by TherminatorX** [comment]
Mith, do you think a work around could be made by putting "lore" on the item before it's crafted, like "REMOVE SPELLS BEFORE CONTINUING" in bright green or something else that will catch the player's eye.
That way, there is a "You have been warned" in this case.

**Comment by Mithion** [comment]
Honestly, that's likely going to be the only fix this will get.  The crafting event doesn't seem to want to let me modify the crafted item stack, and I'm not about to implement custom crafting for one feature :)

**Comment by Iivaitte** [comment]
I could imagine "When I went to dye my spellbook I realized I had dyed over my pages as well by mistake!  I had better take the pages out next time."

**Comment by Mithion** [comment]
This warning has been added in 1.4.0.007 (Dev).
