### ISSUE TITLE
am2.items.ItemRune cannot be cast to thaumcraft.api.wands.ItemFocusBasic

### ISSUE THREAD

**Issue by Tsunayoshi** [Mithion/ArsMagica2#993]
I have updated my private modpack and I have a crash loading my server world in singe player (for testing before updating the server :p) and creating a new world.

Used Versions:
AM2-1.4.0.006.jar
AnimationAPI-1.7.10-1.2.4.jar
Thaumcraft-1.7.10-4.2.3.0.jar
ThaumicExploration-1.7.10-1.1-34.jar
ThaumicTinkerer-2.5-1.7.10-439.jar

Crashlogs:
Client: http://pastebin.com/9PkkNrgR
Server: http://pastebin.com/8MjLjsSW

Maybe it is a problem from thaumcraft side, I don't know.

**Comment by Hades99** [comment]
make a backup of your player.dat file and delete it from your world folder.
Then, give yourself a gold banded greatwood wand. Also, try removing
optifine first...always try that first.

On Thu, Jan 8, 2015 at 8:42 AM, Schuby <notifications@github.com> wrote:

> I have updated my modpack and I have a crash loading my server world in
> singe player (for testing before updating the server :p) and creating a new
> world.
>
> Used Versions:
> AM2-1.4.0.006.jar
> AnimationAPI-1.7.10-1.2.4.jar
> Thaumcraft-1.7.10-4.2.3.0.jar
> ThaumicExploration-1.7.10-1.1-34.jar
> ThaumicTinkerer-2.5-1.7.10-439.jar
>
> Crashlogs:
> Client: http://pastebin.com/9PkkNrgR
> Server: http://pastebin.com/8MjLjsSW
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mithion/ArsMagica2/issues/993>.
>



-- 
Eli

**Comment by Tsunayoshi** [comment]
I have removed it both and the client side crash was gone without optifine. But without optifine, mc is not playable and fastcraft generates weird artifacts. But this not your problem I think.
The Serverside crash stays: http://pastebin.com/cXd6GXTb

**Comment by Tsunayoshi** [comment]
Ok the server side crash was from HQM, I discard this mod now, because there is no update since Aug'14 and it wasn't the first time.

I can'nt reproduce the client side crash, so I think this is solved! Thank for your help.
