### ISSUE TITLE
[BUG] Spellbook Deleted with active bind tool on action bar.

### ISSUE THREAD

**Issue by kaianvestra** [Mithion/ArsMagica2#994]
I had a self toolbinding spell that summons a sword active on my action bar, meaning it was in sword form and not in spell form.

In my hand I was holding my arcane spellbook, the special soulbound one that drops from a boss that reduces mana costs of spells.

From my arcane spellbook I was casting [Projectile -> AoE -> Dig] until I ran low on mana. When this happened, my active spellblade reverted back to spell form, and my arcane spellbook also turned into the toolbinding spell.

My spellbook was deleted including all the spells in it and now I have 2 toolbinding spells, one of them being a duplicate made by the bug on the action bar where my spellbook used to be.

Hope that was descriptive enough :]

**Comment by kaianvestra** [comment]
Oh I'm sorry, this was for version 1.4.0.006 for MC 1.7.10

**Comment by kaianvestra** [comment]
Couldn't upload to pastebin cuz it was too big so I uploaded the text to google drive.
https://drive.google.com/file/d/0B2NoTA0YQ_NPMTFTV1c1VGlvZWs/view?usp=sharing

Going to try to recreate it in singleplayer.

**Comment by Mithion** [comment]
That...is a first.  Thanks for the logs and version info - I will also try to replicate this from my end.

**Comment by kaianvestra** [comment]
http://www.twitch.tv/kaianvestra/b/608991555

Recorded it for you :]

**Comment by Mithion** [comment]
that spells it out perfectly...I know exactly where and how to fix it.

**Comment by kaianvestra** [comment]
Typo'd there. I progressed in the mod and experienced the bug completely in survival mode. I only went creative to replicate. I know now not to have an active spellblade on my bar when I'm not using it :p

Glad I was able to help, Ars Magica is literally my favorite mod. Good luck.

**Comment by Mithion** [comment]
This bug has been corrected in 1.4.0.007 (dev).
