### ISSUE TITLE
Custom NPC enchantment conflict

### ISSUE THREAD

**Issue by Pure-Diamond** [Mithion/ArsMagica2#996]
http://pastebin.com/ybR0QeFU I don't even get to the Mojang startup splash. To me it looks like a conflict in the enchantment ID. What can I do to fix this?

**Comment by Hades99** [comment]
first try updating to the latest version 1.4.0.006

On Fri, Jan 9, 2015 at 8:00 PM, Pure-Diamond <notifications@github.com>
wrote:

> http://pastebin.com/ybR0QeFU I don't even get to the Mojang startup
> splash. To me it looks like a conflict in the enchantment ID. What can I do
> to fix this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mithion/ArsMagica2/issues/996>.
>



-- 
Eli

**Comment by Pure-Diamond** [comment]
I did shortly after posting this and no dice

**Comment by sheynandr** [comment]
Change in CustomNpcs.cfg
>#Start Id for enchants
EnchantStartId=120

**Comment by Mithion** [comment]
Since this has a workaround, I am closing it as not actioned in the final update.
