### ISSUE TITLE
[Bug] Duplicating Items in Keystone Receptacle

### ISSUE THREAD

**Issue by sheynandr** [Mithion/ArsMagica2#997]
Hi. I'm found a dupe. 
Items and blocks duplicating in keystone receptacle when hold shift and click them.
Work in ArsMagica2-1.4.0.006.

P/S If i'm found a new dupe, i need create a new issue or post here?

**Comment by sheynandr** [comment]
Seriously? No answer?

**Comment by Mithion** [comment]
New dupes should be separate issues.  This issue has been corrected as of 1.4.0.007 (dev).
