### ISSUE TITLE
[Crash] Server Crash EntityArcaneGuardian

### ISSUE THREAD

**Issue by sheynandr** [Mithion/ArsMagica2#998]
Hi. My Server today freeze and crashed.
Full Crash Report See in my Gist https://gist.github.com/sheynandr/54a1c99ea11ac71ea8fc
Any ideas?

**Comment by sheynandr** [comment]
Seriously? No answer?

**Comment by Mithion** [comment]
Bukkit/Cauldron is not supported, and this issue would have to happen without it.  In local testing, it does not happen.
