### ISSUE TITLE
Essence Refiner accept no Light Etherium

### ISSUE THREAD

**Issue by Dsorum** [Mithion/ArsMagica2#999]
When checked with a Magitech's Staff the Essence Refiner can't hold any Light Etherium but in the Compendium Light Etherium is the first one named.
So is this a Bug or is the Compendium not updated yet?
I already tried the new Version ;)

**Comment by TherminatorX** [comment]
https://github.com/Mithion/ArsMagica2/commit/a1a49b6eb73af8fb7ffab2e573d08f22ba3264f8
If your text matches the first, the text has not been implemented yet. If it does, you need glasses. :smiley:

**Comment by Mithion** [comment]
The compendium entry is correct as of version 1.4.0.007 (dev).
